/* ============================================================
   TOEIC Part 7 — 멀티 지문 (Double / Triple Passage)
   ------------------------------------------------------------
   Part 7 후반부는 지문 두세 개를 함께 읽고 5문항을 푸는 형식이다.
   핵심은 "연계 문제": 한 지문만 봐서는 답이 나오지 않고,
   두 지문의 정보를 겹쳐 놓아야 답이 나오는 문항이다.

   kind  : "double" (2지문) | "triple" (3지문)
   docs  : [{label, en, ko}]  라벨은 지문 번호와 문서 형식
   qs    : [{q, opts, ans, exp, link}]
           link:true 이면 연계 문제 (두 개 이상 지문을 겹쳐야 풀린다)
   ============================================================ */
window.PART7 = [

  /* ═══════════ 1. 2지문 — 원정 응원 버스 (공지 + 이메일) ═══════════ */
  {id:"p7-1", exam:"TOEIC", part7:true, kind:"double", level:3,
   series:"⚽ 축구", type:"Part 7 · 2지문", title:"Away Travel — Coach Booking",
   topic:"서포터스 원정 버스 예약 공지와 회원 문의",
   docs:[
     {label:"지문 1 · 공지",
      en:"NORTHFIELD UNITED SUPPORTERS' CLUB\nAway Travel — Kesterly City (Saturday, 14 March)\n\nCoach travel to Kesterly City is now open for booking. Places are limited to 96 and are allocated in the order that payment is received.\n\nDeparture:  9:00 A.M. from Gate C, Fairview Park\nReturn:     approximately 8:30 P.M. (subject to traffic)\nFare:       £24 standard\n            £18 concession (under 18, over 65, full-time students)\n\nMatch tickets are NOT included in the fare and must be purchased separately through the ticket office.\n\nMembers who booked coach travel for the postponed December fixture will find a credit of £24 already applied to their account. This credit may be used for any away journey this season but cannot be refunded in cash.\n\nTo book, reply to this notice with your membership number by Friday, 6 March. Cancellations made after 9 March will not be refunded.\n\nPriya Raman\nTravel Coordinator",
      ko:"노스필드 유나이티드 서포터스 클럽\n원정 이동 — 케스털리 시티전 (3월 14일 토요일)\n\n케스털리 시티 원정 버스 예약을 시작합니다. 좌석은 96석으로 제한되며 입금 순서대로 배정됩니다.\n\n출발:  오전 9시, 페어뷰 파크 C 게이트\n귀환:  오후 8시 30분경 (교통 상황에 따라 달라질 수 있음)\n요금:  일반 24파운드\n       할인 18파운드 (18세 미만, 65세 초과, 전일제 학생)\n\n경기 입장권은 요금에 포함되어 있지 않으며 매표소에서 따로 구매하셔야 합니다.\n\n연기된 12월 경기 때 버스를 예약하셨던 회원께는 이미 24파운드의 적립금이 계정에 반영되어 있습니다. 이 적립금은 이번 시즌 어느 원정에나 쓸 수 있지만 현금으로 환불되지는 않습니다.\n\n예약하시려면 3월 6일 금요일까지 회원 번호를 적어 이 공지에 회신해 주십시오. 3월 9일 이후의 취소는 환불되지 않습니다.\n\n프리야 라만\n이동 담당자"},
     {label:"지문 2 · 이메일",
      en:"To:      Priya Raman <travel@nusupporters.org>\nFrom:    Daniel Okonkwo <d.okonkwo@mailbox.net>\nDate:    3 March\nSubject: Booking — membership 4471\n\nDear Ms. Raman,\n\nI would like to book two places on the coach for the Kesterly City match. One is for me and the other is for my daughter, who is sixteen.\n\nI was among those affected by the December postponement, so I believe the credit you mention applies to my account. If that is correct, I assume I need only pay the difference, and I will transfer that amount today.\n\nOne further question. My daughter has a music examination that morning and may not reach the ground until 9:15. Would it be possible for us to join the coach at the Riverside stop instead? I understand this may not be permitted, but I thought it worth asking.\n\nKind regards,\nDaniel Okonkwo",
      ko:"받는 사람: 프리야 라만 <travel@nusupporters.org>\n보낸 사람: 대니얼 오콘쿠오 <d.okonkwo@mailbox.net>\n날짜: 3월 3일\n제목: 예약 — 회원번호 4471\n\n라만 님께,\n\n케스털리 시티 경기 버스에 두 자리를 예약하고 싶습니다. 하나는 제 자리이고 다른 하나는 열여섯 살인 제 딸 자리입니다.\n\n저도 12월 경기 연기의 영향을 받은 사람 중 하나라, 말씀하신 적립금이 제 계정에 적용될 것으로 압니다. 그렇다면 차액만 내면 될 것으로 보고, 오늘 그 금액을 송금하겠습니다.\n\n한 가지 더 여쭙습니다. 딸이 그날 아침에 음악 시험이 있어 9시 15분이 되어서야 경기장에 도착할 수도 있습니다. 대신 리버사이드 정류장에서 버스를 타는 것이 가능할까요? 허용되지 않을 수도 있다고 생각합니다만, 여쭤볼 만하다고 판단했습니다.\n\n감사합니다.\n대니얼 오콘쿠오"}
   ],
   gloss:[{w:"allocate",ko:"배정하다"},{w:"concession",ko:"할인 요금(대상)"},{w:"postponed",ko:"연기된"},
          {w:"credit",ko:"적립금"},{w:"subject to ~",ko:"~에 따라 달라지는"},{w:"pay the difference",ko:"차액을 지불하다"}],
   qs:[
     {q:"What is the purpose of the notice?",
      opts:["To announce a change to a match date",
            "To invite members to reserve seats on a coach",
            "To explain a new refund policy for match tickets",
            "To recruit volunteers for an away fixture"],
      ans:1, exp:"지문 1 첫 문장: 'Coach travel … is now open for booking.' 예약 접수를 알리는 공지다. (A) 연기는 12월 경기의 지난 일이고, (C) 환불은 부수적 안내일 뿐이다."},
     {q:"According to the notice, what is true about match tickets?",
      opts:["They are included for concession holders.",
            "They must be obtained from the ticket office.",
            "They are limited to 96 per fixture.",
            "They can be paid for on the coach."],
      ans:1, exp:"지문 1: 'Match tickets are NOT included in the fare and must be purchased separately through the ticket office.' 96석 제한은 입장권이 아니라 버스 좌석이다."},
     {q:"How much will Mr. Okonkwo need to transfer?",
      opts:["£18","£24","£42","£48"],
      ans:0, link:true,
      exp:"연계 문제. 지문 2에서 본인 1석 + 열여섯 살 딸 1석을 예약한다 → 지문 1의 요금표에서 일반 £24 + 할인(18세 미만) £18 = £42. 여기서 이미 적립된 £24를 빼면 £18. 두 지문을 겹쳐야 답이 나온다."},
     {q:"What is indicated about the December fixture?",
      opts:["It was played at a different ground.",
            "It did not take place as scheduled.",
            "It was the last away match of the season.",
            "It sold out within one day."],
      ans:1, exp:"지문 1: 'the postponed December fixture' — 예정대로 열리지 않았기 때문에 적립금이 발생했다."},
     {q:"What does Mr. Okonkwo ask permission to do?",
      opts:["Pay after the deadline has passed",
            "Cancel one of the two places later",
            "Board the coach at another location",
            "Bring a guest who is not a member"],
      ans:2, exp:"지문 2 마지막 단락: 'Would it be possible for us to join the coach at the Riverside stop instead?' 출발 장소 변경을 요청하고 있다."}
   ]},

  /* ═══════════ 2. 3지문 — 아카데미 코치 채용 (공고 + 지원 + 면접표) ═══════════ */
  {id:"p7-2", exam:"TOEIC", part7:true, kind:"triple", level:4,
   series:"⚽ 축구", type:"Part 7 · 3지문", title:"Academy Coach Recruitment",
   topic:"유소년 코치 채용 공고·지원 이메일·면접 일정",
   docs:[
     {label:"지문 1 · 채용 공고",
      en:"NORTHFIELD UNITED ACADEMY\nVacancy: Assistant Coach (Under-14s)\n\nNorthfield United Academy invites applications for a part-time Assistant Coach working with our Under-14 squad. The post involves three evening sessions per week during term time and occasional Saturday fixtures.\n\nEssential\n· A national coaching licence at Level 2 or above\n· At least two years' experience coaching players aged 12 to 16\n· A current safeguarding certificate\n\nDesirable\n· Experience with video analysis software\n· A second language, as roughly a third of our academy families speak Portuguese or Polish at home\n\nApplicants should send a curriculum vitae and a statement of no more than 400 words describing their coaching philosophy to recruitment@nufc-academy.org by 28 April. Candidates invited to interview will also deliver a twenty-minute practical session with the squad.\n\nPlease note that the successful candidate must complete our in-house first-aid course before the season begins in August, regardless of any equivalent qualification already held.",
      ko:"노스필드 유나이티드 아카데미\n채용: 어시스턴트 코치 (14세 이하부)\n\n노스필드 유나이티드 아카데미에서 U14 선수단을 맡을 시간제 어시스턴트 코치를 모집합니다. 학기 중 주 3회 저녁 훈련과 간헐적인 토요일 경기 업무가 포함됩니다.\n\n필수 요건\n· 레벨 2 이상의 국가 코칭 자격증\n· 12~16세 선수 지도 경력 2년 이상\n· 유효한 아동보호(safeguarding) 인증서\n\n우대 사항\n· 영상 분석 소프트웨어 사용 경험\n· 제2 언어. 아카데미 가정의 약 3분의 1이 가정에서 포르투갈어나 폴란드어를 씁니다.\n\n지원자는 이력서와 400단어 이내의 코칭 철학 기술서를 4월 28일까지 recruitment@nufc-academy.org 로 보내 주십시오. 면접에 초청된 지원자는 선수단을 상대로 20분간의 실기 세션도 진행하게 됩니다.\n\n최종 합격자는 이미 동등한 자격을 갖고 있더라도 8월 시즌 개막 전에 반드시 자체 응급처치 과정을 이수해야 합니다."},
     {label:"지문 2 · 지원 이메일",
      en:"To:      recruitment@nufc-academy.org\nFrom:    Marta Oliveira <m.oliveira@swiftmail.com>\nDate:    21 April\nSubject: Application — Assistant Coach (U14)\n\nDear Recruitment Team,\n\nPlease find attached my curriculum vitae and coaching statement for the Assistant Coach position advertised on your website.\n\nI have held a Level 3 licence since 2019 and have spent the last four years coaching age groups from eleven to fifteen, most recently at Brackenhill Juniors, where I introduced a video review session before every league match. I am a native speaker of Portuguese and work regularly with families who are more comfortable in that language than in English.\n\nI should mention that my safeguarding certificate expired last month. I have enrolled on the renewal course and will hold the new certificate by 12 May. I do hold a current first-aid certificate issued by the county association. I hope the lapse does not put me at a disadvantage, and I am of course willing to complete any additional training the academy requires.\n\nI am available for interview on any weekday afternoon except 5 May.\n\nYours sincerely,\nMarta Oliveira",
      ko:"받는 사람: recruitment@nufc-academy.org\n보낸 사람: 마르타 올리베이라 <m.oliveira@swiftmail.com>\n날짜: 4월 21일\n제목: 지원 — 어시스턴트 코치 (U14)\n\n채용 담당자님께,\n\n귀 웹사이트에 공고된 어시스턴트 코치직에 지원하며 이력서와 코칭 기술서를 첨부합니다.\n\n저는 2019년부터 레벨 3 자격증을 보유해 왔고, 지난 4년간 11세에서 15세까지의 연령대를 지도했습니다. 가장 최근에는 브래큰힐 주니어스에서 일하며 리그 경기마다 사전 영상 리뷰 세션을 도입했습니다. 저는 포르투갈어 원어민이며, 영어보다 포르투갈어가 편한 가정들과 정기적으로 소통해 왔습니다.\n\n한 가지 말씀드릴 점은 제 아동보호 인증서가 지난달에 만료되었다는 것입니다. 갱신 과정에 등록했고 5월 12일까지는 새 인증서를 받게 됩니다. 카운티 협회에서 발급한 유효한 응급처치 자격증은 보유하고 있습니다. 인증서 공백이 불이익이 되지 않기를 바라며, 아카데미가 요구하는 추가 교육은 물론 기꺼이 이수하겠습니다.\n\n면접은 5월 5일을 제외한 평일 오후라면 언제든 가능합니다.\n\n마르타 올리베이라 드림"},
     {label:"지문 3 · 면접 일정표",
      en:"ASSISTANT COACH (U14) — INTERVIEW SCHEDULE\nVenue: Academy Building, Room 2 / Pitch 4\n\nMon 4 May   1:30 P.M.   J. Feldman     panel only\nTue 5 May   2:00 P.M.   M. Oliveira    panel + practical\nWed 6 May   1:30 P.M.   A. Whitcombe   panel + practical\nThu 7 May   3:00 P.M.   S. Nakamura    panel only\n\nCandidates marked \"panel + practical\" should arrive one hour before the time shown and bring training kit.\n\nJ. Feldman and S. Nakamura will deliver their practical sessions on a later date, as the U14 squad is away at a tournament on 4 and 7 May.\n\nAny candidate unable to attend at the time shown should contact Priya Raman on extension 214 as soon as this schedule is received.",
      ko:"어시스턴트 코치 (U14) — 면접 일정\n장소: 아카데미 건물 2호실 / 4번 구장\n\n5월 4일 월  오후 1:30  J. 펠드먼      면접만\n5월 5일 화  오후 2:00  M. 올리베이라  면접 + 실기\n5월 6일 수  오후 1:30  A. 위트콤      면접 + 실기\n5월 7일 목  오후 3:00  S. 나카무라    면접만\n\n\"면접 + 실기\"로 표시된 지원자는 명시된 시각보다 한 시간 일찍 도착하고 훈련복을 지참해야 합니다.\n\nJ. 펠드먼과 S. 나카무라의 실기 세션은 추후 날짜에 진행됩니다. U14 선수단이 5월 4일과 7일에 대회 원정을 가기 때문입니다.\n\n표시된 시각에 참석할 수 없는 지원자는 이 일정을 받는 즉시 내선 214번으로 프리야 라만에게 연락하시기 바랍니다."}
   ],
   gloss:[{w:"vacancy",ko:"공석, 채용 자리"},{w:"essential / desirable",ko:"필수 / 우대"},
          {w:"safeguarding certificate",ko:"아동보호 인증서"},{w:"curriculum vitae",ko:"이력서"},
          {w:"regardless of ~",ko:"~와 상관없이"},{w:"lapse",ko:"(자격 등의) 실효, 공백"},
          {w:"practical session",ko:"실기 시연"},{w:"extension",ko:"내선 번호"}],
   qs:[
     {q:"What is listed as an essential requirement for the position?",
      opts:["Experience coaching players between the ages of 12 and 16",
            "Familiarity with video analysis software",
            "The ability to speak Portuguese or Polish",
            "Availability on weekday mornings"],
      ans:0, exp:"지문 1의 Essential 항목: 'At least two years' experience coaching players aged 12 to 16.' (B)와 (C)는 Desirable(우대)이지 필수가 아니다 — Part 7이 즐겨 쓰는 함정이다."},
     {q:"What does Ms. Oliveira indicate about one of her certificates?",
      opts:["It was issued in another country.",
            "It is not currently valid.",
            "It will be upgraded to Level 3.",
            "It was lost and must be reissued."],
      ans:1, exp:"지문 2: 'my safeguarding certificate expired last month' — 현재는 유효하지 않은 상태이며 5월 12일에 갱신된다."},
     {q:"Why will Ms. Oliveira most likely need to telephone extension 214?",
      opts:["To confirm which documents to bring",
            "To ask where the practical session will be held",
            "Because she has been scheduled on a day she is unavailable",
            "Because she has not received the interview schedule"],
      ans:2, link:true,
      exp:"연계 문제. 지문 2에서 '5월 5일만은 안 된다'고 했는데, 지문 3의 일정표는 그를 5월 5일 오후 2시에 배정했다. 지문 3은 참석 불가 시 내선 214번으로 연락하라고 안내한다."},
     {q:"What is suggested about Ms. Oliveira's first-aid certificate?",
      opts:["It will exempt her from a required course.",
            "It must be renewed before 12 May.",
            "It will not remove the need for further training if she is hired.",
            "It is the only qualification the academy will accept."],
      ans:2, link:true,
      exp:"연계 문제. 지문 2는 유효한 응급처치 자격증을 갖고 있다고 하지만, 지문 1은 '이미 동등한 자격을 갖고 있더라도(regardless of any equivalent qualification already held)' 자체 과정을 이수해야 한다고 못박는다. 따라서 면제되지 않는다."},
     {q:"According to the schedule, why will two candidates give their practical sessions later?",
      opts:["The pitch will be undergoing maintenance.",
            "The players they would work with will be away.",
            "The panel is unavailable on those afternoons.",
            "Their applications arrived after the deadline."],
      ans:1, exp:"지문 3: 'as the U14 squad is away at a tournament on 4 and 7 May' — 실기 대상인 선수단이 없기 때문이다."}
   ]},

  /* ═══════════ 3. 2지문 — 단편 영화제 출품 (안내 + 문의) ═══════════ */
  {id:"p7-3", exam:"TOEIC", part7:true, kind:"double", level:4,
   series:"🎬 영화 일반", type:"Part 7 · 2지문", title:"Short Film Festival — Call for Entries",
   topic:"영화제 출품 규정과 감독의 사전 문의",
   docs:[
     {label:"지문 1 · 출품 안내",
      en:"HARBOUR CITY SHORT FILM FESTIVAL\nCall for Entries — Eighteenth Edition\n\nSubmissions are now open in four categories: Fiction, Documentary, Animation, and Student Work. Films must have been completed after 1 January of last year and must not exceed thirty minutes including credits.\n\nEntry fees\n  Standard                  $45 per film\n  Student                   $20 per film (proof of enrolment required)\n  Late (after 1 September)  add $15 to either rate\n\nFilms not in English must be submitted with English subtitles burned into the image. Separate subtitle files cannot be accepted, as our screening committee reviews entries on a shared platform that does not support them.\n\nA film may be entered in only one category. Entries that have already screened at another festival in the region remain eligible, but the entry form must list every prior screening. Failure to do so has in the past led to disqualification at a late stage, which we are keen to avoid.\n\nDecisions will be sent by email in the first week of November.",
      ko:"하버 시티 단편 영화제\n출품 공고 — 제18회\n\n네 개 부문에서 출품을 받습니다: 극영화, 다큐멘터리, 애니메이션, 학생 작품. 작품은 작년 1월 1일 이후에 완성되어야 하며, 엔딩 크레딧을 포함해 30분을 넘지 않아야 합니다.\n\n출품료\n  일반                        편당 45달러\n  학생                        편당 20달러 (재학 증명 필요)\n  마감 후 (9월 1일 이후)      위 요금에 15달러 추가\n\n영어가 아닌 작품은 영어 자막을 영상에 새겨 넣은(burned-in) 상태로 제출해야 합니다. 별도의 자막 파일은 받지 않습니다. 심사위원단이 자막 파일을 지원하지 않는 공용 플랫폼에서 출품작을 보기 때문입니다.\n\n한 작품은 한 부문에만 출품할 수 있습니다. 역내 다른 영화제에서 이미 상영된 작품도 출품 자격이 있으나, 출품 양식에 이전 상영 이력을 빠짐없이 적어야 합니다. 이를 누락해 뒤늦게 실격 처리된 사례가 있었고, 저희는 그런 일을 피하고자 합니다.\n\n심사 결과는 11월 첫째 주에 이메일로 발송됩니다."},
     {label:"지문 2 · 문의 이메일",
      en:"To:      entries@harbourcityfilm.org\nFrom:    Tobias Lund <t.lund@northlight.studio>\nDate:    4 September\nSubject: Two questions before submitting\n\nHello,\n\nI am preparing to submit my short film \"The Ferry at Dusk\" and have two questions.\n\nFirst, the film runs twenty-six minutes without credits and thirty-two with them. Is there any flexibility here, or should I prepare a shorter credit sequence?\n\nSecond, the dialogue is in Danish. I have an English subtitle file that was prepared for an earlier screening, and re-exporting the film with the subtitles fixed into the image will take my editor about a week. I would rather not delay if it can be avoided.\n\nThe film played at the Rosewater Documentary Days in April, and I will note that screening on the form. I am submitting to the Documentary category.\n\nI should add that I graduated in June and am no longer enrolled anywhere.\n\nBest,\nTobias Lund",
      ko:"받는 사람: entries@harbourcityfilm.org\n보낸 사람: 토비아스 룬드 <t.lund@northlight.studio>\n날짜: 9월 4일\n제목: 출품 전 두 가지 문의\n\n안녕하세요,\n\n제 단편 「해질 무렵의 페리」를 출품하려 준비 중인데 두 가지 여쭙고 싶습니다.\n\n첫째, 이 작품은 크레딧을 빼면 26분, 크레딧을 포함하면 32분입니다. 이 부분에 여유가 있는지, 아니면 크레딧을 짧게 다시 만들어야 하는지 궁금합니다.\n\n둘째, 대사는 덴마크어입니다. 이전 상영을 위해 만든 영어 자막 파일이 있는데, 자막을 영상에 새겨 넣어 다시 출력하려면 편집자에게 일주일쯤 걸립니다. 피할 수 있다면 일정을 늦추고 싶지 않습니다.\n\n이 작품은 4월에 로즈워터 다큐멘터리 데이즈에서 상영되었고, 그 이력은 양식에 기재하겠습니다. 다큐멘터리 부문으로 출품합니다.\n\n덧붙이자면 저는 6월에 졸업해서 지금은 어디에도 재학 중이 아닙니다.\n\n감사합니다.\n토비아스 룬드"}
   ],
   gloss:[{w:"call for entries",ko:"출품 공고"},{w:"exceed",ko:"넘다, 초과하다"},
          {w:"proof of enrolment",ko:"재학 증명"},{w:"burned-in subtitles",ko:"영상에 새겨 넣은 자막"},
          {w:"eligible",ko:"자격이 있는"},{w:"disqualification",ko:"실격"},{w:"flexibility",ko:"융통성, 여지"}],
   qs:[
     {q:"What does the festival require of films in other languages?",
      opts:["A translated script submitted with the entry form",
            "Subtitles that are part of the picture itself",
            "A dubbed English soundtrack",
            "Approval from the screening committee in advance"],
      ans:1, exp:"지문 1: 'English subtitles burned into the image. Separate subtitle files cannot be accepted.' 자막이 영상에 새겨져 있어야 한다."},
     {q:"What will Mr. Lund most likely have to do before submitting?",
      opts:["Change the category of his entry",
            "Obtain permission from another festival",
            "Shorten the closing credits of his film",
            "Complete the film before 1 January"],
      ans:2, link:true,
      exp:"연계 문제. 지문 1은 '크레딧 포함 30분 이내'라고 규정하는데, 지문 2에서 그의 작품은 크레딧 포함 32분이다. 크레딧을 줄이지 않으면 규정을 넘는다. 크레딧 없이 26분이라는 수치에 속지 않는 것이 관건이다."},
     {q:"How much will Mr. Lund be required to pay?",
      opts:["$20","$35","$45","$60"],
      ans:3, link:true,
      exp:"연계 문제. 지문 2에서 6월에 졸업해 재학 중이 아니므로 학생 요금은 적용되지 않아 일반 45달러다. 메일 날짜가 9월 4일로 지문 1의 마감(9월 1일)을 지났으므로 15달러가 추가되어 60달러."},
     {q:"Why does the festival ask entrants to list previous screenings?",
      opts:["To decide which category a film belongs in",
            "To calculate the correct entry fee",
            "To avoid removing a film from consideration at a late stage",
            "To arrange publicity with other festivals in the region"],
      ans:2, exp:"지문 1: 'Failure to do so has in the past led to disqualification at a late stage, which we are keen to avoid.' 뒤늦은 실격을 막기 위해서다."},
     {q:"What does Mr. Lund say about his editor?",
      opts:["The editor is unavailable until November.",
            "The editor would need about a week to complete a task.",
            "The editor prepared the film for a student competition.",
            "The editor recommended a different category."],
      ans:1, exp:"지문 2: 're-exporting the film with the subtitles fixed into the image will take my editor about a week.'"}
   ]},

  /* ═══════════ 4. 3지문 — 극장 지정좌석제 (메모 + 후기 + 답신) ═══════════ */
  {id:"p7-4", exam:"TOEIC", part7:true, kind:"triple", level:3,
   series:"🎬 영화 일반", type:"Part 7 · 3지문", title:"Reserved Seating Trial",
   topic:"극장 지정좌석제 시범 운영 — 사내 메모·고객 후기·답신",
   docs:[
     {label:"지문 1 · 사내 메모",
      en:"MEMORANDUM\n\nTo:      All Branch Managers\nFrom:    Elena Vasquez, Director of Operations\nDate:    12 October\nSubject: Reserved seating trial\n\nBeginning 1 November, the four branches listed below will move from open seating to fully reserved seating for all evening screenings. Matinees will be unaffected during the trial.\n\n   Riverside  ·  Kingsway  ·  Fairport  ·  Old Mill\n\nStaff should expect a slower start at the box office for the first two weeks, as customers accustomed to choosing a seat on arrival will need help using the seat map. Please roster one additional floor assistant for Friday and Saturday evenings through 15 November.\n\nWe will collect feedback through the usual comment cards and the website form. A decision on extending the trial to the remaining eleven branches will be made in January, and it will rest primarily on whether complaints about latecomers fall, since that is the problem the change was designed to solve.",
      ko:"업무 연락\n\n받는 사람: 전 지점장\n보낸 사람: 엘레나 바스케스, 운영 총괄\n날짜: 10월 12일\n제목: 지정좌석제 시범 운영\n\n11월 1일부터 아래 네 지점은 저녁 상영 전 회차를 자유석에서 전면 지정좌석제로 전환합니다. 시범 기간 동안 낮 상영(마티네)은 그대로 유지됩니다.\n\n   리버사이드 · 킹스웨이 · 페어포트 · 올드밀\n\n첫 2주간은 매표 진행이 평소보다 느릴 것으로 예상해 주십시오. 도착해서 자리를 고르는 데 익숙한 고객들이 좌석표 사용에 도움을 필요로 하기 때문입니다. 11월 15일까지 금요일과 토요일 저녁에는 플로어 담당 직원을 한 명 추가 배치해 주십시오.\n\n의견은 기존의 의견 카드와 웹사이트 양식을 통해 수집합니다. 나머지 11개 지점으로 확대할지는 1월에 결정하며, 판단 기준은 주로 지각 입장 고객에 대한 불만이 줄어드는지 여부입니다. 애초에 이 변경이 해결하려 한 문제가 바로 그것이기 때문입니다."},
     {label:"지문 2 · 고객 의견 (웹 양식)",
      en:"Harbour Cinemas — Customer Feedback\n\nBranch: Kingsway          Date of visit: Saturday, 8 November\nScreening: 7:45 P.M.      Rating: 3 / 5\n\nI have been coming to this cinema for eleven years and I am sorry to say the new system has made things worse, at least for now. The queue at the counter took nearly twenty minutes, because the one staff member serving had to explain the seat map to almost everyone ahead of me.\n\nI will say that the film started on time and nobody climbed over me halfway through looking for a seat, which used to happen constantly at the late showings. So I can see what you are trying to achieve. My complaint is about the queue, not the seating.\n\nWould you consider putting a screen in the lobby where people can choose their seats before they reach the counter?\n\n— H. Bergstrom",
      ko:"하버 시네마 — 고객 의견\n\n지점: 킹스웨이            방문일: 11월 8일 토요일\n상영: 오후 7시 45분       평점: 3 / 5\n\n11년째 이 극장을 다니고 있습니다만, 안타깝게도 새 제도는 적어도 지금으로서는 상황을 나쁘게 만들었습니다. 카운터 줄에서 20분 가까이 기다렸습니다. 응대하는 직원이 한 명뿐이었는데 제 앞의 거의 모든 사람에게 좌석표 사용법을 설명해야 했기 때문입니다.\n\n다만 영화는 정시에 시작했고, 중간에 자리를 찾느라 제 앞을 넘어 다니는 사람도 없었습니다. 늦은 회차에서는 늘 있던 일이었죠. 그러니 무엇을 이루려는지는 알겠습니다. 제 불만은 줄에 관한 것이지 좌석 제도에 관한 것이 아닙니다.\n\n사람들이 카운터에 오기 전에 로비에서 좌석을 고를 수 있는 화면을 두는 것은 어떨까요?\n\n— H. 베리스트롬"},
     {label:"지문 3 · 답신 이메일",
      en:"To:      H. Bergstrom\nFrom:    Daniel Ruiz, Manager, Kingsway Branch\nDate:    11 November\nSubject: Re: your feedback of 8 November\n\nDear H. Bergstrom,\n\nThank you for writing, and for being so precise about what did and did not work. Your comment about the late showings is exactly the outcome we hoped for.\n\nYou are right about the queue, and I owe you an explanation. Our roster called for a second assistant on the floor that evening, but the colleague concerned was unwell and we could not find cover at short notice. That is not the experience we intend, and I am sorry you waited as long as you did.\n\nYour lobby suggestion has now reached us twice in one week. I have passed it to Ms. Vasquez, who is compiling the trial report, and I have added that two terminals would serve this branch better than one, given how busy our Saturday evenings are.\n\nPlease accept the enclosed pair of complimentary tickets, valid at any branch until the end of February.\n\nWith thanks,\nDaniel Ruiz",
      ko:"받는 사람: H. 베리스트롬\n보낸 사람: 대니얼 루이스, 킹스웨이 지점장\n날짜: 11월 11일\n제목: 회신: 11월 8일자 의견에 대하여\n\nH. 베리스트롬 님께,\n\n의견 주셔서 감사합니다. 무엇이 잘되었고 무엇이 잘되지 않았는지 정확하게 짚어 주신 점에도 감사드립니다. 늦은 회차에 대해 말씀하신 부분은 저희가 바라던 바로 그 결과입니다.\n\n대기 줄에 관해서는 말씀이 옳고, 설명을 드려야겠습니다. 그날 저녁 근무표에는 플로어 담당 직원이 한 명 더 배치되어 있었으나 해당 직원이 몸이 좋지 않았고, 급히 대체 인력을 구하지 못했습니다. 저희가 의도한 경험이 아니며, 그렇게 오래 기다리시게 해 죄송합니다.\n\n로비 관련 제안은 이번 주에만 두 번째로 접수되었습니다. 시범 운영 보고서를 정리하고 있는 바스케스 님께 전달했고, 저희 지점은 토요일 저녁이 특히 붐비므로 단말기가 하나보다 둘이 낫겠다는 의견을 덧붙였습니다.\n\n동봉한 무료 관람권 두 장을 받아 주십시오. 2월 말까지 전 지점에서 사용하실 수 있습니다.\n\n감사합니다.\n대니얼 루이스"}
   ],
   gloss:[{w:"open seating",ko:"자유석"},{w:"matinee",ko:"낮 상영"},{w:"roster",ko:"근무표에 넣다; 근무표"},
          {w:"rest on ~",ko:"~에 달려 있다"},{w:"latecomer",ko:"늦게 오는 사람"},
          {w:"find cover",ko:"대체 인력을 구하다"},{w:"compile",ko:"취합하다, 정리하다"},
          {w:"complimentary",ko:"무료의"}],
   qs:[
     {q:"According to the memo, what problem was the new system intended to solve?",
      opts:["Long queues at the box office",
            "Disturbance caused by customers arriving late",
            "Low attendance at matinee screenings",
            "Errors in online ticket sales"],
      ans:1, exp:"지문 1 마지막 문장: '…whether complaints about latecomers fall, since that is the problem the change was designed to solve.' (A)는 이 제도가 일시적으로 만들어 낸 부작용이지 해결하려던 문제가 아니다."},
     {q:"What does the memo indicate should have been in place during H. Bergstrom's visit?",
      opts:["A reduced ticket price",
            "An extra member of staff on the floor",
            "A lobby terminal for choosing seats",
            "A manager stationed at the counter"],
      ans:1, link:true,
      exp:"연계 문제. 지문 1은 11월 15일까지 금·토 저녁에 플로어 직원 한 명을 추가 배치하라고 지시했고, 지문 2의 방문일은 11월 8일 토요일 저녁이다. 즉 추가 인력이 있어야 했던 날이다."},
     {q:"What does H. Bergstrom say has improved?",
      opts:["The choice of films at the Kingsway branch",
            "The speed of service at the counter",
            "The absence of interruptions during the film",
            "The comfort of the seats"],
      ans:2, exp:"지문 2 둘째 단락: 'nobody climbed over me halfway through looking for a seat, which used to happen constantly.' 상영 중 방해가 사라졌다는 것이 개선점이다."},
     {q:"Who will most likely consider the suggestion about the lobby?",
      opts:["The manager of the Kingsway branch",
            "The company's Director of Operations",
            "The staff member who was absent",
            "The customers who submitted comment cards"],
      ans:1, link:true,
      exp:"연계 문제. 지문 3은 제안을 '바스케스 님'에게 전달했다고만 하고, 지문 1의 머리글에서 엘레나 바스케스가 운영 총괄(Director of Operations)임을 알 수 있다."},
     {q:"What is stated about the tickets sent to H. Bergstrom?",
      opts:["They must be used at the Kingsway branch.",
            "They are valid for evening screenings only.",
            "They can be used at any location until February ends.",
            "They were requested in the feedback form."],
      ans:2, exp:"지문 3 마지막: 'valid at any branch until the end of February.' 지점 제한이 없고 2월 말까지 유효하다."}
   ]}

];
