/* ============================================================
   구문 (Sentence Structures) — 학술 지문에 자주 나오는
   관용적·고난도 문장 구조 모음
   ------------------------------------------------------------
   cat   : 구조 유형 13종
   topic : 주제 13종 (words.js 와 동일 체계 — 예문의 소재)
   level : 1 기초 / 2 중급 / 3 고급 / 4 최고급
   en    : 예문        ko : 해석        note : 구조 설명
   blank : en 안에서 빈칸으로 가릴 부분 (반드시 en 의 부분문자열)
   opts  : 오답 보기 3개 (정답은 blank 자신)
   ============================================================ */
window.STRUCTURES = [

  /* ───────── 도치·강조 ───────── */
  {pat:"Not only A but (also) B",cat:"도치·강조",topic:"사회·정치",level:3,
   en:"Not only did the reforms fail to curb inflation, but they also deepened inequality.",
   ko:"그 개혁은 인플레이션을 억제하지 못했을 뿐 아니라 불평등까지 심화시켰다.",
   blank:"did the reforms fail",opts:["the reforms failed","the reforms did fail","failed the reforms"],
   note:"부정어구 Not only가 문두에 오면 뒤 절이 「조동사+주어+동사원형」의 의문문 어순으로 도치된다."},

  {pat:"Only when ... + 도치",cat:"도치·강조",topic:"학문·연구",level:3,
   en:"Only when the sample was reanalyzed did the discrepancy become apparent.",
   ko:"표본을 재분석하고 나서야 그 불일치가 드러났다.",
   blank:"did the discrepancy become",opts:["the discrepancy became","the discrepancy did become","became the discrepancy"],
   note:"Only+부사절이 문두에 오면 주절이 도치된다. 도치되는 것은 Only절이 아니라 뒤의 주절임에 주의."},

  {pat:"It is X that ... (분열문)",cat:"도치·강조",topic:"자연·환경",level:3,
   en:"It was the unequal distribution of rainfall, not the total amount, that determined crop yields.",
   ko:"작물 수확량을 결정한 것은 총 강우량이 아니라 강우의 불균등한 분포였다.",
   blank:"that determined",opts:["what determined","which it determined","determining"],
   note:"It is/was와 that 사이에 강조할 요소를 넣는 분열문. 강조 대상이 사물·개념이면 that(또는 which)을 쓴다."},

  {pat:"What ... is ~ (의사분열문)",cat:"도치·강조",topic:"학문·연구",level:2,
   en:"What makes the theory compelling is its ability to predict anomalies.",
   ko:"그 이론을 설득력 있게 만드는 것은 변칙 사례를 예측하는 능력이다.",
   blank:"What makes",opts:["That makes","Which makes","What it makes"],
   note:"관계대명사 what이 이끄는 명사절을 주어로 삼아 뒤의 보어를 부각한다. what 자체가 주어라 뒤에 다시 it을 쓰지 않는다."},

  {pat:"So + 형용사 + be + S + that",cat:"도치·강조",topic:"자연·환경",level:4,
   en:"So rapid was the collapse of the fishery that regulators had no time to intervene.",
   ko:"어장의 붕괴가 너무 빨라서 규제 당국이 개입할 시간조차 없었다.",
   blank:"So rapid was the collapse",opts:["So rapid the collapse was","So rapidly was the collapse","Such rapid was the collapse"],
   note:"So+형용사가 문두로 나가면 「be동사+주어」로 도치된다. 형용사 자리이므로 부사 rapidly는 쓸 수 없다."},

  {pat:"Such + be + S + that",cat:"도치·강조",topic:"역사·문화",level:4,
   en:"Such was the scale of the eruption that ash circled the globe for months.",
   ko:"분화의 규모가 워낙 커서 화산재가 몇 달 동안 지구를 돌았다.",
   blank:"Such was the scale",opts:["So was the scale","Such the scale was","Such scale was"],
   note:"Such가 문두에 오면 「be동사+주어」로 도치된다. Such는 명사(scale)를 받고, So는 형용사·부사를 받는다."},

  {pat:"부정 부사 + 도치 (Rarely/Seldom)",cat:"도치·강조",topic:"학문·연구",level:3,
   en:"Rarely has a single discovery reshaped an entire discipline so quickly.",
   ko:"단 하나의 발견이 학문 분야 전체를 이토록 빠르게 바꿔 놓은 일은 드물다.",
   blank:"has a single discovery reshaped",opts:["a single discovery has reshaped","did a single discovery reshaped","a single discovery reshaped"],
   note:"Rarely·Seldom·Hardly 같은 준부정어가 문두에 오면 도치된다. 완료형은 「has+주어+과거분사」 순서."},

  {pat:"No sooner ... than",cat:"도치·강조",topic:"경제·경영",level:4,
   en:"No sooner had the tariffs taken effect than exporters began rerouting shipments.",
   ko:"관세가 발효되자마자 수출업자들은 운송 경로를 바꾸기 시작했다.",
   blank:"than exporters began",opts:["when exporters began","then exporters began","that exporters began"],
   note:"No sooner는 반드시 than과 짝을 이룬다(when·then 아님). 앞 절은 과거완료, 뒤 절은 과거시제."},

  {pat:"장소 부사구 + 도치",cat:"도치·강조",topic:"자연·환경",level:3,
   en:"Beneath the ice sheet lie lakes that have been sealed off for millions of years.",
   ko:"빙상 아래에는 수백만 년간 밀폐되어 온 호수들이 있다.",
   blank:"lie lakes",opts:["lakes lie","lies lakes","do lakes lie"],
   note:"장소 부사구가 문두에 오면 「자동사+주어」로 도치된다. 주어가 복수(lakes)이므로 동사도 lie."},

  {pat:"do/does/did 강조",cat:"도치·강조",topic:"생물·의학",level:2,
   en:"The fossil record does suggest a gradual transition, even if the intermediate forms are scarce.",
   ko:"중간 형태가 드물기는 해도 화석 기록은 점진적 이행을 분명히 시사한다.",
   blank:"does suggest",opts:["do suggest","does suggests","is suggesting"],
   note:"긍정문의 동사를 강조할 때 do/does/did를 앞에 두고 뒤에는 동사원형을 쓴다."},

  /* ───────── 관계절 ───────── */
  {pat:"전치사 + 관계대명사",cat:"관계절",topic:"과학·기술",level:3,
   en:"The mechanism by which the enzyme accelerates the reaction remains poorly understood.",
   ko:"그 효소가 반응을 가속하는 메커니즘은 여전히 잘 밝혀지지 않았다.",
   blank:"by which",opts:["which by","by that","that by"],
   note:"전치사 바로 뒤에는 that을 쓸 수 없고 which/whom만 온다. by which는 the way in which와 같은 방법의 의미."},

  {pat:", which (계속적 용법)",cat:"관계절",topic:"학문·연구",level:2,
   en:"The trial was halted after six months, which forced the researchers to revise their timeline.",
   ko:"그 시험은 6개월 만에 중단되었고, 그로 인해 연구진은 일정을 수정해야 했다.",
   blank:", which forced",opts:[", what forced",", that forced",", it forced"],
   note:"콤마 뒤의 which는 앞 절 전체를 받는다. 계속적 용법에는 that을 쓸 수 없다."},

  {pat:"관계부사 where",cat:"관계절",topic:"자연·환경",level:2,
   en:"Coastal wetlands, where sediment accumulates rapidly, bury carbon far faster than forests.",
   ko:"퇴적물이 빠르게 쌓이는 연안 습지는 숲보다 훨씬 빠르게 탄소를 묻는다.",
   blank:"where sediment accumulates",opts:["which sediment accumulates","where sediment accumulate","that sediment accumulates"],
   note:"뒤 절이 완전한 문장이고 선행사가 장소이면 관계부사 where를 쓴다. 주어 sediment는 단수 취급."},

  {pat:"관계부사 why",cat:"관계절",topic:"사회·정치",level:2,
   en:"One reason why the policy stalled is that no agency was given clear authority.",
   ko:"그 정책이 정체된 한 가지 이유는 어떤 기관에도 명확한 권한이 주어지지 않았다는 점이다.",
   blank:"why the policy stalled",opts:["what the policy stalled","which the policy stalled","why did the policy stall"],
   note:"선행사가 reason이면 관계부사 why. 관계절 안에서는 의문문 어순으로 도치되지 않는다."},

  {pat:"whose + 명사",cat:"관계절",topic:"생물·의학",level:3,
   en:"Species whose ranges are already restricted face the highest extinction risk.",
   ko:"서식 범위가 이미 제한된 종들이 멸종 위험이 가장 높다.",
   blank:"whose ranges are",opts:["which ranges are","whose ranges is","of which ranges are"],
   note:"소유 관계는 whose+명사로 잇는다. 뒤 동사는 whose가 아니라 그 명사(ranges)의 수에 맞춘다."},

  {pat:"수량사 + of which",cat:"관계절",topic:"사회·정치",level:3,
   en:"The survey covered 40 municipalities, most of which had no formal recycling program.",
   ko:"그 조사는 40개 지자체를 다뤘는데, 그중 대부분은 공식 재활용 프로그램이 없었다.",
   blank:"most of which",opts:["most of them","most of that","most which"],
   note:"콤마로 이어 붙일 때 them을 쓰면 접속사가 없어 비문이 된다. 관계대명사 which를 써야 한 문장으로 연결된다."},

  {pat:"관계대명사 what",cat:"관계절",topic:"역사·문화",level:3,
   en:"What the excavation revealed contradicted decades of accepted chronology.",
   ko:"그 발굴이 밝혀낸 것은 수십 년간 통용된 연대기와 모순되었다.",
   blank:"What the excavation revealed",opts:["That the excavation revealed","Which the excavation revealed","What did the excavation reveal"],
   note:"what은 선행사를 포함한 관계대명사로 '~한 것'이라는 명사절을 만든다. 여기서는 문장의 주어."},

  {pat:"관계절 안의 삽입절",cat:"관계절",topic:"생물·의학",level:4,
   en:"The compound that researchers believe causes the toxicity has not yet been isolated.",
   ko:"연구자들이 독성을 일으킨다고 보는 그 화합물은 아직 분리되지 않았다.",
   blank:"that researchers believe causes",opts:["that researchers believe it causes","which researchers believe it causes","what researchers believe causes"],
   note:"researchers believe가 삽입된 형태로, that이 causes의 주어 역할을 한다. 따라서 it을 다시 쓰면 안 된다."},

  {pat:"the extent to which",cat:"관계절",topic:"경제·경영",level:4,
   en:"The extent to which early trade networks shaped urban growth is still debated.",
   ko:"초기 무역망이 도시 성장을 어느 정도로 형성했는지는 여전히 논쟁 중이다.",
   blank:"to which early trade networks shaped",opts:["which early trade networks shaped","to that early trade networks shaped","to which early trade networks shaping"],
   note:"the extent to which는 '어느 정도까지 ~한지'를 뜻하는 학술 지문 상용 표현. 뒤에는 완전한 절이 온다."},

  {pat:"such + 명사 + as",cat:"관계절",topic:"과학·기술",level:3,
   en:"Instruments such as those deployed on the seafloor can record tremors too faint for surface stations.",
   ko:"해저에 설치된 것과 같은 장비는 지표 관측소가 잡지 못할 만큼 미약한 진동도 기록할 수 있다.",
   blank:"such as those deployed",opts:["such as these deploying","such that deployed","such as those deploy"],
   note:"those는 앞의 Instruments를 대신하는 대명사이고, deployed는 그것을 뒤에서 꾸미는 과거분사."},

  /* ───────── 분사구문 ───────── */
  {pat:"현재분사 분사구문",cat:"분사구문",topic:"역사·문화",level:3,
   en:"Lacking any written records, historians must reconstruct the period from material remains.",
   ko:"문헌 기록이 전혀 없기 때문에 역사학자들은 물질적 유물로 그 시기를 재구성해야 한다.",
   blank:"Lacking any written records",opts:["Lacked any written records","Being lack of any written records","To lack any written records"],
   note:"이유를 나타내는 분사구문. 주절의 주어(historians)가 lack의 주체이므로 능동인 현재분사를 쓴다."},

  {pat:"과거분사 분사구문",cat:"분사구문",topic:"생물·의학",level:3,
   en:"Deprived of sunlight, the deeper corals rely almost entirely on their host tissue.",
   ko:"햇빛을 빼앗긴 더 깊은 곳의 산호는 거의 전적으로 숙주 조직에 의존한다.",
   blank:"Deprived of sunlight",opts:["Depriving of sunlight","Deprive of sunlight","Being deprive of sunlight"],
   note:"주어가 동작을 당하는 관계이면 과거분사로 시작한다. Being은 생략되는 것이 자연스럽다."},

  {pat:"with + 명사 + 분사 (부대상황)",cat:"분사구문",topic:"경제·경영",level:3,
   en:"With demand rising faster than supply, prices climbed for eleven consecutive quarters.",
   ko:"수요가 공급보다 빠르게 늘면서 물가는 11분기 연속 상승했다.",
   blank:"With demand rising",opts:["With demand rise","With demand risen","With rising demand rises"],
   note:"「with+명사+분사」는 동시 상황을 나타낸다. demand가 rise의 주체이므로 현재분사."},

  {pat:"완료 분사구문",cat:"분사구문",topic:"자연·환경",level:4,
   en:"Having been isolated for millennia, the island's fauna evolved along a distinct path.",
   ko:"수천 년간 고립되어 있었기에 그 섬의 동물상은 독자적인 경로로 진화했다.",
   blank:"Having been isolated",opts:["Having isolated","Being isolated","Have been isolated"],
   note:"주절보다 앞선 시점이면 Having+과거분사. 고립'된' 것이므로 수동까지 더해 Having been+과거분사."},

  {pat:"독립분사구문 (의미상 주어)",cat:"분사구문",topic:"학문·연구",level:4,
   en:"The rainy season having ended, the crews resumed excavation in early November.",
   ko:"우기가 끝나자 작업팀은 11월 초에 발굴을 재개했다.",
   blank:"The rainy season having ended",opts:["The rainy season has ended","Having the rainy season ended","The rainy season had ended"],
   note:"분사의 주체가 주절 주어(crews)와 다르면 분사 앞에 의미상 주어를 그대로 남긴다."},

  {pat:"결과를 나타내는 분사구문",cat:"분사구문",topic:"자연·환경",level:2,
   en:"The glacier retreated steadily, exposing bedrock that had been buried since the last ice age.",
   ko:"빙하가 꾸준히 후퇴하면서 마지막 빙하기 이후 묻혀 있던 기반암이 드러났다.",
   blank:"exposing bedrock",opts:["exposed bedrock","to expose bedrock","it exposed bedrock"],
   note:"주절 뒤에 놓인 현재분사는 '그래서 ~하다'라는 결과·연속 동작을 나타낸다."},

  {pat:"부정 분사구문",cat:"분사구문",topic:"사회·정치",level:4,
   en:"Not having anticipated the backlash, the committee withdrew the proposal within a week.",
   ko:"반발을 예상하지 못했던 위원회는 일주일 만에 그 제안을 철회했다.",
   blank:"Not having anticipated",opts:["Not anticipated","Without having anticipate","Not to have anticipating"],
   note:"분사구문의 부정은 not을 분사 바로 앞에 둔다. 시점이 앞서므로 having+과거분사."},

  {pat:"Judging from ~ (비인칭 분사구문)",cat:"분사구문",topic:"역사·문화",level:3,
   en:"Judging from the isotope ratios, the artifacts were produced locally rather than imported.",
   ko:"동위원소 비율로 판단하건대 그 유물들은 수입된 것이 아니라 현지에서 제작되었다.",
   blank:"Judging from",opts:["Judged from","Being judged from","Judge from"],
   note:"Judging from·Considering·Speaking of는 주어와 무관하게 굳어진 관용 분사구문이다."},

  {pat:"명사 + 과거분사 (후치 수식)",cat:"분사구문",topic:"자연·환경",level:2,
   en:"Sediment cores taken from the lake bed record two thousand years of drought cycles.",
   ko:"호수 바닥에서 채취한 퇴적물 코어는 2천 년에 걸친 가뭄 주기를 기록하고 있다.",
   blank:"taken from the lake bed",opts:["taking from the lake bed","which taken from the lake bed","were taken from the lake bed"],
   note:"「관계대명사+be동사」가 생략된 형태. 문장의 본동사는 뒤의 record이므로 여기에 동사를 쓰면 안 된다."},

  {pat:"as + 과거분사 (삽입)",cat:"분사구문",topic:"변화·수량",level:3,
   en:"The population, as measured by the most recent census, has declined by nearly a fifth.",
   ko:"가장 최근 인구조사로 측정한 바에 따르면 그 인구는 거의 5분의 1이 줄었다.",
   blank:"as measured by",opts:["as measuring by","as it measured by","as measure by"],
   note:"as+과거분사는 '~된 바에 따르면'이라는 뜻으로 삽입되어 근거를 밝힌다."},

  /* ───────── 가정법·양보 ───────── */
  {pat:"if 생략 도치 (가정법 과거완료)",cat:"가정법·양보",topic:"사회·정치",level:4,
   en:"Had the levees held, the flooding would have been confined to the outer districts.",
   ko:"제방이 버텨 주었더라면 침수는 외곽 지역에 국한되었을 것이다.",
   blank:"Had the levees held",opts:["If the levees held","Had the levees hold","If had the levees held"],
   note:"If를 생략하면 had가 문두로 나가 도치된다. If를 남기면 도치하지 않는다."},

  {pat:"Were it not for ~",cat:"가정법·양보",topic:"자연·환경",level:4,
   en:"Were it not for the buffering capacity of the oceans, atmospheric warming would be far more severe.",
   ko:"바다의 완충 능력이 없다면 대기 온난화는 훨씬 더 심각할 것이다.",
   blank:"Were it not for",opts:["If it were not","Was it not for","Were not it for"],
   note:"If it were not for에서 If를 생략해 도치한 형태. 가정법이므로 주어가 it이어도 was가 아닌 were."},

  {pat:"But for ~ (~가 없었다면)",cat:"가정법·양보",topic:"생물·의학",level:4,
   en:"But for the timely embargo, the epidemic would have spread to neighboring provinces.",
   ko:"시의적절한 봉쇄가 없었다면 그 전염병은 인접 주까지 번졌을 것이다.",
   blank:"But for",opts:["But of","Unless for","But that for"],
   note:"But for는 Without과 같은 뜻의 가정 표현으로 명사구를 이끈다. 주절에는 조동사 과거형이 온다."},

  {pat:"otherwise + 가정법",cat:"가정법·양보",topic:"과학·기술",level:3,
   en:"The samples were sealed immediately; otherwise the volatile compounds would have escaped.",
   ko:"표본은 즉시 밀봉되었다. 그러지 않았다면 휘발성 화합물이 빠져나갔을 것이다.",
   blank:"would have escaped",opts:["would escape","will have escaped","had escaped"],
   note:"otherwise가 '그러지 않았다면'이라는 if절을 대신한다. 과거 사실의 반대이므로 would have+과거분사."},

  {pat:"as if + 가정법",cat:"가정법·양보",topic:"경제·경영",level:3,
   en:"The market behaved as if the shortage were permanent, though inventories recovered within weeks.",
   ko:"재고는 몇 주 만에 회복되었지만 시장은 마치 그 부족이 영구적인 것처럼 움직였다.",
   blank:"as if the shortage were",opts:["as if the shortage is","as though the shortage has been","like the shortage were"],
   note:"사실과 다른 가정을 나타내는 as if 뒤에는 가정법 과거(were)를 쓴다."},

  {pat:"It is time + 과거시제",cat:"가정법·양보",topic:"사회·정치",level:3,
   en:"It is time that regulators reconsidered how emissions are measured.",
   ko:"이제 규제 당국이 배출량 측정 방식을 재고할 때다.",
   blank:"that regulators reconsidered",opts:["that regulators reconsider","that regulators will reconsider","when regulators reconsidered"],
   note:"It is time that 뒤에는 현재의 일이라도 과거시제를 써서 '아직 안 했다'는 뉘앙스를 담는다."},

  {pat:"형용사 + as + S + V (양보 도치)",cat:"가정법·양보",topic:"학문·연구",level:4,
   en:"Compelling as the evidence appeared, it rested on a single contaminated sample.",
   ko:"그 증거가 아무리 설득력 있어 보였어도 그것은 오염된 표본 하나에 기대고 있었다.",
   blank:"Compelling as the evidence appeared",opts:["As compelling the evidence appeared","Compelling though appeared the evidence","As the evidence compelling appeared"],
   note:"보어인 형용사를 문두로 보내고 as를 쓰면 '비록 ~일지라도'의 양보가 된다."},

  {pat:"However + 형용사/부사",cat:"가정법·양보",topic:"학문·연구",level:3,
   en:"However carefully the trial is designed, some confounding variables remain.",
   ko:"시험을 아무리 세심하게 설계하더라도 일부 교란 변수는 남는다.",
   blank:"However carefully",opts:["However careful","How carefully","Whatever carefully"],
   note:"However 바로 뒤에는 수식 대상이 붙는다. 여기서는 동사 is designed를 꾸미므로 부사 carefully."},

  {pat:"Whether A or B (양보)",cat:"가정법·양보",topic:"생물·의학",level:2,
   en:"Whether the decline stems from habitat loss or from disease, the outcome for the population is the same.",
   ko:"그 감소가 서식지 상실에서 비롯되든 질병에서 비롯되든 개체군에 미치는 결과는 같다.",
   blank:"Whether the decline stems",opts:["If the decline stems","Whether does the decline stem","Either the decline stems"],
   note:"'~이든 아니든'의 양보 부사절에는 if가 아니라 whether를 쓴다."},

  {pat:"혼합 가정법",cat:"가정법·양보",topic:"역사·문화",level:4,
   en:"Had the treaty been ratified in 1975, the region would look very different today.",
   ko:"그 조약이 1975년에 비준되었더라면 그 지역은 오늘날 매우 다른 모습일 것이다.",
   blank:"would look",opts:["would have looked","will look","would be looked"],
   note:"조건은 과거(1975), 결과는 현재(today)인 혼합 가정법. 주절은 「would+동사원형」."},

  /* ───────── 비교·대조 ───────── */
  {pat:"The 비교급 ~, the 비교급 ~",cat:"비교·대조",topic:"자연·환경",level:2,
   en:"The denser the canopy, the less light reaches the forest floor.",
   ko:"수관이 빽빽할수록 숲 바닥에 닿는 빛은 적어진다.",
   blank:"the less light reaches",opts:["the least light reaches","the less light does reach","less light reaches"],
   note:"「The+비교급 ~, the+비교급 ~」은 비례 관계를 나타낸다. 두 번째 the를 빠뜨리면 안 된다."},

  {pat:"no less than (무려)",cat:"비교·대조",topic:"경제·경영",level:3,
   en:"The reform cut administrative costs by no less than forty percent.",
   ko:"그 개혁은 행정 비용을 무려 40퍼센트나 줄였다.",
   blank:"no less than",opts:["no less as","not less as","no lesser than"],
   note:"no less than은 수치가 많음을 강조해 '무려 ~나'로 옮긴다. not less than(적어도)과 뜻이 다르다."},

  {pat:"not so much A as B",cat:"비교·대조",topic:"경제·경영",level:4,
   en:"The decline was not so much a collapse in demand as a shift toward substitutes.",
   ko:"그 하락은 수요의 붕괴라기보다는 대체재로의 이동이었다.",
   blank:"not so much a collapse in demand as",opts:["not so much a collapse in demand than","not as much a collapse in demand than","not so much a collapse in demand like"],
   note:"'A라기보다 B'라는 뜻. 짝이 되는 접속사는 than이 아니라 as."},

  {pat:"as + 형용사 + a + 명사 + as",cat:"비교·대조",topic:"역사·문화",level:4,
   en:"This inscription is as reliable a source as any that survives from the period.",
   ko:"이 비문은 그 시기에서 전해지는 어떤 자료 못지않게 신뢰할 만하다.",
   blank:"as reliable a source as",opts:["as a reliable source as","so reliable a source as","as reliable source as"],
   note:"as+형용사가 오면 관사 a는 형용사 뒤로 밀려 「as+형용사+a+명사」 어순이 된다."},

  {pat:"no more A than B",cat:"비교·대조",topic:"언어·논증",level:4,
   en:"A model is no more a substitute for observation than a map is for terrain.",
   ko:"지도가 지형을 대신할 수 없듯 모형도 관측을 대신할 수 없다.",
   blank:"no more a substitute for observation than",opts:["no more a substitute for observation as","not more a substitute for observation than that","no more substitute for observation than"],
   note:"「A is no more X than B is Y」는 둘 다 아니라는 뜻의 양자 부정 구문이다."},

  {pat:"In contrast to ~",cat:"비교·대조",topic:"역사·문화",level:2,
   en:"In contrast to the coastal sites, inland settlements show no evidence of long-distance trade.",
   ko:"연안 유적지와 달리 내륙 정착지에서는 원거리 교역의 증거가 나타나지 않는다.",
   blank:"In contrast to",opts:["In contrast with that","In contrary to","On contrast to"],
   note:"In contrast to+명사로 대조 대상을 밝힌다. In contrary to는 쓰지 않는 형태."},

  {pat:"than that of (비교 대상 일치)",cat:"비교·대조",topic:"생물·의학",level:3,
   en:"The metabolic rate of the deep-sea species is far lower than that of its shallow-water relatives.",
   ko:"심해종의 대사율은 천해에 사는 근연종의 대사율보다 훨씬 낮다.",
   blank:"than that of",opts:["than of","than those of","than it of"],
   note:"비교 대상은 rate 대 rate여야 하므로 단수를 받는 that of를 쓴다. 복수라면 those of."},

  {pat:"배수 + as ~ as",cat:"비교·대조",topic:"변화·수량",level:2,
   en:"The revised estimate is nearly twice as large as the figure reported a decade ago.",
   ko:"수정된 추정치는 10년 전 보고된 수치의 거의 두 배에 이른다.",
   blank:"twice as large as",opts:["twice as larger as","as twice large as","twice so large as"],
   note:"배수 표현은 「배수사+as+원급+as」 순서. 비교급(larger)을 쓰지 않는다."},

  {pat:"rather than + 병렬",cat:"비교·대조",topic:"사회·정치",level:3,
   en:"The committee chose to delay the vote rather than risk a narrow defeat.",
   ko:"위원회는 근소한 패배를 무릅쓰기보다 표결을 미루기로 했다.",
   blank:"rather than risk",opts:["rather than risking","rather than to risking","instead of risk"],
   note:"rather than 앞뒤는 같은 형태로 맞춘다. 앞이 to delay이므로 뒤도 원형 risk."},

  {pat:"Of all ~, 최상급",cat:"비교·대조",topic:"자연·환경",level:2,
   en:"Of all the factors examined, soil acidity proved the most reliable predictor of yield.",
   ko:"검토된 모든 요인 가운데 토양 산도가 수확량의 가장 믿을 만한 예측 변수로 드러났다.",
   blank:"the most reliable predictor",opts:["the more reliable predictor","most reliable predictor of the","the most reliably predictor"],
   note:"셋 이상을 비교하는 범위(Of all ~)에서는 최상급을 쓰고 the를 붙인다."},

  /* ───────── 삽입·동격 ───────── */
  {pat:"동격의 that",cat:"삽입·동격",topic:"경제·경영",level:3,
   en:"The assumption that markets clear instantaneously underlies much of classical theory.",
   ko:"시장이 즉각 청산된다는 가정이 고전 이론의 상당 부분을 떠받치고 있다.",
   blank:"The assumption that markets clear",opts:["The assumption which markets clear","The assumption what markets clear","The assumption of markets clear"],
   note:"assumption·fact·idea 뒤의 that은 관계대명사가 아니라 내용을 설명하는 동격 접속사다."},

  {pat:"콤마 동격 (명사구)",cat:"삽입·동격",topic:"학문·연구",level:2,
   en:"Marie Tharp, a geologist working from soundings alone, mapped the mid-ocean ridge.",
   ko:"오직 음향 측심 자료만으로 작업한 지질학자 마리 사프는 대양 중앙 해령을 지도로 그렸다.",
   blank:"a geologist working from soundings alone",opts:["a geologist worked from soundings alone","who a geologist working from soundings alone","being a geologist worked from soundings alone"],
   note:"콤마 사이에 명사구를 넣어 앞 명사를 다시 설명한다. working은 그 명사구를 꾸미는 현재분사."},

  {pat:"삽입절 (they argue)",cat:"삽입·동격",topic:"역사·문화",level:3,
   en:"The migration, they argue, was driven by drought rather than by conflict.",
   ko:"그들은 그 이주가 분쟁이 아니라 가뭄에 의해 촉발되었다고 주장한다.",
   blank:"they argue",opts:["they argue that","which they argue","they argue it"],
   note:"주어와 동사만 콤마 사이에 삽입하는 형태. 뒤에 that이나 it을 덧붙이면 문장이 겹친다."},

  {pat:"namely / that is (부연)",cat:"삽입·동격",topic:"자연·환경",level:3,
   en:"Only one variable proved significant, namely the timing of the first frost.",
   ko:"단 하나의 변수만이 유의미했는데, 바로 첫서리가 내린 시점이었다.",
   blank:"namely the timing",opts:["namely of the timing","namely is the timing","name the timing"],
   note:"namely는 앞의 말을 구체적으로 짚어 주는 부사로, 뒤에 명사구를 바로 붙인다."},

  {pat:"의문사절 동격 (of how ~)",cat:"삽입·동격",topic:"학문·연구",level:3,
   en:"The problem of how to date the layers was solved by tephra analysis.",
   ko:"지층의 연대를 어떻게 측정할 것인가 하는 문제는 테프라 분석으로 해결되었다.",
   blank:"of how to date",opts:["of how dating","that how to date","of how to dating"],
   note:"「전치사+의문사+to부정사」로 명사를 부연한다. 전치사 뒤에 that절은 올 수 없다."},

  {pat:"few, if any (삽입)",cat:"삽입·동격",topic:"예술·문학",level:4,
   en:"Few, if any, of the early manuscripts survive in their original form.",
   ko:"초기 필사본 중 원형 그대로 전해지는 것은 설령 있다 해도 극소수다.",
   blank:"if any,",opts:["if some,","if ever,","if anything,"],
   note:"few, if any는 '있다 하더라도 거의 없다'는 뜻의 굳어진 삽입구. 시간이면 if ever를 쓴다."},

  {pat:"what is more (게다가)",cat:"삽입·동격",topic:"과학·기술",level:3,
   en:"The method is cheap and, what is more, requires no specialized training.",
   ko:"그 방법은 저렴하고 게다가 특별한 훈련도 필요 없다.",
   blank:"what is more",opts:["what is most","which is more that","that is more"],
   note:"what is more는 '더욱이'라는 뜻으로 문장 중간에 삽입되는 관용 표현이다."},

  {pat:"동격 that + 완전한 절",cat:"삽입·동격",topic:"학문·연구",level:3,
   en:"The finding that no two samples matched forced a redesign of the protocol.",
   ko:"어떤 두 표본도 일치하지 않았다는 발견은 실험 절차의 재설계를 불러왔다.",
   blank:"The finding that no two samples matched",opts:["The finding which no two samples matched","The finding of no two samples matched","The finding that no two samples matching"],
   note:"동격의 that 뒤에는 성분이 빠지지 않은 완전한 절이 온다. 문장의 본동사는 뒤의 forced."},

  {pat:"so to speak (말하자면)",cat:"삽입·동격",topic:"생물·의학",level:3,
   en:"The reef functions as a nursery, so to speak, for dozens of commercially important species.",
   ko:"그 산호초는 말하자면 상업적으로 중요한 수십 종의 보육원 역할을 한다.",
   blank:"so to speak",opts:["so to speaking","to so speak","so speak to"],
   note:"so to speak·as it were는 비유를 완화하는 굳어진 삽입구로 형태가 변하지 않는다."},

  {pat:"부사 삽입 (however)",cat:"삽입·동격",topic:"언어·논증",level:2,
   en:"The correlation is strong; the causal direction, however, remains unresolved.",
   ko:"상관관계는 강하지만 인과의 방향은 여전히 밝혀지지 않았다.",
   blank:"however",opts:["however that","but however","however it"],
   note:"however는 접속사가 아닌 부사라서 콤마 사이에 삽입할 수 있고 but과 겹쳐 쓰지 않는다."},

  /* ───────── 생략·대용 ───────── */
  {pat:"대부정사 (to 만 남기기)",cat:"생략·대용",topic:"학문·연구",level:3,
   en:"The team wanted to publish immediately, but the reviewers advised them not to.",
   ko:"연구팀은 즉시 발표하고 싶어 했지만 심사위원들은 그러지 말라고 조언했다.",
   blank:"not to",opts:["not to do","to not","not"],
   note:"앞에 나온 to publish의 반복을 피해 to만 남긴다. 부정어 not은 to 앞에 온다."},

  {pat:"so + 조동사 + 주어 (~도 그렇다)",cat:"생략·대용",topic:"역사·문화",level:2,
   en:"The northern colonies declined sharply, and so did the southern ones.",
   ko:"북부 식민지들이 급격히 쇠퇴했고 남부 식민지들도 마찬가지였다.",
   blank:"and so did the southern ones",opts:["and so the southern ones did","and so were the southern ones","and also did the southern ones"],
   note:"「so+조동사+주어」로 앞 내용의 반복을 대신한다. 앞 동사가 declined이므로 did."},

  {pat:"do so 대용",cat:"생략·대용",topic:"학문·연구",level:3,
   en:"Few laboratories can replicate the assay, and those that do so report wide variation.",
   ko:"그 분석법을 재현할 수 있는 실험실은 드물고, 재현하는 곳들도 큰 편차를 보고한다.",
   blank:"those that do so",opts:["those that do it so","those which so do","those that make so"],
   note:"do so는 앞의 동사구(replicate the assay) 전체를 대신한다. it을 덧붙이지 않는다."},

  {pat:"the ones (반복 명사 대용)",cat:"생략·대용",topic:"과학·기술",level:2,
   en:"Older instruments were less precise than the ones installed after 1990.",
   ko:"구형 장비는 1990년 이후 설치된 것들보다 정밀도가 떨어졌다.",
   blank:"the ones installed",opts:["the one installed","that installed","the ones installing"],
   note:"복수 명사(instruments)의 반복을 피할 때는 the ones를 쓰고, 뒤에서 분사로 꾸민다."},

  {pat:"비교절의 동사 대용",cat:"생략·대용",topic:"변화·수량",level:2,
   en:"Urban households consume more water per capita than rural ones do.",
   ko:"도시 가구는 농촌 가구보다 1인당 물 소비량이 많다.",
   blank:"than rural ones do",opts:["than rural ones are","than do rural ones consume","than rural ones does"],
   note:"than 뒤에서 consume의 반복을 do로 대신한다. 주어가 복수(ones)이므로 does가 아닌 do."},

  {pat:"if necessary (주어+be 생략)",cat:"생략·대용",topic:"과학·기술",level:2,
   en:"The filters should be replaced monthly, or more often if necessary.",
   ko:"필터는 매달, 필요하다면 더 자주 교체해야 한다.",
   blank:"if necessary",opts:["if it necessary","if necessarily","if is necessary"],
   note:"if it is necessary에서 「주어+be동사」가 생략된 형태. 형용사가 그대로 남는다."},

  {pat:"as + 과거분사 (as 뒤 생략)",cat:"생략·대용",topic:"학문·연구",level:3,
   en:"The results were interpreted as predicted by the original model.",
   ko:"그 결과는 원래 모형이 예측한 대로 해석되었다.",
   blank:"as predicted by",opts:["as predicting by","as it predicted by","as predict by"],
   note:"as it was predicted에서 「주어+be동사」가 빠진 형태로, 과거분사만 남는다."},

  {pat:"When/While + 분사·형용사",cat:"생략·대용",topic:"생물·의학",level:2,
   en:"When exposed to acid, the mineral dissolves within minutes.",
   ko:"산에 노출되면 그 광물은 몇 분 안에 녹는다.",
   blank:"When exposed to acid",opts:["When exposing to acid","When it exposed to acid","When expose to acid"],
   note:"부사절의 주어가 주절과 같으면 「주어+be동사」를 생략할 수 있다. 노출'되는' 것이므로 과거분사."},

  {pat:"접속사 that 생략",cat:"생략·대용",topic:"경제·경영",level:2,
   en:"Most economists agree the effect is temporary, though they differ on its size.",
   ko:"대부분의 경제학자는 그 효과가 일시적이라는 데 동의하지만 규모에 대해서는 견해가 갈린다.",
   blank:"agree the effect is",opts:["agree with the effect is","agree that the effect being","agree the effect being"],
   note:"목적어절을 이끄는 that은 생략할 수 있다. 다만 절이므로 동사는 그대로 남는다."},

  {pat:"the former / the latter",cat:"생략·대용",topic:"자연·환경",level:3,
   en:"Both drought and overgrazing degrade the soil, but the latter acts far more quickly.",
   ko:"가뭄과 과방목 모두 토양을 훼손하지만 후자가 훨씬 빠르게 작용한다.",
   blank:"the latter acts",opts:["the later acts","the latter act","latter acts"],
   note:"the latter는 앞서 언급한 둘 중 뒤의 것(overgrazing)을 가리키는 단수 취급 대용어다."},

  /* ───────── 명사구 압축 ───────── */
  {pat:"명사화된 주어",cat:"명사구 압축",topic:"역사·문화",level:3,
   en:"The widespread adoption of crop rotation reduced soil exhaustion across the region.",
   ko:"윤작의 광범위한 도입이 그 지역 전반의 지력 고갈을 줄였다.",
   blank:"The widespread adoption of",opts:["The widespread adopting of","Widespread adoption for","The widely adoption of"],
   note:"동사(adopt)를 명사(adoption)로 바꿔 주어로 압축하는 학술문 특유의 방식. adoption of가 짝."},

  {pat:"명사 연쇄 (복합 명사구)",cat:"명사구 압축",topic:"과학·기술",level:4,
   en:"Groundwater contamination risk assessment now precedes any drilling permit.",
   ko:"이제 지하수 오염 위험 평가가 모든 시추 허가에 선행한다.",
   blank:"Groundwater contamination risk assessment",opts:["Groundwater contaminating risk assessment","Contamination groundwater risk assessment","Groundwater contamination risky assessment"],
   note:"명사를 여러 개 이어 붙일 때 앞의 명사들은 형태를 바꾸지 않고 뒤 명사를 꾸민다."},

  {pat:"전치사구 중첩",cat:"명사구 압축",topic:"생물·의학",level:3,
   en:"The effect of temperature on the rate of enzyme activity is nonlinear.",
   ko:"온도가 효소 활성 속도에 미치는 영향은 비선형적이다.",
   blank:"of temperature on the rate of",opts:["of temperature to the rate of","for temperature on the rate of","of temperature on the rate for"],
   note:"「the effect of A on B」가 고정 짝이다. 무엇의 영향인지는 of, 무엇에 대한 영향인지는 on."},

  {pat:"There + 자동사 + 긴 주어",cat:"명사구 압축",topic:"학문·연구",level:3,
   en:"There remains considerable disagreement about how the layers should be dated.",
   ko:"그 지층의 연대를 어떻게 측정해야 하는지를 두고 상당한 이견이 남아 있다.",
   blank:"There remains considerable disagreement",opts:["There remain considerable disagreement","It remains considerable disagreement","There is remained considerable disagreement"],
   note:"There 구문의 동사는 뒤의 진짜 주어에 수를 맞춘다. disagreement가 단수이므로 remains."},

  {pat:"가주어 it + that절",cat:"명사구 압축",topic:"자연·환경",level:2,
   en:"It is widely accepted that the extinction was triggered by an impact.",
   ko:"그 멸종이 충돌로 촉발되었다는 것은 널리 받아들여진다.",
   blank:"It is widely accepted that",opts:["That is widely accepted that","It is widely accepted what","There is widely accepted that"],
   note:"긴 that절을 뒤로 보내고 자리를 it이 대신한다. There로는 대체할 수 없다."},

  {pat:"가주어 it + to부정사",cat:"명사구 압축",topic:"역사·문화",level:2,
   en:"It proved difficult to distinguish weathering from deliberate shaping.",
   ko:"풍화와 의도적 가공을 구분하기란 어려운 일로 드러났다.",
   blank:"It proved difficult to distinguish",opts:["It proved difficult distinguishing","That proved difficult to distinguish","It proved difficulty to distinguish"],
   note:"진주어가 to부정사구일 때 가주어 it을 쓴다. difficult는 형용사 자리."},

  {pat:"동명사 주어",cat:"명사구 압축",topic:"학문·연구",level:2,
   en:"Measuring the depth of the sediment proved harder than dating it.",
   ko:"퇴적물의 깊이를 재는 일은 연대를 측정하는 일보다 어려운 것으로 드러났다.",
   blank:"Measuring the depth",opts:["Measure the depth","To measuring the depth","Measured the depth"],
   note:"동명사구가 주어가 되면 단수 취급한다. 뒤의 than dating과 형태를 맞춘 병렬이기도 하다."},

  {pat:"명사 + to부정사",cat:"명사구 압축",topic:"언어·논증",level:3,
   en:"The failure to account for seasonal variation weakened the conclusion.",
   ko:"계절 변동을 고려하지 못한 점이 그 결론을 약화시켰다.",
   blank:"The failure to account for",opts:["The failure of accounting for","The failure to accounting for","The fail to account for"],
   note:"failure·ability·attempt 등은 뒤에 to부정사를 취해 명사구를 이룬다."},

  {pat:"전치사 + 동명사 (의미상 주어)",cat:"명사구 압축",topic:"사회·정치",level:4,
   en:"The committee objected to the results being released before peer review.",
   ko:"위원회는 동료 심사 전에 결과가 공개되는 것에 반대했다.",
   blank:"the results being released",opts:["the results being release","the results to be releasing","the results are being released"],
   note:"전치사 to 뒤에는 동명사가 온다. 동명사의 주체(the results)를 앞에 두고 수동은 being+과거분사."},

  {pat:"추상명사 + with which",cat:"명사구 압축",topic:"과학·기술",level:4,
   en:"The ease with which the material fractures limits its structural use.",
   ko:"그 재료가 쉽게 갈라진다는 점이 구조재로서의 쓰임을 제한한다.",
   blank:"The ease with which",opts:["The ease which","The ease in that","The easy with which"],
   note:"「the ease/speed/accuracy with which+절」은 '얼마나 쉽게/빠르게 ~하는가'를 명사구로 압축한다."},

  /* ───────── 부정 표현 ───────── */
  {pat:"hardly (준부정)",cat:"부정 표현",topic:"언어·논증",level:2,
   en:"The correlation is hardly strong enough to justify the policy.",
   ko:"그 상관관계는 해당 정책을 정당화할 만큼 강하다고 보기 어렵다.",
   blank:"hardly strong enough",opts:["hardly enough strong","hard strong enough","hardly not strong enough"],
   note:"hardly는 그 자체로 부정의 뜻이라 not과 겹쳐 쓰지 않는다. enough는 형용사 뒤에 온다."},

  {pat:"by no means (결코 ~아닌)",cat:"부정 표현",topic:"학문·연구",level:3,
   en:"The evidence is by no means conclusive, despite the confident framing.",
   ko:"자신 있는 서술과 달리 그 증거는 결코 결정적이지 않다.",
   blank:"by no means conclusive",opts:["by no mean conclusive","by any means conclusive","by no means not conclusive"],
   note:"by no means는 강한 부정으로 means는 항상 복수형. by any means(어떻게든)와 뜻이 정반대다."},

  {pat:"far from (전혀 ~이 아닌)",cat:"부정 표현",topic:"역사·문화",level:3,
   en:"The dating method is far from precise when organic material is scarce.",
   ko:"유기물이 부족할 때 그 연대 측정법은 전혀 정밀하지 않다.",
   blank:"far from precise",opts:["far from precisely","far to precise","far from being precisely"],
   note:"far from 뒤에는 형용사·명사·동명사가 온다. 부사(precisely)는 올 수 없다."},

  {pat:"nonetheless (그럼에도)",cat:"부정 표현",topic:"학문·연구",level:3,
   en:"The sample was small; the pattern was nonetheless consistent across all sites.",
   ko:"표본은 작았지만 그럼에도 그 양상은 모든 지점에서 일관되었다.",
   blank:"nonetheless consistent",opts:["nonetheless consistently","none the less consistently","nevertheless of consistent"],
   note:"nonetheless는 부사로 be동사 뒤에 놓이며, 뒤의 보어 자리에는 형용사가 온다."},

  {pat:"cannot be too ~ (아무리 ~해도 지나치지 않다)",cat:"부정 표현",topic:"과학·기술",level:4,
   en:"One cannot be too careful when handling the reagent.",
   ko:"그 시약을 다룰 때는 아무리 조심해도 지나치지 않다.",
   blank:"cannot be too careful",opts:["cannot be very careful","can not be too carefully","cannot too be careful"],
   note:"형태는 부정이지만 뜻은 강한 긍정 권고다. too 뒤에는 형용사가 온다."},

  {pat:"이중부정 (강한 긍정)",cat:"부정 표현",topic:"생물·의학",level:4,
   en:"No study has failed to find some seasonal effect.",
   ko:"계절 효과를 찾아내지 못한 연구는 하나도 없다.",
   blank:"No study has failed to find",opts:["No study has not failed to find","Any study has failed to find","No study did not fail to find"],
   note:"No와 failed 두 부정이 겹쳐 '모든 연구가 찾아냈다'는 강한 긍정이 된다. not을 더 넣으면 안 된다."},

  {pat:"not necessarily (부분부정)",cat:"부정 표현",topic:"언어·논증",level:2,
   en:"A strong correlation does not necessarily indicate a causal link.",
   ko:"강한 상관관계가 반드시 인과 관계를 뜻하는 것은 아니다.",
   blank:"does not necessarily indicate",opts:["does necessarily not indicate","not necessarily indicates","does not indicate necessarily any"],
   note:"not+necessarily는 '반드시 ~인 것은 아니다'라는 부분부정. 어순이 바뀌면 뜻이 달라진다."},

  {pat:"Not all (부분부정)",cat:"부정 표현",topic:"자연·환경",level:2,
   en:"Not all sediment layers preserve pollen, which complicates the reconstruction.",
   ko:"모든 퇴적층이 꽃가루를 보존하는 것은 아니어서 복원이 까다로워진다.",
   blank:"Not all sediment layers preserve",opts:["All sediment layers not preserve","Not any sediment layers preserve","No all sediment layers preserve"],
   note:"Not all은 '전부는 아니다'라는 부분부정. Not any는 전체부정이라 뜻이 완전히 달라진다."},

  {pat:"anything but (결코 ~이 아닌)",cat:"부정 표현",topic:"변화·수량",level:4,
   en:"The transition was anything but gradual; the record shows an abrupt shift.",
   ko:"그 이행은 결코 점진적이지 않았다. 기록은 급격한 변화를 보여 준다.",
   blank:"anything but gradual",opts:["anything than gradual","nothing but gradual","anything but gradually"],
   note:"anything but은 강한 부정(결코 ~아닌), nothing but은 '오직 ~일 뿐'으로 정반대 뜻이다."},

  {pat:"Little is known (부정어 주어)",cat:"부정 표현",topic:"생물·의학",level:2,
   en:"Little is known about how the species overwinters.",
   ko:"그 종이 어떻게 겨울을 나는지에 대해서는 알려진 바가 거의 없다.",
   blank:"Little is known",opts:["Little are known","A little is known","Few is known"],
   note:"Little은 불가산 개념을 받는 단수 주어로 '거의 없다'는 뜻. a little은 '조금 있다'로 긍정이다."},

  /* ───────── 인과·결과 ───────── */
  {pat:"so + 형용사 + that",cat:"인과·결과",topic:"자연·환경",level:2,
   en:"The canopy is so dense that almost no light reaches the understory.",
   ko:"수관이 너무 빽빽해서 하층 식생에는 빛이 거의 닿지 않는다.",
   blank:"so dense that",opts:["so dense as","such dense that","so densely that"],
   note:"「so+형용사/부사+that절」로 정도와 결과를 잇는다. 명사를 꾸밀 때만 such를 쓴다."},

  {pat:"such + a + 형용사 + 명사 + that",cat:"인과·결과",topic:"경제·경영",level:3,
   en:"It was such a sharp decline that regulators suspended trading.",
   ko:"하락이 워낙 가팔라서 규제 당국이 거래를 중단시켰다.",
   blank:"such a sharp decline that",opts:["so a sharp decline that","such sharp decline that","such a sharp decline as"],
   note:"명사구를 받을 때는 「such+a+형용사+명사+that」. 관사 a의 위치가 so 구문과 다르다."},

  {pat:"give rise to (~을 낳다)",cat:"인과·결과",topic:"사회·정치",level:3,
   en:"Rapid urbanization gave rise to sanitation problems that persisted for decades.",
   ko:"급속한 도시화는 수십 년간 이어진 위생 문제를 낳았다.",
   blank:"gave rise to",opts:["gave a rise to","gave rise for","raised rise to"],
   note:"give rise to는 관사 없이 굳어진 표현으로 '~을 일으키다'라는 뜻이다."},

  {pat:"account for (~을 차지하다/설명하다)",cat:"인과·결과",topic:"변화·수량",level:2,
   en:"Agriculture accounts for roughly seventy percent of global freshwater withdrawal.",
   ko:"농업은 전 세계 담수 취수량의 약 70퍼센트를 차지한다.",
   blank:"accounts for",opts:["accounts to","accounts of","account for"],
   note:"account for는 비율을 '차지하다' 또는 원인을 '설명하다'는 뜻. 주어가 단수라 accounts."},

  {pat:"result from vs result in",cat:"인과·결과",topic:"경제·경영",level:3,
   en:"The shortage resulted from a policy change rather than from any physical scarcity.",
   ko:"그 부족은 실제 자원 고갈이 아니라 정책 변화에서 비롯되었다.",
   blank:"resulted from",opts:["resulted in","resulted by","resulted of"],
   note:"result from은 원인을 가리키고(~에서 비롯되다), result in은 결과를 가리킨다(~을 낳다)."},

  {pat:"lead to (~로 이어지다)",cat:"인과·결과",topic:"자연·환경",level:1,
   en:"Prolonged drought can lead to irreversible loss of topsoil.",
   ko:"장기간의 가뭄은 표토의 되돌릴 수 없는 손실로 이어질 수 있다.",
   blank:"lead to",opts:["lead into","lead for","leading to"],
   note:"조동사 can 뒤에는 동사원형이 온다. lead to 뒤에는 명사(구)가 따른다."},

  {pat:"attribute A to B",cat:"인과·결과",topic:"생물·의학",level:3,
   en:"Researchers attribute the recovery to the ban on drift nets.",
   ko:"연구자들은 그 회복을 유자망 금지 조치의 결과로 본다.",
   blank:"attribute the recovery to",opts:["attribute the recovery for","attribute the recovery on","attribute to the recovery"],
   note:"「attribute+결과+to+원인」 어순이 고정이다. 원인 앞의 전치사는 반드시 to."},

  {pat:"Owing to ~ (~때문에)",cat:"인과·결과",topic:"학문·연구",level:3,
   en:"Owing to the loss of the original notebooks, the calculation cannot be verified.",
   ko:"원본 노트가 소실된 탓에 그 계산은 검증할 수 없다.",
   blank:"Owing to",opts:["Owing for","Owing that","Owe to"],
   note:"Owing to·Due to는 뒤에 명사구를 취한다. 절을 이으려면 Because를 써야 한다."},

  {pat:"thereby + 현재분사",cat:"인과·결과",topic:"자연·환경",level:4,
   en:"The dam altered the flow regime, thereby reducing sediment delivery to the delta.",
   ko:"그 댐은 유황을 바꾸었고 그로써 삼각주로 가는 퇴적물 공급을 줄였다.",
   blank:"thereby reducing",opts:["thereby reduced","thereby it reduces","thereby to reduce"],
   note:"thereby 뒤에는 현재분사가 이어져 '그럼으로써 ~하다'라는 결과를 나타낸다."},

  {pat:"consequently (따라서)",cat:"인과·결과",topic:"학문·연구",level:2,
   en:"The gauge failed in mid-season; consequently, the records for that year are incomplete.",
   ko:"계측기가 시즌 중반에 고장 났고, 따라서 그해 기록은 불완전하다.",
   blank:"consequently",opts:["consequent","consequential","consequence"],
   note:"결과를 잇는 접속부사 자리이므로 부사형을 쓴다. consequent·consequential은 형용사."},

  /* ───────── 목적·조건 ───────── */
  {pat:"so that + 조동사 (목적)",cat:"목적·조건",topic:"생물·의학",level:2,
   en:"The samples were frozen on site so that the DNA would remain intact.",
   ko:"DNA가 온전히 유지되도록 표본은 현장에서 냉동되었다.",
   blank:"so that the DNA would remain",opts:["so that the DNA remaining","so as the DNA would remain","so that the DNA to remain"],
   note:"목적의 so that 뒤에는 「주어+조동사(would/could/might)+동사원형」의 완전한 절이 온다."},

  {pat:"so as to + 동사원형",cat:"목적·조건",topic:"과학·기술",level:3,
   en:"The instrument was recalibrated monthly so as to minimize drift.",
   ko:"편차를 최소화하기 위해 그 장비는 매달 재보정되었다.",
   blank:"so as to minimize",opts:["so as minimize","so as to minimizing","so that to minimize"],
   note:"so as to는 in order to와 같은 목적 표현으로 뒤에 동사원형이 온다."},

  {pat:"lest + 주어 + 동사원형",cat:"목적·조건",topic:"역사·문화",level:4,
   en:"The excavation was documented at every stage lest crucial context be lost.",
   ko:"결정적인 맥락이 사라지지 않도록 발굴은 모든 단계가 기록되었다.",
   blank:"lest crucial context be lost",opts:["lest crucial context is lost","lest crucial context will be lost","lest crucial context be lose"],
   note:"lest는 '~하지 않도록'이라는 뜻으로 그 자체에 부정이 들어 있고 뒤에 동사원형(가정법 현재)이 온다."},

  {pat:"provided that (~라면)",cat:"목적·조건",topic:"학문·연구",level:3,
   en:"The method works well, provided that the sample is uncontaminated.",
   ko:"표본이 오염되지 않았다면 그 방법은 잘 작동한다.",
   blank:"provided that the sample is",opts:["provide that the sample is","providing of the sample is","provided that the sample being"],
   note:"provided/providing that은 if보다 조건을 뚜렷이 못 박는 표현으로 뒤에 완전한 절이 온다."},

  {pat:"Unless (~하지 않는 한)",cat:"목적·조건",topic:"자연·환경",level:2,
   en:"Unless the trend reverses, the aquifer will be depleted within a generation.",
   ko:"추세가 반전되지 않는 한 그 대수층은 한 세대 안에 고갈될 것이다.",
   blank:"Unless the trend reverses",opts:["Unless the trend does not reverse","Unless the trend will reverse","If the trend reverses not"],
   note:"unless에 이미 부정이 들어 있어 절 안에 not을 또 쓰지 않는다. 조건절이라 미래도 현재시제로."},

  {pat:"in case + 절 (~할 경우에 대비해)",cat:"목적·조건",topic:"학문·연구",level:3,
   en:"Duplicate cores were stored off site in case the primary archive was damaged.",
   ko:"주 보관소가 훼손될 경우에 대비해 중복 시료는 외부에 보관되었다.",
   blank:"in case the primary archive was damaged",opts:["in case of the primary archive was damaged","in case the primary archive damaged","in the case the primary archive was damaged"],
   note:"in case 뒤에는 절이 오고, in case of 뒤에는 명사구가 온다. 둘을 섞어 쓰지 않는다."},

  {pat:"as long as (~하는 한)",cat:"목적·조건",topic:"변화·수량",level:2,
   en:"The estimate holds as long as the deposition rate remains constant.",
   ko:"퇴적 속도가 일정하게 유지되는 한 그 추정치는 유효하다.",
   blank:"as long as the deposition rate remains",opts:["as long the deposition rate remains","as long as the deposition rate remaining","so long the deposition rate remains"],
   note:"as long as는 조건을 나타내는 접속사로 뒤에 완전한 절이 온다. as를 빠뜨리면 안 된다."},

  {pat:"Should + 주어 (if 생략)",cat:"목적·조건",topic:"사회·정치",level:4,
   en:"Should the funding lapse, the monitoring network will be dismantled.",
   ko:"만약 예산 지원이 끊긴다면 그 관측망은 해체될 것이다.",
   blank:"Should the funding lapse",opts:["Should the funding lapses","If should the funding lapse","Should the funding to lapse"],
   note:"If it should ~에서 If를 생략해 Should가 문두로 나온 도치. 뒤에는 동사원형이 온다."},

  {pat:"for fear that (~할까 봐)",cat:"목적·조건",topic:"역사·문화",level:4,
   en:"The site was left unpublished for fear that looters would target it.",
   ko:"도굴꾼들이 노릴까 봐 그 유적은 공개되지 않은 채 남겨졌다.",
   blank:"for fear that looters would target",opts:["for fear of looters would target","for fear that looters target","in fear that looters would targeting"],
   note:"for fear that 뒤에는 「주어+would/might+동사원형」이 온다. of를 쓰면 뒤에 명사구만 가능하다."},

  {pat:"only if (오직 ~인 경우에만)",cat:"목적·조건",topic:"과학·기술",level:3,
   en:"The model reproduces the record only if the volcanic forcing is included.",
   ko:"화산 강제력을 포함할 때에만 그 모형은 기록을 재현한다.",
   blank:"only if the volcanic forcing is",opts:["if only the volcanic forcing is","only if the volcanic forcing being","only when if the volcanic forcing is"],
   note:"only if는 '~인 경우에만'이라는 필요조건. if only는 '~이기만 하면'이라는 소망으로 뜻이 다르다."},

  /* ───────── 학술 관용표현 ───────── */
  {pat:"in light of (~에 비추어)",cat:"학술 관용표현",topic:"역사·문화",level:3,
   en:"In light of the revised chronology, several earlier claims must be reconsidered.",
   ko:"수정된 연대기에 비추어 볼 때 앞선 몇몇 주장은 재검토되어야 한다.",
   blank:"In light of",opts:["In the light for","In lights of","On light of"],
   note:"in light of는 '~을 고려하면'이라는 뜻으로 뒤에 명사구가 온다."},

  {pat:"with respect to (~에 관하여)",cat:"학술 관용표현",topic:"과학·기술",level:3,
   en:"The two samples differ markedly with respect to trace element composition.",
   ko:"두 표본은 미량 원소 조성에 관해 뚜렷이 다르다.",
   blank:"with respect to",opts:["with respect of","in respect for","with respective to"],
   note:"with respect to·with regard to는 논의 범위를 한정하는 학술 상용구다."},

  {pat:"on the grounds that (~라는 이유로)",cat:"학술 관용표현",topic:"언어·논증",level:4,
   en:"The proposal was rejected on the grounds that the sample size was inadequate.",
   ko:"그 제안은 표본 크기가 불충분하다는 이유로 기각되었다.",
   blank:"on the grounds that",opts:["on the ground of that","in the grounds that","on the grounds which"],
   note:"근거를 밝히는 표현으로 grounds는 항상 복수. 뒤에는 완전한 절이 온다."},

  {pat:"bear on (~와 관련되다)",cat:"학술 관용표현",topic:"학문·연구",level:4,
   en:"These findings bear directly on the debate over early domestication.",
   ko:"이 연구 결과들은 초기 가축화 논쟁과 직접적으로 관련된다.",
   blank:"bear directly on",opts:["bear directly to","bears directly on","bear directly for"],
   note:"bear on은 '~에 영향을 미치다·관련되다'는 뜻. 주어가 복수(findings)라 bear."},

  {pat:"at odds with (~와 상충하는)",cat:"학술 관용표현",topic:"학문·연구",level:4,
   en:"The new dates are at odds with the stratigraphic sequence.",
   ko:"새로 측정된 연대는 층서 순서와 어긋난다.",
   blank:"at odds with",opts:["at odd with","in odds with","at odds to"],
   note:"at odds with는 '~와 불일치하는'이라는 굳어진 표현으로 odds는 항상 복수형이다."},

  {pat:"subject to (~의 대상이 되는)",cat:"학술 관용표현",topic:"학문·연구",level:3,
   en:"All estimates are subject to revision as further cores are analyzed.",
   ko:"추가 시료가 분석되면 모든 추정치는 수정될 수 있다.",
   blank:"subject to revision",opts:["subject of revision","subject to revise","subjecting to revision"],
   note:"be subject to 뒤에는 명사(또는 동명사)가 온다. to는 부정사가 아닌 전치사다."},

  {pat:"in terms of (~의 측면에서)",cat:"학술 관용표현",topic:"경제·경영",level:2,
   en:"The two approaches differ less in terms of accuracy than in terms of cost.",
   ko:"두 접근법은 정확도 측면보다 비용 측면에서 더 크게 다르다.",
   blank:"in terms of accuracy",opts:["in term of accuracy","in terms for accuracy","on terms of accuracy"],
   note:"in terms of는 비교·평가의 기준을 밝히는 표현으로 terms는 항상 복수."},

  {pat:"as opposed to (~와 달리)",cat:"학술 관용표현",topic:"생물·의학",level:3,
   en:"The decline reflects reduced recruitment, as opposed to increased mortality.",
   ko:"그 감소는 사망률 증가가 아니라 개체 보충 감소를 반영한다.",
   blank:"as opposed to",opts:["as opposing to","as opposed from","in opposed to"],
   note:"as opposed to는 두 대안을 대비해 '~가 아니라'로 옮긴다. 뒤에 명사구·동명사가 온다."},

  {pat:"give way to (~에 자리를 내주다)",cat:"학술 관용표현",topic:"예술·문학",level:3,
   en:"Hand copying gave way to print within two generations.",
   ko:"필사는 두 세대 만에 인쇄에 자리를 내주었다.",
   blank:"gave way to",opts:["gave the way to","gave way for","gave away to"],
   note:"give way to는 관사 없이 쓰며 '~로 대체되다'는 뜻. give away(내주다)와 혼동하지 않는다."},

  {pat:"hold true (들어맞다)",cat:"학술 관용표현",topic:"성질·상태",level:3,
   en:"The relationship holds true only within a narrow temperature range.",
   ko:"그 관계는 좁은 온도 범위 안에서만 성립한다.",
   blank:"holds true",opts:["holds truly","hold true","holds a true"],
   note:"hold true는 「동사+보어」 구조라 형용사 true를 쓴다. 주어가 단수라 holds."},

  /* ───────── 담화 표지 ───────── */
  {pat:"albeit (비록 ~이지만)",cat:"담화 표지",topic:"과학·기술",level:4,
   en:"The technique is effective, albeit expensive for routine screening.",
   ko:"그 기법은 일상적 선별 검사로는 비싸긴 해도 효과적이다.",
   blank:"albeit expensive",opts:["albeit it expensive","albeit is expensive","albeit of expensive"],
   note:"albeit 뒤에는 절이 아니라 형용사구가 바로 온다. 주어·동사를 넣지 않는다."},

  {pat:"Notwithstanding (~에도 불구하고)",cat:"담화 표지",topic:"학문·연구",level:4,
   en:"Notwithstanding these limitations, the dataset remains the most complete available.",
   ko:"이러한 한계에도 불구하고 그 자료집은 현존하는 가장 완전한 것이다.",
   blank:"Notwithstanding these limitations",opts:["Notwithstanding of these limitations","Notwithstand these limitations","Notwithstanding that these limitations"],
   note:"Notwithstanding은 그 자체가 전치사라 of를 붙이지 않고 명사구를 바로 취한다."},

  {pat:"insofar as (~하는 한에서)",cat:"담화 표지",topic:"언어·논증",level:4,
   en:"The argument holds insofar as the assumptions about migration are correct.",
   ko:"이주에 관한 가정이 옳은 한에서 그 논증은 성립한다.",
   blank:"insofar as the assumptions",opts:["insofar that the assumptions","in so far the assumptions","insofar as of the assumptions"],
   note:"insofar as는 적용 범위를 한정하는 접속사로 뒤에 완전한 절이 온다."},

  {pat:"whereas (반면에)",cat:"담화 표지",topic:"역사·문화",level:2,
   en:"Coastal sites yielded abundant shell, whereas inland sites produced almost none.",
   ko:"연안 유적에서는 조개껍데기가 많이 나온 반면 내륙 유적에서는 거의 나오지 않았다.",
   blank:"whereas inland sites produced",opts:["whereas inland sites producing","whereas of inland sites produced","whereas do inland sites produce"],
   note:"whereas는 두 절을 대조하는 접속사다. 도치되지 않고 평서문 어순을 유지한다."},

  {pat:"hence (그러므로)",cat:"담화 표지",topic:"학문·연구",level:3,
   en:"The layers are undisturbed; hence the sequence can be read directly.",
   ko:"지층이 교란되지 않았으므로 그 순서를 그대로 읽어 낼 수 있다.",
   blank:"hence the sequence can be read",opts:["hence of the sequence can be read","hence the sequence can read","hence to the sequence can be read"],
   note:"hence는 접속부사로 뒤에 완전한 절이 온다. 순서가 '읽히는' 것이므로 수동태."},

  {pat:"conversely (거꾸로)",cat:"담화 표지",topic:"생물·의학",level:3,
   en:"Warmer winters favor the beetle; conversely, prolonged frost suppresses outbreaks.",
   ko:"따뜻한 겨울은 그 딱정벌레에 유리하고, 반대로 긴 서리는 대발생을 억제한다.",
   blank:"conversely, prolonged frost suppresses",opts:["conversely of, prolonged frost suppresses","converse, prolonged frost suppresses","conversely, prolonged frost suppress"],
   note:"conversely는 앞뒤를 뒤집어 대비하는 접속부사. 주어 frost가 단수라 suppresses."},

  {pat:"By contrast (그에 반해)",cat:"담화 표지",topic:"자연·환경",level:2,
   en:"By contrast, the southern basin shows no comparable enrichment.",
   ko:"그에 반해 남쪽 분지에서는 비교할 만한 농집이 나타나지 않는다.",
   blank:"By contrast,",opts:["By the contrast,","In contrast of,","By contrary,"],
   note:"By contrast는 문두에서 앞 문장과 대비를 표시한다. In contrast to+명사와 형태가 다르다."},

  {pat:"That said (그렇다고는 해도)",cat:"담화 표지",topic:"언어·논증",level:3,
   en:"The correlation is robust. That said, the mechanism remains speculative.",
   ko:"그 상관관계는 견고하다. 그렇다고는 해도 메커니즘은 여전히 추정에 머문다.",
   blank:"That said,",opts:["That saying,","That is said,","Those said,"],
   note:"That said는 앞 내용을 인정한 뒤 단서를 다는 굳어진 표현으로 형태가 변하지 않는다."},

  {pat:"To the extent that (~하는 만큼)",cat:"담화 표지",topic:"학문·연구",level:4,
   en:"To the extent that the record is complete, it supports a gradual model.",
   ko:"그 기록이 완전한 만큼은 점진적 모형을 뒷받침한다.",
   blank:"To the extent that",opts:["To the extent which","In the extent that","To the extend that"],
   note:"조건의 정도를 한정하는 표현. extend(동사)가 아니라 extent(명사)임에 주의."},

  {pat:"not A but rather B",cat:"담화 표지",topic:"역사·문화",level:3,
   en:"The shift was not a replacement but rather a gradual blending of traditions.",
   ko:"그 변화는 대체가 아니라 오히려 전통들의 점진적 융합이었다.",
   blank:"but rather a gradual blending",opts:["but rather of a gradual blending","but rather gradual blending of","but rather to a gradual blending"],
   note:"「not A but rather B」에서 A와 B는 같은 형태로 맞춘다. 앞이 a replacement이므로 뒤도 관사+명사구."},

  /* ───────── 주제 보강 (심리·감정 / 행동·관계 / 성질·상태 / 예술·문학) ───────── */
  {pat:"Little did + 주어 + 동사원형",cat:"도치·강조",topic:"심리·감정",level:4,
   en:"Little did the researchers suspect that the effect would reverse under stress.",
   ko:"연구자들은 그 효과가 스트레스 상황에서 역전되리라고는 전혀 예상하지 못했다.",
   blank:"Little did the researchers suspect",opts:["Little the researchers suspected","Little did the researchers suspected","Little have the researchers suspect"],
   note:"부정어 Little이 문두에 오면 도치된다. did 뒤에는 반드시 동사원형이 온다."},

  {pat:"Of + 추상명사 + be (도치)",cat:"도치·강조",topic:"성질·상태",level:4,
   en:"Of particular interest is the material's behavior near the phase boundary.",
   ko:"특히 흥미로운 것은 상 경계 부근에서 그 물질이 보이는 거동이다.",
   blank:"Of particular interest is",opts:["Of particular interest are","Of particular interest it is","In particular interest is"],
   note:"「Of+추상명사」는 형용사(=particularly interesting) 역할을 하며, 문두로 나가면 도치된다. 주어 behavior가 단수라 is."},

  {pat:"전치사 + whom",cat:"관계절",topic:"행동·관계",level:3,
   en:"The colleagues with whom she collaborated most closely later disputed the findings.",
   ko:"그가 가장 가깝게 협업했던 동료들이 훗날 그 연구 결과에 이의를 제기했다.",
   blank:"with whom she collaborated",opts:["with who she collaborated","with whom she collaborated with","whom she collaborated with them"],
   note:"전치사 뒤의 사람 선행사는 who가 아니라 whom. 전치사를 앞으로 뺐으면 뒤에 또 쓰지 않는다."},

  {pat:"비교급 + than + 절",cat:"비교·대조",topic:"심리·감정",level:3,
   en:"Anxiety impairs recall less than it impairs planning.",
   ko:"불안은 계획 능력보다 회상 능력을 덜 손상시킨다.",
   blank:"less than it impairs",opts:["less as it impairs","lesser than it impairs","less than it impair"],
   note:"than 뒤에 완전한 절이 올 수 있다. less의 짝은 as가 아니라 than이며 lesser는 다른 뜻."},

  {pat:"비교급 + than + 주어 + be (두 속성 대비)",cat:"비교·대조",topic:"성질·상태",level:3,
   en:"The coating is more durable than it is attractive.",
   ko:"그 코팅은 보기 좋다기보다는 내구성이 좋다.",
   blank:"more durable than it is",opts:["more durable than it does","more durable as it is","durabler than it is"],
   note:"한 대상의 두 속성을 견줄 때는 「more A than it is B」를 쓴다. 음절이 길어 durabler는 불가."},

  {pat:"so as not to + 동사원형",cat:"목적·조건",topic:"행동·관계",level:3,
   en:"The pairs were separated so as not to bias each other's responses.",
   ko:"서로의 응답에 영향을 주지 않도록 짝들은 분리되었다.",
   blank:"so as not to bias",opts:["so as to not bias","so not as to bias","so as not biasing"],
   note:"so as to의 부정은 not을 to 앞에 둔다. to와 동사원형 사이를 가르지 않는 것이 원칙."},

  {pat:"대시 삽입 + 독립분사",cat:"삽입·동격",topic:"예술·문학",level:4,
   en:"The novel — its author never named — circulated in manuscript for a decade.",
   ko:"저자가 끝내 밝혀지지 않은 그 소설은 10년간 필사본으로 유통되었다.",
   blank:"its author never named",opts:["its author was never named","it author never named","its author never naming"],
   note:"대시 사이에 「의미상 주어+과거분사」를 넣은 독립분사구문. 정동사(was)를 쓰면 문장이 겹친다."},

  {pat:"no longer (더 이상 ~않다)",cat:"부정 표현",topic:"심리·감정",level:2,
   en:"The distinction between memory and imagination is no longer regarded as sharp.",
   ko:"기억과 상상의 구분은 더 이상 뚜렷한 것으로 여겨지지 않는다.",
   blank:"no longer regarded",opts:["not longer regarded","no long regarded","no longer regarding"],
   note:"no longer가 하나의 부정 부사구다. not longer로 쪼개 쓰지 않으며 뒤는 수동의 과거분사."},

  {pat:"in the absence of (~이 없으면)",cat:"학술 관용표현",topic:"행동·관계",level:3,
   en:"Cooperation tends to break down in the absence of repeated encounters.",
   ko:"반복적인 만남이 없으면 협력은 무너지는 경향이 있다.",
   blank:"in the absence of",opts:["in absence of","in the absent of","on the absence of"],
   note:"in the absence of는 관사 the가 붙어 굳어진 표현이다. absent는 형용사라 이 자리에 올 수 없다."},

  {pat:"if not ~ (~까지는 아니어도)",cat:"담화 표지",topic:"예술·문학",level:4,
   en:"The style is unmistakably late, if not demonstrably his own.",
   ko:"그 문체는 그의 것임이 입증되지는 않더라도 후기 양식임은 분명하다.",
   blank:"if not demonstrably",opts:["if not demonstrable","if no demonstrably","if not to demonstrably"],
   note:"if not은 앞의 표현보다 한 단계 강한 가능성을 덧붙인다. 뒤의 형태는 앞(unmistakably)과 맞춘다."},

];
