/* ============================================================
   관심주제 리딩 — 기술·IT 20편
   ------------------------------------------------------------
   🌱 스프링·백엔드 7편 / ⚙️ 소프트웨어 공학 7편 / 🤖 인공지능 6편

   기술 문서 요약이 아니라, 각 기술이 무슨 문제를 풀려고
   나왔고 그 대가로 무엇을 내주는지를 따지는 글이다.
   문장 수준과 문제 유형은 실제 TOEFL·TOEIC 그대로 유지했다.
   ============================================================ */
window.TOPIC_READING_EXTRA = (window.TOPIC_READING_EXTRA||[]).concat([

/* ═══════════ 🌱 스프링 · 백엔드 ═══════════ */

{id:"sp-ioc", exam:"TOEFL", type:"설계·원리", level:3,
 series:"🌱 스프링·백엔드", title:"Why Spring Chose Inversion of Control",
 topic:"스프링은 왜 제어를 뒤집었나",
 passage:"Before dependency injection became standard practice, an object that needed a database connection typically created one itself. The code that used a service also decided which implementation of that service would exist. This arrangement seems economical, but it fuses two responsibilities that have no reason to be joined: deciding what work to do, and deciding which collaborators will do it.\n\nThe consequence appears first in testing. A class that constructs its own database connection cannot be exercised without a database. Substituting a fake requires editing the class under test, which means the version being tested is no longer the version that will run in production. Teams working this way tend to test very little, and they usually describe the situation as a shortage of time rather than as a consequence of design.\n\nInversion of control moves the decision outward. The class declares what it needs and receives it from elsewhere — in Spring's case, a container that reads configuration and assembles the object graph before the application begins serving requests. Because the class never names a concrete implementation, a different one can be supplied without the class being touched.\n\nThe word inversion refers to the direction of control, not to its disappearance. Somebody still chooses the implementation; the choice has simply moved from the consumer to a place where it can be changed centrally. Critics observe that this makes the flow of a program harder to follow, since the wiring is no longer visible at the point where an object is used. The trade is deliberate. Legibility at the call site is exchanged for the ability to reconfigure a system without recompiling the parts that do the actual work.",
 ko:"의존성 주입이 표준 관행이 되기 전에는, 데이터베이스 커넥션이 필요한 객체가 대개 그것을 직접 만들었다. 어떤 서비스를 쓰는 코드가 그 서비스의 어떤 구현체가 존재할지까지 결정했다. 경제적으로 보이는 배치이지만, 이는 함께 묶일 이유가 없는 두 책임을 융합한다. 무슨 일을 할지 정하는 것과, 어떤 협력 객체가 그 일을 할지 정하는 것이다.\n\n그 결과는 우선 테스트에서 드러난다. 자기 데이터베이스 커넥션을 직접 만드는 클래스는 데이터베이스 없이 실행해 볼 수 없다. 가짜 객체로 바꾸려면 테스트 대상 클래스를 고쳐야 하는데, 그러면 테스트한 버전이 실제로 운영에서 돌아갈 버전과 달라진다. 이런 식으로 작업하는 팀은 테스트를 거의 하지 않는 경향이 있고, 대개 그 상황을 설계의 결과가 아니라 시간 부족이라고 설명한다.\n\n제어의 역전은 그 결정을 바깥으로 옮긴다. 클래스는 자기에게 필요한 것을 선언하고 다른 곳에서 그것을 건네받는다. 스프링의 경우에는 설정을 읽어 애플리케이션이 요청을 처리하기 전에 객체 그래프를 조립하는 컨테이너가 그 역할을 한다. 클래스가 구체 구현체의 이름을 결코 부르지 않기 때문에, 클래스를 건드리지 않고도 다른 구현체를 넣을 수 있다.\n\n'역전'이라는 말은 제어가 사라졌다는 뜻이 아니라 제어의 방향을 가리킨다. 여전히 누군가는 구현체를 고른다. 다만 그 선택이 사용하는 쪽에서 중앙에서 바꿀 수 있는 자리로 옮겨 갔을 뿐이다. 비판자들은 이 때문에 프로그램의 흐름을 따라가기가 더 어려워진다고 지적한다. 배선이 객체를 쓰는 지점에서는 더 이상 보이지 않기 때문이다. 이 교환은 의도적이다. 호출 지점의 가독성을 내주고, 실제 일을 하는 부분을 다시 컴파일하지 않고도 시스템을 재구성할 수 있는 능력을 얻는 것이다.",
 gloss:[{w:"fuse",ko:"융합하다, 하나로 묶다"},{w:"collaborator",ko:"협력 객체"},{w:"exercise",ko:"(코드를) 실행해 보다"},{w:"substitute",ko:"대체하다"},{w:"assemble",ko:"조립하다"},{w:"legibility",ko:"가독성"},{w:"call site",ko:"호출 지점"},{w:"deliberate",ko:"의도적인"}],
 qs:[
  {q:"According to the passage, what problem arises first when a class creates its own dependencies?",
   opts:["The application consumes more memory at startup.",
         "The container becomes unable to read its configuration.",
         "The class cannot be exercised without the real collaborator it constructs.",
         "The class grows too small to be useful."],
   ans:2,exp:"2문단 첫 두 문장. 자기 DB 커넥션을 만드는 클래스는 DB 없이는 실행해 볼 수 없고, 그래서 테스트에서 문제가 먼저 드러난다고 했다."},
  {q:"The word inversion in the passage refers to",
   opts:["a change in which part of the system makes a choice",
         "the removal of control from the program entirely",
         "the reversal of the order in which methods execute",
         "the elimination of all configuration files"],
   ans:0,exp:"4문단 첫 두 문장이 직접 정의한다. 제어가 사라진 것이 아니라 선택하는 주체의 위치가 옮겨 간 것이다."},
  {q:"Which criticism of inversion of control does the passage acknowledge?",
   opts:["It requires substantially more memory at runtime.",
         "It prevents teams from writing any tests at all.",
         "It forces every class to name a concrete implementation.",
         "It makes a program's flow harder to trace because the wiring is not visible where an object is used."],
   ans:3,exp:"4문단의 'Critics observe that ~' 문장. 배선이 사용 지점에서 보이지 않아 흐름 추적이 어려워진다는 지적이다."},
  {q:"The passage implies that teams describing their testing problem as a shortage of time",
   opts:["are correct, since testing genuinely takes longer than writing code",
         "may in fact be facing a design problem that makes testing expensive",
         "should hire more engineers before attempting to write tests",
         "have usually adopted dependency injection already"],
   ans:1,exp:"2문단 마지막 문장이 '설계의 결과가 아니라 시간 부족이라고 설명한다'고 대비시킨다. 원인을 잘못 짚고 있다는 함의다."}
 ]},

{id:"sp-proxy", exam:"TOEFL", type:"구현·함정", level:4,
 series:"🌱 스프링·백엔드", title:"The Annotation That Does Nothing",
 topic:"동작하지 않는 애노테이션 — 프록시의 한계",
 passage:"A developer marks a method with an annotation declaring that it must run inside a transaction. The application starts without complaint. Under load, the database records show that the method has been committing partial work for months. The annotation was present, correct, and inert.\n\nThe explanation lies in how the framework applies such declarations. Spring does not rewrite the annotated class. It wraps the object in a proxy — a second object that presents the same interface, performs the additional behaviour, and then delegates to the original. Every call arriving from outside passes through the proxy and receives the transaction. A call that originates inside the object, however, invokes the method directly on the target instance, bypassing the wrapper entirely. The annotation is never consulted because the code path that would consult it was never entered.\n\nWhat makes this failure durable is that nothing reports it. A misspelled annotation is a compile error; a missing bean is a startup failure. Self-invocation produces a system that runs correctly in every respect except the one that was declared, and it does so silently. Developers commonly discover the problem only when reconciling inconsistent data long after the fact.\n\nThe episode illustrates a general property of declarative frameworks. A declaration is a request to an intermediary, and the request is honoured only along the paths the intermediary controls. Understanding a framework therefore means understanding not only what its annotations promise but where those promises are actually enforced — a boundary that documentation tends to state briefly and readers tend to skip.",
 ko:"한 개발자가 어떤 메서드에 트랜잭션 안에서 실행되어야 한다고 선언하는 애노테이션을 붙인다. 애플리케이션은 아무 불평 없이 기동한다. 부하가 걸린 상태에서 데이터베이스 기록을 보니, 그 메서드는 몇 달째 작업을 절반만 커밋해 왔다. 애노테이션은 붙어 있었고, 철자도 맞았고, 아무 일도 하지 않았다.\n\n설명은 프레임워크가 그런 선언을 적용하는 방식에 있다. 스프링은 애노테이션이 붙은 클래스를 다시 쓰지 않는다. 대신 객체를 프록시로 감싼다. 같은 인터페이스를 내보이고, 추가 동작을 수행한 뒤, 원래 객체에 위임하는 두 번째 객체다. 바깥에서 들어오는 모든 호출은 프록시를 거치며 트랜잭션을 받는다. 그러나 객체 내부에서 시작된 호출은 대상 인스턴스의 메서드를 직접 부르며 감싸개를 통째로 건너뛴다. 애노테이션을 참조하는 코드 경로에 애초에 들어가지 않았으므로 애노테이션은 조회되지도 않는다.\n\n이 실패를 오래 살아남게 만드는 것은 아무것도 그것을 보고하지 않는다는 점이다. 애노테이션 철자가 틀리면 컴파일 오류가 나고, 빈이 없으면 기동 실패가 난다. 자기 호출은 선언된 그 한 가지만 빼고 모든 면에서 정상적으로 돌아가는 시스템을 만들어 내며, 그것도 조용히 그렇게 한다. 개발자들은 대개 한참 뒤 어긋난 데이터를 맞춰 보다가 문제를 발견한다.\n\n이 일화는 선언적 프레임워크의 일반적 성질을 보여 준다. 선언이란 중개자에게 보내는 요청이고, 그 요청은 중개자가 통제하는 경로에서만 지켜진다. 따라서 프레임워크를 이해한다는 것은 애노테이션이 무엇을 약속하는지뿐 아니라 그 약속이 실제로 어디에서 강제되는지를 아는 것이다. 문서가 짧게만 언급하고 독자는 건너뛰기 쉬운 바로 그 경계다.",
 gloss:[{w:"inert",ko:"작동하지 않는, 무력한"},{w:"delegate",ko:"위임하다"},{w:"bypass",ko:"우회하다, 건너뛰다"},{w:"consult",ko:"참조하다, 조회하다"},{w:"durable",ko:"오래 지속되는"},{w:"reconcile",ko:"(어긋난 것을) 맞춰 보다, 대조하다"},{w:"intermediary",ko:"중개자"},{w:"enforce",ko:"강제하다, 시행하다"}],
 qs:[
  {q:"Why does the annotation fail to take effect in the case described?",
   opts:["The annotation was spelled incorrectly and the compiler ignored it.",
         "The call came from inside the object and therefore never passed through the proxy.",
         "The database rejected the transaction because of heavy load.",
         "The framework had not finished assembling the object graph."],
   ans:1,exp:"2문단. 내부에서 시작된 호출은 대상 인스턴스를 직접 부르므로 프록시(감싸개)를 건너뛴다."},
  {q:"According to the passage, what makes this particular failure especially persistent?",
   opts:["It occurs only on systems under extremely heavy load.",
         "It can be fixed only by rewriting the annotated class.",
         "It is documented nowhere in the framework's manuals.",
         "It produces no error signal, so the system appears to work normally."],
   ans:3,exp:"3문단. 철자 오류는 컴파일 오류로, 빈 누락은 기동 실패로 즉시 드러나지만 자기 호출은 '조용히' 지나간다."},
  {q:"The word inert in the first paragraph is closest in meaning to",
   opts:["having no effect","incorrectly written","recently added","difficult to read"],
   ans:0,exp:"바로 앞에 'present, correct'가 나열되어 있다. 붙어 있고 철자도 맞았는데 '아무 효력이 없었다'는 대조다."},
  {q:"What general lesson about declarative frameworks does the final paragraph draw?",
   opts:["Declarations should always be replaced with explicit procedural code.",
         "Framework documentation is generally unreliable and should be ignored.",
         "A declaration holds only along the paths that the intermediary actually controls.",
         "Proxies should be avoided in any system that handles transactions."],
   ans:2,exp:"마지막 문단의 두 번째 문장이 그대로 일반화한다. 약속이 지켜지는 '경계'를 아는 것이 이해라고 했다."}
 ]},

{id:"sp-boot", exam:"TOEFL", type:"역사·설계", level:3,
 series:"🌱 스프링·백엔드", title:"What Convention Bought, and What It Cost",
 topic:"설정보다 관례 — 스프링 부트가 산 것과 치른 값",
 passage:"Early Spring applications were configured in XML. A modest web service might require several hundred lines describing which objects existed, what they depended on, and how requests should be routed. The configuration was explicit and complete: a reader could determine the entire structure of the application by reading it. It was also tedious, easy to get wrong, and almost identical from one project to the next.\n\nThat last observation is the one the framework's authors acted on. If nearly every project declares the same components in the same way, the declarations carry little information. Spring Boot replaced them with defaults that activate according to what is present. Find a database driver on the classpath, and a connection pool is configured. Find a web server library, and an embedded server starts. The developer writes configuration only where the project departs from the ordinary.\n\nThe gain is not merely fewer lines. It is that the remaining lines describe what is distinctive about the application, which is exactly the part a reader needs. The cost is that the default behaviour is now invisible. A newcomer cannot read the project and learn what it does, because most of what it does was never written down in it.\n\nThis is a familiar bargain rather than a novel one. Build tools, package managers, and operating system installers all trade explicitness for defaults, and all produce the same class of difficulty: when a default is wrong, the person debugging it must first discover that the default exists. Frameworks that make this bargain well are distinguished less by having good defaults than by making it cheap to find out which defaults are in force.",
 ko:"초기 스프링 애플리케이션은 XML로 설정했다. 크지 않은 웹 서비스도 어떤 객체가 존재하는지, 무엇에 의존하는지, 요청을 어떻게 라우팅할지 기술하는 데 수백 줄이 필요할 수 있었다. 그 설정은 명시적이고 완전했다. 읽는 사람은 그것만 읽고도 애플리케이션의 전체 구조를 파악할 수 있었다. 동시에 지루했고, 틀리기 쉬웠고, 프로젝트마다 거의 똑같았다.\n\n프레임워크 제작자들이 손을 댄 것은 마지막 관찰이다. 거의 모든 프로젝트가 같은 구성요소를 같은 방식으로 선언한다면, 그 선언이 담은 정보는 별로 없다. 스프링 부트는 그것을 무엇이 존재하는지에 따라 켜지는 기본값으로 대체했다. 클래스패스에서 데이터베이스 드라이버를 찾으면 커넥션 풀이 설정된다. 웹 서버 라이브러리를 찾으면 내장 서버가 뜬다. 개발자는 프로젝트가 통상적인 것에서 벗어나는 지점에만 설정을 쓴다.\n\n얻은 것은 단지 줄 수가 줄었다는 것이 아니다. 남은 줄들이 이 애플리케이션의 무엇이 특별한지를 기술한다는 점이고, 그것이 바로 읽는 사람에게 필요한 부분이다. 치른 값은 이제 기본 동작이 보이지 않는다는 것이다. 새로 온 사람은 프로젝트를 읽고도 이것이 무엇을 하는지 알 수 없다. 하는 일의 대부분이 애초에 그 안에 적히지 않았기 때문이다.\n\n이는 새로운 거래가 아니라 익숙한 거래다. 빌드 도구, 패키지 관리자, 운영체제 설치 프로그램이 모두 명시성을 기본값과 맞바꾸며, 모두 같은 종류의 어려움을 낳는다. 기본값이 틀렸을 때, 디버깅하는 사람은 먼저 그 기본값이 존재한다는 사실부터 알아내야 한다. 이 거래를 잘 해내는 프레임워크는 좋은 기본값을 가졌다는 점보다, 지금 어떤 기본값이 적용되고 있는지 알아내는 비용이 싸다는 점에서 구별된다.",
 gloss:[{w:"tedious",ko:"지루한, 성가신"},{w:"depart from",ko:"~에서 벗어나다"},{w:"distinctive",ko:"특징적인, 구별되는"},{w:"bargain",ko:"거래, 흥정"},{w:"explicitness",ko:"명시성"},{w:"in force",ko:"효력이 있는, 적용 중인"},{w:"classpath",ko:"클래스패스(라이브러리 탐색 경로)"},{w:"embedded",ko:"내장된"}],
 qs:[
  {q:"What observation about XML configuration led to the change described?",
   opts:["It was too short to describe complex applications.",
         "It could not express dependencies between objects.",
         "It slowed applications down at runtime.",
         "It was nearly identical across projects and therefore carried little information."],
   ans:3,exp:"1문단 마지막과 2문단 첫 두 문장이 이어진다. '프로젝트마다 거의 똑같다'는 관찰에 손을 댄 것이다."},
  {q:"According to the passage, the main benefit of auto-configuration is that",
   opts:["applications start considerably faster",
         "developers no longer need to understand the framework",
         "the configuration that remains describes what is distinctive about the project",
         "errors in configuration become impossible"],
   ans:2,exp:"3문단 첫 두 문장. 줄 수가 준 것이 아니라 '남은 줄이 특별한 부분을 기술한다'는 것이 핵심 이득이다."},
  {q:"The passage compares Spring Boot to build tools and package managers in order to",
   opts:["argue that Spring Boot borrowed its design directly from them",
         "show that the trade-off it makes is a common one with a predictable cost",
         "suggest that all such tools should be replaced",
         "explain why XML configuration disappeared"],
   ans:1,exp:"4문단. '새로운 거래가 아니라 익숙한 거래'이며 모두 같은 종류의 어려움을 낳는다고 했다."},
  {q:"By what standard does the passage judge frameworks that rely on defaults?",
   opts:["How cheaply a developer can discover which defaults are currently applied",
         "Whether their defaults are correct in the largest number of cases",
         "How few lines of configuration they require in total",
         "Whether they allow defaults to be disabled entirely"],
   ans:0,exp:"마지막 문장이 기준을 명시한다. 좋은 기본값보다 '어떤 기본값이 적용 중인지 알아내는 비용'이 판별 기준이다."}
 ]},

{id:"sp-layer", exam:"TOEFL", type:"구조·설계", level:3,
 series:"🌱 스프링·백엔드", title:"Layers That Do Not Leak",
 topic:"새지 않는 계층 — 백엔드 구조의 규율",
 passage:"Most server applications are described as having three layers: one that receives requests, one that carries out business rules, and one that stores and retrieves data. Drawn as a diagram, the arrangement is obvious enough that teams rarely discuss it. In running code, it survives or collapses on a single question — whether a type defined for one layer is allowed to appear in another.\n\nThe pressure to let it appear is constant, because the shortcut always looks harmless. An entity class already has every field the response needs, so returning it directly saves writing a second class that says almost the same thing. The saving is real on the day it is taken. What follows is that the database schema and the public interface of the service become the same object. Renaming a column now changes the contract that external clients depend on, and adding an internal field now exposes it to anyone who calls the endpoint.\n\nThe discipline that prevents this is unglamorous: define a separate type at the boundary and translate. The cost is a class that looks redundant and a mapping step that appears to do nothing. Junior developers regularly propose removing both, and the proposal is difficult to refuse on the evidence available, since the duplication is visible and the coupling it prevents is not.\n\nThe argument for the boundary is therefore an argument about rates of change. Two things that appear identical today should still be kept apart if they will be changed by different people, for different reasons, on different schedules. That criterion, rather than the present shape of the data, is what determines whether a layer is real or merely drawn.",
 ko:"대부분의 서버 애플리케이션은 세 계층을 가진다고 설명된다. 요청을 받는 계층, 업무 규칙을 수행하는 계층, 데이터를 저장하고 꺼내는 계층이다. 그림으로 그려 놓으면 너무 당연해 보여서 팀에서 따로 논의하는 일이 드물다. 그러나 돌아가는 코드에서 이 구조는 단 하나의 질문에 따라 살아남거나 무너진다. 한 계층을 위해 정의된 타입이 다른 계층에 나타나도 되는가 하는 질문이다.\n\n나타나게 두려는 압력은 늘 있다. 지름길이 언제나 무해해 보이기 때문이다. 엔티티 클래스에는 응답에 필요한 필드가 이미 다 있으니, 그것을 그대로 반환하면 거의 같은 말을 하는 두 번째 클래스를 쓰는 수고를 던다. 그 절약은 그것을 취한 날에는 실제 이득이다. 뒤따르는 것은 데이터베이스 스키마와 서비스의 공개 인터페이스가 같은 객체가 된다는 사실이다. 이제 컬럼 이름을 바꾸면 외부 클라이언트가 의존하는 계약이 바뀌고, 내부용 필드를 하나 추가하면 그 엔드포인트를 호출하는 누구에게나 그것이 노출된다.\n\n이를 막는 규율은 멋이 없다. 경계에 별도의 타입을 정의하고 변환하는 것이다. 대가는 중복처럼 보이는 클래스 하나와 아무 일도 안 하는 것처럼 보이는 매핑 단계다. 주니어 개발자들은 이 둘을 없애자고 정기적으로 제안하고, 눈앞의 증거만으로는 그 제안을 반박하기 어렵다. 중복은 눈에 보이고, 그 중복이 막고 있는 결합은 보이지 않기 때문이다.\n\n따라서 경계를 두자는 주장은 변화 속도에 관한 주장이다. 오늘 똑같아 보이는 두 가지라도, 서로 다른 사람이 서로 다른 이유로 서로 다른 일정에 바꿀 것이라면 떼어 놓아야 한다. 계층이 실제로 존재하는지 아니면 그림으로만 그려져 있는지를 가르는 것은 지금 데이터의 모양이 아니라 바로 그 기준이다.",
 gloss:[{w:"collapse",ko:"무너지다"},{w:"shortcut",ko:"지름길, 편법"},{w:"schema",ko:"(데이터베이스) 스키마"},{w:"contract",ko:"계약, (인터페이스의) 약속"},{w:"unglamorous",ko:"멋없는, 볼품없는"},{w:"redundant",ko:"불필요하게 중복된"},{w:"coupling",ko:"결합(도)"},{w:"criterion",ko:"기준"}],
 qs:[
  {q:"According to the passage, what single question determines whether the three-layer structure holds in practice?",
   opts:["Whether a type defined for one layer may appear in another",
         "How many classes each layer contains",
         "Which layer receives incoming requests first",
         "How often the database schema is modified"],
   ans:0,exp:"1문단 마지막 문장이 그 질문을 그대로 제시한다."},
  {q:"What consequence follows from returning an entity class directly to clients?",
   opts:["The application takes longer to respond to each request.",
         "The database schema and the service's public interface become the same object.",
         "The business rules layer can no longer be tested.",
         "External clients must write their own mapping code."],
   ans:1,exp:"2문단 중반. 그 결과 컬럼 이름 변경이 외부 계약 변경이 되고 내부 필드가 노출된다."},
  {q:"Why is it difficult to refuse the proposal to remove the boundary type?",
   opts:["Junior developers usually have more experience with the framework.",
         "The mapping step measurably slows the application down.",
         "The duplication is visible while the coupling it prevents is not.",
         "Most teams have no way to test the boundary type."],
   ans:2,exp:"3문단 마지막 문장이 이유를 명시한다. 눈앞의 증거가 한쪽으로만 기울어 있다."},
  {q:"The final paragraph argues that two things should be kept separate when they",
   opts:["contain different fields today",
         "are stored in different databases",
         "are written in different programming languages",
         "will be changed by different people, for different reasons, on different schedules"],
   ans:3,exp:"마지막 문단의 두 번째 문장 그대로다. 판단 기준은 현재 모양이 아니라 변화의 속도와 주체다."}
 ]},

{id:"sp-nplus1", exam:"TOEFL", type:"성능·데이터", level:4,
 series:"🌱 스프링·백엔드", title:"One Query, Then a Hundred More",
 topic:"N+1 문제 — 편리함이 청구서를 늦게 보내는 방식",
 passage:"An object-relational mapper allows a developer to treat rows in a database as ordinary objects. Navigating from an order to its customer is written as a field access, and the framework issues whatever query that access requires. The abstraction is convincing enough that developers stop thinking about queries at all, which is precisely the condition under which the N+1 problem appears.\n\nThe mechanism is simple. A page lists one hundred orders, retrieved in a single query. For each order the template displays the customer's name, and each of those accesses triggers a separate query for a customer that was not loaded. One query becomes a hundred and one. In development, against a local database holding twenty rows, the page is instantaneous. In production the same page becomes the slowest endpoint in the system, and the profile shows no single expensive operation — only a very large number of cheap ones.\n\nWhat makes the defect instructive is that it is not a mistake in the ordinary sense. Nothing in the code is incorrect, and no rule of the framework has been violated. The cost is produced by the interaction between a lazy loading strategy, which is the sensible default, and an access pattern that the strategy did not anticipate. Neither party is wrong on its own.\n\nRemedies exist — fetching the association eagerly for this query, or loading customers in a second batched query — but each is a decision about a particular use, not a global setting. This is the durable lesson. An abstraction that hides cost does not remove it; it relocates the moment at which the cost must be reasoned about, usually to a later date and a less convenient place.",
 ko:"객체-관계 매퍼는 개발자가 데이터베이스의 행을 평범한 객체처럼 다루게 해 준다. 주문에서 고객으로 넘어가는 일은 필드 접근으로 쓰이고, 그 접근에 필요한 질의는 프레임워크가 알아서 날린다. 이 추상은 충분히 설득력이 있어서 개발자는 질의라는 것을 아예 생각하지 않게 되는데, 바로 그 상태가 N+1 문제가 나타나는 조건이다.\n\n원리는 간단하다. 한 페이지가 주문 100건을 한 번의 질의로 가져와 나열한다. 각 주문마다 템플릿이 고객 이름을 보여 주고, 그 접근 하나하나가 아직 로딩되지 않은 고객을 가져오는 별도의 질의를 유발한다. 질의 하나가 101개가 된다. 개발 환경에서 20행짜리 로컬 데이터베이스를 상대로 하면 그 페이지는 즉시 뜬다. 운영에서는 같은 페이지가 시스템에서 가장 느린 엔드포인트가 되며, 프로파일에는 값비싼 연산이 하나도 보이지 않는다. 아주 많은 수의 값싼 연산만 있을 뿐이다.\n\n이 결함이 배울 점이 있는 이유는 그것이 통상적인 의미의 실수가 아니라는 데 있다. 코드에 틀린 곳이 없고, 프레임워크의 규칙을 어긴 것도 없다. 비용은 지연 로딩 전략 — 합리적인 기본값이다 — 과 그 전략이 예상하지 못한 접근 패턴 사이의 상호작용이 만들어 낸다. 어느 쪽도 그 자체로는 틀리지 않았다.\n\n해결책은 있다. 이 질의에 한해 연관을 즉시 함께 가져오거나, 고객들을 두 번째 질의로 묶어서 한꺼번에 로딩하는 방법이다. 그러나 각각은 전역 설정이 아니라 특정 용도에 대한 결정이다. 여기에 오래가는 교훈이 있다. 비용을 숨기는 추상은 비용을 없애지 않는다. 그 비용을 따져 봐야 하는 시점을 옮길 뿐이며, 대개 더 나중으로 그리고 더 곤란한 자리로 옮긴다.",
 gloss:[{w:"issue a query",ko:"질의를 날리다"},{w:"trigger",ko:"유발하다"},{w:"instantaneous",ko:"즉각적인"},{w:"profile",ko:"성능 프로파일(측정 결과)"},{w:"instructive",ko:"교훈적인, 배울 점이 있는"},{w:"anticipate",ko:"예상하다"},{w:"eagerly",ko:"즉시, 미리"},{w:"relocate",ko:"위치를 옮기다"}],
 qs:[
  {q:"Why does the problem often go unnoticed during development?",
   opts:["Development environments disable lazy loading by default.",
         "The framework reports the number of queries only in production.",
         "Development databases hold few rows, so the page still responds instantly.",
         "Developers rarely display customer names on list pages."],
   ans:2,exp:"2문단. 20행짜리 로컬 DB에서는 즉시 뜨기 때문에 개발 중에는 드러나지 않는다."},
  {q:"What does the performance profile of the affected page look like?",
   opts:["A single operation consuming nearly all of the time",
         "Repeated failures of the database connection",
         "Long pauses caused by the framework's startup routine",
         "A very large number of individually inexpensive operations"],
   ans:3,exp:"2문단 마지막 문장. 값비싼 연산 하나가 아니라 값싼 연산이 아주 많은 것이 이 문제의 특징이다."},
  {q:"According to the third paragraph, the defect is unusual because",
   opts:["neither the default strategy nor the access pattern is wrong on its own",
         "it appears only in very old versions of the framework",
         "it can be repaired only by abandoning the mapper entirely",
         "it violates an explicit rule that most developers have not read"],
   ans:0,exp:"3문단. 코드도 규칙도 틀리지 않았고 둘의 상호작용이 비용을 만든다고 했다."},
  {q:"What is the passage's broader claim about abstractions that hide cost?",
   opts:["They eliminate the cost by handling it automatically.",
         "They move the point at which the cost must be reasoned about, usually to a worse time.",
         "They are always preferable to writing queries by hand.",
         "They should be configured globally rather than per use."],
   ans:1,exp:"마지막 두 문장. 비용을 없애는 것이 아니라 따져야 할 시점을 더 나중, 더 곤란한 자리로 옮긴다."}
 ]},

{id:"sp-incident", exam:"TOEIC", type:"이메일", level:2,
 series:"🌱 스프링·백엔드", title:"Incident Report — Connection Pool Exhaustion",
 topic:"장애 보고 이메일 — 커넥션 풀 고갈",
 passage:"From: Priya Raman, Platform Engineering\nTo: Backend Team; Customer Support Leads\nSubject: Incident 2041 — checkout service outage, Tuesday 14:20–15:05\n\nThis is the summary I promised at yesterday's stand-up.\n\nWhat happened. Between 14:20 and 15:05 the checkout service returned errors for roughly one request in three. Support received forty-two tickets during that window. No orders were lost, and no payment was charged twice.\n\nCause. A report generated for the finance team opened a database connection for each row it processed and did not release them. The connection pool holds fifty connections; the report consumed all of them within eleven minutes. Checkout requests then waited for a connection that never became available and timed out.\n\nWhy it was not caught earlier. The report has run monthly since March without incident. This month it processed about nine times the usual number of rows because the date filter was widened last week. The leak had always been present; only the volume changed.\n\nWhat we have done. The report now closes each connection explicitly and runs against the read replica rather than the primary database. We have also added an alert that fires when pool usage stays above eighty percent for two minutes.\n\nWhat we still owe you. A review of the other four scheduled jobs for the same pattern, by Friday. If you have questions before then, reply to this thread rather than messaging me directly, so that the answers stay in one place.",
 ko:"보낸 사람: Priya Raman, 플랫폼 엔지니어링\n받는 사람: 백엔드 팀, 고객지원 리드\n제목: 장애 2041 — 결제 서비스 중단, 화요일 14:20–15:05\n\n어제 스탠드업에서 약속한 요약입니다.\n\n무슨 일이 있었나. 14:20부터 15:05까지 결제 서비스가 대략 세 건 중 한 건꼴로 오류를 반환했습니다. 그 시간 동안 고객지원에 42건의 문의가 접수됐습니다. 유실된 주문은 없고, 이중 청구된 결제도 없습니다.\n\n원인. 재무팀용으로 생성되는 리포트가 처리하는 행마다 데이터베이스 커넥션을 열고 반환하지 않았습니다. 커넥션 풀은 50개를 보유하는데, 리포트가 11분 만에 전부 소진했습니다. 이후 결제 요청들은 결코 확보되지 않는 커넥션을 기다리다 타임아웃됐습니다.\n\n왜 더 일찍 잡히지 않았나. 이 리포트는 3월부터 매달 문제없이 돌아왔습니다. 이번 달에는 지난주에 날짜 필터를 넓힌 탓에 평소의 약 아홉 배에 달하는 행을 처리했습니다. 누수는 줄곧 있었고, 바뀐 것은 처리량뿐이었습니다.\n\n조치한 것. 리포트는 이제 커넥션을 명시적으로 닫으며, 주 데이터베이스가 아니라 읽기 전용 복제본을 상대로 실행됩니다. 풀 사용률이 2분 동안 80%를 넘으면 울리는 알림도 추가했습니다.\n\n아직 드릴 것. 같은 패턴이 있는지 나머지 예약 작업 네 건을 금요일까지 검토하겠습니다. 그전에 질문이 있으면 제게 개별 메시지를 보내지 마시고 이 스레드에 답장해 주십시오. 답변이 한곳에 모이도록 하기 위함입니다.",
 gloss:[{w:"outage",ko:"(서비스) 중단, 장애"},{w:"release",ko:"(자원을) 반환하다, 놓아주다"},{w:"time out",ko:"시간 초과로 실패하다"},{w:"leak",ko:"누수"},{w:"read replica",ko:"읽기 전용 복제본"},{w:"fire (an alert)",ko:"(알림이) 울리다, 발동하다"},{w:"scheduled job",ko:"예약 작업"},{w:"thread",ko:"(메일) 스레드"}],
 qs:[
  {q:"What is the main purpose of this email?",
   opts:["To request additional database capacity from management",
         "To summarize an outage, its cause, and the steps taken afterwards",
         "To announce a change to the finance team's reporting schedule",
         "To ask the support team to stop forwarding customer tickets"],
   ans:1,exp:"첫 줄에서 '어제 약속한 요약'이라 밝히고, 이후 무슨 일·원인·조치 순으로 정리한다."},
  {q:"According to the email, why did the problem appear this month rather than earlier?",
   opts:["The report processed far more rows after its date filter was widened.",
         "The connection pool was reduced from fifty to a smaller size.",
         "A new version of the database was installed last week.",
         "The report was run at a busier time of day than usual."],
   ans:0,exp:"'왜 더 일찍 잡히지 않았나' 문단. 누수는 원래 있었고 처리량만 아홉 배로 늘었다."},
  {q:"What does Ms. Raman say the team still has to do?",
   opts:["Restore the orders that were lost during the outage",
         "Move the checkout service to a new database entirely",
         "Reply individually to each of the forty-two support tickets",
         "Check four other scheduled jobs for the same pattern by Friday"],
   ans:3,exp:"마지막 문단 첫 문장. 나머지 예약 작업 4건을 금요일까지 검토한다고 했다."},
  {q:"Why does Ms. Raman ask recipients to reply to the thread?",
   opts:["Because she will be away from the office until Friday",
         "Because direct messages are blocked during an incident",
         "So that the answers remain in one place",
         "So that the support team is not disturbed"],
   ans:2,exp:"마지막 문장이 이유를 직접 밝힌다. 'so that the answers stay in one place'."}
 ]},

{id:"sp-frame", exam:"TOEFL", type:"비평·논증", level:4,
 series:"🌱 스프링·백엔드", title:"What a Framework Takes Away",
 topic:"프레임워크가 가져가는 것",
 passage:"A library is called when you want it; a framework calls you. The distinction is often presented as a technical detail, but it determines who owns the shape of a program. Adopting a framework means accepting a structure that was decided before the problem was known, in exchange for not having to decide it.\n\nFor most projects this is an excellent trade. The structural questions a web application must answer — how requests are routed, where transactions begin and end, how configuration is loaded — have been answered many thousands of times, and the answers are not where a particular product differs from its competitors. Deciding them again is expenditure without return. A team that declines the framework in order to keep control typically spends its first year rebuilding what it declined, more slowly and with fewer people reviewing it.\n\nThe cost falls elsewhere, and it is not primarily technical. A framework establishes a vocabulary, and the vocabulary becomes the boundary of what the team readily imagines. Problems that fit the framework's categories are seen immediately; problems that do not are either forced into those categories or postponed. Long-lived codebases often contain a feature that is oddly shaped for no reason visible in the requirements, and the reason turns out to be that it was easier to express that way.\n\nNone of this argues against frameworks, which remain the correct default. It argues against a particular kind of forgetting. The structure a team works inside was authored by people solving a general problem, and the fit between that general problem and the specific one at hand is a question that has to be asked deliberately, because nothing in daily work will raise it.",
 ko:"라이브러리는 당신이 원할 때 호출하고, 프레임워크는 당신을 호출한다. 이 구별은 흔히 기술적 세부처럼 제시되지만, 프로그램의 형태를 누가 소유하는지를 결정한다. 프레임워크를 채택한다는 것은 문제를 알기도 전에 결정된 구조를, 그것을 직접 결정하지 않아도 되는 대가로 받아들이는 일이다.\n\n대부분의 프로젝트에서 이는 훌륭한 거래다. 웹 애플리케이션이 답해야 하는 구조적 질문들 — 요청을 어떻게 라우팅할지, 트랜잭션이 어디서 시작하고 끝날지, 설정을 어떻게 읽어 올지 — 은 이미 수천 번 답해졌고, 그 답들은 어떤 제품이 경쟁자와 갈리는 지점이 아니다. 그것을 다시 결정하는 것은 회수 없는 지출이다. 통제권을 지키겠다며 프레임워크를 거절한 팀은 대개 첫 해를 자기가 거절한 것을 다시 만드는 데 쓴다. 더 느리게, 그리고 검토하는 사람은 더 적은 채로.\n\n대가는 다른 곳에서 치러지며, 주로 기술적인 것이 아니다. 프레임워크는 어휘를 세우고, 그 어휘는 팀이 쉽게 떠올릴 수 있는 것의 경계가 된다. 프레임워크의 범주에 들어맞는 문제는 즉시 보이고, 그렇지 않은 문제는 그 범주 안으로 밀어 넣어지거나 미뤄진다. 오래된 코드베이스에는 요구사항만 봐서는 이유를 알 수 없는 이상한 모양의 기능이 종종 있는데, 알고 보면 그렇게 표현하는 편이 쉬웠다는 것이 이유다.\n\n이 중 어느 것도 프레임워크를 쓰지 말라는 논거는 아니다. 프레임워크는 여전히 옳은 기본값이다. 이것은 특정한 종류의 망각에 반대하는 논거다. 팀이 그 안에서 일하는 구조는 일반적인 문제를 풀던 사람들이 지은 것이고, 그 일반적 문제와 지금 눈앞의 구체적 문제 사이의 적합성은 의식적으로 물어야만 하는 질문이다. 일상 업무에서는 아무것도 그 질문을 꺼내 주지 않기 때문이다.",
 gloss:[{w:"expenditure",ko:"지출"},{w:"decline",ko:"거절하다"},{w:"establish a vocabulary",ko:"어휘를 세우다"},{w:"readily",ko:"쉽게, 선뜻"},{w:"postpone",ko:"미루다"},{w:"oddly shaped",ko:"이상한 모양의"},{w:"author (v.)",ko:"만들다, 저술하다"},{w:"deliberately",ko:"의식적으로, 일부러"}],
 qs:[
  {q:"What does the passage identify as the essential difference between a library and a framework?",
   opts:["A framework is larger and contains more code.",
         "A library must be recompiled whenever it changes.",
         "A framework can be used only by experienced teams.",
         "A framework determines who controls the overall shape of the program."],
   ans:3,exp:"1문단. '누가 호출하는가'의 차이가 곧 프로그램의 형태를 누가 소유하는가의 문제라고 했다."},
  {q:"Why does the passage consider adopting a framework a good trade for most projects?",
   opts:["Frameworks are usually faster than hand-written code.",
         "The structural questions it answers are not where a product differs from competitors.",
         "Frameworks remove the need to hire experienced engineers.",
         "Most teams are contractually required to use one."],
   ans:1,exp:"2문단. 그 질문들은 이미 수천 번 답해졌고 제품이 갈리는 지점이 아니므로 다시 결정하는 것은 '회수 없는 지출'이다."},
  {q:"According to the third paragraph, the real cost of a framework is that",
   opts:["it consumes computing resources that could be used elsewhere",
         "it must be upgraded on a schedule the team does not control",
         "its vocabulary limits what problems the team readily perceives",
         "it prevents any feature from being implemented quickly"],
   ans:2,exp:"3문단. 어휘가 팀이 쉽게 떠올리는 것의 경계가 되고, 범주 밖 문제는 밀어 넣어지거나 미뤄진다."},
  {q:"What does the author ultimately recommend?",
   opts:["Asking deliberately whether the framework's general problem matches the specific one",
         "Building the structural parts of an application without a framework",
         "Choosing the framework with the largest number of users",
         "Rewriting oddly shaped features as soon as they are noticed"],
   ans:0,exp:"마지막 문단. 프레임워크 자체를 반대하는 것이 아니라, 그 적합성을 '의식적으로' 물으라는 것이 결론이다."}
 ]},

/* ═══════════ ⚙️ 소프트웨어 공학 ═══════════ */

{id:"se-mmm", exam:"TOEFL", type:"역사·논증", level:4,
 series:"⚙️ 소프트웨어 공학", title:"The Mythical Man-Month, Fifty Years On",
 topic:"인월의 신화 — 반세기 뒤에 다시 읽기",
 passage:"Frederick Brooks managed the development of an operating system at IBM in the 1960s and drew from it a conclusion that has been quoted ever since: adding people to a late software project makes it later. The claim is counterintuitive enough that it is often repeated as a paradox, which obscures the ordinary arithmetic behind it.\n\nThe argument rests on a distinction between two kinds of work. Some tasks divide cleanly, so that ten workers finish in a tenth of the time. Others require the participants to remain in agreement, and the cost of maintaining that agreement grows with the number of pairs who must communicate — a quantity that rises roughly with the square of the team size. Software belongs to the second kind. Beyond a certain point, each new member adds more coordination than capacity.\n\nA second observation compounds the first. A person joining a project cannot contribute until they understand it, and the only people who can explain it are the ones currently producing work. Training therefore consumes exactly the resource that is already scarce. On a project that is late, this exchange is at its worst precisely when it is most tempting.\n\nSubsequent decades have qualified the argument without overturning it. Modular architectures, better tooling, and asynchronous written communication have all raised the size at which coordination overtakes output. What has not changed is the shape of the curve. Managers who respond to a slipping schedule by enlarging the team are not making an error of degree that better tools have solved; they are treating a problem of communication as though it were a problem of labour supply.",
 ko:"프레더릭 브룩스는 1960년대 IBM에서 운영체제 개발을 관리했고, 그 경험에서 이후 줄곧 인용되는 결론을 끌어냈다. 늦어진 소프트웨어 프로젝트에 사람을 더 넣으면 더 늦어진다는 것이다. 이 주장은 직관에 어긋나는 정도가 커서 흔히 역설처럼 되뇌어지는데, 그 바람에 뒤에 있는 평범한 산수가 가려진다.\n\n논증은 두 종류의 일을 구별하는 데 기댄다. 어떤 과업은 깔끔하게 나뉘어서 열 사람이 붙으면 십분의 일 시간에 끝난다. 다른 과업은 참여자들이 계속 합의된 상태로 있어야 하고, 그 합의를 유지하는 비용은 서로 소통해야 하는 짝의 수에 따라 늘어난다. 그 수는 대략 팀 규모의 제곱에 비례해 커진다. 소프트웨어는 두 번째 종류에 속한다. 어느 지점을 넘어서면 새 구성원 한 명이 더하는 조율 부담이 그가 더하는 생산 능력보다 커진다.\n\n두 번째 관찰이 첫 번째를 가중시킨다. 프로젝트에 합류한 사람은 그것을 이해하기 전까지 기여할 수 없고, 그것을 설명해 줄 수 있는 사람은 지금 결과물을 만들고 있는 사람들뿐이다. 따라서 교육은 이미 부족한 바로 그 자원을 소모한다. 늦어진 프로젝트에서 이 맞바꿈은 가장 솔깃해지는 바로 그때 가장 나쁘다.\n\n그 뒤 수십 년은 이 논증을 뒤엎지 않으면서 단서를 달았다. 모듈화된 아키텍처, 나아진 도구, 비동기 문서 소통은 모두 조율 비용이 산출을 앞지르는 팀 규모를 끌어올렸다. 바뀌지 않은 것은 곡선의 모양이다. 일정이 밀린다고 팀을 키우는 관리자는 더 나은 도구가 이미 해결한 정도의 오류를 범하는 것이 아니다. 그는 소통의 문제를 노동력 공급의 문제인 양 다루고 있는 것이다.",
 gloss:[{w:"counterintuitive",ko:"직관에 어긋나는"},{w:"obscure (v.)",ko:"가리다, 흐리게 하다"},{w:"divide cleanly",ko:"깔끔하게 나뉘다"},{w:"coordination",ko:"조율"},{w:"compound (v.)",ko:"가중시키다"},{w:"scarce",ko:"부족한, 희소한"},{w:"qualify",ko:"단서를 달다, 제한하다"},{w:"labour supply",ko:"노동력 공급"}],
 qs:[
  {q:"According to the passage, why does the cost of coordination grow so quickly?",
   opts:["Because the number of pairs who must communicate rises roughly with the square of team size",
         "Because new members are usually less skilled than existing ones",
         "Because managers must approve every decision personally",
         "Because software tasks cannot be divided at all"],
   ans:0,exp:"2문단. 합의 유지 비용이 소통해야 하는 '짝의 수'를 따라 늘고, 그 수는 팀 규모의 제곱에 비례한다."},
  {q:"What is the second observation that makes the problem worse?",
   opts:["New members are typically hired at higher salaries.",
         "Late projects tend to have poorly written documentation.",
         "Training a new member consumes the time of the people already producing work.",
         "Managers rarely measure how long tasks actually take."],
   ans:2,exp:"3문단. 설명해 줄 수 있는 사람은 지금 일하고 있는 사람뿐이라 교육이 이미 부족한 자원을 갉아먹는다."},
  {q:"How have later developments affected Brooks's argument?",
   opts:["They have shown it to be entirely mistaken.",
         "They have raised the team size at which coordination overtakes output, without changing the shape of the curve.",
         "They have made coordination costs disappear in modular systems.",
         "They have confirmed that adding people always helps."],
   ans:1,exp:"4문단. '뒤엎지 않으면서 단서를 달았다'며 임계 규모만 올랐을 뿐 곡선의 모양은 그대로라고 했다."},
  {q:"The final sentence characterizes the manager's error as",
   opts:["underestimating how long training takes",
         "refusing to adopt modern development tools",
         "hiring people with the wrong technical background",
         "mistaking a communication problem for a shortage of labour"],
   ans:3,exp:"마지막 문장 그대로다. 정도의 오류가 아니라 문제의 종류를 잘못 짚은 것이다."}
 ]},

{id:"se-estimate", exam:"TOEFL", type:"방법론", level:3,
 series:"⚙️ 소프트웨어 공학", title:"Why Estimates Fail",
 topic:"추정은 왜 빗나가는가",
 passage:"Ask a team how long a feature will take and the answer will usually be wrong in one direction. Studies of completed projects across several decades find that estimates are optimistic far more often than pessimistic, and that the bias survives experience: engineers who have been late on every previous project remain confident about the next one.\n\nThe usual explanation blames pressure from managers, and pressure certainly exists. But the bias appears even when estimates are collected anonymously and carry no consequence, which suggests something structural. The likeliest account is that an estimate is produced by imagining the work, and imagination is efficient. A person planning a task rehearses the steps they can foresee, and the steps they can foresee are the ones that go as planned. Waiting three days for another team's approval is not a step; it is an absence, and absences are hard to picture.\n\nThis explains a pattern that otherwise looks like carelessness. Estimates are reasonably accurate for work the estimator has done many times, where the unforeseen has already been seen, and grow rapidly worse as novelty increases. It also explains why breaking a task into smaller pieces improves accuracy only partly: decomposition surfaces forgotten steps, but the gaps between the pieces are exactly what was invisible to begin with.\n\nThe practical conclusion is not that teams should estimate more carefully. It is that a single number is the wrong output. A range, with the assumptions that would push the result toward each end, gives a manager something to act on — which risk to remove first — whereas a point estimate offers only the choice of believing it or not.",
 ko:"어떤 기능이 얼마나 걸리겠느냐고 팀에 물으면 답은 대개 한쪽 방향으로 틀린다. 수십 년에 걸친 완료 프로젝트 연구들은 추정이 비관적인 경우보다 낙관적인 경우가 훨씬 많으며, 그 편향이 경험을 견디고 살아남는다는 것을 발견한다. 이전 프로젝트마다 늦었던 엔지니어도 다음 프로젝트에 대해서는 여전히 자신 있어 한다.\n\n흔한 설명은 관리자의 압박을 탓하고, 압박은 분명히 존재한다. 그러나 이 편향은 추정을 익명으로 걷고 아무 불이익이 없을 때에도 나타나며, 이는 뭔가 구조적인 것이 있음을 시사한다. 가장 그럴듯한 설명은 추정이 일을 상상함으로써 만들어지고, 상상은 효율적이라는 것이다. 과업을 계획하는 사람은 자기가 내다볼 수 있는 단계들을 머릿속에서 훑는데, 내다볼 수 있는 단계란 계획대로 되는 단계들이다. 다른 팀의 승인을 사흘 기다리는 것은 단계가 아니다. 그것은 부재이고, 부재는 그림으로 떠올리기 어렵다.\n\n이는 그러지 않으면 그저 부주의로 보일 패턴을 설명해 준다. 추정은 추정자가 여러 번 해 본 일 — 예상 밖의 일이 이미 목격된 일 — 에 대해서는 꽤 정확하고, 새로움이 커질수록 급격히 나빠진다. 또한 과업을 잘게 쪼개는 것이 정확도를 부분적으로만 개선하는 이유도 설명한다. 분해는 잊고 있던 단계를 드러내지만, 조각들 사이의 틈이야말로 애초에 보이지 않던 바로 그것이기 때문이다.\n\n실용적 결론은 팀이 더 신중하게 추정해야 한다는 것이 아니다. 숫자 하나가 잘못된 산출물이라는 것이다. 결과를 양 끝으로 밀어붙일 가정들을 함께 붙인 범위는 관리자에게 행동할 거리를 준다. 어느 위험부터 없앨 것인가 하는 것이다. 반면 하나짜리 추정치는 그것을 믿을지 말지의 선택만 남긴다.",
 gloss:[{w:"optimistic",ko:"낙관적인"},{w:"bias",ko:"편향"},{w:"anonymously",ko:"익명으로"},{w:"rehearse",ko:"머릿속으로 훑다, 되풀이하다"},{w:"foresee",ko:"내다보다"},{w:"novelty",ko:"새로움, 생소함"},{w:"decomposition",ko:"분해"},{w:"point estimate",ko:"단일 추정치"}],
 qs:[
  {q:"What evidence suggests that manager pressure is not the whole explanation?",
   opts:["Estimates improve when managers are removed from the room.",
         "Experienced engineers no longer show the bias.",
         "The bias appears even in anonymous estimates that carry no consequence.",
         "Studies of completed projects were conducted only recently."],
   ans:2,exp:"2문단. 익명이고 불이익도 없는 조건에서도 편향이 나타나므로 구조적 원인이 있다는 논리다."},
  {q:"According to the passage, why is waiting for another team's approval usually left out of an estimate?",
   opts:["It is normally handled by managers rather than engineers.",
         "It is an absence rather than a step, and absences are hard to imagine.",
         "It takes less time than engineers expect.",
         "It occurs only in unusually large organizations."],
   ans:1,exp:"2문단 마지막 두 문장. 부재는 상상 속에서 그려지지 않는다."},
  {q:"Why does breaking a task into smaller pieces help only partly?",
   opts:["The gaps between the pieces are exactly what was invisible in the first place.",
         "Smaller pieces take longer to estimate individually.",
         "Decomposition requires experience that novice estimators lack.",
         "Managers usually ignore decomposed estimates."],
   ans:0,exp:"3문단 마지막 문장. 분해는 잊힌 단계를 드러내지만 조각 사이의 틈은 여전히 보이지 않는다."},
  {q:"What does the author recommend instead of a single estimate?",
   opts:["A deadline set by the manager rather than the team",
         "An estimate produced only after the work has begun",
         "A commitment to finish within the most optimistic figure",
         "A range together with the assumptions that would push the result each way"],
   ans:3,exp:"마지막 문단. 범위와 가정을 주면 '어느 위험부터 없앨지'라는 행동 거리가 생긴다."}
 ]},

{id:"se-debt", exam:"TOEFL", type:"개념·비평", level:4,
 series:"⚙️ 소프트웨어 공학", title:"Technical Debt Is a Metaphor, Not an Excuse",
 topic:"기술 부채 — 비유가 변명이 될 때",
 passage:"Ward Cunningham introduced the phrase technical debt to describe a specific and defensible decision: shipping code that reflects an incomplete understanding of the problem, then revising it as understanding improves. The borrowing is deliberate, the lender is future effort, and the interest is the extra work required while the mismatch persists. Used this way, the metaphor is precise.\n\nIn ordinary usage it has come to mean any code someone dislikes. This inflation matters because the metaphor carries an implication that survives the change in meaning. Debt implies that something was received in exchange, and that the balance can be repaid. Neither is true of code that was simply written badly. Nothing was borrowed, no schedule was accelerated, and there is no principal to return — there is only work that was done poorly and will have to be done again.\n\nThe distinction has consequences for how the two situations should be handled. Genuine debt is a portfolio question: an organization can carry it deliberately, track where it sits, and decide which positions to close as the cost of servicing them rises. Carelessness is not a position to be managed but a practice to be changed, and describing it in financial language moves it into a register where it sounds prudent.\n\nThe useful test is whether anyone can name what was bought. If the answer is a specific date that was met, or a hypothesis that was tested cheaply, the metaphor applies and the repayment schedule is a real decision. If the answer is that the team was busy, the term is functioning as a euphemism, and the first repair required is to the vocabulary.",
 ko:"워드 커닝햄이 '기술 부채'라는 말을 도입한 것은 구체적이고 옹호 가능한 결정을 묘사하기 위해서였다. 문제에 대한 이해가 아직 불완전한 상태를 반영한 코드를 내보낸 다음, 이해가 나아지는 대로 그것을 고쳐 나가는 일이다. 빌리는 행위는 의도적이고, 빌려주는 쪽은 미래의 노력이며, 이자는 그 어긋남이 지속되는 동안 드는 추가 작업이다. 이렇게 쓰면 이 비유는 정확하다.\n\n일상적 용법에서 이 말은 누군가 마음에 들지 않는 아무 코드나 가리키게 되었다. 이 팽창이 문제인 것은, 뜻이 바뀌어도 비유가 품은 함의는 살아남기 때문이다. 부채라는 말은 그 대가로 무언가를 받았고 그 잔액을 갚을 수 있다는 것을 함축한다. 그냥 잘못 쓴 코드에는 둘 다 해당하지 않는다. 빌린 것이 없고, 앞당겨진 일정도 없고, 돌려줄 원금도 없다. 부실하게 한 일, 그래서 다시 해야 할 일이 있을 뿐이다.\n\n이 구별은 두 상황을 어떻게 다뤄야 하는지에 결과를 남긴다. 진짜 부채는 포트폴리오의 문제다. 조직은 그것을 의도적으로 안고 갈 수 있고, 어디에 있는지 추적할 수 있으며, 유지 비용이 올라가는 포지션부터 정리할지 결정할 수 있다. 부주의는 관리할 포지션이 아니라 바꿔야 할 관행이며, 그것을 금융 언어로 기술하면 신중해 보이는 어조 속으로 옮겨 놓게 된다.\n\n쓸모 있는 판별법은 무엇을 샀는지 누군가 댈 수 있느냐다. 답이 지켜 낸 특정 날짜이거나 값싸게 검증한 가설이라면 비유가 적용되고 상환 일정은 실제 결정이 된다. 답이 팀이 바빴다는 것이라면, 그 용어는 완곡어법으로 기능하고 있는 것이고, 가장 먼저 손봐야 할 것은 어휘다.",
 gloss:[{w:"defensible",ko:"옹호할 수 있는"},{w:"mismatch",ko:"어긋남, 불일치"},{w:"inflation",ko:"(의미의) 팽창"},{w:"principal",ko:"원금"},{w:"portfolio",ko:"포트폴리오, 보유 자산"},{w:"service (a debt)",ko:"(부채를) 갚아 나가다"},{w:"register",ko:"(말의) 어조, 격식 수준"},{w:"euphemism",ko:"완곡어법"}],
 qs:[
  {q:"In Cunningham's original sense, what is borrowed when a team takes on technical debt?",
   opts:["Money that must be repaid to an outside investor",
         "Time from another team working on the same product",
         "Code written by a previous generation of engineers",
         "Future effort, exchanged for shipping under incomplete understanding"],
   ans:3,exp:"1문단. 빌려주는 쪽은 '미래의 노력'이고, 이해가 불완전한 상태에서 출시하는 대가로 빌린다."},
  {q:"Why does the passage object to calling badly written code technical debt?",
   opts:["Because nothing was received in exchange and there is no principal to return",
         "Because badly written code is usually easier to fix than real debt",
         "Because the term was legally registered by its inventor",
         "Because managers cannot understand financial metaphors"],
   ans:0,exp:"2문단. 부채라는 말이 함축하는 두 가지(받은 대가, 갚을 잔액)가 모두 성립하지 않는다."},
  {q:"According to the passage, how should genuine debt and carelessness be handled differently?",
   opts:["Debt should be repaid immediately; carelessness can be scheduled.",
         "Debt requires new hiring; carelessness requires new tools.",
         "Debt can be managed as a portfolio; carelessness is a practice that must change.",
         "Both should be tracked in the same list to keep priorities clear."],
   ans:2,exp:"3문단. 하나는 관리할 포지션이고 다른 하나는 바꿔야 할 관행이라고 대비시킨다."},
  {q:"What test does the author propose for deciding whether the metaphor applies?",
   opts:["Whether the code passes its automated tests",
         "Whether anyone can name what was bought with the shortcut",
         "Whether the original author is still with the company",
         "Whether the repair would take more than one sprint"],
   ans:1,exp:"마지막 문단 첫 문장. '무엇을 샀는지 댈 수 있는가'가 판별법이다."}
 ]},

{id:"se-conway", exam:"TOEFL", type:"조직·구조", level:3,
 series:"⚙️ 소프트웨어 공학", title:"Conway's Law",
 topic:"콘웨이의 법칙 — 조직도가 아키텍처가 된다",
 passage:"In 1967 Melvin Conway observed that organizations designing systems produce designs that copy their own communication structure. Four teams building a compiler will produce a four-pass compiler. The claim was offered as an empirical regularity rather than a rule, and it was largely ignored for two decades before becoming one of the most cited remarks in the field.\n\nThe mechanism requires no conspiracy. An interface between two components must be agreed by the people responsible for them, and agreement is expensive across organizational distance. Where two engineers sit together, they will move a responsibility back and forth until it sits in the right place. Where two departments are involved, the boundary will be settled once and then defended, because reopening it requires a meeting that neither side wants to call. The architecture ends up recording, quite faithfully, which conversations were easy.\n\nThe observation is often quoted as a warning, but its more useful form is a lever. If structure follows communication, then reorganizing teams is a way of changing architecture — the approach sometimes called the inverse Conway manoeuvre. Firms that wish to split a monolithic system into services frequently split the teams first and let the code follow, on the grounds that the reverse order produces services that still require constant cross-team negotiation and therefore deliver none of the intended independence.\n\nThe limitation is that the law describes a tendency, not a destiny. A team that understands it can deliberately design against its own shape, and some of the best-known systems were built by groups that did exactly that. But doing so requires continuous effort, and effort that is not spent is not neutral: in its absence, the organization chart writes the architecture by default.",
 ko:"1967년 멜빈 콘웨이는 시스템을 설계하는 조직이 자기 자신의 소통 구조를 그대로 베낀 설계를 내놓는다고 관찰했다. 네 팀이 컴파일러를 만들면 4패스 컴파일러가 나온다는 것이다. 이 주장은 규칙이 아니라 경험적 규칙성으로 제시되었고, 이 분야에서 가장 많이 인용되는 말 중 하나가 되기까지 20년 동안은 거의 무시되었다.\n\n이 메커니즘에는 어떤 음모도 필요 없다. 두 구성요소 사이의 인터페이스는 그것을 맡은 사람들이 합의해야 하고, 합의는 조직적 거리가 멀수록 비싸진다. 두 엔지니어가 나란히 앉아 있으면 어떤 책임을 이리저리 옮겨 보다가 제자리를 찾아 준다. 두 부서가 걸려 있으면 그 경계는 한 번 정해진 뒤 방어된다. 다시 열려면 양쪽 다 소집하고 싶지 않은 회의가 필요하기 때문이다. 아키텍처는 결국 어떤 대화가 쉬웠는지를 꽤 충실하게 기록하게 된다.\n\n이 관찰은 흔히 경고로 인용되지만, 더 쓸모 있는 형태는 지렛대다. 구조가 소통을 따라간다면, 팀을 재편하는 것이 아키텍처를 바꾸는 방법이 된다. 이른바 역(逆)콘웨이 기동이다. 단일 시스템을 서비스들로 쪼개려는 기업들은 흔히 팀부터 쪼개고 코드가 따라오게 두는데, 순서를 반대로 하면 여전히 팀 간 협상이 끊임없이 필요한 서비스들이 나와서 애초에 노린 독립성을 하나도 얻지 못한다는 근거에서다.\n\n한계는 이 법칙이 운명이 아니라 경향을 기술한다는 점이다. 이를 이해하는 팀은 자기 조직의 모양에 맞서 의도적으로 설계할 수 있고, 가장 잘 알려진 시스템 몇몇은 바로 그렇게 한 집단이 만들었다. 그러나 그렇게 하려면 지속적인 노력이 들고, 쓰지 않은 노력은 중립적이지 않다. 그것이 없으면 조직도가 기본값으로 아키텍처를 써 버린다.",
 gloss:[{w:"empirical regularity",ko:"경험적 규칙성"},{w:"conspiracy",ko:"음모"},{w:"organizational distance",ko:"조직적 거리"},{w:"settle",ko:"정하다, 결정짓다"},{w:"faithfully",ko:"충실하게"},{w:"lever",ko:"지렛대"},{w:"monolithic",ko:"하나로 뭉쳐진, 단일체의"},{w:"destiny",ko:"운명"}],
 qs:[
  {q:"According to the passage, why does a boundary between two departments tend to be defended rather than adjusted?",
   opts:["Departments are usually rewarded for defending their boundaries.",
         "Reopening it requires a meeting that neither side wants to call.",
         "Company policy forbids changing interfaces after release.",
         "Engineers in different departments rarely speak the same technical language."],
   ans:1,exp:"2문단. 조직적 거리가 멀면 합의를 다시 여는 비용이 커서 경계가 고정된다."},
  {q:"What is the inverse Conway manoeuvre?",
   opts:["Rewriting a system before reorganizing the teams that own it",
         "Merging separate services back into a single system",
         "Reorganizing teams in order to change the architecture that follows",
         "Assigning one engineer to every interface in the system"],
   ans:2,exp:"3문단. 구조가 소통을 따라가므로 팀을 먼저 쪼개고 코드가 따라오게 하는 방식이다."},
  {q:"Why do firms split teams before splitting the code?",
   opts:["Because new teams can be hired faster than new services can be written",
         "Because splitting code first violates Conway's original formulation",
         "Because managers prefer to reorganize before technical work begins",
         "Because the reverse order yields services that still require constant cross-team negotiation"],
   ans:3,exp:"3문단 마지막. 순서를 반대로 하면 독립성을 얻지 못한다는 것이 근거다."},
  {q:"What does the final paragraph mean by saying that effort not spent is not neutral?",
   opts:["Without deliberate counter-effort, the organization chart determines the architecture by default.",
         "Unused effort can always be redirected to other projects.",
         "Teams that ignore the law produce no architecture at all.",
         "The law applies only to organizations that fail to plan."],
   ans:0,exp:"마지막 문장이 직접 설명한다. 아무것도 하지 않으면 조직도가 기본값으로 아키텍처를 쓴다."}
 ]},

{id:"se-coverage", exam:"TOEFL", type:"품질·측정", level:3,
 series:"⚙️ 소프트웨어 공학", title:"The Test That Tests Nothing",
 topic:"아무것도 검증하지 않는 테스트 — 지표의 함정",
 passage:"Code coverage measures the proportion of lines executed while a test suite runs. It is easy to compute, easy to display on a dashboard, and easy to require: many organizations set a threshold below which changes cannot be merged. The measure is genuinely informative in one direction. Code that is never executed by any test is certainly untested.\n\nThe reverse inference does not hold, and this is where the trouble begins. A test can execute a line without checking anything about the result. A suite that calls every method and asserts nothing will report full coverage while detecting no defect whatever. Such tests are not usually written in bad faith; they accumulate because a threshold has to be met by a deadline, and writing an assertion requires deciding what the correct behaviour is, which is the slow part.\n\nThe deeper difficulty is that a threshold converts a diagnostic into a target. Once a number is used to judge people, they optimize the number, and the cheapest way to raise coverage is to test the code that is easiest to test. The parts hardest to cover — error handling, concurrency, the branches that only occur when something has already gone wrong — are precisely the parts where defects concentrate. A team can therefore raise coverage and lower quality at the same time without anyone acting dishonestly.\n\nNone of this makes the measurement worthless. Read as a map of what has not been touched, coverage tells a reviewer where to look. Read as a score to be maximized, it reliably produces a suite that is large, slow, and silent about the failures that matter. The difference lies entirely in whether the number is being used to ask a question or to close one.",
 ko:"코드 커버리지는 테스트 스위트가 도는 동안 실행된 줄의 비율을 잰다. 계산하기 쉽고, 대시보드에 띄우기 쉽고, 요구하기도 쉽다. 많은 조직이 그 아래로는 변경을 병합할 수 없는 기준선을 정해 둔다. 이 지표는 한 방향으로는 진짜로 유익하다. 어떤 테스트로도 실행되지 않는 코드는 분명히 검증되지 않은 코드다.\n\n반대 방향의 추론은 성립하지 않으며, 문제는 여기서 시작된다. 테스트는 결과에 대해 아무것도 확인하지 않으면서 어떤 줄을 실행할 수 있다. 모든 메서드를 호출하되 아무것도 단언하지 않는 스위트는 커버리지를 만점으로 보고하면서 결함은 하나도 잡아내지 못한다. 그런 테스트가 보통 악의로 쓰이는 것은 아니다. 기준선을 마감까지 맞춰야 하는데, 단언을 하나 쓰려면 무엇이 올바른 동작인지 결정해야 하고 그것이 느린 부분이기 때문에 쌓이는 것이다.\n\n더 깊은 어려움은 기준선이 진단 도구를 목표로 바꿔 놓는다는 점이다. 어떤 숫자가 사람을 평가하는 데 쓰이는 순간 사람들은 그 숫자를 최적화하고, 커버리지를 올리는 가장 값싼 방법은 테스트하기 가장 쉬운 코드를 테스트하는 것이다. 덮기 가장 어려운 부분 — 오류 처리, 동시성, 이미 뭔가 잘못됐을 때만 타는 분기 — 이 바로 결함이 몰리는 부분이다. 따라서 팀은 아무도 부정직하게 굴지 않으면서도 커버리지를 올리는 동시에 품질을 낮출 수 있다.\n\n이 중 어느 것도 이 측정을 무가치하게 만들지는 않는다. 무엇이 손대지지 않았는지를 보여 주는 지도로 읽으면, 커버리지는 검토자에게 어디를 봐야 할지 알려 준다. 최대화해야 할 점수로 읽으면, 크고 느리면서 정작 중요한 실패에 대해서는 아무 말도 하지 않는 스위트를 어김없이 만들어 낸다. 차이는 전적으로 그 숫자가 질문을 여는 데 쓰이느냐 닫는 데 쓰이느냐에 있다.",
 gloss:[{w:"threshold",ko:"기준선, 문턱값"},{w:"inference",ko:"추론"},{w:"assert",ko:"단언하다, 검증하다"},{w:"in bad faith",ko:"악의로"},{w:"diagnostic",ko:"진단 도구"},{w:"concurrency",ko:"동시성"},{w:"branch",ko:"분기"},{w:"maximize",ko:"최대화하다"}],
 qs:[
  {q:"In which direction is coverage genuinely informative, according to the passage?",
   opts:["Code executed by no test is certainly untested.",
         "High coverage proves that a suite detects defects.",
         "Low coverage proves that the code contains defects.",
         "Coverage predicts how long a suite will take to run."],
   ans:0,exp:"1문단 마지막 문장. 한 방향(실행되지 않은 코드는 미검증)으로만 확실하다."},
  {q:"Why do tests without assertions accumulate?",
   opts:["Most testing frameworks do not support assertions.",
         "Reviewers are not permitted to reject tests once written.",
         "Assertions cause suites to run considerably more slowly.",
         "Deciding what the correct behaviour is takes time, while meeting a threshold has a deadline."],
   ans:3,exp:"2문단 마지막 문장. 악의가 아니라 '느린 부분'을 건너뛴 결과로 쌓인다."},
  {q:"How can a team raise coverage and lower quality at the same time?",
   opts:["By deleting tests that fail intermittently",
         "By testing the code that is easiest to cover while defects concentrate in the hardest parts",
         "By merging changes without review",
         "By measuring coverage only on new code"],
   ans:1,exp:"3문단. 가장 덮기 쉬운 곳을 덮고, 결함이 몰린 어려운 부분은 남는다."},
  {q:"According to the final paragraph, what determines whether coverage is useful?",
   opts:["Whether the threshold is set above or below eighty percent",
         "Whether the suite runs on every commit",
         "Whether the number is used to open a question or to close one",
         "Whether the tool measures lines or branches"],
   ans:2,exp:"마지막 문장 그대로다. 지도로 읽는가 점수로 읽는가의 차이다."}
 ]},

{id:"se-freeze", exam:"TOEIC", type:"공지·일정", level:2,
 series:"⚙️ 소프트웨어 공학", title:"Notice — Deployment Freeze",
 topic:"공지 — 배포 동결 기간 안내",
 passage:"NOTICE TO ALL ENGINEERING TEAMS\nDeployment freeze: Monday 18 November, 09:00 — Friday 22 November, 18:00\n\nThe annual enrollment period opens on 18 November, and traffic is expected to reach four times its normal level. To reduce the risk of disruption during this period, all non-essential deployments to production will be suspended for the week.\n\nWhat is suspended\nNew features, database schema changes, and dependency upgrades. This applies to every service, including internal tools, since several of them share infrastructure with customer-facing systems.\n\nWhat is not suspended\nSecurity patches and fixes for defects that are actively affecting customers. These require written approval from a team lead and from the on-call platform engineer. Send both approvals to the release channel before merging, not afterwards.\n\nPreparing for the freeze\nAnything you intend to release beforehand must be merged by 17:00 on Friday 15 November. Work merged after that time will remain in the staging environment until the freeze lifts. Please do not hold changes back and then deploy several at once on 25 November; stagger them across that week instead.\n\nStaffing\nTwo platform engineers will be on call at all times, and the schedule is posted in the team calendar. If you expect to be unavailable during the freeze, tell your team lead by 13 November so that coverage can be arranged.\n\nQuestions may be directed to the platform team through the usual channel. Please do not send them by direct message.",
 ko:"전 엔지니어링 팀 공지\n배포 동결: 11월 18일 월요일 09:00 — 11월 22일 금요일 18:00\n\n연례 가입 신청 기간이 11월 18일에 시작되며, 트래픽이 평소의 네 배에 이를 것으로 예상됩니다. 이 기간 중 장애 위험을 줄이기 위해, 필수적이지 않은 모든 운영 환경 배포를 한 주간 중단합니다.\n\n중단되는 것\n신규 기능, 데이터베이스 스키마 변경, 의존성 업그레이드입니다. 내부 도구를 포함한 모든 서비스에 적용됩니다. 그중 여럿이 고객 대면 시스템과 인프라를 공유하기 때문입니다.\n\n중단되지 않는 것\n보안 패치와 현재 고객에게 영향을 주고 있는 결함의 수정입니다. 이들은 팀 리드와 온콜 플랫폼 엔지니어의 서면 승인이 필요합니다. 두 승인 모두 병합 이후가 아니라 병합 전에 릴리스 채널로 보내 주십시오.\n\n동결 준비\n그전에 배포하려는 것은 11월 15일 금요일 17:00까지 병합되어야 합니다. 그 이후 병합된 작업은 동결이 풀릴 때까지 스테이징 환경에 남습니다. 변경을 쌓아 두었다가 11월 25일에 한꺼번에 배포하지 마시고, 그 주에 걸쳐 나눠서 배포해 주십시오.\n\n인력 배치\n플랫폼 엔지니어 두 명이 상시 온콜로 대기하며, 일정은 팀 캘린더에 게시되어 있습니다. 동결 기간 중 자리를 비울 예정이라면 11월 13일까지 팀 리드에게 알려 인력을 조정할 수 있게 해 주십시오.\n\n문의는 평소 채널을 통해 플랫폼 팀으로 보내 주십시오. 개별 메시지로는 보내지 말아 주십시오.",
 gloss:[{w:"freeze",ko:"동결"},{w:"enrollment period",ko:"가입 신청 기간"},{w:"disruption",ko:"중단, 차질"},{w:"suspend",ko:"중단하다, 보류하다"},{w:"customer-facing",ko:"고객을 직접 대하는"},{w:"staging environment",ko:"스테이징(사전 검증) 환경"},{w:"stagger",ko:"시차를 두고 분산하다"},{w:"on call",ko:"대기 근무 중인"}],
 qs:[
  {q:"Why has the deployment freeze been scheduled?",
   opts:["Several platform engineers will be on vacation that week.",
         "A new database version is being installed across all services.",
         "The staging environment is being replaced.",
         "Traffic is expected to be about four times higher during the enrollment period."],
   ans:3,exp:"두 번째 문단. 가입 신청 기간에 트래픽이 평소의 네 배에 이를 것으로 예상되기 때문이다."},
  {q:"What is required before an urgent customer-affecting fix may be merged?",
   opts:["A note in the team calendar describing the change",
         "Approval from the enrollment team",
         "Written approval from a team lead and the on-call platform engineer",
         "Confirmation that the fix has already been deployed to staging"],
   ans:2,exp:"'중단되지 않는 것' 문단. 두 승인을 병합 전에 릴리스 채널로 보내야 한다."},
  {q:"What are teams asked NOT to do after the freeze lifts?",
   opts:["Deploy several accumulated changes on the same day",
         "Merge any work into the staging environment",
         "Upgrade dependencies for internal tools",
         "Contact the platform team through the usual channel"],
   ans:0,exp:"'동결 준비' 문단 마지막 문장. 25일에 몰아서 배포하지 말고 그 주에 나눠서 하라고 했다."},
  {q:"By when must engineers report that they will be unavailable during the freeze?",
   opts:["15 November","13 November","18 November","22 November"],
   ans:1,exp:"'인력 배치' 문단. 11월 13일까지 팀 리드에게 알려야 한다."}
 ]},

{id:"se-postmortem", exam:"TOEFL", type:"문화·제도", level:3,
 series:"⚙️ 소프트웨어 공학", title:"Postmortems Without Blame",
 topic:"책임을 묻지 않는 사후분석은 왜 더 안전한가",
 passage:"After a serious outage, the natural question is who caused it. Blameless postmortem culture, adopted from aviation and now widespread in software operations, asks organizations to set that question aside. The reasoning is not that individuals never err. It is that an organization which punishes error learns less about it.\n\nThe argument turns on where information comes from. The only complete account of an incident is held by the people who were present, and what they report is shaped by what reporting will cost them. Where accounts are used to assign fault, the details that arrive are the defensible ones: the engineer who took a risky shortcut under time pressure describes a decision that sounds reasonable, and the pressure that produced it disappears from the record. The organization then draws conclusions from a version of events that was edited for safety.\n\nRemoving the penalty changes what can be said. An engineer who will not be punished for saying that the runbook was out of date, or that the alert had been firing so often that it was ignored, supplies exactly the conditions that made the error likely. These conditions are also the only things that can be fixed. A person can be replaced; the next person will face the same stale runbook and the same noisy alert.\n\nThe practice is regularly misunderstood as an absence of accountability, and the misunderstanding is worth answering directly. Blamelessness applies to the investigation, not to the organization's obligations afterwards. A team that identifies a cause and does not repair it has failed at something the postmortem cannot excuse — and repeated failure to act is the one pattern that a blameless process is designed to make visible rather than hide.",
 ko:"심각한 장애가 난 뒤 자연스럽게 나오는 질문은 누가 그랬느냐다. 항공 분야에서 들여와 이제 소프트웨어 운영에 널리 퍼진 무징벌 사후분석 문화는 조직에 그 질문을 옆으로 치워 두라고 요구한다. 그 논거는 개인이 결코 실수하지 않는다는 것이 아니다. 실수를 처벌하는 조직은 그 실수에 대해 더 적게 배운다는 것이다.\n\n논증의 축은 정보가 어디서 오는가에 있다. 사건에 대한 유일한 완전한 진술은 그 자리에 있던 사람들이 갖고 있고, 그들이 보고하는 내용은 보고가 자신에게 무엇을 치르게 할지에 따라 모양이 잡힌다. 진술이 잘못을 묻는 데 쓰이는 곳에서는 방어 가능한 세부만 올라온다. 시간 압박 속에 위험한 지름길을 택한 엔지니어는 그럴듯하게 들리는 결정을 서술하고, 그 결정을 낳은 압박은 기록에서 사라진다. 그러면 조직은 안전을 위해 편집된 버전의 사건 경과에서 결론을 끌어내게 된다.\n\n처벌을 없애면 말할 수 있는 것이 달라진다. 운영 지침서가 낡았다고, 혹은 그 알림이 하도 자주 울려서 무시하고 있었다고 말해도 벌받지 않는 엔지니어는 그 실수를 개연적으로 만든 조건을 정확히 제공한다. 그리고 그 조건들이야말로 고칠 수 있는 유일한 것이다. 사람은 교체할 수 있지만, 다음 사람도 똑같이 낡은 지침서와 똑같이 시끄러운 알림을 마주할 것이다.\n\n이 관행은 책임의 부재로 오해되곤 하고, 그 오해는 직접 답해 둘 값어치가 있다. 무징벌은 조사 과정에 적용되는 것이지 그 뒤 조직이 지는 의무에까지 적용되는 것이 아니다. 원인을 밝혀 놓고 고치지 않은 팀은 사후분석이 면제해 줄 수 없는 무언가에 실패한 것이다. 그리고 반복적으로 조치하지 않는 것이야말로, 무징벌 절차가 감추는 것이 아니라 드러나게 하려고 설계된 바로 그 패턴이다.",
 gloss:[{w:"set aside",ko:"옆으로 치워 두다"},{w:"assign fault",ko:"잘못을 묻다, 책임을 지우다"},{w:"defensible",ko:"방어할 수 있는"},{w:"penalty",ko:"처벌, 불이익"},{w:"runbook",ko:"운영 지침서"},{w:"stale",ko:"낡은, 오래된"},{w:"accountability",ko:"책임(성)"},{w:"excuse (v.)",ko:"면제하다, 봐주다"}],
 qs:[
  {q:"What is the central reason given for setting aside the question of who caused an outage?",
   opts:["Individuals almost never make mistakes during outages.",
         "An organization that punishes error receives less information about it.",
         "Aviation regulations forbid naming individuals in reports.",
         "Outages are usually caused by external vendors."],
   ans:1,exp:"1문단 마지막 두 문장. 개인이 실수하지 않는다는 것이 아니라 처벌하면 배움이 줄어든다는 논거다."},
  {q:"According to the passage, what happens to reports when accounts are used to assign fault?",
   opts:["Only the defensible details survive, and the conditions that produced the error disappear.",
         "They become longer but less accurate about timing.",
         "They are written by managers instead of engineers.",
         "They focus on technical causes rather than human ones."],
   ans:0,exp:"2문단. 방어 가능한 세부만 올라오고 압박 같은 조건은 기록에서 사라진다."},
  {q:"Why does the passage say that replacing a person does not solve the problem?",
   opts:["Hiring a replacement takes longer than repairing the system.",
         "The original engineer usually understood the system best.",
         "The next person will face the same stale runbook and noisy alert.",
         "Replacements are rarely trained on incident procedures."],
   ans:2,exp:"3문단 마지막 문장. 조건이 그대로면 사람만 바뀌어도 같은 상황이 재현된다."},
  {q:"How does the author answer the charge that blameless postmortems remove accountability?",
   opts:["By arguing that accountability is unnecessary after a serious outage",
         "By noting that aviation has abandoned the practice",
         "By claiming that causes can rarely be identified with confidence",
         "By distinguishing the investigation from the organization's later obligation to act"],
   ans:3,exp:"마지막 문단. 무징벌은 '조사'에 적용될 뿐이며 조치하지 않는 것은 면제되지 않는다."}
 ]},

/* ═══════════ 🤖 인공지능 ═══════════ */

{id:"ai-learn", exam:"TOEFL", type:"개념·정의", level:3,
 series:"🤖 인공지능", title:"What Learning Means in Machine Learning",
 topic:"기계학습에서 '학습'이란 무엇인가",
 passage:"The word learning invites a comparison with what a student does, and the comparison misleads in both directions. A statistical model does not understand the material it is trained on, and a student does not adjust several billion numerical parameters. What the two share is narrower and more interesting than the word suggests.\n\nIn its technical sense, learning means adjusting parameters so as to reduce error on examples that have already been seen, in a way that also reduces error on examples that have not. The second half of that sentence carries the whole difficulty. Reducing error on the training data alone is trivial; a model with enough capacity can memorize every example and answer perfectly on all of them while performing no better than chance on anything new. This failure has a name, overfitting, and detecting it is the reason data is divided before training begins.\n\nGeneralization, the property that overfitting destroys, is not something the procedure can verify from the inside. A model has no access to the world; it has access to a sample. Whether performance on that sample transfers depends on whether the sample resembles what the model will later encounter, and that is a claim about the world that no amount of computation can settle. Systems that perform superbly in evaluation and poorly in deployment have almost always failed at this point rather than at any point in the mathematics.\n\nThe practical implication is that the interesting questions in applied machine learning are rarely about algorithms. They are about whether the data collected represents the situation the system will be used in — a question that belongs to the domain rather than to the model, and one that a training procedure will never raise on its own.",
 ko:"'학습'이라는 말은 학생이 하는 일과의 비교를 부르는데, 그 비교는 양쪽 방향 모두에서 오해를 낳는다. 통계 모델은 자기가 학습한 자료를 이해하지 않고, 학생은 수십억 개의 수치 파라미터를 조정하지 않는다. 둘이 공유하는 것은 그 단어가 시사하는 것보다 좁고, 또 더 흥미롭다.\n\n기술적 의미에서 학습이란, 이미 본 예제에 대한 오차를 줄이되 아직 보지 않은 예제에 대한 오차도 함께 줄어드는 방식으로 파라미터를 조정하는 일이다. 그 문장의 뒷부분이 어려움 전부를 짊어진다. 학습 데이터에 대한 오차만 줄이는 것은 사소한 일이다. 용량이 충분한 모델은 모든 예제를 통째로 외워 그것들에 대해서는 완벽하게 답하면서, 새로운 것에 대해서는 찍는 것과 다를 바 없이 굴 수 있다. 이 실패에는 과적합이라는 이름이 있고, 그것을 탐지하는 것이 학습을 시작하기 전에 데이터를 나눠 두는 이유다.\n\n과적합이 망가뜨리는 성질인 일반화는 그 절차가 내부에서 검증할 수 있는 것이 아니다. 모델은 세계에 접근할 수 없다. 모델이 접근하는 것은 표본이다. 그 표본에서의 성능이 이전되는지는 표본이 모델이 나중에 마주할 것과 닮았는지에 달려 있고, 그것은 아무리 계산해도 정할 수 없는 세계에 관한 주장이다. 평가에서는 뛰어나고 실제 투입에서는 형편없는 시스템은 거의 언제나 수학의 어느 지점이 아니라 바로 이 지점에서 실패한 것이다.\n\n실무적 함의는 응용 기계학습에서 흥미로운 질문이 알고리즘에 관한 것인 경우가 드물다는 점이다. 그 질문들은 수집된 데이터가 시스템이 쓰일 상황을 대표하는가에 관한 것이며, 이는 모델이 아니라 그 분야에 속한 질문이고, 학습 절차가 스스로 꺼내는 법이 결코 없는 질문이다.",
 gloss:[{w:"mislead",ko:"오해하게 하다"},{w:"parameter",ko:"파라미터, 매개변수"},{w:"trivial",ko:"사소한, 별것 아닌"},{w:"capacity",ko:"용량, 수용력"},{w:"overfitting",ko:"과적합"},{w:"generalization",ko:"일반화"},{w:"transfer",ko:"(다른 상황으로) 이전되다"},{w:"deployment",ko:"실제 투입, 배치"}],
 qs:[
  {q:"According to the passage, which part of the technical definition of learning creates the real difficulty?",
   opts:["Adjusting parameters numerically rather than symbolically",
         "Collecting enough examples to begin training",
         "Reducing error on examples that have not been seen",
         "Deciding how many parameters a model should have"],
   ans:2,exp:"2문단. '아직 보지 않은 예제에 대한 오차도 줄어드는' 뒷부분이 어려움 전부를 짊어진다고 했다."},
  {q:"Why is reducing error on the training data alone described as trivial?",
   opts:["Training data is usually much smaller than test data.",
         "Training error is not measured in most modern systems.",
         "Errors on training data are corrected automatically by the algorithm.",
         "A model with enough capacity can memorize every example without generalizing."],
   ans:3,exp:"2문단. 통째로 외우면 학습 데이터에서는 완벽하지만 새 데이터에서는 찍는 것과 같다."},
  {q:"Why can a training procedure not verify generalization from the inside?",
   opts:["Verification would require more computation than is available.",
         "The procedure has access only to a sample, not to the world.",
         "Generalization can be measured only after deployment fails.",
         "Most procedures discard their evaluation data before finishing."],
   ans:1,exp:"3문단. 모델은 세계가 아니라 표본에 접근하며, 표본의 대표성은 계산으로 정할 수 없는 세계에 관한 주장이다."},
  {q:"What does the author conclude about applied machine learning?",
   opts:["The key questions concern whether the data represents the situation of use.",
         "Algorithm choice is the decisive factor in most projects.",
         "Overfitting can be eliminated by increasing model capacity.",
         "Evaluation results are generally a reliable guide to deployment."],
   ans:0,exp:"마지막 문단. 흥미로운 질문은 알고리즘이 아니라 데이터의 대표성이며 그것은 도메인의 문제다."}
 ]},

{id:"ai-bench", exam:"TOEFL", type:"평가·방법론", level:4,
 series:"🤖 인공지능", title:"The Benchmark Problem",
 topic:"벤치마크가 측정을 멈추는 순간",
 passage:"Progress in machine learning is reported against benchmarks: fixed collections of problems with known answers, against which successive systems are scored. The arrangement has obvious virtues. It makes claims checkable, allows independent groups to compare results, and converts an argument about impressions into one about numbers.\n\nIt also creates a target, and targets are pursued. Charles Goodhart's observation that a measure ceases to be a good measure once it becomes a goal applies here with unusual force, because the pursuit need not be deliberate. Researchers choose problems that a benchmark rewards, publish the architectures that score well on it, and discard the variants that did not — a filtering process that shapes an entire field toward whatever the benchmark happens to capture, including its idiosyncrasies.\n\nA second difficulty is specific to systems trained on large collections of text. A benchmark is only a test if the answers were not available during training, and material published on the internet has a way of appearing in training corpora. When a benchmark's questions and answers are absorbed this way, high scores measure retrieval rather than capability, and the contamination is difficult to detect from the outside because the training data is often undisclosed and always too large to inspect exhaustively.\n\nNeither problem argues for abandoning quantitative evaluation, which remains the only alternative to assertion. What they argue for is treating a benchmark result as evidence about a particular test rather than about a general ability, and for retiring benchmarks once they have been optimized against — as several research groups now do deliberately. A measure that no longer discriminates between systems has finished its work, whatever the scores continue to say.",
 ko:"기계학습의 진전은 벤치마크에 견주어 보고된다. 정답이 알려진 문제들을 고정된 묶음으로 모아 두고 이후 나오는 시스템들의 점수를 매기는 방식이다. 이 배치에는 분명한 미덕이 있다. 주장을 확인 가능하게 만들고, 독립된 연구 집단들이 결과를 비교할 수 있게 하며, 인상에 관한 논쟁을 숫자에 관한 논쟁으로 바꾼다.\n\n동시에 이는 표적을 만들고, 표적은 추격당한다. 어떤 척도가 목표가 되는 순간 좋은 척도이기를 그친다는 찰스 굿하트의 관찰이 여기에 유별나게 강하게 적용되는데, 그 추격이 의도적일 필요조차 없기 때문이다. 연구자들은 벤치마크가 보상하는 문제를 고르고, 거기서 점수가 잘 나온 구조를 발표하며, 그렇지 않은 변형은 버린다. 이 걸러 내기 과정이 한 분야 전체를 그 벤치마크가 어쩌다 담아낸 것 — 그 특이한 버릇까지 포함해 — 쪽으로 형성해 간다.\n\n두 번째 어려움은 대규모 텍스트 묶음으로 학습한 시스템에 특유하다. 벤치마크가 시험이 되려면 학습 중에 정답을 볼 수 없었어야 하는데, 인터넷에 공개된 자료는 학습 말뭉치에 흘러들기 마련이다. 벤치마크의 문제와 정답이 그런 식으로 흡수되면 높은 점수는 능력이 아니라 인출을 측정하게 되고, 이 오염은 바깥에서 탐지하기 어렵다. 학습 데이터가 공개되지 않는 경우가 많고, 공개되더라도 남김없이 들여다보기에는 언제나 너무 크기 때문이다.\n\n두 문제 중 어느 것도 정량 평가를 버리라는 논거는 아니다. 정량 평가는 단언 말고 남은 유일한 대안이다. 두 문제가 요구하는 것은 벤치마크 결과를 일반적 능력이 아니라 특정 시험에 관한 증거로 다루라는 것, 그리고 최적화의 대상이 되어 버린 벤치마크는 은퇴시키라는 것이다. 여러 연구 집단이 이제 의도적으로 그렇게 한다. 시스템들을 더 이상 변별하지 못하는 척도는 점수가 계속 무엇을 말하든 제 할 일을 마친 것이다.",
 gloss:[{w:"successive",ko:"잇따르는, 연속하는"},{w:"checkable",ko:"확인 가능한"},{w:"cease",ko:"그치다, 멈추다"},{w:"discard",ko:"버리다"},{w:"idiosyncrasy",ko:"특이한 성질, 버릇"},{w:"corpus (pl. corpora)",ko:"말뭉치"},{w:"contamination",ko:"오염"},{w:"discriminate",ko:"변별하다, 구별하다"}],
 qs:[
  {q:"According to the passage, why does Goodhart's observation apply with unusual force to benchmarks?",
   opts:["Because the pursuit of the target need not be deliberate to shape the field",
         "Because researchers deliberately cheat on well-known benchmarks",
         "Because benchmarks are updated too frequently to be reliable",
         "Because no independent group can reproduce benchmark results"],
   ans:0,exp:"2문단. 문제 선택과 발표·폐기라는 걸러 내기가 의도 없이도 분야 전체를 형성한다."},
  {q:"What is the specific problem described for systems trained on large text collections?",
   opts:["Text benchmarks contain fewer problems than image benchmarks.",
         "Benchmark answers may appear in the training data, so scores measure retrieval.",
         "Such systems cannot be evaluated with numerical scores at all.",
         "Training corpora are usually too small to cover the benchmark topics."],
   ans:1,exp:"3문단. 오염되면 능력이 아니라 인출을 재게 된다."},
  {q:"Why is contamination hard to detect from outside?",
   opts:["Benchmarks do not record when their questions were published.",
         "Research groups are legally prevented from publishing their data.",
         "Retrieval and capability produce identical internal representations.",
         "Training data is often undisclosed and always too large to inspect exhaustively."],
   ans:3,exp:"3문단 마지막 문장이 두 이유를 함께 든다."},
  {q:"What does the author recommend doing with a benchmark that has been heavily optimized against?",
   opts:["Increasing the number of problems it contains",
         "Keeping it but weighting its score lower",
         "Retiring it, since a measure that no longer discriminates has finished its work",
         "Replacing quantitative evaluation with expert judgement"],
   ans:2,exp:"마지막 문단. 여러 연구 집단이 이미 의도적으로 은퇴시키고 있다고 했다."}
 ]},

{id:"ai-halluc", exam:"TOEFL", type:"원리·한계", level:4,
 series:"🤖 인공지능", title:"Why Language Models Invent Things",
 topic:"언어 모델은 왜 없는 것을 지어내는가",
 passage:"A language model asked for a citation will sometimes produce one that does not exist, complete with plausible authors, a real journal, and a volume number in the right range. The behaviour is commonly called hallucination, a term that suggests malfunction. It is more accurately described as the system doing exactly what it was built to do under conditions where that is not what the user wanted.\n\nSuch a model is trained to continue text in a way consistent with the patterns of its training data. A citation has a strong and regular form, and producing a well-formed instance of that pattern is the same operation whether or not the particular work exists. Nothing in the training objective distinguishes a true statement from a statement shaped like a true one, because truth is not a property the objective can observe. It can observe only what typically follows what.\n\nThe difficulty is therefore not a defect that a larger model removes. Scale has reduced the frequency of confident errors, largely by making the patterns finer, but it does not introduce a mechanism for checking claims against the world, and there is no reason internal to the method why it would. Improvements that do help — retrieving documents before answering, restricting responses to a supplied source, exposing uncertainty — all work by adding something outside the model rather than by making the model better at prediction.\n\nThis has a consequence for how such systems should be deployed. A model's fluency is uninformative about its reliability, since both are produced by the same process, and users calibrate trust largely on fluency. Any deployment that presents generated text without a route back to a source is relying on a signal that the system does not in fact provide.",
 ko:"언어 모델에 인용 출처를 요구하면 때때로 존재하지 않는 것을 만들어 낸다. 그럴듯한 저자, 실재하는 학술지, 범위에 맞는 권 번호까지 갖춘 채로. 이 행동은 흔히 환각이라 불리는데, 이 용어는 오작동을 시사한다. 더 정확하게는, 그것이 사용자가 원한 바가 아닌 조건에서 시스템이 만들어진 그대로를 하고 있는 것이다.\n\n그런 모델은 학습 데이터의 패턴과 일관되게 텍스트를 이어 가도록 훈련된다. 인용에는 강하고 규칙적인 형식이 있고, 그 패턴에 잘 들어맞는 사례를 만들어 내는 일은 그 특정 저작이 실재하든 아니든 동일한 연산이다. 학습 목표 안에는 참인 진술과 참인 진술처럼 생긴 진술을 구별하는 것이 아무것도 없다. 참은 그 목표가 관찰할 수 있는 성질이 아니기 때문이다. 목표가 관찰할 수 있는 것은 무엇 다음에 무엇이 흔히 오는가뿐이다.\n\n따라서 이 어려움은 더 큰 모델이 없애 주는 결함이 아니다. 규모는 자신만만한 오류의 빈도를 줄여 왔다. 주로 패턴을 더 촘촘하게 만듦으로써다. 그러나 규모가 주장을 세계에 대조해 보는 기제를 도입하지는 않으며, 그 방법 자체에 그렇게 될 이유가 내재해 있지도 않다. 실제로 도움이 되는 개선들 — 답하기 전에 문서를 검색하기, 제공된 출처 안으로 응답을 제한하기, 불확실성을 드러내기 — 은 모두 모델을 예측에 더 능하게 만드는 것이 아니라 모델 바깥에 무언가를 덧붙임으로써 작동한다.\n\n이는 그런 시스템을 어떻게 투입해야 하는지에 결과를 남긴다. 모델의 유창함은 그 신뢰도에 대해 아무것도 알려 주지 않는다. 둘 다 같은 과정에서 나오기 때문이다. 그런데 사용자는 대체로 유창함을 근거로 신뢰를 조정한다. 생성된 텍스트를 출처로 되돌아갈 경로 없이 내보이는 모든 투입 방식은, 시스템이 실제로는 제공하지 않는 신호에 기대고 있는 셈이다.",
 gloss:[{w:"plausible",ko:"그럴듯한"},{w:"malfunction",ko:"오작동"},{w:"objective",ko:"(학습) 목표, 목적함수"},{w:"scale",ko:"규모"},{w:"retrieve",ko:"검색해 가져오다"},{w:"expose",ko:"드러내다"},{w:"fluency",ko:"유창함"},{w:"calibrate",ko:"(기준을) 맞추다, 조정하다"}],
 qs:[
  {q:"Why does the passage object to the term hallucination?",
   opts:["It is too technical for general readers.",
         "It suggests malfunction, whereas the system is doing what it was built to do.",
         "It was borrowed from psychology without permission.",
         "It applies only to models trained on images."],
   ans:1,exp:"1문단 마지막 두 문장. 오작동이 아니라 설계대로의 동작이라는 점을 강조한다."},
  {q:"According to the passage, why can the training objective not distinguish true statements from false ones?",
   opts:["The training data contains too many false statements to learn from.",
         "Citations are excluded from most training corpora.",
         "The objective is evaluated only after deployment.",
         "Truth is not a property the objective can observe; it observes only what typically follows what."],
   ans:3,exp:"2문단 마지막 두 문장이 직접 답한다."},
  {q:"What does the passage say about the effect of increasing model scale?",
   opts:["It eliminates confident errors entirely.",
         "It makes the problem measurably worse.",
         "It reduces their frequency but adds no mechanism for checking claims against the world.",
         "It replaces prediction with retrieval."],
   ans:2,exp:"3문단. 빈도는 줄었지만 대조 기제가 생기지는 않았고, 방법 내부에 그럴 이유도 없다."},
  {q:"Why is fluency a misleading signal for users?",
   opts:["Fluency and reliability come from the same process, so one says nothing about the other.",
         "Fluent text is usually generated more slowly.",
         "Users generally distrust fluent text more than awkward text.",
         "Fluency is measured differently by each research group."],
   ans:0,exp:"마지막 문단. 둘 다 같은 과정의 산물이라 유창함은 신뢰도의 근거가 되지 못한다."}
 ]},

{id:"ai-data", exam:"TOEFL", type:"윤리·사회", level:3,
 series:"🤖 인공지능", title:"Data Is Not Neutral",
 topic:"데이터는 중립적이지 않다",
 passage:"A recruiting system trained on a decade of a company's hiring decisions will reproduce those decisions, including the ones the company would not defend. This is often described as bias entering the model, but the phrasing misplaces the event. Nothing entered. The model was asked to predict what the company had done, and it succeeded.\n\nThe error is in treating a record of past decisions as a record of merit. Historical data documents outcomes together with everything that produced them: which schools recruiters visited, who was encouraged to apply, which résumés were read on a busy afternoon. A model fitted to that record cannot separate the signal a designer intended from the circumstances that accompanied it, because both are present in exactly the same numbers.\n\nRemedies are harder than they first appear. Deleting the sensitive attribute rarely works, since other variables carry the same information — a postal code, an activity, the name of a school. Enforcing equal outcomes across groups conflicts with equal treatment of individuals in ways that cannot be resolved by tuning, since the two criteria are mathematically incompatible except in special cases. Each choice among these is a decision about what fairness means in the particular setting, and it is not the kind of decision that a metric can make.\n\nWhat follows is not that such systems should never be built. It is that the important work occurs before any model is fitted, in specifying what the system is supposed to predict and whether the available record can stand in for it. A team that skips that step has not avoided the decision; it has delegated it to whatever the data happened to contain.",
 ko:"어떤 회사의 10년치 채용 결정으로 학습한 채용 시스템은 그 결정들을 재생산한다. 그 회사가 옹호하지 않을 결정들까지 포함해서다. 이는 흔히 편향이 모델에 '들어갔다'고 설명되지만, 그 표현은 사건이 일어난 자리를 잘못 짚는다. 들어간 것은 없다. 모델은 그 회사가 무엇을 했는지 예측하라는 요구를 받았고, 성공했다.\n\n오류는 과거 결정의 기록을 능력의 기록으로 취급하는 데 있다. 역사적 데이터는 결과와 함께 그 결과를 낳은 모든 것을 기록한다. 채용 담당자가 어느 학교를 방문했는지, 누가 지원을 권유받았는지, 바쁜 오후에 어느 이력서가 읽혔는지까지. 그 기록에 맞춰진 모델은 설계자가 의도한 신호를 그것에 동반된 정황으로부터 떼어 낼 수 없다. 둘 다 정확히 같은 숫자들 속에 들어 있기 때문이다.\n\n해결책은 처음 보이는 것보다 어렵다. 민감한 속성을 지우는 것은 거의 통하지 않는다. 우편번호, 활동 이력, 학교 이름 같은 다른 변수들이 같은 정보를 실어 나르기 때문이다. 집단 간 결과를 같게 강제하는 것은 개인에 대한 동등한 처우와 충돌하며, 이는 조정으로 풀 수 있는 성질이 아니다. 두 기준은 특수한 경우를 빼면 수학적으로 양립할 수 없기 때문이다. 이 중에서 무엇을 고르든 그것은 그 특정 상황에서 공정함이 무엇을 뜻하는지에 대한 결정이며, 지표가 대신 내릴 수 있는 종류의 결정이 아니다.\n\n여기서 따라 나오는 결론은 그런 시스템을 결코 만들지 말라는 것이 아니다. 중요한 작업이 모델을 맞추기 전에, 즉 이 시스템이 무엇을 예측해야 하는지와 지금 가진 기록이 그것을 대신할 수 있는지를 규정하는 단계에서 일어난다는 것이다. 그 단계를 건너뛴 팀은 결정을 피한 것이 아니다. 데이터에 어쩌다 담겨 있던 것에 그 결정을 위임한 것이다.",
 gloss:[{w:"reproduce",ko:"재생산하다"},{w:"misplace",ko:"자리를 잘못 짚다"},{w:"merit",ko:"능력, 공로"},{w:"fit (a model)",ko:"모델을 (데이터에) 맞추다"},{w:"attribute",ko:"속성, 변수"},{w:"incompatible",ko:"양립할 수 없는"},{w:"stand in for",ko:"~을 대신하다"},{w:"delegate",ko:"위임하다"}],
 qs:[
  {q:"Why does the passage object to saying that bias entered the model?",
   opts:["Because the bias was introduced by the engineers rather than the data",
         "Because recruiting systems are not trained on historical data",
         "Because the term bias has a different technical meaning",
         "Because nothing entered — the model succeeded at predicting past decisions"],
   ans:3,exp:"1문단 마지막 세 문장. 실패가 아니라 성공이며, 무언가 유입된 사건이 아니다."},
  {q:"According to the passage, what does historical hiring data actually record?",
   opts:["Outcomes together with all the circumstances that produced them",
         "Only the qualifications of the candidates who applied",
         "The reasoning each recruiter wrote down at the time",
         "A representative sample of the labour market"],
   ans:0,exp:"2문단. 방문한 학교, 지원 권유, 읽힌 이력서 같은 정황이 결과와 함께 기록된다."},
  {q:"Why does deleting a sensitive attribute usually fail?",
   opts:["The model requires that attribute in order to converge.",
         "Other variables such as postal code carry the same information.",
         "Regulations require the attribute to be retained.",
         "Deletion makes the training data too small to use."],
   ans:1,exp:"3문단. 다른 변수들이 같은 정보를 대신 실어 나른다."},
  {q:"What does the passage say a team does by skipping the specification step?",
   opts:["It avoids making a contested decision about fairness.",
         "It guarantees that the model will overfit.",
         "It delegates the decision to whatever the data happened to contain.",
         "It reduces the cost of building the system substantially."],
   ans:2,exp:"마지막 문장 그대로다. 피한 것이 아니라 데이터에 위임한 것이다."}
 ]},

{id:"ai-cost", exam:"TOEFL", type:"경제·환경", level:3,
 series:"🤖 인공지능", title:"The Cost of Asking",
 topic:"묻는 데 드는 값 — 추론 비용의 경제학",
 passage:"Public discussion of the resources consumed by artificial intelligence has concentrated on training, and the figures are striking: months of computation across thousands of processors for a single large model. Training, however, happens once. Inference — the work of answering an individual request — happens every time anyone uses the system, and for a widely deployed model the accumulated total surpasses training within a period usually measured in weeks.\n\nThis changes which engineering decisions matter. A technique that shortens training by a fifth is worth having; a technique that reduces the cost of a single response by the same proportion is worth far more, because it applies to every request for the life of the deployment. Much recent work reflects this, concentrating on making models smaller, quantizing their parameters, or routing easy requests to cheaper systems and reserving the expensive one for cases that need it.\n\nThe economics have a physical dimension as well. Inference must be fast enough to feel immediate, which means the hardware has to be available at the moment of the request rather than scheduled when power is cheap. Training can be moved to a region with surplus renewable generation and run overnight; a chat response cannot. The environmental profile of the two activities is therefore different in kind, not only in magnitude, and comparisons that report a single figure for the energy cost of a model tend to obscure this.\n\nThe practical upshot is that the cost of these systems is a recurring operating expense rather than a capital investment, and it scales with success. A product that becomes popular becomes more expensive to run in direct proportion, which is a relationship that most software businesses have not had to plan around before.",
 ko:"인공지능이 쓰는 자원에 관한 공개 논의는 학습에 집중되어 왔고, 그 수치는 인상적이다. 단일 대형 모델 하나에 수천 개 프로세서로 몇 달치 연산이 든다. 그러나 학습은 한 번 일어난다. 추론 — 개별 요청에 답하는 작업 — 은 누군가 그 시스템을 쓸 때마다 일어나며, 널리 배포된 모델이라면 누적 총량이 대개 몇 주 단위로 측정되는 기간 안에 학습을 넘어선다.\n\n이는 어떤 공학적 결정이 중요한지를 바꿔 놓는다. 학습 시간을 5분의 1 줄이는 기법은 가질 만한 것이다. 응답 하나의 비용을 같은 비율로 줄이는 기법은 훨씬 더 값지다. 그 서비스가 살아 있는 내내 모든 요청에 적용되기 때문이다. 최근 연구의 상당 부분이 이를 반영해 모델을 더 작게 만들거나, 파라미터를 양자화하거나, 쉬운 요청은 더 값싼 시스템으로 보내고 비싼 쪽은 정말 필요한 경우에만 남겨 두는 데 집중한다.\n\n이 경제학에는 물리적 차원도 있다. 추론은 즉각적으로 느껴질 만큼 빨라야 하고, 이는 하드웨어가 전기가 쌀 때로 일정을 잡히는 것이 아니라 요청이 오는 그 순간에 대기하고 있어야 한다는 뜻이다. 학습은 재생에너지가 남아도는 지역으로 옮겨 밤새 돌릴 수 있지만, 대화 응답은 그럴 수 없다. 따라서 두 활동의 환경적 성격은 크기만이 아니라 종류가 다르며, 어떤 모델의 에너지 비용을 숫자 하나로 보고하는 비교는 이 점을 가리는 경향이 있다.\n\n실질적 귀결은 이런 시스템의 비용이 자본 투자가 아니라 반복되는 운영비이며, 성공에 비례해 커진다는 것이다. 인기를 얻은 제품은 그에 정비례해 굴리는 데 더 비싸진다. 이는 대부분의 소프트웨어 사업이 지금까지 계획에 넣을 필요가 없었던 관계다.",
 gloss:[{w:"inference",ko:"추론(요청에 답하는 연산)"},{w:"surpass",ko:"넘어서다"},{w:"proportion",ko:"비율"},{w:"quantize",ko:"양자화하다(정밀도를 낮추다)"},{w:"route",ko:"(요청을) 보내다, 경로를 정하다"},{w:"surplus",ko:"남는, 잉여의"},{w:"in kind",ko:"종류에서"},{w:"operating expense",ko:"운영비"}],
 qs:[
  {q:"Why does the passage argue that inference deserves more attention than training?",
   opts:["Training requires more processors than inference does.",
         "Training results are rarely published in detail.",
         "Inference happens on every request and soon exceeds the total cost of training.",
         "Inference produces more accurate results over time."],
   ans:2,exp:"1문단 마지막 문장. 널리 배포되면 몇 주 안에 누적 추론량이 학습을 넘어선다."},
  {q:"Which of the following is NOT mentioned as recent work aimed at reducing inference cost?",
   opts:["Making models smaller",
         "Training models on smaller datasets",
         "Quantizing parameters",
         "Routing easy requests to cheaper systems"],
   ans:1,exp:"2문단이 앞의 세 가지를 열거한다. 데이터셋 축소는 언급되지 않았다."},
  {q:"Why is the environmental profile of inference different in kind from that of training?",
   opts:["Inference uses hardware that cannot be manufactured sustainably.",
         "Training consumes no electricity once the model is complete.",
         "Inference is performed only in regions with surplus renewable generation.",
         "Inference must run at the moment of the request, so it cannot be scheduled when power is cheap."],
   ans:3,exp:"3문단. 학습은 시간과 장소를 옮길 수 있지만 대화 응답은 그럴 수 없다."},
  {q:"What is unusual about the cost structure described in the final paragraph?",
   opts:["It is a recurring operating expense that scales directly with success.",
         "It falls as the number of users grows.",
         "It must be paid entirely before the product launches.",
         "It cannot be measured until the product is retired."],
   ans:0,exp:"마지막 문단. 자본 투자가 아니라 성공에 정비례해 커지는 운영비라는 점이 새롭다."}
 ]},

{id:"ai-work", exam:"TOEFL", type:"사회·노동", level:4,
 series:"🤖 인공지능", title:"Automation and the Shape of Work",
 topic:"자동화는 일의 모양을 어떻게 바꾸는가",
 passage:"Predictions about automation usually take the form of a count: how many occupations will disappear. The historical record suggests that this is the wrong unit. Technologies rarely remove whole occupations; they remove particular tasks, after which the occupation reassembles around what is left, sometimes growing rather than shrinking.\n\nThe case of the automated teller machine is instructive because it contradicts the intuitive prediction. Machines took over cash handling, the most visible part of a bank teller's job, and the number of tellers employed in the United States nevertheless rose for two decades afterwards. Branches became cheaper to operate, so banks opened more of them, and the remaining staff moved toward sales and customer problems. The task vanished; the occupation was reorganized around a different centre.\n\nThis pattern offers no general reassurance, because reorganization distributes its costs unevenly. The tellers of the following decade were not the same individuals, and the skills that became valuable were not the skills that had been displaced. An aggregate employment figure that holds steady can conceal a complete turnover in who holds the jobs, which is why studies reporting no net loss and workers reporting severe disruption are often both describing the situation accurately.\n\nWhat distinguishes the current wave is which tasks are exposed. Earlier automation displaced physical and routine clerical work, leaving analysis and composition largely untouched; recent systems are strongest at exactly the drafting, summarizing, and first-pass reasoning that formed the training ground of many professions. The concern is less that these occupations will vanish than that the lower rungs by which people entered them may. An occupation can survive the loss of its entry-level tasks; the pipeline of people who would have learned the work by doing them may not.",
 ko:"자동화에 관한 예측은 대개 개수를 세는 형태를 띤다. 몇 개의 직업이 사라질 것인가 하는 식이다. 역사적 기록은 그것이 잘못된 단위임을 시사한다. 기술이 직업을 통째로 없애는 일은 드물다. 기술은 특정 과업을 없애고, 그 뒤 직업은 남은 것을 중심으로 다시 조립되며, 줄어드는 대신 늘어나기도 한다.\n\n현금자동입출금기 사례는 직관적 예측과 어긋나기 때문에 교훈적이다. 기계가 은행 창구직원 업무에서 가장 눈에 띄는 부분인 현금 취급을 넘겨받았는데도, 미국에서 고용된 창구직원 수는 그 뒤 20년 동안 오히려 늘었다. 지점 운영비가 싸지자 은행들이 지점을 더 열었고, 남은 인력은 영업과 고객 문제 해결 쪽으로 옮겨 갔다. 과업은 사라졌고, 직업은 다른 중심을 축으로 재편되었다.\n\n이 패턴이 일반적인 안심을 주지는 않는다. 재편은 비용을 고르지 않게 분배하기 때문이다. 그다음 10년의 창구직원은 같은 사람들이 아니었고, 값어치가 생긴 기술은 밀려난 그 기술이 아니었다. 총량으로 본 고용 수치가 변함없어 보여도 그 자리를 누가 차지하는지는 완전히 물갈이되었을 수 있다. 순손실이 없다고 보고하는 연구와 심각한 타격을 호소하는 노동자가 둘 다 상황을 정확히 기술하고 있는 경우가 잦은 이유가 여기에 있다.\n\n지금의 물결을 구별 짓는 것은 어떤 과업이 노출되는가다. 이전의 자동화는 육체노동과 정형화된 사무 업무를 밀어냈고 분석과 작성은 대체로 건드리지 않았다. 최근 시스템은 바로 그 초안 작성, 요약, 1차 추론에 가장 강한데, 그것들은 많은 전문직의 훈련장이었던 일들이다. 우려는 이 직업들이 사라진다는 것보다, 사람들이 그 직업에 들어서던 아래쪽 발판이 사라질 수 있다는 데 있다. 직업은 입문 단계 과업을 잃고도 살아남을 수 있다. 그 일을 하면서 일을 배웠을 사람들의 유입 경로는 그러지 못할 수도 있다.",
 gloss:[{w:"occupation",ko:"직업"},{w:"reassemble",ko:"다시 조립되다, 재구성되다"},{w:"instructive",ko:"교훈적인"},{w:"displace",ko:"밀어내다, 대체하다"},{w:"aggregate",ko:"총계의, 합산한"},{w:"turnover",ko:"인력 교체, 물갈이"},{w:"first-pass",ko:"1차의, 초벌의"},{w:"rung",ko:"(사다리의) 가로대, 단계"}],
 qs:[
  {q:"Why does the passage say that counting occupations is the wrong unit?",
   opts:["Technologies remove tasks, after which occupations reorganize around what remains.",
         "Occupations are defined differently in different countries.",
         "Employment statistics are collected too infrequently to be useful.",
         "Most occupations disappear for reasons unrelated to technology."],
   ans:0,exp:"1문단. 직업이 아니라 과업이 사라지고 직업은 남은 것을 중심으로 재조립된다."},
  {q:"What happened to the number of bank tellers after cash handling was automated?",
   opts:["It fell sharply within five years.",
         "It remained exactly constant for two decades.",
         "It rose for two decades as banks opened more branches.",
         "It rose only in branches that refused to install machines."],
   ans:2,exp:"2문단. 지점 운영비가 싸져 지점이 늘었고 창구직원 수도 20년간 증가했다."},
  {q:"Why can a steady aggregate employment figure be misleading?",
   opts:["It is usually collected from employers rather than workers.",
         "It excludes part-time and temporary positions.",
         "It is published years after the period it describes.",
         "It may conceal a complete turnover in who holds the jobs."],
   ans:3,exp:"3문단. 총량이 같아도 그 자리를 차지하는 사람이 물갈이될 수 있다."},
  {q:"According to the final paragraph, what is the principal concern about the current wave?",
   opts:["That analysis and composition will become impossible for humans",
         "That the entry-level tasks through which people learned a profession may disappear",
         "That physical and clerical work will be automated a second time",
         "That professions will grow faster than they can train new members"],
   ans:1,exp:"마지막 두 문장. 직업 자체보다 '들어서던 아래쪽 발판'과 유입 경로가 걱정거리다."}
 ]}

]);
