/* ============================================================
   관심주제 리딩 — 영화
   ------------------------------------------------------------
   쥬라기 공원 4편 · 쇼생크 탈출 3편 · 아메리칸 뷰티 3편

   줄거리 요약이 아니라 각 작품이 실제로 무엇을 주장하는지,
   그 주장을 어떤 형식으로 밀고 나가는지를 따지는 분석문이다.
   ============================================================ */
window.TOPIC_READING_EXTRA = (window.TOPIC_READING_EXTRA||[]).concat([

  /* ═══════════ 쥬라기 공원 ═══════════ */

  {id:"jp-chaos", exam:"TOEFL", type:"과학·논증", level:4,
   series:"🦖 쥬라기 공원", title:"What the Mathematician Is Actually Saying",
   topic:"쥬라기 공원 — 혼돈 이론은 무엇을 주장했나",
   passage:"The mathematician's warnings in Jurassic Park are often summarized as a claim that nature cannot be controlled, which makes the argument sound mystical. The argument he actually makes is narrower and stronger.\n\nHis position concerns prediction in systems with many interacting parts. In such systems, small differences in starting conditions produce large differences in outcome, and the differences grow rather than settling. This does not mean the system is random or that its behaviour is unknowable in principle. It means that a list of the ways the system might fail cannot be completed in advance, because the number of relevant interactions exceeds what can be enumerated.\n\nThe park's designers are not portrayed as careless, and this is essential to the point. They have addressed every failure mode they identified: electrified enclosures, restricted breeding, redundant computer systems, staged introductions of visitors. The disaster arrives through a combination they did not list — a single employee's sabotage, a tropical storm, and a security system that concentrated all controls in one place. Each element was foreseeable individually.\n\nThis is why the film's most quoted line is a criticism of process rather than of ambition. The objection is not that the scientists created something dangerous but that they treated the absence of an identified problem as evidence that no problem existed — a mistake available to any project complex enough that no one holds the whole of it in mind.",
   ko:"『쥬라기 공원』에서 수학자가 내놓는 경고는 흔히 '자연은 통제할 수 없다'는 주장으로 요약되고, 그렇게 옮기면 그의 논지가 신비주의처럼 들린다. 그가 실제로 펴는 논지는 그보다 좁고 그래서 더 강하다.\n\n그의 입장은 서로 영향을 주고받는 부분이 많은 체계에서의 예측에 관한 것이다. 그런 체계에서는 초기 조건의 작은 차이가 결과의 큰 차이를 낳고, 그 차이는 가라앉는 대신 커진다. 이는 체계가 무작위라거나 그 거동을 원리적으로 알 수 없다는 뜻이 아니다. 그 체계가 고장 날 수 있는 방식의 목록을 미리 완성할 수 없다는 뜻이다. 관련된 상호작용의 수가 열거할 수 있는 범위를 넘어서기 때문이다.\n\n공원의 설계자들이 부주의한 사람으로 그려지지 않는다는 점이 이 논지에 결정적이다. 그들은 자신들이 식별한 고장 방식을 모두 처리해 두었다. 전기 울타리, 번식 제한, 이중화된 전산 체계, 방문객의 단계적 투입. 재난은 그들이 목록에 넣지 않은 조합으로 도착한다. 직원 한 명의 파괴 행위, 열대 폭풍, 그리고 모든 제어를 한곳에 몰아 둔 보안 체계. 각 요소는 하나씩 떼어 놓으면 충분히 예견할 수 있는 것들이었다.\n\n그래서 이 영화에서 가장 많이 인용되는 대사는 야심이 아니라 절차에 대한 비판이다. 반론은 과학자들이 위험한 무언가를 만들었다는 것이 아니라, 식별된 문제가 없다는 사실을 문제가 없다는 증거로 취급했다는 것이다. 이는 아무도 전체를 머릿속에 담지 못할 만큼 복잡한 어떤 사업에서도 저지를 수 있는 잘못이다.",
   gloss:[{w:"enumerate",ko:"열거하다"},{w:"failure mode",ko:"고장 방식, 실패 유형"},
          {w:"enclosure",ko:"울타리, 사육 구역"},{w:"redundant",ko:"이중화된, 여분의"},
          {w:"sabotage",ko:"고의적 파괴 행위"},{w:"foreseeable",ko:"예견 가능한"}],
   qs:[
     {q:"According to the passage, what does the mathematician's argument actually claim?",
      opts:["That complex systems behave randomly",
            "That the list of possible failures cannot be completed in advance",
            "That computers should not be trusted with safety functions",
            "That biological systems differ fundamentally from mechanical ones"],
      ans:1, exp:"2문단: 무작위라는 뜻이 아니라 '고장 날 수 있는 방식의 목록을 미리 완성할 수 없다'는 뜻이다."},
     {q:"Why is it important that the designers are not portrayed as careless?",
      opts:["It shows that the disaster was caused by a single individual.",
            "It establishes that competence alone does not prevent this kind of failure.",
            "It explains why the park was approved by regulators.",
            "It suggests the warnings were unnecessary."],
      ans:1, exp:"3문단: 식별한 고장 방식은 전부 처리했는데도 목록에 없던 조합으로 재난이 온다. 부주의가 원인이 아니라는 점이 논지의 핵심이다."},
     {q:"What mistake does the author identify as the film's real target?",
      opts:["Treating the absence of an identified problem as proof there is none",
            "Allowing visitors onto the island too early",
            "Hiring staff without adequate background checks",
            "Pursuing scientific goals for commercial reasons"],
      ans:0, exp:"마지막 문단: '식별된 문제가 없다는 사실을 문제가 없다는 증거로 취급했다'는 절차상의 잘못이다."}
   ]},

  {id:"jp-control", exam:"TOEFL", type:"과학·설계", level:4,
   series:"🦖 쥬라기 공원", title:"The Safeguard That Became the Failure",
   topic:"쥬라기 공원 — 통제 장치가 실패 지점이 될 때",
   passage:"Two engineering decisions define the park's biological containment, and the film arranges for both to fail in the same way: by working exactly as designed.\n\nThe first concerns the reconstruction of incomplete genetic material. Where sequences were missing, the geneticists filled the gaps with material from living amphibians. The choice was practical — something had to occupy the gaps — and its consequences were not examined, because the inserted material was regarded as filler rather than as part of the organism. The film's premise is that no genetic contribution is inert. Whatever is added is expressed.\n\nThe second decision was to produce only female animals, on the reasoning that a population unable to breed cannot establish itself. This is sound as far as it goes, and it is presented in the film with justified confidence. It fails because it depends on the first decision: the amphibian contribution carried a capacity for reproductive change that the designers had no reason to look for, since they were not thinking of that material as contributing anything.\n\nThe structure of the failure is worth noting. Neither measure was defeated by an outside force. The single-sex population was enforced successfully; the gaps were filled successfully. The two safeguards interacted, and the interaction lay outside the responsibility of anyone who had designed either. Systems assembled from separately validated components can fail in precisely this manner, at the joints nobody owns.",
   ko:"이 공원의 생물학적 격리를 규정하는 공학적 결정은 두 가지이고, 영화는 그 둘이 똑같은 방식으로 무너지도록 배치한다. 설계된 그대로 작동함으로써 무너지는 것이다.\n\n첫째는 불완전한 유전 물질의 복원에 관한 것이다. 서열이 빠진 자리를 유전학자들은 현생 양서류의 물질로 메웠다. 실용적인 선택이었다. 무언가는 그 빈자리를 채워야 했으니까. 그리고 그 결과는 검토되지 않았는데, 삽입된 물질이 생물의 일부가 아니라 채움재로 여겨졌기 때문이다. 이 영화의 전제는 어떤 유전적 기여도 불활성이 아니라는 것이다. 더해진 것은 무엇이든 발현된다.\n\n둘째 결정은 암컷만 생산한다는 것이었다. 번식할 수 없는 개체군은 자리 잡을 수 없다는 논리였다. 그 자체로는 타당하며 영화도 정당한 자신감과 함께 이를 제시한다. 이 결정이 실패하는 것은 그것이 첫 번째 결정에 기대고 있기 때문이다. 양서류에서 온 기여는 설계자들이 찾아볼 이유가 없던 생식적 변화의 가능성을 품고 있었다. 그들은 그 물질이 무언가를 기여한다고 생각조차 하지 않았으니 말이다.\n\n이 실패의 구조는 눈여겨볼 만하다. 어느 조치도 외부의 힘에 뚫린 것이 아니다. 단일 성별 개체군은 성공적으로 관철되었고, 빈자리는 성공적으로 메워졌다. 두 안전장치가 서로 영향을 주고받았고, 그 상호작용은 둘 중 어느 것을 설계한 사람의 책임 범위에도 들어 있지 않았다. 각각 검증된 부품으로 조립된 체계는 바로 이런 방식으로, 아무도 소유하지 않은 이음매에서 무너질 수 있다.",
   gloss:[{w:"containment",ko:"격리, 봉쇄"},{w:"sequence",ko:"(유전자) 서열"},
          {w:"filler",ko:"채움재"},{w:"inert",ko:"불활성의, 아무 작용도 하지 않는"},
          {w:"express",ko:"(유전자가) 발현되다"},{w:"validated",ko:"검증된"},
          {w:"joint",ko:"이음매"}],
   qs:[
     {q:"Why were the consequences of the gap-filling not examined?",
      opts:["The material was thought of as filler rather than part of the organism.",
            "No suitable donor species was available for testing.",
            "The geneticists were working under severe time pressure.",
            "Regulations did not require such an examination."],
      ans:0, exp:"2문단: 삽입된 물질이 '생물의 일부가 아니라 채움재로 여겨졌기 때문'에 검토되지 않았다."},
     {q:"What does the passage say about the single-sex policy?",
      opts:["It was never properly enforced.",
            "It was sound in itself but depended on the earlier decision.",
            "It was introduced only after the first breeding was detected.",
            "It applied to some species but not others."],
      ans:1, exp:"3문단: 'sound as far as it goes'였으나 첫 번째 결정에 기대고 있었기에 실패한다."},
     {q:"What general point does the last paragraph make?",
      opts:["Safety measures should be tested by outside inspectors.",
            "Systems can fail at interactions that no designer is responsible for.",
            "Biological systems cannot be engineered reliably.",
            "Redundancy always increases the chance of failure."],
      ans:1, exp:"마지막 문장: 검증된 부품으로 조립된 체계가 '아무도 소유하지 않은 이음매'에서 무너진다는 것이 요지다."}
   ]},

  {id:"jp-effects", exam:"TOEFL", type:"영화·기술", level:3,
   series:"🦖 쥬라기 공원", title:"Showing Less: The Restraint Behind the Effects",
   topic:"쥬라기 공원 — 적게 보여 주는 기술",
   passage:"Jurassic Park is remembered as the film that made digital creatures convincing, and it is usually discussed in terms of what the technology could do. The more instructive question is how little of it the film uses.\n\nThe production combined two methods. Full-size mechanical models handled close contact — animals seen at rest, in confined spaces, or touching the actors — while computer-generated imagery handled movement across open ground. The combination mattered because each method's weakness was covered by the other's strength: mechanical models were convincing but could barely move, and digital models moved freely but were less convincing when examined at length.\n\nThe editing follows from this division. Total screen time for the animals is remarkably small for a film of its reputation, and the most frightening sequence contains almost no visible creature at all — a vibration in a glass of water, a mirror, a sound. The withholding is not merely a budget constraint made into a virtue. An audience shown a creature briefly completes the image itself and does so more effectively than a longer look would allow, because attention supplies detail that scrutiny would question.\n\nLater productions with far greater digital capacity have frequently produced less convincing results by reversing this ratio. What the film demonstrates is that credibility in effects work depends less on the quality of any single image than on how much time an audience is given to disbelieve it.",
   ko:"『쥬라기 공원』은 디지털 생물을 설득력 있게 만든 영화로 기억되며, 대개 그 기술이 무엇을 할 수 있었는가를 두고 이야기된다. 더 배울 것이 많은 물음은 이 영화가 그것을 얼마나 적게 썼는가이다.\n\n제작진은 두 가지 방법을 결합했다. 실물 크기의 기계 모형은 가까운 접촉을 맡았다. 가만히 있는 동물, 좁은 공간에 있는 동물, 배우와 닿는 동물이 그것이다. 컴퓨터 생성 영상은 트인 땅을 가로지르는 움직임을 맡았다. 이 결합이 중요했던 것은 각 방법의 약점을 다른 쪽의 강점이 덮어 주었기 때문이다. 기계 모형은 설득력이 있었지만 거의 움직이지 못했고, 디지털 모형은 자유롭게 움직였지만 오래 들여다보면 설득력이 떨어졌다.\n\n편집은 이 분업에서 따라 나온다. 이 정도 명성의 영화치고 동물이 화면에 나오는 총 시간은 놀랄 만큼 짧고, 가장 무서운 장면에는 보이는 생물이 사실상 하나도 없다. 물컵의 진동, 거울, 소리뿐이다. 이 아껴 두기는 예산의 제약을 미덕으로 포장한 것만이 아니다. 잠깐 본 관객은 그 이미지를 스스로 완성하며, 오래 보여 줄 때보다 그 편이 더 효과적이다. 뜯어보기라면 의심했을 세부를 주의력이 채워 넣기 때문이다.\n\n훨씬 큰 디지털 역량을 갖춘 후대의 제작물들이 이 비율을 뒤집어 놓고 도리어 덜 설득력 있는 결과를 낸 경우가 잦다. 이 영화가 보여 주는 것은, 특수효과의 신뢰도가 어느 한 이미지의 품질보다 관객에게 그것을 의심할 시간을 얼마나 주는가에 더 달려 있다는 점이다.",
   gloss:[{w:"instructive",ko:"배울 것이 많은"},{w:"confined",ko:"좁은, 한정된"},
          {w:"imagery",ko:"영상"},{w:"withholding",ko:"아껴 둠, 내보이지 않음"},
          {w:"scrutiny",ko:"자세히 뜯어보기"},{w:"credibility",ko:"신뢰도, 그럴듯함"}],
   qs:[
     {q:"Why did combining the two methods work?",
      opts:["Each method's weakness was covered by the other's strength.",
            "It reduced the cost of the production by half.",
            "Audiences could not distinguish between the two.",
            "Mechanical models were cheaper to build than digital ones."],
      ans:0, exp:"2문단이 명시한다 — 모형은 설득력은 있으나 움직이지 못하고, 디지털은 그 반대였다."},
     {q:"Why is a brief glimpse more effective than a longer look?",
      opts:["It allows the film to include more creatures overall.",
            "The audience completes the image with detail scrutiny would question.",
            "It reduces the number of shots that must be edited.",
            "Longer shots reveal the join between the two methods."],
      ans:1, exp:"3문단: 주의력이 세부를 채워 넣는데, 뜯어보기였다면 그 세부는 의심받았을 것이다."},
     {q:"What does the author conclude about later productions?",
      opts:["They lacked access to mechanical model-making skills.",
            "Greater digital capacity often produced less convincing results.",
            "They avoided showing creatures in daylight.",
            "Their budgets were smaller in real terms."],
      ans:1, exp:"마지막 문단: 역량이 훨씬 커진 후대 작품들이 비율을 뒤집어 도리어 덜 설득력 있는 결과를 냈다."}
   ]},

  {id:"jp-funding", exam:"TOEFL", type:"과학·윤리", level:4,
   series:"🦖 쥬라기 공원", title:"Who Paid for the Science",
   topic:"쥬라기 공원 — 누가 그 연구에 돈을 댔는가",
   passage:"A detail easy to overlook is that no university appears in Jurassic Park. The research that produced the animals was conducted inside a private company, on private land, under conditions the company set. The film treats this as the enabling fact rather than as background.\n\nCommercial funding does not corrupt research by making scientists dishonest, and the film does not suggest that it does. Its effect is on which questions get asked. A publicly funded programme working on ancient genetic material would have produced papers, and papers are reviewed by people whose professional interest lies in finding the weaknesses in them. The park's programme produced an attraction, and an attraction is reviewed by people assessing whether visitors will pay to see it. Both are forms of scrutiny; they select for different things.\n\nThe film makes the consequence concrete in a scene where visiting specialists learn how the animals were made and are visibly the first outsiders to hear it. The technique had been in operation for years without anyone outside the company examining it. What the specialists identify within minutes — the gap-filling, the assumptions about breeding — had not been contested because there had been no forum in which to contest it.\n\nThe famous line about scientists being preoccupied with whether they could is therefore incomplete as usually quoted. The reason the prior question went unasked is institutional: the arrangement that funded the work contained no one whose job was to ask it.",
   ko:"놓치기 쉬운 사실 하나는 『쥬라기 공원』에 대학이 전혀 등장하지 않는다는 점이다. 그 동물들을 만들어 낸 연구는 사기업 안에서, 사유지에서, 그 회사가 정한 조건 아래 수행되었다. 영화는 이것을 배경이 아니라 모든 것을 가능하게 한 사실로 다룬다.\n\n상업적 자금이 연구를 타락시키는 방식은 과학자를 부정직하게 만드는 것이 아니며, 영화도 그렇게 말하지 않는다. 그 효과는 어떤 물음이 제기되는가에 미친다. 고대 유전 물질을 다루는 공적 자금 사업이었다면 논문이 나왔을 것이고, 논문은 그 약점을 찾아내는 데 직업적 이해가 걸린 사람들이 심사한다. 이 공원의 사업은 볼거리를 내놓았고, 볼거리는 관람객이 돈을 내고 보러 올지를 따지는 사람들이 심사한다. 둘 다 검증의 한 형태이지만 서로 다른 것을 걸러 낸다.\n\n영화는 그 결과를 한 장면에서 손에 잡히게 만든다. 초청된 전문가들이 그 동물들이 어떻게 만들어졌는지를 듣는데, 그들이 그 설명을 듣는 첫 외부인이라는 사실이 눈에 보인다. 그 기법은 몇 해 동안 가동되면서도 회사 바깥의 누구에게도 검토된 적이 없었다. 전문가들이 몇 분 만에 짚어 내는 것들 — 빈자리 메우기, 번식에 관한 전제 — 이 그때까지 반박되지 않은 것은 반박할 자리가 없었기 때문이다.\n\n과학자들이 '할 수 있는가'에만 골몰했다는 유명한 대사는 그래서 흔히 인용되는 형태로는 불완전하다. 그 앞의 물음이 제기되지 않은 이유는 제도적이다. 그 연구에 돈을 댄 배치 안에는 그 물음을 던지는 것이 직무인 사람이 아무도 없었다.",
   gloss:[{w:"enabling",ko:"가능하게 하는"},{w:"corrupt",ko:"타락시키다"},
          {w:"peer review 관련 scrutiny",ko:"심사, 검증"},{w:"attraction",ko:"관람 상품, 볼거리"},
          {w:"contest",ko:"이의를 제기하다, 반박하다"},{w:"forum",ko:"논의의 장"},
          {w:"preoccupied with",ko:"~에만 골몰한"}],
   qs:[
     {q:"According to the passage, how does commercial funding affect research?",
      opts:["It causes scientists to falsify their results.",
            "It changes which questions are asked and by whom the work is judged.",
            "It reduces the total amount of research that is possible.",
            "It shortens the time available for each experiment."],
      ans:1, exp:"2문단: 부정직하게 만드는 것이 아니라 '어떤 물음이 제기되는가'에 영향을 미치고, 심사의 성격이 달라진다."},
     {q:"What does the scene with the visiting specialists demonstrate?",
      opts:["The specialists were unqualified to assess the technique.",
            "The method had operated for years without outside examination.",
            "The company had concealed the method deliberately from regulators.",
            "The specialists had been consulted at every earlier stage."],
      ans:1, exp:"3문단: 그들이 첫 외부인이며, 기법은 몇 해 동안 외부 검토 없이 가동되었다."},
     {q:"Why does the author call the famous line incomplete?",
      opts:["It was spoken by a character with no scientific training.",
            "It omits that no one in the funding arrangement was tasked with asking the question.",
            "It applies only to genetic research and not to other fields.",
            "It was contradicted by events later in the film."],
      ans:1, exp:"마지막 문단: 이유가 개인의 태만이 아니라 제도적이라는 점 — 그 물음을 던지는 것이 직무인 사람이 없었다."}
   ]},

  /* ═══════════ 쇼생크 탈출 ═══════════ */

  {id:"sr-institution", exam:"TOEFL", type:"심리·사회", level:4,
   series:"🎬 영화 일반", title:"Institutionalization as an Adaptation",
   topic:"쇼생크 탈출 — 제도화는 적응이다",
   passage:"The most quoted speech in The Shawshank Redemption describes what the film calls being institutionalized: at first a man hates the walls, then he grows used to them, and enough time later he depends on them. The speech is usually treated as a lament. It is more precisely a description of successful adaptation, and the film's argument depends on that precision.\n\nA prison is an environment with unusually reliable rules. Meals arrive at fixed times, decisions are made elsewhere, and the range of possible actions is small enough to be learned completely. A person who adapts to it acquires competence — knowing whom to avoid, what can be obtained, how a day is structured. That competence is real, and it is worthless anywhere else.\n\nThe film illustrates this through an elderly inmate released after decades. He is not persecuted on the outside; he is given a job and a room. What defeats him is the volume of unstructured choice, and the discovery that a form of expertise he spent a lifetime accumulating has no application. The film is careful to show that his difficulty is practical before it is emotional.\n\nThis is why the story treats hope as requiring maintenance rather than mere possession. Adaptation happens by default, without anyone deciding on it. Remaining unfitted to an environment one cannot leave is the effortful condition, and the film presents it as a discipline rather than a temperament.",
   ko:"『쇼생크 탈출』에서 가장 많이 인용되는 대사는 이 영화가 '제도화'라 부르는 상태를 묘사한다. 처음에는 벽을 미워하고, 그다음에는 익숙해지고, 시간이 충분히 흐르면 그 벽에 기대게 된다는 것이다. 이 대사는 흔히 탄식으로 다루어진다. 더 정확히는 성공적인 적응에 대한 서술이며, 이 영화의 논지는 그 정확함에 기대고 있다.\n\n감옥은 규칙이 유난히 안정된 환경이다. 식사는 정해진 시각에 오고, 결정은 다른 데서 내려지며, 가능한 행동의 범위는 남김없이 익힐 수 있을 만큼 좁다. 여기에 적응한 사람은 역량을 얻는다. 누구를 피해야 하는지, 무엇을 구할 수 있는지, 하루가 어떻게 짜이는지를 아는 능력 말이다. 그 역량은 실재하며, 다른 어디에서도 아무 값어치가 없다.\n\n영화는 수십 년 만에 출소한 노인을 통해 이를 보여 준다. 바깥에서 그는 박해받지 않는다. 일자리와 방이 주어진다. 그를 무너뜨리는 것은 짜여 있지 않은 선택의 양이며, 평생 쌓아 온 한 종류의 전문성이 쓸 데가 없다는 발견이다. 영화는 그의 곤경이 감정의 문제이기 전에 실제적인 문제임을 조심스럽게 보여 준다.\n\n그래서 이 이야기는 희망을 그저 품는 것이 아니라 관리해야 하는 것으로 다룬다. 적응은 아무도 결심하지 않아도 저절로 일어난다. 떠날 수 없는 환경에 끝내 맞춰지지 않은 채로 남는 쪽이 힘이 드는 상태이고, 영화는 그것을 기질이 아니라 하나의 규율로 제시한다.",
   gloss:[{w:"institutionalized",ko:"제도화된, 시설에 길들여진"},{w:"lament",ko:"탄식"},
          {w:"competence",ko:"역량"},{w:"inmate",ko:"수감자"},
          {w:"persecute",ko:"박해하다"},{w:"unstructured",ko:"짜여 있지 않은"},
          {w:"temperament",ko:"타고난 기질"}],
   qs:[
     {q:"How does the author reinterpret the famous speech?",
      opts:["As an expression of regret about wasted years",
            "As an accurate description of successful adaptation",
            "As a warning aimed at newly arrived inmates",
            "As a criticism of the prison's administration"],
      ans:1, exp:"1문단: 탄식이 아니라 '성공적인 적응에 대한 서술'로 읽어야 논지가 선다."},
     {q:"What defeats the released elderly inmate?",
      opts:["Hostility from people who know his history",
            "The amount of unstructured choice and the uselessness of his expertise",
            "The absence of any employment or housing",
            "A physical illness contracted in prison"],
      ans:1, exp:"3문단: 박해받은 것이 아니라 '짜여 있지 않은 선택의 양'과 전문성의 무용함이 그를 무너뜨린다."},
     {q:"Why does the film present hope as a discipline?",
      opts:["Because adaptation occurs by default and resisting it takes effort",
            "Because inmates are punished for expressing it openly",
            "Because it can only be learned from other prisoners",
            "Because it is useful only after release"],
      ans:0, exp:"마지막 문단: 적응은 저절로 일어나므로, 맞춰지지 않은 채 남는 쪽이 노력이 드는 상태다."}
   ]},

  {id:"sr-narrator", exam:"TOEFL", type:"서사·시점", level:4,
   series:"🎬 영화 일반", title:"Why the Story Is Told by the Man Who Stays",
   topic:"쇼생크 탈출 — 왜 남는 사람이 화자인가",
   passage:"The escape belongs to one character; the narration belongs to another. This division is the film's central formal decision, and almost everything the story can and cannot do follows from it.\n\nThe narrator is a long-term inmate who observes the protagonist over two decades without access to his intentions. He can report what he saw and what he was told, and he is candid about the limits of both. Consequently the audience learns of the tunnel at the same time he does, and the years of digging are recovered retrospectively rather than witnessed. A film narrated by the escaper would have had to conceal his plan deliberately from the audience, which is a manipulation. Narrating from beside him makes the same concealment honest.\n\nThe choice also changes the subject. A story told by the man who leaves is about escaping. Told by the man who remains, it is about what watching someone refuse to adapt does to an observer who has adapted. The narrator's parole hearings are the film's structural spine: three scenes, decades apart, in which he gives progressively less of the answer the board wants to hear.\n\nThe ending is therefore his rather than the escaper's. The final question the film poses is not whether a prisoner can get out of a prison but whether a man released after forty years can be persuaded that his remaining time is worth organizing.",
   ko:"탈출은 한 인물의 것이고, 서술은 다른 인물의 것이다. 이 분할이 이 영화의 핵심적인 형식적 결정이며, 이 이야기가 할 수 있는 일과 할 수 없는 일이 거의 전부 여기에서 나온다.\n\n화자는 장기 수감자로, 주인공을 20년 넘게 지켜보되 그의 의도에는 접근하지 못한다. 그는 자신이 본 것과 전해 들은 것을 전할 수 있고, 그 둘의 한계에 대해 솔직하다. 그래서 관객은 그와 같은 시점에 굴의 존재를 알게 되고, 굴을 파던 세월은 목격되는 대신 뒤늦게 복원된다. 탈출한 사람이 서술하는 영화였다면 그의 계획을 관객에게 의도적으로 숨겨야 했을 것이고, 그것은 조작이다. 그의 곁에서 서술하면 같은 숨김이 정직해진다.\n\n이 선택은 주제도 바꾼다. 떠나는 사람이 하는 이야기는 탈출에 관한 것이다. 남는 사람이 하면, 그것은 적응해 버린 관찰자가 적응하기를 거부하는 사람을 지켜본다는 것이 그에게 무엇을 하는가에 관한 이야기가 된다. 화자의 가석방 심사 장면들이 이 영화의 구조적 척추다. 수십 년 간격을 둔 세 장면에서 그는 심사위원회가 듣고 싶어 하는 답을 점점 덜 내놓는다.\n\n그러므로 결말은 탈출한 사람이 아니라 그의 것이다. 이 영화가 마지막으로 던지는 물음은 죄수가 감옥에서 나올 수 있는가가 아니라, 40년 만에 풀려난 사람이 자신에게 남은 시간을 꾸릴 만하다고 설득될 수 있는가이다.",
   gloss:[{w:"narration",ko:"서술, 내레이션"},{w:"candid",ko:"솔직한"},
          {w:"retrospectively",ko:"뒤늦게, 소급해서"},{w:"conceal",ko:"숨기다"},
          {w:"manipulation",ko:"조작"},{w:"parole hearing",ko:"가석방 심사"},
          {w:"spine",ko:"척추, 중심 뼈대"}],
   qs:[
     {q:"Why would narration by the escaper have been a problem?",
      opts:["He is absent for much of the film's running time.",
            "Hiding his own plan from the audience would be a manipulation.",
            "He does not speak enough to sustain narration.",
            "His account of the prison would be less accurate."],
      ans:1, exp:"2문단: 탈출한 사람이 서술하면 자기 계획을 의도적으로 숨겨야 하고 그것은 조작이 된다."},
     {q:"What does the passage call the film's structural spine?",
      opts:["The scenes in the prison library",
            "The narrator's three parole hearings",
            "The digging of the tunnel",
            "The arrival of new inmates each year"],
      ans:1, exp:"3문단: 수십 년 간격의 가석방 심사 세 장면이 구조적 척추라고 명시한다."},
     {q:"According to the author, what is the film's final question?",
      opts:["Whether a prisoner can escape a prison",
            "Whether a long-imprisoned man can be persuaded his remaining time is worth organizing",
            "Whether the parole system can be reformed",
            "Whether the narrator's account can be trusted"],
      ans:1, exp:"마지막 문단이 두 물음을 명시적으로 대비하며 후자를 택한다."}
   ]},

  {id:"sr-hope", exam:"TOEFL", type:"주제·논증", level:3,
   series:"🎬 영화 일반", title:"\"Hope Is a Dangerous Thing\"",
   topic:"쇼생크 탈출 — 희망은 위험하다는 반론",
   passage:"The film puts its strongest objection to its own theme in the mouth of its most sympathetic character. Hope, the narrator says, is a dangerous thing; it can drive a man insane. He is not being cynical, and the film does not treat the remark as an error to be corrected.\n\nHis reasoning is sound within his situation. A person serving an indefinite sentence has no reliable information about release. Sustained expectation under those conditions produces repeated disappointment, and repeated disappointment is corrosive in a way that resignation is not. Adjusting expectations downward is, for him, a rational response to an environment that punishes optimism with regularity.\n\nWhat the film offers against this is not a counter-argument but a distinction. The protagonist's version of hope is not expectation. He does not predict release; he behaves as though certain things remain worth doing regardless of whether release occurs — building a library, teaching a younger inmate to read, keeping a rock hammer. Each activity has value on the day it is performed. None of them depends on an outcome, which is why none of them can be disappointed.\n\nThe narrator's objection therefore stands against a version of hope that the film has quietly declined to defend. This is why the ending can affirm hope without contradicting the earlier speech: the two men were describing different things, and only one of them was talking about waiting.",
   ko:"이 영화는 자기 주제에 대한 가장 강한 반론을 가장 공감이 가는 인물의 입에 담아 놓는다. 희망은 위험한 것이며 사람을 미치게 할 수 있다고 화자는 말한다. 그는 냉소하는 것이 아니고, 영화도 그 말을 바로잡아야 할 오류로 다루지 않는다.\n\n그의 논리는 그가 처한 상황 안에서 타당하다. 기약 없는 형기를 사는 사람에게는 출소에 관한 믿을 만한 정보가 없다. 그런 조건에서 기대를 계속 품으면 실망이 되풀이되고, 되풀이되는 실망은 체념과 달리 사람을 갉아먹는다. 기대치를 낮추는 것은 그에게 낙관을 규칙적으로 처벌하는 환경에 대한 합리적인 대응이다.\n\n영화가 이에 맞세워 내놓는 것은 반박이 아니라 구분이다. 주인공이 지닌 희망은 기대가 아니다. 그는 출소를 예측하지 않는다. 다만 출소가 일어나든 아니든 어떤 일들은 여전히 할 만하다는 듯이 행동한다. 도서관을 만들고, 어린 수감자에게 글을 가르치고, 암석 망치를 간직하는 일 말이다. 각 활동은 그것을 하는 그날에 값어치가 있다. 어느 것도 결과에 기대지 않으며, 그래서 어느 것도 실망당할 수 없다.\n\n그러므로 화자의 반론은 영화가 조용히 변호하지 않기로 한 판본의 희망을 겨누고 있다. 결말이 앞선 대사와 모순되지 않으면서 희망을 긍정할 수 있는 이유가 여기에 있다. 두 사람은 서로 다른 것을 말하고 있었고, 그중 기다림을 이야기한 사람은 한 명뿐이었다.",
   gloss:[{w:"cynical",ko:"냉소적인"},{w:"indefinite",ko:"기약 없는"},
          {w:"corrosive",ko:"갉아먹는, 부식시키는"},{w:"resignation",ko:"체념"},
          {w:"regularity",ko:"규칙성"},{w:"affirm",ko:"긍정하다"}],
   qs:[
     {q:"Why does the author say the narrator is not being cynical?",
      opts:["He changes his opinion later in the film.",
            "His reasoning is sound given the conditions he is describing.",
            "He is quoting an older inmate rather than speaking for himself.",
            "The film shows that his prediction turns out to be correct."],
      ans:1, exp:"2문단 전체가 그 논리의 타당성을 설명한다 — 기약 없는 형기에서 기대는 되풀이되는 실망을 낳는다."},
     {q:"What distinguishes the protagonist's version of hope?",
      opts:["It is based on better information about the parole system.",
            "It consists of actions valuable on the day they are done, not predictions.",
            "It is shared openly with the other inmates.",
            "It arises only after the tunnel is complete."],
      ans:1, exp:"3문단: 예측이 아니라 결과에 기대지 않는 행동이며, 그래서 실망당할 수 없다."},
     {q:"Why is there no contradiction between the speech and the ending?",
      opts:["The narrator retracts his earlier statement.",
            "The two characters are describing different things.",
            "The ending takes place outside the prison.",
            "The film presents the speech as a mistake."],
      ans:1, exp:"마지막 문단: 반론이 겨눈 것은 영화가 변호하지 않기로 한 판본의 희망이고, 기다림을 말한 사람은 한 명뿐이었다."}
   ]},

  /* ═══════════ 아메리칸 뷰티 ═══════════ */

  {id:"ab-suburb", exam:"TOEFL", type:"사회·비평", level:4,
   series:"🎬 영화 일반", title:"The Suburb as a Subject",
   topic:"아메리칸 뷰티 — 교외라는 소재",
   passage:"American Beauty belongs to a long line of works treating the affluent suburb as a place where appearance and condition come apart. What distinguishes it is less the theme than the method by which the film keeps the theme visible.\n\nThe visual scheme is built on symmetry and framing. Characters are repeatedly placed at the centre of doorways, windows, and rectangular compositions, and the household objects are arranged with a regularity that no one is shown maintaining. The effect is to make the domestic interior resemble a display, and to imply an audience for whom it is arranged. The film's most efficient character sketch is a woman selling a house who repeats an affirmation to herself before opening the door to buyers.\n\nThe risk in this material is condescension, and the film does not entirely escape it. The satire is sharpest against characters whose failing is that they care about surfaces, and the sharpness can slide into contempt for people trying to hold a life together with the tools available to them.\n\nWhere the film is stronger is in refusing to locate the problem in the suburb itself. The setting supplies pressure but does not supply the characters' choices, and the ones who behave worst are those who have converted a private difficulty into a public performance. That conversion is portable. It is available anywhere there is someone to perform for.",
   ko:"『아메리칸 뷰티』는 부유한 교외를 겉모습과 실상이 어긋나는 장소로 다뤄 온 긴 계보에 속한다. 이 작품을 구별 짓는 것은 주제라기보다 그 주제를 계속 눈에 보이게 유지하는 방법이다.\n\n시각 설계는 대칭과 액자 구도 위에 서 있다. 인물들은 거듭 문간과 창과 직사각형 구도의 한가운데에 놓이고, 집 안의 물건들은 아무도 그것을 관리하는 모습이 보이지 않는데도 일정하게 정돈되어 있다. 그 효과는 가정의 실내를 전시물처럼 보이게 만들고, 그것이 누군가를 위해 배치되었음을 암시하는 것이다. 이 영화에서 가장 효율적인 인물 소묘는 매수자에게 문을 열어 주기 전에 스스로에게 다짐의 말을 되뇌는 부동산 중개인이다.\n\n이런 소재의 위험은 내려다보기이고, 이 영화가 그것을 온전히 피해 가지는 못한다. 풍자는 겉모습에 마음 쓰는 것이 결함인 인물들에게 가장 날카로운데, 그 날카로움은 자신에게 주어진 도구로 삶을 붙들어 보려는 사람들에 대한 경멸로 미끄러질 수 있다.\n\n이 영화가 더 강한 지점은 문제의 원인을 교외 자체에 두기를 거부한다는 데 있다. 그 배경은 압력을 공급하지만 인물들의 선택까지 공급하지는 않으며, 가장 나쁘게 행동하는 이들은 사적인 곤경을 공적인 연기로 바꿔 놓은 사람들이다. 그 전환은 들고 다닐 수 있는 것이다. 보아 줄 사람이 있는 곳이라면 어디서든 가능하다.",
   gloss:[{w:"affluent",ko:"부유한"},{w:"come apart",ko:"어긋나다, 갈라지다"},
          {w:"symmetry",ko:"대칭"},{w:"affirmation",ko:"자기 다짐의 말"},
          {w:"condescension",ko:"내려다보는 태도"},{w:"contempt",ko:"경멸"},
          {w:"portable",ko:"들고 다닐 수 있는"}],
   qs:[
     {q:"What effect does the film's visual scheme produce?",
      opts:["It makes the interiors resemble arranged displays.",
            "It emphasizes how cramped the houses are.",
            "It disguises the wealth of the neighbourhood.",
            "It draws attention to the passage of time."],
      ans:0, exp:"2문단: 대칭과 액자 구도가 실내를 '전시물처럼' 보이게 하고 그것을 위한 관객을 암시한다."},
     {q:"What weakness does the author acknowledge in the film?",
      opts:["Its plot is difficult to follow.",
            "Its satire can slide into contempt for the people it depicts.",
            "It relies too heavily on voice-over narration.",
            "It confines its criticism to a single family."],
      ans:1, exp:"3문단: 내려다보기의 위험을 온전히 피하지 못하고, 날카로움이 경멸로 미끄러질 수 있다고 인정한다."},
     {q:"Why does the author consider the film stronger for not blaming the suburb?",
      opts:["Because the suburb is depicted sympathetically elsewhere",
            "Because the behaviour it criticizes can occur anywhere there is an audience",
            "Because most viewers do not live in suburbs",
            "Because the characters eventually move away"],
      ans:1, exp:"마지막 문단: 사적 곤경을 공적 연기로 바꾸는 전환은 '들고 다닐 수 있는' 것이며 보아 줄 사람이 있는 곳이면 어디서든 가능하다."}
   ]},

  {id:"ab-bag", exam:"TOEFL", type:"영화·해석", level:4,
   series:"🎬 영화 일반", title:"The Plastic Bag and the Question It Leaves Open",
   topic:"아메리칸 뷰티 — 비닐봉지 장면은 진심인가",
   passage:"A teenage character shows a video he filmed of a plastic bag circling in the wind and describes it as the most beautiful thing he has recorded. The scene has been received in two incompatible ways: as the film's sincere statement about attention, and as a portrait of a young man mistaking a mood for an insight. The disagreement is not a failure of the film. It is produced deliberately.\n\nSeveral features support the sincere reading. The footage is given considerable screen time, the score treats it seriously, and the speech that accompanies it is the only sustained account in the film of why anything might be worth looking at closely. The character is also the only one who observes without needing to be observed, which the film elsewhere treats as the relevant virtue.\n\nFeatures supporting the sceptical reading are equally present. The speech is delivered by an adolescent to someone he is trying to impress; it is grandiose; and the film has already established that this character films people without their knowledge, which complicates any claim that his looking is innocent.\n\nThe film supplies no scene that settles the matter, and its refusal is consistent with its subject. A work about the gap between how things appear and what they are cannot resolve, on the viewer's behalf, whether a particular moment of apparent depth is depth. It can only stage the difficulty and decline to close it.",
   ko:"한 십 대 인물이 바람에 맴도는 비닐봉지를 찍은 영상을 보여 주며, 자신이 기록한 것 중 가장 아름다운 것이라고 말한다. 이 장면은 서로 양립하지 않는 두 방식으로 받아들여져 왔다. 주의(注意)에 관한 이 영화의 진심 어린 진술로, 그리고 어떤 기분을 통찰로 착각하는 젊은이의 초상으로. 이 불일치는 영화의 실패가 아니다. 의도적으로 만들어진 것이다.\n\n진심으로 읽을 근거는 여럿이다. 그 영상에는 상당한 상영 시간이 주어지고, 음악은 그것을 진지하게 다루며, 함께 나오는 대사는 무언가를 가까이 들여다볼 값어치가 있을 수 있는 이유를 이 영화에서 유일하게 길게 설명한다. 또한 그는 관찰당할 필요 없이 관찰하는 유일한 인물인데, 영화는 다른 곳에서 그것을 문제의 미덕으로 다룬다.\n\n회의적으로 읽을 근거도 그만큼 갖춰져 있다. 그 대사는 잘 보이고 싶은 상대에게 청소년이 하는 말이고, 과장되어 있으며, 영화는 이미 그가 사람들을 당사자 모르게 찍는다는 사실을 확립해 두었다. 그의 바라봄이 순수하다는 주장은 그 때문에 복잡해진다.\n\n영화는 이 문제를 매듭짓는 장면을 제공하지 않으며, 그 거부는 자기 소재와 일관된다. 사물이 어떻게 보이는가와 그것이 무엇인가 사이의 간극을 다루는 작품은, 겉보기의 깊이가 정말 깊이인지를 관객 대신 판정해 줄 수 없다. 할 수 있는 일은 그 난제를 무대에 올리고 닫기를 거부하는 것뿐이다.",
   gloss:[{w:"incompatible",ko:"양립할 수 없는"},{w:"sincere",ko:"진심의"},
          {w:"insight",ko:"통찰"},{w:"score",ko:"영화 음악"},
          {w:"grandiose",ko:"과장된, 거창한"},{w:"stage",ko:"무대에 올리다"},
          {w:"on someone's behalf",ko:"~를 대신하여"}],
   qs:[
     {q:"How does the author characterize the disagreement about the scene?",
      opts:["As evidence that the scene was poorly edited",
            "As an effect the film produces on purpose",
            "As a misunderstanding among early reviewers",
            "As a result of the character's unclear dialogue"],
      ans:1, exp:"1문단 마지막: 'It is produced deliberately.' 불일치는 실패가 아니라 의도된 효과다."},
     {q:"Which detail is offered in support of the sceptical reading?",
      opts:["The footage is given very little screen time.",
            "The character films people without their knowledge.",
            "The score treats the scene as comic.",
            "The speech is interrupted before it finishes."],
      ans:1, exp:"3문단: 몰래 촬영한다는 사실이 그의 '바라봄이 순수하다'는 주장을 복잡하게 만든다."},
     {q:"Why does the author say the film's refusal to resolve the question is consistent?",
      opts:["Because the character never appears again",
            "Because a film about appearance versus reality cannot judge apparent depth for the viewer",
            "Because the director has declined to comment on it",
            "Because the scene was added late in production"],
      ans:1, exp:"마지막 문단이 그대로 밝힌다 — 겉보기와 실상의 간극을 다루는 작품은 관객 대신 판정해 줄 수 없다."}
   ]},

  {id:"ab-dead", exam:"TOEFL", type:"서사·형식", level:4,
   series:"🎬 영화 일반", title:"A Narrator Who Tells You He Dies",
   topic:"아메리칸 뷰티 — 죽는다고 먼저 말하는 화자",
   passage:"American Beauty opens with its narrator stating that he will be dead within a year. The disclosure is unusual: most films withhold the ending, and suspense is conventionally understood to depend on that withholding. The choice is worth examining, because the film gains something specific from giving the ending away.\n\nWhat it gains is a change of question. A viewer who does not know the outcome watches to find out what happens. A viewer who knows the outcome watches to find out how, and more importantly which of the events on screen turn out to matter. Every scene is therefore examined for its bearing on a known end, and the film can present ordinary domestic material — a dinner, a job, a neighbour — with an attention that would otherwise require justification.\n\nThe disclosure also fixes the narrator's tone. He speaks from after the events, and the retrospection removes urgency from his account. He is not trying to prevent anything or persuade anyone. What remains available to him is assessment, which is why the closing narration can make a claim about gratitude that would sound unearned from a character still inside the story.\n\nThe device has an obvious cost: it forecloses the possibility of surprise about the central fact. The film accepts this and compensates by making the identity of the person responsible the thing that is withheld — a smaller question, but one the structure has taught the viewer to care about.",
   ko:"『아메리칸 뷰티』는 화자가 자신이 1년 안에 죽을 것이라고 말하며 시작한다. 이 공개는 이례적이다. 대부분의 영화는 결말을 감추며, 긴장은 관례적으로 그 감춤에 기댄다고 이해된다. 이 선택은 따져 볼 값어치가 있는데, 결말을 미리 내주고서 이 영화가 얻는 것이 분명히 있기 때문이다.\n\n얻는 것은 물음의 교체다. 결과를 모르는 관객은 무슨 일이 일어나는지 알아내려고 본다. 결과를 아는 관객은 어떻게 그렇게 되는지를, 그리고 더 중요하게는 화면에 나오는 사건 가운데 무엇이 결국 중요해지는지를 알아내려고 본다. 그래서 모든 장면이 이미 알려진 끝과 어떤 관계인지를 두고 살펴지고, 영화는 저녁 식사, 직장, 이웃 같은 평범한 가정사를 따로 정당화할 필요 없는 주의로 제시할 수 있게 된다.\n\n이 공개는 화자의 어조도 고정한다. 그는 사건들이 끝난 뒤에서 말하고 있고, 그 회고성은 그의 진술에서 다급함을 걷어낸다. 그는 무언가를 막으려 하지도, 누구를 설득하려 하지도 않는다. 그에게 남은 것은 평가이며, 그래서 마지막 내레이션은 아직 이야기 안에 있는 인물이 했다면 자격 없어 보였을 감사에 관한 주장을 할 수 있다.\n\n이 장치에는 뚜렷한 대가가 있다. 중심 사실에 관한 놀라움의 가능성을 미리 닫아 버린다는 점이다. 영화는 이를 받아들이고, 누가 그 일을 저질렀는가를 감추는 쪽으로 벌충한다. 더 작은 물음이지만, 구조가 관객으로 하여금 신경 쓰도록 훈련시켜 놓은 물음이다.",
   gloss:[{w:"disclosure",ko:"공개, 밝힘"},{w:"withhold",ko:"감추다, 내주지 않다"},
          {w:"suspense",ko:"긴장, 서스펜스"},{w:"bearing on",ko:"~와의 관련성"},
          {w:"retrospection",ko:"회고"},{w:"unearned",ko:"자격 없는, 값을 치르지 않은"},
          {w:"foreclose",ko:"미리 차단하다"}],
   qs:[
     {q:"What does the film gain by revealing the ending at the start?",
      opts:["It shortens the running time considerably.",
            "It changes the viewer's question from what happens to how and what matters.",
            "It allows the narrator to appear in more scenes.",
            "It removes the need for a conventional plot."],
      ans:1, exp:"2문단: 'A change of question' — 무엇이 일어나는가에서 어떻게, 그리고 무엇이 중요해지는가로 바뀐다."},
     {q:"How does the disclosure affect the narrator's tone?",
      opts:["It makes him more urgent and persuasive.",
            "It leaves him assessment rather than urgency.",
            "It causes him to withhold his own opinions.",
            "It requires him to address the other characters directly."],
      ans:1, exp:"3문단: 회고성이 다급함을 걷어내고 '그에게 남은 것은 평가'다."},
     {q:"How does the film compensate for the cost of the device?",
      opts:["By concealing who is responsible for the death",
            "By introducing a second narrator later on",
            "By repeating the opening scene at the end",
            "By leaving the year in which events occur unstated"],
      ans:0, exp:"마지막 문단: 중심 사실을 미리 공개한 대신 '누가 그 일을 저질렀는가'를 감추는 쪽으로 벌충한다."}
   ]}

]);
