/* ============================================================
   관심주제 리딩 — 톨킨 세계의 장소와 인물
   ------------------------------------------------------------
   로스로리엔 · 리벤델 · 에도라스 · 미나스 티리스 · 모리아 ·
   스마우그 · 브리 · 샤이어 · 호비튼

   소재는 익숙하지만 문장 수준과 문제 유형은 TOEFL 리딩 그대로다.
   각 지문은 장소를 소개하는 글이 아니라 그 장소를 하나의 논점으로
   다루는 분석적인 글이며, 문제는 추론·수사적 의도·부정 사실 정보 등
   실제 출제 유형을 따른다.

   구조는 topics.js 의 TOPIC_READING 과 동일하다.
   확장 파일은 여러 개일 수 있으므로 기존 배열에 이어 붙인다.
   ============================================================ */
window.TOPIC_READING_EXTRA = (window.TOPIC_READING_EXTRA||[]).concat([

  /* ─────────── 1. 로스로리엔 ─────────── */
  {id:"tk-lorien", exam:"TOEFL", type:"문학·세계관", level:4,
   series:"💍 반지의 제왕", title:"Lothlórien and the Problem of Preservation",
   topic:"로스로리엔 — 보존의 역설",
   passage:"Lothlórien presents a paradox that the narrative never fully resolves. The wood is described as a place where nothing is stained or withered, yet its preservation depends on a power its keepers know to be temporary. Galadriel maintains the realm through one of the Three Rings, and she states plainly that if the One Ring is destroyed her own work will fade with it. The forest is therefore not timeless but held, in the way that a held breath is not the absence of breathing.\n\nVisitors experience this as a distortion of duration. Members of the Fellowship cannot afterwards agree on how long they stayed. Sam concludes that time simply did not pass there. Legolas offers a more careful account: time does pass in Lórien, but the Elves perceive its passing differently, feeling it as both swift and slow. The disagreement is left standing rather than settled, which is itself significant, since the narrative consistently prefers an unresolved perception to an authoritative measurement.\n\nWhat Lothlórien makes available is not escape but contrast. The travellers arrive exhausted and grieving; they leave carrying gifts that will matter only outside the wood. The realm's function in the story is to supply what cannot be used within it. This is why the farewell is written as a drifting departure into current and daylight rather than as an expulsion. The wood was never a destination, and the narrative declines to let anyone treat it as one.",
   ko:"로스로리엔은 이야기가 끝내 완전히 해소하지 않는 역설을 제시한다. 이 숲은 아무것도 더럽혀지거나 시들지 않는 곳으로 묘사되지만, 그 보존은 그것을 지키는 이들 스스로가 한시적임을 아는 힘에 기대고 있다. 갈라드리엘은 세 반지 중 하나로 이 땅을 유지하고 있으며, 절대반지가 파괴되면 자신의 일도 함께 스러지리라고 분명히 말한다. 그러므로 이 숲은 시간을 초월한 것이 아니라 붙들려 있는 것이다. 참은 숨이 숨쉬지 않음이 아닌 것과 같은 방식으로.\n\n방문자들은 이것을 시간 감각의 왜곡으로 경험한다. 원정대원들은 나중에 자신들이 얼마나 오래 머물렀는지에 대해 의견을 모으지 못한다. 샘은 그곳에서는 시간이 아예 흐르지 않았다고 결론짓는다. 레골라스는 더 조심스러운 설명을 내놓는다. 로리엔에서도 시간은 흐르지만 요정들은 그 흐름을 다르게 지각하여 빠르면서도 느리게 느낀다는 것이다. 이 불일치는 정리되지 않은 채 남는데, 이 점 자체가 의미심장하다. 이 이야기는 일관되게 권위 있는 측정보다 해소되지 않은 지각 쪽을 택하기 때문이다.\n\n로스로리엔이 내어 주는 것은 도피가 아니라 대비(對比)다. 여행자들은 지치고 슬픔에 잠긴 채 도착하고, 숲 밖에서라야 쓸모가 있을 선물들을 들고 떠난다. 이 땅이 이야기에서 맡은 기능은 그 안에서는 쓸 수 없는 것을 공급하는 데 있다. 작별이 추방이 아니라 물살과 햇빛 속으로 흘러 나가는 장면으로 쓰인 까닭이 여기에 있다. 이 숲은 애초에 목적지가 아니었고, 이야기는 누구에게도 그곳을 목적지로 삼도록 허락하지 않는다.",
   gloss:[{w:"paradox",ko:"역설"},{w:"withered",ko:"시든"},{w:"preservation",ko:"보존"},
          {w:"duration",ko:"(시간의) 지속, 길이"},{w:"authoritative",ko:"권위 있는, 확정적인"},
          {w:"expulsion",ko:"추방"}],
   qs:[
     {q:"What can be inferred about Galadriel's power over the wood?",
      opts:["It was granted to her by the One Ring.",
            "It will end once the One Ring no longer exists.",
            "It grows stronger the longer visitors remain.",
            "It is unknown to the other inhabitants of Lórien."],
      ans:1, exp:"1문단: 'if the One Ring is destroyed her own work will fade with it.' 절대반지가 사라지면 그 힘도 끝난다는 뜻이다. (A)는 반대 — 그는 세 반지 중 하나를 쓰고 있지 절대반지에서 힘을 받은 것이 아니다."},
     {q:"How does Legolas's account differ from Sam's?",
      opts:["He believes the visitors stayed far longer than they realized.",
            "He denies that anything unusual happened to the travellers.",
            "He says time did flow but was experienced in an unfamiliar way.",
            "He argues that only Elves are affected by the wood."],
      ans:2, exp:"2문단: 'time does pass in Lórien, but the Elves perceive its passing differently.' 샘은 시간이 흐르지 않았다고 했고, 레골라스는 흐르되 지각이 다르다고 했다."},
     {q:"Why does the author compare the wood to a held breath?",
      opts:["To suggest that its stillness requires continuous effort",
            "To emphasize how quiet the forest is",
            "To indicate that the visitors were afraid while there",
            "To show that the Elves rarely speak of their own history"],
      ans:0, exp:"수사적 의도 문제. 바로 앞 문장이 '시간을 초월한 것이 아니라 붙들려 있는(held) 것'이므로, 참은 숨은 저절로 유지되는 상태가 아니라 계속 힘을 들여야 하는 상태를 나타낸다."}
   ]},

  /* ─────────── 2. 리벤델 ─────────── */
  {id:"tk-rivendell", exam:"TOEFL", type:"문학·구성", level:4,
   series:"💍 반지의 제왕", title:"Rivendell as a Narrative Device",
   topic:"리벤델 — 서사 장치로서의 쉼터",
   passage:"Readers remember Rivendell as a refuge, but its more important work in the story is informational. Almost every fact the Fellowship needs is delivered there, and almost nothing is decided anywhere else. The Council of Elrond, which occupies a single long chapter, functions less as a meeting than as an assembly of testimony: Glóin reports the dwarves' unease, Boromir describes the pressure on Gondor, Gandalf accounts for his absence, and the history of the Ring is reconstructed from fragments held by people who had never previously compared them.\n\nThis concentration is a structural solution to a genuine problem. A story whose central object has a three-thousand-year history must convey that history without stopping the plot in the middle of a journey. Placing the explanation at a waypoint, where the characters have legitimate reason to rest and talk, allows a great deal of exposition to occur without the narrative appearing to pause for it.\n\nThe house itself is described in terms that support the function. It is a place, we are told, where weariness and fear are eased and where one may hear songs, tales, or simply think. Each of those activities is a form of processing rather than acting. Elrond's own role reinforces this: he supplies memory, not force. Notably, he does not accompany the Fellowship. The waypoint gives what it has to give, and the story moves on without it.",
   ko:"독자들은 리벤델을 피난처로 기억하지만, 이 장소가 이야기에서 맡은 더 중요한 일은 정보 전달이다. 원정대에 필요한 사실은 거의 전부 이곳에서 전해지고, 결정 역시 사실상 다른 어디에서도 내려지지 않는다. 긴 한 장(章)을 차지하는 엘론드의 회의는 회의라기보다 증언의 집합처럼 작동한다. 글로인은 난쟁이들의 불안을 보고하고, 보로미르는 곤도르가 받는 압박을 설명하며, 간달프는 자신이 자리를 비운 사정을 밝히고, 반지의 역사는 그때까지 서로 견주어 본 적 없는 사람들이 각자 쥐고 있던 조각들로부터 재구성된다.\n\n이러한 집중은 실제로 존재하는 문제에 대한 구조적 해법이다. 중심 사물이 삼천 년의 내력을 지닌 이야기라면 그 내력을 전달해야 하되, 여정 한복판에서 줄거리를 멈춰 세워서는 안 된다. 설명을 경유지에 배치하면, 등장인물들이 쉬고 이야기를 나눌 정당한 이유가 있는 자리이므로, 많은 양의 배경 설명을 넣고도 이야기가 그것 때문에 멈춘 것처럼 보이지 않는다.\n\n저택 자체도 그 기능을 뒷받침하는 방식으로 묘사된다. 그곳은 피로와 두려움이 누그러지는 곳이며, 노래와 이야기를 듣거나 그저 생각에 잠길 수 있는 곳이라고 서술된다. 이 활동들은 모두 행동이 아니라 소화(消化)의 한 형태다. 엘론드가 맡은 역할도 이를 강화한다. 그가 제공하는 것은 무력이 아니라 기억이다. 눈여겨볼 점은 그가 원정대에 동행하지 않는다는 것이다. 경유지는 자신이 줄 수 있는 것을 주고, 이야기는 그것을 남겨 둔 채 나아간다.",
   gloss:[{w:"refuge",ko:"피난처"},{w:"testimony",ko:"증언"},{w:"unease",ko:"불안"},
          {w:"exposition",ko:"(작품의) 배경 설명"},{w:"waypoint",ko:"경유지"},{w:"reinforce",ko:"강화하다"}],
   qs:[
     {q:"According to the passage, what problem does the Council of Elrond solve for the author?",
      opts:["How to introduce a large number of characters quickly",
            "How to deliver a long history without halting the journey",
            "How to justify the destruction of the Ring",
            "How to explain why Elrond refuses to leave his house"],
      ans:1, exp:"2문단: '…must convey that history without stopping the plot in the middle of a journey.' 경유지에 설명을 몰아넣어 서사가 멈춘 것처럼 보이지 않게 한다는 것이 핵심이다."},
     {q:"The word \"processing\" in the passage is closest in meaning to",
      opts:["manufacturing","taking in and sorting out","postponing","recording in writing"],
      ans:1, exp:"어휘 문제. 앞 문장에서 열거된 활동(노래 듣기, 이야기 듣기, 생각하기)은 모두 받아들여 정리하는 일이며, 바로 뒤에 'rather than acting'으로 행동과 대비된다."},
     {q:"What does the passage suggest by noting that Elrond does not travel with the Fellowship?",
      opts:["He considers the quest unlikely to succeed.",
            "His contribution is complete once the information has been given.",
            "He is prevented from leaving by the terms of his authority.",
            "The Fellowship distrusts the counsel he has offered."],
      ans:1, exp:"마지막 두 문장: '그가 제공하는 것은 무력이 아니라 기억' + '경유지는 줄 수 있는 것을 주고 이야기는 나아간다.' 정보 전달로 그의 역할이 끝난다는 뜻이다."}
   ]},

  /* ─────────── 3. 에도라스 ─────────── */
  {id:"tk-edoras", exam:"TOEFL", type:"문학·언어", level:4,
   series:"💍 반지의 제왕", title:"Edoras and the Anglo-Saxon Borrowing",
   topic:"에도라스 — 고대 영어 차용과 그 변형",
   passage:"The Rohirrim are the most transparently borrowed culture in the legendarium, and Edoras is where the borrowing is most visible. The name of the royal hall, Meduseld, is an Old English word for mead-hall, and the hall's described features — the raised seat, the gold-worked roof, the tapestries of ancestors, the doorward who demands that weapons be left outside — follow the pattern of Heorot in Beowulf closely enough that the resemblance can hardly be accidental. Even the verse spoken as the travellers approach is composed on the alliterative principle of Old English poetry rather than on rhyme.\n\nThe borrowing is not, however, a transposition. Tolkien altered one decisive element: the Anglo-Saxons of the historical record were not notably a people of horses, and the Rohirrim are defined by nothing else. This single change reorganizes the whole culture. Their wealth is mobile, their settlements few, their military strength concentrated in an arm that must be gathered rather than garrisoned. Edoras is consequently a capital in name more than in mass — a hall on a hill above a plain, holding the memory of the people while most of their strength is elsewhere.\n\nThe effect is a society that reads as historically grounded while behaving in ways no historical Anglo-Saxon kingdom did. Readers who recognize the source often assume they are being shown the past. They are being shown a deliberate variation on it.",
   ko:"로한인들은 이 신화 체계에서 차용의 흔적이 가장 뚜렷하게 드러나는 문화이며, 에도라스는 그 차용이 가장 잘 보이는 장소다. 왕궁의 이름 메두셀드는 고대 영어로 '벌꿀술 회당'을 뜻하는 낱말이고, 묘사된 회당의 특징들 — 높은 자리, 금세공을 한 지붕, 조상들을 그린 벽걸이, 무기를 밖에 두라고 요구하는 문지기 — 은 『베오울프』의 헤오로트가 보여 주는 양식을 상당히 가깝게 따르므로 그 닮음을 우연으로 보기는 어렵다. 여행자들이 다가갈 때 읊어지는 시행마저 각운이 아니라 고대 영시의 두운 원리에 따라 지어졌다.\n\n그러나 이 차용은 그대로 옮겨 놓기가 아니다. 톨킨은 결정적인 요소 하나를 바꾸었다. 역사 기록 속 앵글로색슨인은 특별히 말의 민족이라 할 수 없었지만, 로한인은 말 말고는 그들을 규정할 것이 없다. 이 한 가지 변경이 문화 전체를 다시 짜 놓는다. 그들의 부는 이동하고, 정착지는 적으며, 군사력은 주둔시키는 것이 아니라 소집해야 하는 병종에 집중되어 있다. 그래서 에도라스는 규모보다 이름에서 수도인 곳이다. 평원 위 언덕에 선 회당 하나가 백성의 기억을 간직하고 있고, 그들의 힘 대부분은 다른 곳에 있다.\n\n그 결과는 역사에 뿌리를 둔 것처럼 읽히면서도 실제 앵글로색슨 왕국 어디도 하지 않았던 방식으로 움직이는 사회다. 출처를 알아본 독자들은 흔히 자신이 과거를 보고 있다고 여긴다. 그들이 보고 있는 것은 과거에 가해진 의도적인 변주다.",
   gloss:[{w:"legendarium",ko:"(작가가 구축한) 신화 체계"},{w:"alliterative",ko:"두운의"},
          {w:"transposition",ko:"그대로 옮겨 놓기"},{w:"garrison",ko:"주둔시키다"},
          {w:"deliberate",ko:"의도적인"},{w:"variation",ko:"변주, 변형"}],
   qs:[
     {q:"According to the passage, all of the following link Meduseld to Heorot EXCEPT",
      opts:["a seat raised above the floor",
            "a requirement that visitors leave weapons outside",
            "a roof decorated with worked gold",
            "a stable attached to the hall"],
      ans:3, exp:"부정 사실 정보 문제. 1문단이 나열한 항목은 높은 자리·금세공 지붕·조상 벽걸이·무기를 맡기는 문지기다. 마구간은 언급되지 않았다 — 말은 두 문화를 잇는 요소가 아니라 갈라놓는 요소다."},
     {q:"What does the author identify as the decisive change Tolkien made?",
      opts:["He replaced rhyme with alliteration in their poetry.",
            "He made horses central to a culture whose model was not built around them.",
            "He moved the royal hall from a plain to a hilltop.",
            "He removed the figure of the doorward from the hall."],
      ans:1, exp:"2문단: 역사 속 앵글로색슨인은 말의 민족이 아니었으나 로한인은 말로만 규정된다. 이 한 가지가 문화 전체를 재편한다고 서술된다."},
     {q:"Why is Edoras described as \"a capital in name more than in mass\"?",
      opts:["Its buildings were constructed from temporary materials.",
            "Its population moved to a new site each season.",
            "Most of the kingdom's strength is not located there.",
            "Its authority is disputed by rival halls."],
      ans:2, exp:"2문단 마지막: 부는 이동하고 병력은 소집해야 하므로, 회당은 기억을 간직할 뿐 힘 대부분은 다른 곳에 있다."}
   ]},

  /* ─────────── 4. 미나스 티리스 ─────────── */
  {id:"tk-minastirith", exam:"TOEFL", type:"건축·사회", level:4,
   series:"💍 반지의 제왕", title:"Minas Tirith: A City Larger Than Its People",
   topic:"미나스 티리스 — 인구를 앞지른 도시",
   passage:"Minas Tirith is introduced through a description of its defences, and the description carries an argument. Seven walls rise in concentric circles, each with a single gate, and the gates are set alternately to the left and right so that an attacker who breaks one must cross open ground under fire before reaching the next. A spur of rock divides the upper levels like the prow of a ship. The design is intelligent and, on its own terms, close to unanswerable.\n\nYet the narration returns repeatedly to a different observation: the streets are quiet, the houses many of them empty, and the men on the walls fewer than the walls were built to hold. Pippin notices this before he notices anything about the fortifications' quality. The city has not been defeated; it has been outlived by its own architecture. Gondor's decline is presented not as ruin but as dilution — the same forms maintained by fewer and fewer people, until maintenance becomes the principal activity.\n\nThis is why the White Tree matters so much within the text. A dead tree kept in a courtyard and guarded continuously is a precise image of the state: something preserved with great care after its function has ceased. The city's eventual survival depends on relief arriving from outside — from Rohan, from the coast, from the Paths of the Dead. Its walls hold, but they do not save it. That distinction is the point.",
   ko:"미나스 티리스는 방어 시설에 대한 묘사를 통해 소개되며, 그 묘사는 하나의 논지를 담고 있다. 일곱 겹의 성벽이 동심원으로 솟아 있고 각각에 성문이 하나씩 있는데, 성문들은 좌우로 번갈아 배치되어 있어 하나를 뚫은 공격자는 다음 문에 닿기까지 포화 속에서 빈 땅을 가로질러야 한다. 바위 돌출부가 배의 이물처럼 위쪽 층들을 갈라놓는다. 이 설계는 영리하며, 그 자체의 논리 안에서는 사실상 반박하기 어렵다.\n\n그러나 서술은 다른 관찰로 거듭 돌아온다. 거리는 조용하고, 집들은 상당수가 비어 있으며, 성벽 위의 병사는 그 성벽이 수용하도록 지어진 수보다 적다. 피핀은 요새의 우수함을 알아차리기 전에 이 점을 먼저 알아본다. 이 도시는 패배한 것이 아니라 제 건축물보다 먼저 수명을 다한 것이다. 곤도르의 쇠퇴는 폐허가 아니라 희석(稀釋)으로 제시된다. 같은 형식을 점점 더 적은 사람이 유지하다가, 마침내 유지 자체가 주된 활동이 되어 버리는 것이다.\n\n작품 안에서 백색 나무가 그토록 중요한 이유가 여기에 있다. 안뜰에 놓인 채 끊임없이 지켜지는 죽은 나무는 이 국가의 정확한 상(像)이다. 기능이 멎은 뒤에도 지극한 정성으로 보존되는 무엇. 이 도시가 결국 살아남는 것은 바깥에서 오는 구원 덕분이다. 로한에서, 해안에서, 사자(死者)의 길에서. 성벽은 버텨 내지만 도시를 구하지는 못한다. 바로 그 구분이 요점이다.",
   gloss:[{w:"concentric",ko:"동심원의"},{w:"fortification",ko:"요새, 방어 시설"},
          {w:"outlive",ko:"~보다 오래 살아남다"},{w:"dilution",ko:"희석, 묽어짐"},
          {w:"cease",ko:"멎다, 그치다"},{w:"relief",ko:"구원(군)"}],
   qs:[
     {q:"Why are the gates of the city set alternately to left and right?",
      opts:["To make the streets easier to clean and repair",
            "To force attackers into exposed ground between walls",
            "To distribute the weight of the walls evenly on the rock",
            "To allow each level to be closed off during festivals"],
      ans:1, exp:"1문단: 'an attacker who breaks one must cross open ground under fire before reaching the next.' 공격자를 노출된 땅으로 몰아넣기 위한 배치다."},
     {q:"What does the author mean by saying the city has been \"outlived by its own architecture\"?",
      opts:["The buildings were designed to last longer than was necessary.",
            "The population has fallen far below what the city was built for.",
            "The oldest levels of the city have been abandoned to ruin.",
            "The architects intended the city to be inherited by another people."],
      ans:1, exp:"2문단 전체가 근거다. 거리는 비고 병사는 성벽이 수용하도록 지어진 수보다 적다. 건물이 사람보다 오래 남았다는 뜻이지 폐허가 되었다는 뜻은 아니다 — (C)는 '폐허가 아니라 희석'이라는 서술과 충돌한다."},
     {q:"Why does the author discuss the White Tree?",
      opts:["To show that Gondor's rulers neglected their oldest traditions",
            "To provide an image of something carefully kept after it stopped working",
            "To explain the origin of the city's seven levels",
            "To contrast Gondor's customs with those of Rohan"],
      ans:1, exp:"수사적 의도 문제. 3문단이 직접 밝힌다: '기능이 멎은 뒤에도 지극한 정성으로 보존되는 무엇' — 국가의 상태를 압축한 이미지로 끌어온 것이다."}
   ]},

  /* ─────────── 5. 모리아 ─────────── */
  {id:"tk-moria", exam:"TOEFL", type:"경제·사회", level:4,
   series:"💍 반지의 제왕", title:"Moria and the Economics of Digging",
   topic:"모리아 — 채굴의 경제학과 그 대가",
   passage:"Moria is usually read as a horror sequence, but the text supplies enough detail to read it as an economic case as well. The dwarves of Khazad-dûm did not merely mine; they sustained the only known source of mithril, a metal light enough to be worn without fatigue and hard enough to turn a spear. The passage notes that its value came to exceed that of gold many times over, and that once the source was closed the metal could no longer be obtained at any price. A shirt of it was reckoned worth more than the whole of the Shire.\n\nThe usual moral drawn from the story is that the dwarves dug too greedily and too deep. The phrasing rewards attention, because the two adverbs are not the same charge. \"Too deep\" is a technical error; \"too greedily\" attributes motive. What the narrative actually shows is a community whose entire prosperity rested on a single irreplaceable deposit, and which therefore had no version of itself that did not involve pursuing that deposit further.\n\nWhat remains is an archaeological record rather than a ruin. The Book of Mazarbul, the tomb of Balin, the abandoned workings and the great empty hall all preserve the shape of an economy in the position where it stopped. Gimli's reverence in these corridors is not sentimentality. He is reading a place that still contains the evidence of what it was, and the evidence is legible precisely because nothing has been built over it.",
   ko:"모리아는 흔히 공포 장면으로 읽히지만, 본문은 이를 경제 사례로 읽을 만한 세부도 충분히 제공한다. 카자드둠의 난쟁이들은 단순히 광물을 캔 것이 아니라, 알려진 유일한 미스릴 산지를 유지했다. 미스릴은 걸쳐도 피로하지 않을 만큼 가볍고 창을 튕겨 낼 만큼 단단한 금속이다. 본문은 그 가치가 금의 몇 배를 넘어서게 되었으며, 산지가 닫힌 뒤로는 어떤 값을 치러도 구할 수 없게 되었다고 적는다. 미스릴 갑옷 한 벌은 샤이어 전체보다 값나가는 것으로 셈해졌다.\n\n이 이야기에서 흔히 끌어내는 교훈은 난쟁이들이 너무 탐욕스럽게, 너무 깊이 팠다는 것이다. 이 표현은 곱씹어 볼 값어치가 있는데, 두 부사가 같은 혐의가 아니기 때문이다. '너무 깊이'는 기술적 판단 착오이고, '너무 탐욕스럽게'는 동기를 문제 삼는다. 서사가 실제로 보여 주는 것은, 번영 전체가 대체 불가능한 단 하나의 광맥에 얹혀 있었고 따라서 그 광맥을 더 파 들어가지 않는 형태의 자기 자신이 존재하지 않았던 공동체다.\n\n남은 것은 폐허라기보다 고고학 기록이다. 마자르불의 책, 발린의 무덤, 버려진 갱도와 텅 빈 대전당은 모두 어느 경제가 멈춰 선 그 자세 그대로의 모습을 간직하고 있다. 이 회랑에서 김리가 보이는 경외는 감상(感傷)이 아니다. 그는 자신이 무엇이었는지에 대한 증거를 아직 품고 있는 장소를 읽고 있으며, 그 증거가 읽히는 것은 바로 그 위에 아무것도 새로 지어지지 않았기 때문이다.",
   gloss:[{w:"sustain",ko:"유지하다, 지탱하다"},{w:"reckon",ko:"~로 셈하다, 여기다"},
          {w:"adverb",ko:"부사"},{w:"attribute",ko:"~의 탓으로 돌리다"},
          {w:"irreplaceable",ko:"대체 불가능한"},{w:"legible",ko:"읽어 낼 수 있는"}],
   qs:[
     {q:"What is stated about mithril after the mines were closed?",
      opts:["Its price fell because demand disappeared.",
            "It could not be acquired regardless of what was offered.",
            "It was replaced by a harder metal found elsewhere.",
            "Only the dwarves who remained were permitted to trade it."],
      ans:1, exp:"1문단: 'once the source was closed the metal could no longer be obtained at any price.' 값의 문제가 아니라 공급 자체가 끊겼다는 것이다."},
     {q:"Why does the author distinguish \"too deep\" from \"too greedily\"?",
      opts:["To argue that only one of the two errors actually occurred",
            "To point out that one describes a miscalculation and the other a motive",
            "To show that the phrase was added to the story much later",
            "To suggest that the dwarves themselves disagreed about the cause"],
      ans:1, exp:"2문단이 직접 구분한다: '너무 깊이'는 기술적 판단 착오, '너무 탐욕스럽게'는 동기에 대한 혐의. 두 부사가 같은 종류의 비난이 아니라는 것이 논점이다."},
     {q:"What can be inferred about the dwarves' position from the second paragraph?",
      opts:["They had alternatives to mining but rejected them.",
            "Their prosperity left them little choice but to keep digging.",
            "They knew what lay beneath and continued anyway.",
            "They were compelled to mine by an outside authority."],
      ans:1, exp:"추론 문제. '그 광맥을 더 파 들어가지 않는 형태의 자기 자신이 존재하지 않았던 공동체'라는 서술은 대안이 없었다는 뜻이다. (A)는 정반대이고, (C)는 본문이 말하지 않은 내용이다."}
   ]},

  /* ─────────── 6. 스마우그 ─────────── */
  {id:"tk-smaug", exam:"TOEFL", type:"문학·인물", level:4,
   series:"💍 반지의 제왕", title:"Smaug and the Hoard That Does Nothing",
   topic:"스마우그 — 아무 일도 하지 않는 축장(蓄藏)",
   passage:"Smaug's most unusual feature as a villain is that he wants nothing. He has already taken the mountain, killed or driven off its people, and gathered its wealth into a single heap on which he sleeps. He does not spend it, trade it, or use it to acquire anything further. The hoard performs no function except to exist and to be his, and he knows it so exactly that he detects the loss of one cup among a mound of thousands.\n\nThis is a precise inversion of what treasure normally means in an adventure story. Gold in such stories is potential: it becomes ships, armies, houses, futures. Under the dragon it becomes the opposite of potential — value withdrawn from every possible use, including his own. The desolation surrounding the mountain is the visible form of that withdrawal. Nothing grows there, not because the dragon consumes it, but because he occupies it.\n\nThe conversation with Bilbo is where the theme surfaces. Smaug is vain, and the scene is often described as a battle of riddles, but what he is actually doing is soliciting recognition. He wants his armour admired and his reputation confirmed by the one visitor available. Bilbo obliges, flatters, and in the flattery finds the bare patch. A creature that has arranged its whole life so that nothing can be taken from it is undone by the one thing it still wants from someone else.",
   ko:"악역으로서 스마우그의 가장 특이한 점은 그가 원하는 것이 없다는 사실이다. 그는 이미 산을 차지했고, 그곳 사람들을 죽이거나 쫓아냈으며, 그 부를 한 무더기로 모아 그 위에서 잠든다. 그는 그것을 쓰지도, 거래하지도, 그것으로 무언가를 더 얻으려 하지도 않는다. 이 축재는 존재한다는 것과 자기 것이라는 것 말고는 아무 기능도 하지 않으며, 그는 그것을 어찌나 정확히 파악하고 있는지 수천 점 더미에서 잔 하나가 사라진 것을 알아챈다.\n\n이는 모험담에서 보물이 통상 뜻하는 바를 정확히 뒤집은 것이다. 그런 이야기에서 금은 잠재력이다. 금은 배가 되고 군대가 되고 집이 되고 미래가 된다. 용 아래에서 금은 잠재력의 반대가 된다. 그 자신의 용도를 포함해 가능한 모든 쓰임에서 회수된 가치가 되는 것이다. 산을 둘러싼 황무지는 그 회수가 눈에 보이는 형태로 드러난 것이다. 그곳에서는 아무것도 자라지 않는데, 용이 먹어 치워서가 아니라 그가 차지하고 있기 때문이다.\n\n주제가 표면으로 떠오르는 곳은 빌보와의 대화다. 스마우그는 허영이 있고, 이 장면은 흔히 수수께끼 대결로 묘사되지만, 그가 실제로 하고 있는 일은 인정을 구하는 것이다. 그는 자기 비늘 갑옷이 감탄받기를, 자기 명성이 확인되기를 바란다. 마침 찾아온 단 하나의 방문객에게서 말이다. 빌보는 그 뜻을 받아 주고 치켜세우며, 그 아첨 속에서 맨살 한 뼘을 찾아낸다. 아무것도 자신에게서 빼앗아 갈 수 없도록 삶 전체를 배치해 둔 존재가, 여전히 남에게서 원하는 단 한 가지 때문에 무너진다.",
   gloss:[{w:"hoard",ko:"축재, 쌓아 둔 재물"},{w:"inversion",ko:"뒤집기, 역전"},
          {w:"withdraw",ko:"회수하다, 거두어들이다"},{w:"desolation",ko:"황폐, 황무지"},
          {w:"solicit",ko:"구하다, 청하다"},{w:"undo",ko:"무너뜨리다, 파멸시키다"}],
   qs:[
     {q:"According to the passage, how does Smaug's hoard differ from treasure in ordinary adventure stories?",
      opts:["It is guarded by magic rather than by force.",
            "It is far smaller than the heroes expect.",
            "It cannot be turned into anything else, even by its owner.",
            "It was created rather than seized."],
      ans:2, exp:"2문단: 보통 이야기에서 금은 배·군대·집·미래가 되는 잠재력이지만, 용 아래에서는 '그 자신의 용도를 포함해' 모든 쓰임에서 회수된 가치가 된다."},
     {q:"What does the passage say about the land around the mountain?",
      opts:["It is barren because the dragon has eaten everything there.",
            "It is barren because of the dragon's mere presence.",
            "It was already barren before the dragon arrived.",
            "It recovers slowly whenever the dragon sleeps."],
      ans:1, exp:"2문단 마지막: 'not because the dragon consumes it, but because he occupies it.' 먹어서가 아니라 점유해서라는 구분이 그대로 출제된다."},
     {q:"What does the author suggest is the weakness Bilbo exploits?",
      opts:["Smaug's inability to count what he owns",
            "Smaug's desire to be admired by another",
            "Smaug's ignorance of the mountain's layout",
            "Smaug's unwillingness to leave the hoard unguarded"],
      ans:1, exp:"3문단: 그가 실제로 하는 일은 '인정을 구하는 것'이고, 마지막 문장이 '여전히 남에게서 원하는 단 한 가지'라고 못박는다. (A)는 본문과 반대다 — 그는 잔 하나까지 안다."}
   ]},

  /* ─────────── 7. 브리 ─────────── */
  {id:"tk-bree", exam:"TOEFL", type:"사회·지리", level:3,
   series:"💍 반지의 제왕", title:"Bree: A Settlement at a Crossing",
   topic:"브리 — 교차로에 선 정착지",
   passage:"Bree occupies a position that most settlements in the story do not: it sits where two old roads meet, and it is the one place where Men and Hobbits live in the same village as a matter of long custom rather than emergency. The arrangement is described without comment, which is itself a kind of comment. Elsewhere, contact between peoples is an event; in Bree it is the ordinary condition.\n\nThe consequences are practical. A crossroads settlement takes in whatever travels the roads, and what travels the roads is chiefly information. The common room of The Prancing Pony functions as a clearing-house: news arrives with strangers, is repeated, altered, and carried onward. This makes Bree useful and also makes it dangerous. The same room that allows Frodo to hear what is happening in the wider world allows the wider world to hear about him, and it takes only a moment of carelessness for that exchange to run in the wrong direction.\n\nThe villagers themselves are drawn as neither hostile nor welcoming but appraising. They are used to strangers and therefore neither alarmed nor impressed by them, and their first response to an unfamiliar face is to work out where it fits. Butterbur's forgetfulness about the letter is treated as a minor human failure rather than a betrayal. Bree is a place where things are known by many people imperfectly, which is precisely the condition that a crossroads produces.",
   ko:"브리는 이 이야기의 대다수 정착지가 갖지 못한 위치에 있다. 옛 도로 두 개가 만나는 자리에 앉아 있고, 인간과 호빗이 비상 상황 때문이 아니라 오랜 관습으로 같은 마을에 사는 유일한 곳이다. 이 사정은 별다른 논평 없이 서술되는데, 그 자체가 일종의 논평이다. 다른 곳에서 종족 간의 접촉은 하나의 사건이지만, 브리에서는 그것이 일상적인 조건이다.\n\n그 결과는 실질적이다. 교차로의 정착지는 길 위를 오가는 것을 받아들이게 되고, 길 위를 오가는 것은 주로 정보다. 달리는 조랑말 여관의 공용실은 집산지(集散地)처럼 작동한다. 소식은 낯선 이들과 함께 도착해 되풀이되고 변형되어 다시 실려 나간다. 이 점이 브리를 유용하게 만들고 동시에 위험하게 만든다. 프로도가 바깥세상에서 무슨 일이 벌어지는지 들을 수 있게 해 주는 바로 그 방이, 바깥세상이 그에 대해 듣게도 해 준다. 그 교환이 엉뚱한 방향으로 흐르는 데는 한순간의 부주의면 족하다.\n\n마을 사람들은 적대적이지도 환대하지도 않고 가늠하는 쪽으로 그려진다. 그들은 낯선 이에 익숙하므로 놀라지도 감탄하지도 않으며, 낯선 얼굴에 대한 첫 반응은 그 얼굴이 어디에 들어맞는지를 헤아리는 것이다. 편지에 관한 버터버의 건망증은 배신이 아니라 사소한 인간적 실수로 취급된다. 브리는 여러 사람이 무언가를 불완전하게 아는 곳이며, 그것이야말로 교차로가 만들어 내는 조건이다.",
   gloss:[{w:"custom",ko:"관습"},{w:"clearing-house",ko:"집산지, 정보가 모였다 흩어지는 곳"},
          {w:"appraising",ko:"가늠하는, 값을 매기는"},{w:"alarmed",ko:"놀란, 경계하는"},
          {w:"forgetfulness",ko:"건망증"},{w:"imperfectly",ko:"불완전하게"}],
   qs:[
     {q:"What does the author find notable about Men and Hobbits living together in Bree?",
      opts:["That it began as a response to a shared danger",
            "That it is treated in the text as unremarkable",
            "That it required an agreement between two rulers",
            "That it is resented by the older families of the village"],
      ans:1, exp:"1문단: 'described without comment, which is itself a kind of comment.' 특별한 일로 다루지 않는다는 점 자체가 주목할 지점이라는 것이다."},
     {q:"Why does the author call the common room both useful and dangerous?",
      opts:["Because news travels in both directions through it",
            "Because the innkeeper cannot be trusted with messages",
            "Because strangers there are often armed",
            "Because it is the only shelter available on the road"],
      ans:0, exp:"2문단: 프로도가 바깥 소식을 듣게 해 주는 바로 그 방이 바깥세상이 그를 알게도 만든다. 정보가 양방향으로 흐른다는 것이 핵심이다."},
     {q:"How are the people of Bree characterized?",
      opts:["As suspicious of anyone they have not met before",
            "As eager to help travellers who arrive at night",
            "As accustomed to strangers and inclined to size them up",
            "As indifferent to everything that happens beyond the village"],
      ans:2, exp:"3문단: '적대적이지도 환대하지도 않고 가늠하는' — 낯선 이에 익숙해서 놀라지 않고, 어디에 들어맞는지 헤아린다."}
   ]},

  /* ─────────── 8. 샤이어 ─────────── */
  {id:"tk-shire", exam:"TOEFL", type:"사회·제도", level:4,
   series:"💍 반지의 제왕", title:"The Shire and the Government You Cannot See",
   topic:"샤이어 — 보이지 않는 통치",
   passage:"The Shire is often taken for an image of unspoiled rural life, but the text is unusually specific about how it is administered, and the specifics complicate the impression. There is a Mayor whose duties are chiefly ceremonial, a postal service, a body of Shirriffs concerned mainly with straying livestock, and a hereditary Thain whose office has not been meaningfully exercised in generations. Almost no authority is applied, because almost none is needed: the hobbits are described as observing rules they believe to be both ancient and just, and therefore keeping them voluntarily.\n\nWhat the hobbits do not know is that this condition has been paid for elsewhere. The Rangers have patrolled the Shire's borders for many years without acknowledgement, and the peace the hobbits attribute to their own good sense has in fact been maintained by an external force they do not perceive. The passage is careful not to make this comic. The hobbits are not ridiculed for their ignorance; they are simply shown not to possess a piece of information about their own situation.\n\nThe consequence appears late in the story. When the Shire is finally occupied, its institutions offer no resistance at all, because they were never designed to resist anything. The recovery is carried out by four hobbits who learned elsewhere what their own society had no means of teaching them. A community can be genuinely well ordered and, at the same time, entirely dependent on conditions it did not create.",
   ko:"샤이어는 흔히 때 묻지 않은 시골 생활의 상(像)으로 받아들여지지만, 본문은 그곳이 어떻게 운영되는지를 이례적으로 구체적으로 적고 있으며, 그 구체성은 그런 인상을 복잡하게 만든다. 직무가 주로 의례적인 촌장이 있고, 우편 제도가 있으며, 주로 길 잃은 가축을 다루는 보안관 조직이 있고, 여러 세대 동안 실질적으로 행사된 적 없는 세습직 세인이 있다. 권력이 거의 행사되지 않는 것은 거의 필요하지 않기 때문이다. 호빗들은 자신들이 오래되고 정당하다고 믿는 규칙을 지키며, 그래서 자발적으로 그것을 따르는 이들로 묘사된다.\n\n호빗들이 모르는 것은 이 상태의 값이 다른 곳에서 치러졌다는 사실이다. 순찰자들은 오랜 세월 아무 인정도 받지 못한 채 샤이어의 국경을 지켜 왔고, 호빗들이 자기네 분별 덕이라 여기는 평화는 사실 그들이 지각하지 못하는 외부의 힘에 의해 유지되어 왔다. 본문은 이것을 우습게 만들지 않으려 조심한다. 호빗들은 무지하다고 조롱당하지 않는다. 다만 자기 처지에 관한 정보 한 조각을 갖고 있지 않은 이들로 제시될 뿐이다.\n\n그 결과는 이야기 후반에 드러난다. 마침내 샤이어가 점령당했을 때 그곳의 제도들은 아무런 저항도 내놓지 못하는데, 애초에 무언가에 저항하도록 설계된 적이 없기 때문이다. 회복은 자기 사회가 가르칠 수단이 없던 것을 바깥에서 배워 온 네 호빗의 손으로 이루어진다. 어떤 공동체는 진정으로 잘 정돈되어 있으면서 동시에, 스스로 만들지 않은 조건에 전적으로 기대고 있을 수 있다.",
   gloss:[{w:"unspoiled",ko:"때 묻지 않은"},{w:"administer",ko:"운영하다, 관리하다"},
          {w:"hereditary",ko:"세습의"},{w:"voluntarily",ko:"자발적으로"},
          {w:"attribute A to B",ko:"A를 B의 덕으로 돌리다"},{w:"ridicule",ko:"조롱하다"}],
   qs:[
     {q:"According to the passage, why is so little authority exercised in the Shire?",
      opts:["The offices that would exercise it have been abolished.",
            "The hobbits follow the rules without being compelled to.",
            "The Rangers have taken over the duties of the Shirriffs.",
            "Disputes are settled by the Thain in private."],
      ans:1, exp:"1문단 마지막: 규칙이 오래되고 정당하다고 믿기에 자발적으로 지킨다 — 그래서 강제가 거의 필요 없다."},
     {q:"What does the author emphasize about the hobbits' ignorance of the Rangers?",
      opts:["It is presented sympathetically rather than as a joke.",
            "It was deliberately encouraged by the Shire's leaders.",
            "It ends as soon as the borders are first crossed.",
            "It is shared by the Rangers themselves."],
      ans:0, exp:"2문단: 'The passage is careful not to make this comic… they are not ridiculed.' 조롱이 아니라 정보의 부재로 다룬다는 점을 강조한다."},
     {q:"What conclusion does the final paragraph draw?",
      opts:["Well-ordered societies are usually unable to defend themselves.",
            "The Shire's institutions failed because its officials were corrupt.",
            "A society can be well run and still rely on conditions it did not make.",
            "Travel is the only reliable form of political education."],
      ans:2, exp:"마지막 문장이 그대로 결론이다. (A)는 '보통 그렇다'는 일반화라 지나치고, (D)는 네 호빗의 사례를 원리로 격상한 오답이다."}
   ]},

  /* ─────────── 9. 호비튼 ─────────── */
  {id:"tk-hobbiton", exam:"TOEFL", type:"건축·계급", level:3,
   series:"💍 반지의 제왕", title:"Hobbiton: Property, Doors, and Standing",
   topic:"호비튼 — 집과 문이 말해 주는 계급",
   passage:"Hobbiton is drawn in enough domestic detail that its social structure can be read off its architecture. The most desirable dwelling is a smial, a tunnelled house set into a hillside, and the narration is explicit that the best of these are held by the oldest and wealthiest families. Bag End sits at the top of the Hill with its round green door, its panelled passage, and a great many rooms on one floor; poorer hobbits, we are told, live in ordinary built houses, and the very poorest in whatever is available. Digging is expensive. The form of the dwelling therefore records the resources of its owner as clearly as a ledger would.\n\nInheritance is treated with the same precision. When Bilbo is presumed dead, his possessions are auctioned, and the Sackville-Bagginses are found measuring rooms before the question of his return has been settled. The episode is comic, but the mechanism behind it is not invented for the joke: property passes by recognized rules, and those rules can be pressed hard by anyone willing to look grasping.\n\nWhat gives the departure at the start of the story its weight is this background. Frodo does not simply leave a house. He sells Bag End to the family that has spent decades trying to obtain it, and he does so quietly, using the transaction as cover. A reader who has registered how much a smial signifies in Hobbiton understands what the sale costs him without being told.",
   ko:"호비튼은 살림살이의 세부가 충분히 그려져 있어서 그 건축에서 사회 구조를 읽어 낼 수 있다. 가장 탐나는 거처는 언덕 비탈을 파 들어간 굴집 스미얼이며, 그중 좋은 것들은 가장 오래되고 부유한 집안이 차지하고 있다고 서술은 분명히 밝힌다. 골목쟁이집은 언덕 꼭대기에 앉아 둥근 초록 문과 판벽을 댄 복도, 한 층에 늘어선 아주 많은 방을 갖추고 있다. 형편이 못한 호빗들은 평범하게 지어 올린 집에 살고, 가장 가난한 이들은 있는 대로 아무 데나 산다고 적혀 있다. 굴을 파는 데는 돈이 든다. 그러므로 거처의 형태는 장부만큼이나 분명하게 그 주인의 재력을 기록한다.\n\n상속도 같은 정밀함으로 다루어진다. 빌보가 죽은 것으로 간주되자 그의 소유물은 경매에 부쳐지고, 사크빌바긴스 가족은 그가 돌아올지 여부가 정리되기도 전에 방 치수를 재고 있는 모습으로 발견된다. 이 대목은 희극적이지만 그 뒤에 놓인 기제는 웃음을 위해 지어낸 것이 아니다. 재산은 인정된 규칙에 따라 넘어가고, 그 규칙은 탐욕스럽게 보이기를 마다하지 않는 사람이라면 얼마든지 세게 밀어붙일 수 있다.\n\n이야기 첫머리의 떠남에 무게를 실어 주는 것이 바로 이 배경이다. 프로도는 그저 집 한 채를 떠나는 것이 아니다. 그는 수십 년 동안 골목쟁이집을 손에 넣으려 애써 온 바로 그 집안에 그 집을 팔고, 그것도 조용히, 그 거래를 위장 삼아 그렇게 한다. 호비튼에서 스미얼이 무엇을 뜻하는지 새겨 둔 독자라면 그 매각이 그에게 무엇을 치르게 하는지 따로 듣지 않고도 안다.",
   gloss:[{w:"dwelling",ko:"거처, 주거"},{w:"panelled",ko:"판벽을 댄"},{w:"ledger",ko:"장부"},
          {w:"presumed",ko:"~로 추정된"},{w:"auction",ko:"경매에 부치다"},
          {w:"grasping",ko:"탐욕스러운"},{w:"cover",ko:"위장, 구실"}],
   qs:[
     {q:"Why does the passage mention that digging is expensive?",
      opts:["To explain why hobbits prefer built houses to smials",
            "To account for why the best smials belong to wealthy families",
            "To show that Hobbiton was settled later than other villages",
            "To suggest that Bag End was constructed unusually quickly"],
      ans:1, exp:"수사적 의도 문제. 앞뒤 문장이 '좋은 스미얼은 부유한 집안 차지' → '굴 파기는 비싸다' → '거처의 형태가 재력을 기록한다'로 이어진다. 비용이 곧 계급의 지표가 되는 이유를 대는 문장이다."},
     {q:"What does the passage indicate about the auction of Bilbo's possessions?",
      opts:["It was held in violation of the Shire's customs.",
            "It proceeded according to accepted rules of inheritance.",
            "It was arranged by Bilbo himself before he left.",
            "It was cancelled once his return became known."],
      ans:1, exp:"2문단: 'property passes by recognized rules.' 규칙 위반이 아니라 인정된 규칙을 세게 밀어붙인 사례로 서술된다."},
     {q:"According to the last paragraph, what makes Frodo's sale of Bag End significant?",
      opts:["He receives far less for it than it is worth.",
            "He hands it to the very family that had long sought it.",
            "He is forbidden by custom to sell a smial at all.",
            "He conceals the sale from everyone in Hobbiton."],
      ans:1, exp:"3문단: '수십 년 동안 그 집을 손에 넣으려 애써 온 바로 그 집안에' 판다는 점이 무게를 만든다. (D)는 과장 — 조용히 처리했을 뿐 모두에게 숨긴 것은 아니다."}
   ]}

]);
