/* ============================================================
   관심주제 리딩 — 만화 『나루토』
   ------------------------------------------------------------
   인주력과 낙인 · 닌자 마을의 경제 · 우치하 일족과 감시 ·
   설득으로 끝내는 결말 · 재능과 노력 · 닌자의 규범

   설정 소개가 아니라 각 설정을 사회·제도의 문제로 바꿔 읽는 글이다.
   ============================================================ */
window.TOPIC_READING_EXTRA = (window.TOPIC_READING_EXTRA||[]).concat([

  /* ─────────── 1. 인주력 ─────────── */
  {id:"nr-jinchuriki", exam:"TOEFL", type:"사회·차별", level:4,
   series:"🍥 나루토", title:"The Container and the Contained",
   topic:"인주력 — 담은 그릇을 담긴 것으로 대하기",
   passage:"The premise that organizes the early portion of the series is administrative rather than mystical. A village possesses a destructive force it cannot destroy, so it seals the force inside a person and assigns that person to remain within its borders. The arrangement solves the immediate problem and creates a second one, which the story treats as the more interesting of the two.\n\nThe difficulty is that the community must simultaneously hold two positions. Officially, the container is a citizen under protection, and revealing the arrangement to children is forbidden. Practically, the adults who remember the destruction treat the container as the thing contained. Neither position is abandoned, so the child grows up in an environment where the stated rule and the observed behaviour disagree, without access to the information that would explain the disagreement.\n\nWhat makes this more than a device for generating sympathy is the story's attention to the adults' reasoning. They are not depicted as irrational. They lost family to a force that is now, by their own government's account, still present and merely restrained. Their fear is accurate about the danger and wrong about the person, and the story declines to let the second error cancel the first.\n\nThe eventual reversal is therefore gradual and specific. Individuals change their assessment one at a time, usually after an occasion on which the container acts in a way the feared thing would not.",
   ko:"이 작품의 초반을 조직하는 전제는 신비롭다기보다 행정적이다. 어느 마을이 파괴할 수 없는 파괴적인 힘을 갖게 되자, 그 힘을 한 사람 안에 봉인하고 그 사람을 마을 경계 안에 두기로 한다. 이 조치는 당면한 문제를 해결하면서 두 번째 문제를 만들어 내는데, 이야기는 둘 중 후자를 더 흥미로운 것으로 다룬다.\n\n난점은 공동체가 두 가지 입장을 동시에 유지해야 한다는 데 있다. 공식적으로 그 그릇은 보호받는 시민이고, 아이들에게 이 사정을 알리는 것은 금지되어 있다. 실제로는 그 파괴를 기억하는 어른들이 그 그릇을 담긴 것으로 대한다. 어느 입장도 버려지지 않으므로, 아이는 명시된 규칙과 관찰되는 행동이 서로 어긋나는 환경에서, 그 어긋남을 설명해 줄 정보에는 접근하지 못한 채 자란다.\n\n이것이 동정심을 자아내는 장치 이상이 되는 까닭은 이야기가 어른들의 논리에도 주의를 기울이기 때문이다. 그들은 비합리적인 존재로 그려지지 않는다. 그들은 어떤 힘에 가족을 잃었고, 자기네 정부의 설명에 따르더라도 그 힘은 여전히 존재하며 단지 억제되어 있을 뿐이다. 그들의 두려움은 위험에 대해서는 정확하고 그 사람에 대해서는 틀렸는데, 이야기는 두 번째 오류가 첫 번째를 지워 버리도록 두지 않는다.\n\n그래서 뒤집힘은 점진적이고 구체적으로 일어난다. 사람들은 한 명씩 판단을 바꾸며, 대개는 그 그릇이 두려움의 대상이라면 하지 않았을 방식으로 행동한 어떤 계기를 겪은 뒤에 그렇게 한다.",
   gloss:[{w:"administrative",ko:"행정적인"},{w:"seal",ko:"봉인하다"},
          {w:"container",ko:"그릇, 담는 것"},{w:"restrain",ko:"억제하다"},
          {w:"cancel",ko:"무효로 만들다, 상쇄하다"},{w:"assessment",ko:"판단, 평가"}],
   qs:[
     {q:"What second problem does the sealing arrangement create?",
      opts:["The seal weakens as the container grows older.",
            "The community holds two contradictory positions at once.",
            "Neighbouring villages demand the container be surrendered.",
            "The force can no longer be studied by the village's researchers."],
      ans:1, exp:"2문단: 공식적으로는 보호받는 시민이지만 실제로는 담긴 것으로 대해진다. 두 입장이 동시에 유지되는 것이 문제다."},
     {q:"Why is the child unable to make sense of the adults' behaviour?",
      opts:["The behaviour changes from day to day.",
            "The information that would explain it is withheld.",
            "The adults deny that any incident ever occurred.",
            "Other children receive the same treatment."],
      ans:1, exp:"2문단 마지막: 규칙과 행동이 어긋나는데 '그 어긋남을 설명해 줄 정보에는 접근하지 못한 채' 자란다."},
     {q:"How does the passage characterize the adults' fear?",
      opts:["As entirely irrational and unsupported by events",
            "As correct about the danger but mistaken about the person",
            "As encouraged by the village's leadership for political reasons",
            "As something they conceal even from one another"],
      ans:1, exp:"3문단: 'accurate about the danger and wrong about the person.' 이야기는 둘 중 하나로 단순화하지 않는다."}
   ]},

  /* ─────────── 2. 마을 경제 ─────────── */
  {id:"nr-village", exam:"TOEFL", type:"제도·경제", level:4,
   series:"🍥 나루토", title:"Hidden Villages as Military Contractors",
   topic:"닌자 마을 — 군사력을 파는 조직",
   passage:"It is easy to read the hidden villages as schools, since the protagonists are students and much of the early narrative concerns examinations. The institutions are better understood as firms. Each village sells military and covert services to the civilian government of its country, receives payment, and distributes work among its personnel according to a graded scale of difficulty and risk.\n\nThe grading system is where the economic logic becomes visible. Assignments are ranked, low-grade work consisting of errands and manual labour while the highest grades involve assassination and the interception of hostile operatives. Junior personnel are restricted to the lower grades not primarily for their safety but because pricing depends on the classification being credible. A village that sent novices on high-grade contracts would soon be unable to charge for them.\n\nThis structure explains several features that look arbitrary. Examinations are held jointly with rival villages and observed by clients, which makes them advertisements as much as assessments. Alliances shift according to contracts rather than principles. And the villages' relationship with their own governments is uneasy, because a state that depends on a military organization it does not directly command has limited leverage over it.\n\nThe series does not present this arrangement approvingly. Much of its later conflict originates in decisions taken by village leaderships that were defensible as institutional strategy and indefensible otherwise — the recurring shape of the story's political material.",
   ko:"주인공들이 학생이고 초반 서사의 상당 부분이 시험을 다루기 때문에, 은둔 마을을 학교로 읽기 쉽다. 이 기관들은 기업으로 이해하는 편이 낫다. 각 마을은 자기 나라의 민간 정부에 군사·첩보 서비스를 팔고 대가를 받으며, 난이도와 위험에 따라 등급이 매겨진 척도에 맞춰 인력에게 일을 배분한다.\n\n경제 논리가 눈에 보이는 지점이 바로 이 등급 체계다. 임무에는 등급이 매겨지는데, 낮은 등급은 심부름과 육체노동으로 이루어지고 가장 높은 등급에는 암살과 적대 요원 차단이 포함된다. 하급 인력이 낮은 등급에 묶여 있는 것은 우선적으로 그들의 안전 때문이 아니라, 가격 책정이 그 분류의 신뢰성에 달려 있기 때문이다. 초심자를 고등급 계약에 내보내는 마을은 머지않아 그 값을 받을 수 없게 된다.\n\n이 구조는 자의적으로 보이는 여러 특징을 설명한다. 시험은 경쟁 마을들과 공동으로 치러지고 고객들이 참관하므로, 평가인 만큼이나 광고이기도 하다. 동맹은 원칙이 아니라 계약에 따라 움직인다. 그리고 마을과 자국 정부의 관계는 껄끄러운데, 직접 지휘하지 않는 군사 조직에 의존하는 국가는 그 조직에 행사할 지렛대가 제한되기 때문이다.\n\n이 작품은 이 배치를 긍정적으로 제시하지 않는다. 후반의 갈등 상당수는 기관의 전략으로는 변호할 수 있으나 그 밖의 관점에서는 변호할 수 없는, 마을 수뇌부의 결정에서 비롯한다. 이 작품의 정치적 소재가 거듭 취하는 형태가 그것이다.",
   gloss:[{w:"covert",ko:"비밀의, 첩보의"},{w:"graded scale",ko:"등급 척도"},
          {w:"interception",ko:"차단, 요격"},{w:"credible",ko:"신뢰할 만한"},
          {w:"leverage",ko:"영향력, 지렛대"},{w:"defensible",ko:"변호할 수 있는"}],
   qs:[
     {q:"Why does the author say junior personnel are kept to lower grades?",
      opts:["Their training is not yet complete.",
            "The credibility of the pricing system depends on it.",
            "Clients specifically request experienced operatives.",
            "Higher grades are reserved for members of certain families."],
      ans:1, exp:"2문단: 안전이 우선적 이유가 아니라 '가격 책정이 그 분류의 신뢰성에 달려 있기 때문'이다."},
     {q:"What does the passage say about the joint examinations?",
      opts:["They function as advertisements as well as assessments.",
            "They were introduced to reduce conflict between villages.",
            "They are open only to personnel of the highest grade.",
            "They replaced an earlier system of direct combat."],
      ans:0, exp:"3문단: 고객이 참관하는 공동 시험이므로 '평가인 만큼이나 광고'다."},
     {q:"Why is the relationship between a village and its government uneasy?",
      opts:["The government cannot afford the village's fees.",
            "The state depends on a force it does not directly command.",
            "The village refuses to accept civilian oversight of examinations.",
            "The two are located in different countries."],
      ans:1, exp:"3문단 마지막: 직접 지휘하지 않는 군사 조직에 의존하는 국가는 지렛대가 제한된다."}
   ]},

  /* ─────────── 3. 우치하 ─────────── */
  {id:"nr-uchiha", exam:"TOEFL", type:"사회·감시", level:4,
   series:"🍥 나루토", title:"Suspicion That Produces What It Fears",
   topic:"우치하 일족 — 감시가 만들어 내는 결과",
   passage:"The clan storyline is the series' most sustained treatment of a familiar political mechanism: how surveillance of a group can bring about the disloyalty it was intended to detect.\n\nThe sequence begins with a plausible suspicion. Following a disaster, the leadership concludes that members of one clan may have been involved. It responds by relocating the clan to a district at the edge of the settlement, assigning its members disproportionately to police duties that keep them under observation, and placing an informant inside. Each measure is individually justifiable as a precaution.\n\nTheir combined effect is to make the clan's position materially worse and visibly so. Members observe that they are watched, excluded from senior decisions, and housed apart. A group treated as untrustworthy accumulates grievances that are real, and those grievances eventually produce the planning that the surveillance was established to find. At that point the original suspicion appears to have been vindicated, and the record will show that it was.\n\nWhat the narrative adds to this pattern is the position of the informant, who is required to choose between the group and the institution and is given no option that does not involve a catastrophe. The story withholds a verdict for a long time, and when it finally supplies context, the effect is not to identify a villain but to show a sequence in which each participant acted within the logic available to them.",
   ko:"이 일족을 둘러싼 이야기는 이 작품이 익숙한 정치적 기제를 가장 길게 다룬 대목이다. 한 집단에 대한 감시가 어떻게 그 감시가 적발하려던 바로 그 불충을 불러오는가 하는 문제다.\n\n이 흐름은 그럴듯한 의심에서 시작한다. 어떤 재난이 있은 뒤 수뇌부는 한 일족의 구성원들이 관여했을 수 있다고 결론짓는다. 그리고 그 일족을 거주지 가장자리 구역으로 옮기고, 감시가 가능한 경찰 업무에 그들을 지나치게 많이 배정하며, 내부에 정보원을 심는다. 각 조치는 하나씩 떼어 놓고 보면 예방책으로 변호할 수 있다.\n\n그러나 그것들이 합쳐진 효과는 그 일족의 처지를 실질적으로, 그리고 눈에 띄게 나쁘게 만드는 것이다. 구성원들은 자신들이 감시당하고, 주요 결정에서 배제되며, 따로 떨어져 산다는 사실을 관찰한다. 믿을 수 없는 존재로 취급받는 집단에는 실제적인 원한이 쌓이고, 그 원한은 결국 감시가 찾아내려고 설치되었던 바로 그 모의를 만들어 낸다. 그 시점에 이르면 애초의 의심은 입증된 것처럼 보이고, 기록에도 그렇게 남는다.\n\n이 서사가 이 양상에 보태는 것은 정보원의 자리다. 그는 집단과 기관 사이에서 선택하도록 요구받되 파국을 포함하지 않는 선택지는 받지 못한다. 이야기는 오랫동안 판정을 유보하고, 마침내 맥락을 제공할 때 그 효과는 악당을 지목하는 것이 아니라 참여자 각자가 자기에게 주어진 논리 안에서 행동한 하나의 연쇄를 보여 주는 것이다.",
   gloss:[{w:"surveillance",ko:"감시"},{w:"disloyalty",ko:"불충, 배신"},
          {w:"relocate",ko:"이주시키다"},{w:"disproportionately",ko:"불균형하게, 지나치게 많이"},
          {w:"informant",ko:"정보원"},{w:"vindicate",ko:"정당함이 입증되다"},
          {w:"withhold a verdict",ko:"판정을 미루다"}],
   qs:[
     {q:"What mechanism does the storyline illustrate?",
      opts:["Surveillance can create the disloyalty it was meant to uncover.",
            "Clans inevitably resist any form of central authority.",
            "Police duties are unsuitable for members of a suspected group.",
            "Informants are rarely able to gather useful information."],
      ans:0, exp:"1문단이 직접 밝힌다: 감시가 적발하려던 불충을 도리어 불러온다는 기제."},
     {q:"According to the passage, what is true of the individual precautions?",
      opts:["They were adopted without the leadership's approval.",
            "Each could be justified on its own, but together they worsened the situation.",
            "They were kept secret from everyone in the settlement.",
            "They were relaxed once the clan cooperated."],
      ans:1, exp:"2문단 마지막과 3문단 첫 문장: 개별로는 변호 가능하지만 합쳐진 효과가 처지를 악화시켰다."},
     {q:"What does the author say the eventual context achieves?",
      opts:["It identifies which party was responsible.",
            "It shows each participant acting within the logic available to them.",
            "It reverses the earlier judgment about the disaster.",
            "It proves the original suspicion had been groundless."],
      ans:1, exp:"마지막 문장: 악당을 지목하는 것이 아니라 각자가 주어진 논리 안에서 행동한 연쇄를 보여 준다."}
   ]},

  /* ─────────── 4. 설득으로 끝내기 ─────────── */
  {id:"nr-talk", exam:"TOEFL", type:"서사·구성", level:3,
   series:"🍥 나루토", title:"Ending Conflicts by Conversion",
   topic:"설득으로 끝내는 결말과 그 대가",
   passage:"A recurring structure in the series is worth examining as a formal choice. Confrontations frequently conclude not with the antagonist's defeat but with the antagonist's change of position, arrived at through an extended exchange during or after the fighting. The pattern is consistent enough that readers anticipate it.\n\nThe device has an evident advantage. It allows the story to give opponents developed motives, since a motive that will later be answered must first be stated seriously. Antagonists therefore receive extended histories, and the narrative accumulates a supply of perspectives that a straightforwardly eliminative structure would discard.\n\nThe costs are equally real and the series does not entirely avoid them. If conversion is the expected outcome, the fighting preceding it becomes decorative, since the physical result rarely determines the resolution. Repetition also flattens the effect: the tenth reformed opponent carries less weight than the first, and the reader begins to attend to the argument rather than the outcome, which the argument must then be strong enough to bear.\n\nThe more interesting instances are those where the pattern is refused. Several antagonists are not persuaded, and one of the story's more durable relationships resists resolution for most of its length precisely because the usual mechanism keeps failing. Those cases are legible as exceptions only because the convention is established, which is the ordinary way a formal habit earns its keep.",
   ko:"이 작품에 되풀이되는 한 구조는 형식적 선택으로 따져 볼 만하다. 대결은 흔히 적대자의 패배가 아니라 적대자의 입장 변화로 끝나며, 그 변화는 싸움 도중이나 그 뒤에 오가는 긴 대화를 통해 이루어진다. 이 양상은 독자가 미리 예상할 만큼 일관되어 있다.\n\n이 장치에는 분명한 이점이 있다. 적대자에게 충실히 전개된 동기를 부여할 수 있게 해 준다는 점이다. 나중에 응답받을 동기라면 먼저 진지하게 진술되어야 하기 때문이다. 그래서 적대자들은 긴 내력을 얻고, 서사는 제거 중심의 구조라면 버렸을 관점들을 차곡차곡 모으게 된다.\n\n대가 또한 실재하며 이 작품이 그것을 온전히 피해 가지는 못한다. 전향이 예상되는 결말이라면 그에 앞선 싸움은 장식이 된다. 물리적 결과가 좀처럼 결론을 정하지 않기 때문이다. 반복은 효과를 무디게도 만든다. 열 번째로 돌아선 적대자는 첫 번째보다 무게가 덜하고, 독자는 결과가 아니라 논변에 주의를 기울이기 시작하는데, 그러면 그 논변이 그 무게를 감당할 만큼 강해야만 한다.\n\n더 흥미로운 사례는 이 양상이 거부되는 경우다. 몇몇 적대자는 설득되지 않으며, 이 이야기에서 가장 오래가는 관계 가운데 하나는 바로 그 통상적 기제가 계속 실패하기 때문에 대부분의 구간 동안 해소되지 않는다. 그런 사례가 예외로 읽히는 것은 관습이 확립되어 있기 때문이며, 형식적 습관이 제 몫을 하는 방식이 원래 그렇다.",
   gloss:[{w:"antagonist",ko:"적대자"},{w:"eliminative",ko:"제거 중심의"},
          {w:"decorative",ko:"장식적인"},{w:"flatten",ko:"무디게 하다, 평평하게 하다"},
          {w:"durable",ko:"오래가는"},{w:"convention",ko:"관습, 관례"}],
   qs:[
     {q:"What advantage does the author attribute to the conversion pattern?",
      opts:["It shortens the length of individual confrontations.",
            "It requires antagonists' motives to be presented seriously.",
            "It reduces the amount of violence shown to readers.",
            "It makes the outcome of fights easier to predict."],
      ans:1, exp:"2문단: 나중에 응답받을 동기라면 먼저 진지하게 진술되어야 하므로 적대자들이 충실한 내력을 얻는다."},
     {q:"According to the passage, what happens to the fighting when conversion is expected?",
      opts:["It becomes longer and more elaborate.",
            "It becomes decorative, since it rarely settles the outcome.",
            "It is moved to the end of each confrontation.",
            "It is replaced entirely by dialogue."],
      ans:1, exp:"3문단: 물리적 결과가 결론을 정하지 않으므로 싸움이 장식이 된다."},
     {q:"Why does the author call the refused cases \"more interesting\"?",
      opts:["They involve the strongest antagonists in the series.",
            "They are legible as exceptions because the convention exists.",
            "They occur only in the final portion of the story.",
            "They avoid dialogue altogether."],
      ans:1, exp:"마지막 문단: 관습이 확립되어 있기에 그 거부가 예외로 읽힌다는 것이 요지다."}
   ]},

  /* ─────────── 5. 재능과 노력 ─────────── */
  {id:"nr-talent", exam:"TOEFL", type:"주제·논증", level:4,
   series:"🍥 나루토", title:"Talent, Work, and an Argument the Series Keeps Having",
   topic:"재능과 노력 — 작품이 반복해서 하는 논쟁",
   passage:"Stories about training tend to endorse effort, and this one appears to do so emphatically. The protagonist is introduced as the weakest student in his year and improves through persistence. Yet the series returns to the question often enough, and with enough discomfort, to suggest that it does not find its own answer sufficient.\n\nThe difficulty is built into the setting. Ability in this world is partly inherited: certain families possess traits that cannot be acquired by anyone outside them, and the narrative does not pretend otherwise. A character who trains without such an inheritance is therefore not merely behind but permanently excluded from a category of technique. The story stages this directly, pairing a student with no inherited advantage against one whose family trait makes an entire class of attack unusable against him.\n\nThe resolution offered is narrower than the slogan suggests. Effort does not overcome inheritance; it produces a different kind of competence, sufficient in some encounters and not in others. The character who trains hardest sustains lasting physical damage and does not become the strongest.\n\nThis is why the series' position is more interesting than the motivational reading of it. What it argues is not that work defeats talent but that a person's worth is not settled by which of the two they have — a claim that survives the counter-evidence the setting keeps producing.",
   ko:"수련을 다루는 이야기는 노력을 옹호하기 마련이고, 이 작품도 겉으로는 강하게 그렇게 한다. 주인공은 같은 학년에서 가장 약한 학생으로 소개되고 끈기를 통해 나아진다. 그런데 이 작품은 그 물음으로 충분히 자주, 그리고 충분히 불편한 태도로 되돌아오므로, 자기가 내놓은 답을 스스로 흡족하게 여기지 않는다는 인상을 준다.\n\n난점은 설정 자체에 박혀 있다. 이 세계에서 능력은 일부 유전된다. 어떤 가문들은 바깥 사람이 결코 습득할 수 없는 형질을 지니며, 서사는 그렇지 않은 척하지 않는다. 그런 상속 없이 수련하는 인물은 그저 뒤처진 것이 아니라 한 부류의 기술에서 영구히 배제되어 있는 셈이다. 이야기는 이 점을 정면으로 무대에 올린다. 물려받은 이점이 없는 학생을, 가문의 형질 덕에 한 부류의 공격 전체가 통하지 않는 상대와 맞붙여 놓는 것이다.\n\n제시되는 해결은 구호가 시사하는 것보다 좁다. 노력은 상속을 이기지 않는다. 노력은 다른 종류의 역량을 만들어 내며, 그것은 어떤 대결에서는 충분하고 어떤 대결에서는 그렇지 않다. 가장 열심히 수련한 인물은 영구적인 신체 손상을 입고, 가장 강해지지도 않는다.\n\n그래서 이 작품의 입장은 그것을 자기계발적으로 읽는 것보다 흥미롭다. 이 작품이 주장하는 바는 노력이 재능을 이긴다는 것이 아니라, 사람의 값어치가 둘 중 무엇을 가졌느냐로 정해지지 않는다는 것이다. 이 주장은 설정이 계속 만들어 내는 반대 증거를 견디고 살아남는다.",
   gloss:[{w:"endorse",ko:"지지하다, 옹호하다"},{w:"persistence",ko:"끈기"},
          {w:"inherited",ko:"물려받은"},{w:"stage",ko:"무대에 올리다, 연출하다"},
          {w:"competence",ko:"역량"},{w:"counter-evidence",ko:"반대 증거"}],
   qs:[
     {q:"What does the author infer from the series returning to the question repeatedly?",
      opts:["That readers had complained about the earlier answer",
            "That the series is not satisfied with its own answer",
            "That the setting was revised partway through",
            "That effort is the only theme the series develops"],
      ans:1, exp:"1문단 마지막: 충분히 자주, 불편하게 되돌아온다는 사실에서 '자기 답을 흡족하게 여기지 않는다'는 인상을 끌어낸다."},
     {q:"What does the passage say about the hardest-working character?",
      opts:["He eventually surpasses those with inherited traits.",
            "He suffers lasting injury and does not become the strongest.",
            "He abandons training after his defeat.",
            "He acquires an inherited trait through practice."],
      ans:1, exp:"3문단: 'sustains lasting physical damage and does not become the strongest.'"},
     {q:"What claim does the author say the series actually makes?",
      opts:["That effort reliably defeats inherited advantage",
            "That a person's worth is not decided by which of the two they possess",
            "That inherited ability should be regulated by the villages",
            "That training systems are unfair and should be reformed"],
      ans:1, exp:"마지막 문단: 노력이 재능을 이긴다는 주장이 아니라, 값어치가 둘 중 무엇을 가졌느냐로 정해지지 않는다는 주장이다."}
   ]},

  /* ─────────── 6. 닌자의 규범 ─────────── */
  {id:"nr-code", exam:"TOEFL", type:"직업·윤리", level:4,
   series:"🍥 나루토", title:"A Professional Code and Everyone Who Breaks It",
   topic:"닌자의 규범 — 지키지 않는 인물만 존경받는 규칙",
   passage:"The shinobi code, as characters recite it, requires the suppression of feeling. An operative is to complete assignments without hesitation, to treat personal attachment as a liability, and to regard emotional display as a professional failure. The rule is stated early, repeated often, and attributed to no particular author, which gives it the character of settled doctrine.\n\nWhat is striking is how the narrative distributes adherence. Nearly every character the story presents as admirable violates the code, usually at a decisive moment and usually at cost. Conversely, the characters who observe it most rigorously are those the story treats as damaged: an instructor who abandoned a teammate and spends years at a memorial, an operative trained from childhood to feel nothing and described as barely a person.\n\nThis distribution is not accidental, and it is not simply an argument that rules should be broken. The code exists for a reason the story acknowledges: an operative who hesitates endangers others, and the profession involves acts that cannot be performed by someone fully attending to their meaning. The narrative does not claim the rule is baseless. It claims that the rule describes a cost the profession imposes rather than a virtue its members should cultivate.\n\nThe distinction matters for how the ending reads. What changes by the conclusion is not that the characters become better at following the code but that the institution stops requiring it of them.",
   ko:"등장인물들이 읊는 닌자의 규범은 감정을 억누를 것을 요구한다. 요원은 망설임 없이 임무를 완수해야 하고, 개인적 애착을 부담으로 취급해야 하며, 감정을 드러내는 것을 직업적 실패로 여겨야 한다. 이 규칙은 일찍 진술되고 자주 반복되며 특정한 작성자가 없으므로, 이미 정해진 교리 같은 성격을 띤다.\n\n눈에 띄는 것은 서사가 이 규범의 준수를 어떻게 배분하는가이다. 이야기가 존경할 만하게 그리는 인물은 거의 전부 이 규범을 어기며, 대개 결정적인 순간에 대가를 치르면서 그렇게 한다. 반대로 이를 가장 엄격히 지키는 인물들은 이야기가 손상된 존재로 다루는 이들이다. 동료를 저버리고 여러 해를 위령비 앞에서 보내는 교관, 어려서부터 아무것도 느끼지 않도록 훈련받아 사람이라 하기 어렵다고 묘사되는 요원 같은.\n\n이 배분은 우연이 아니며, 규칙은 깨져야 한다는 단순한 주장도 아니다. 이 규범이 존재하는 데에는 이야기도 인정하는 이유가 있다. 망설이는 요원은 다른 사람을 위험에 빠뜨리고, 이 직업에는 그 의미에 온전히 주의를 기울이는 사람이라면 수행할 수 없는 행위가 포함된다. 서사는 이 규칙이 근거 없다고 말하지 않는다. 다만 이 규칙이 구성원이 길러야 할 미덕이 아니라 이 직업이 부과하는 대가를 기술하고 있다고 말한다.\n\n이 구분은 결말을 어떻게 읽을지를 좌우한다. 결말에 이르러 달라지는 것은 인물들이 규범을 더 잘 지키게 되었다는 점이 아니라, 기관이 더는 그것을 요구하지 않게 되었다는 점이다.",
   gloss:[{w:"recite",ko:"읊다, 외다"},{w:"suppression",ko:"억누름"},
          {w:"liability",ko:"부담, 짐"},{w:"doctrine",ko:"교리, 원칙"},
          {w:"adherence",ko:"준수"},{w:"rigorously",ko:"엄격하게"},
          {w:"cultivate",ko:"기르다, 함양하다"}],
   qs:[
     {q:"How does the narrative distribute adherence to the code?",
      opts:["Admirable characters break it; the strictest observers are shown as damaged.",
            "Only junior operatives are expected to follow it.",
            "Adherence increases as characters gain experience.",
            "The code is followed in wartime and ignored otherwise."],
      ans:0, exp:"2문단이 그대로 서술한다 — 존경받는 인물은 어기고, 가장 엄격히 지키는 인물은 손상된 존재로 그려진다."},
     {q:"What reason does the story acknowledge for the code's existence?",
      opts:["It preserves the villages' reputation with clients.",
            "Hesitation endangers others and some acts cannot be done while attending to their meaning.",
            "It was imposed by the civilian governments.",
            "It prevents operatives from forming rival alliances."],
      ans:1, exp:"3문단: 망설이는 요원은 남을 위험에 빠뜨리고, 의미에 온전히 주의를 기울이면 수행할 수 없는 행위가 있다."},
     {q:"According to the passage, what changes by the conclusion?",
      opts:["The characters finally learn to obey the code.",
            "The institution stops demanding the code of them.",
            "The code is rewritten by the surviving instructors.",
            "Emotional display becomes a professional requirement."],
      ans:1, exp:"마지막 문장: 인물이 더 잘 지키게 된 것이 아니라 '기관이 더는 요구하지 않게 되었다'는 점이 달라진다."}
   ]}

]);
