/* ============================================================
   관심주제 리딩 — 『매트릭스』 초·중반 시퀀스
   ------------------------------------------------------------
   오프닝 추격 · 흰 토끼와 속 파낸 책 · 심문과 도청 장치 ·
   빨간 알약과 각성 · 컨스트럭트 · 훈련 프로그램

   장면 요약이 아니라 각 시퀀스가 무슨 문제를 풀고 있는지를
   따지는 글이다. 설명을 언제 하는가, 관객을 어떻게 흔드는가,
   선택을 어떻게 선택처럼 보이게 하는가 하는 형식의 문제들.
   ============================================================ */
window.TOPIC_READING_EXTRA = (window.TOPIC_READING_EXTRA||[]).concat([

  /* ─────────── 1. 오프닝 ─────────── */
  {id:"mx-open", exam:"TOEFL", type:"영화·구성", level:4,
   series:"🕶 매트릭스", title:"Demonstration Before Explanation",
   topic:"매트릭스 오프닝 — 설명하기 전에 보여 주기",
   passage:"The Matrix opens with a sequence in which a woman fights several armed officers, runs along a wall, leaps between rooftops, and escapes through a telephone. None of this is explained. The film provides no narration, and the characters speak as though everything occurring is ordinary for them.\n\nThe placement is a solution to a structural problem faced by any film with an unfamiliar premise. Such a film must eventually explain its rules, and explanation is inert: a character describing what is possible cannot generate tension, because nothing is at stake while the description is being delivered. Front-loading a demonstration inverts the order. By the time the rules are stated, roughly forty minutes later, the audience has already seen them operating and is receiving confirmation rather than instruction.\n\nThe sequence also establishes the terms of threat. The pursuers are dressed as ordinary law enforcement and are then shown to be something else, which fixes the film's central anxiety — that any person in view may be an instrument of the system — before that idea is ever articulated. A later scene in which an old woman turns her head at the wrong moment works entirely on the ground prepared here.\n\nWhat the opening withholds is equally deliberate. The audience learns what the characters can do and nothing about why, and the resulting gap is the engine that carries the film through its slow middle section.",
   ko:"『매트릭스』는 한 여성이 무장 경관 여럿과 싸우고, 벽을 타고 달리고, 옥상 사이를 뛰어넘고, 전화기를 통해 빠져나가는 시퀀스로 시작한다. 그 무엇도 설명되지 않는다. 영화는 내레이션을 붙이지 않고, 인물들은 벌어지는 모든 일이 자기들에게는 평범하다는 듯이 말한다.\n\n이 배치는 낯선 전제를 가진 영화라면 어느 것이나 마주하는 구조적 문제에 대한 해법이다. 그런 영화는 언젠가 자기 규칙을 설명해야 하는데, 설명은 불활성이다. 무엇이 가능한지를 인물이 서술하는 동안에는 걸린 것이 없으므로 긴장이 생기지 않는다. 시연을 앞으로 당겨 놓으면 순서가 뒤집힌다. 규칙이 말로 진술되는 대략 40분 뒤에는 관객이 이미 그것이 작동하는 모습을 보았기에, 지시가 아니라 확인을 받게 된다.\n\n이 시퀀스는 위협의 성격도 정해 놓는다. 추격자들은 평범한 법 집행관 차림으로 나왔다가 다른 무엇임이 드러나고, 그럼으로써 이 영화의 중심 불안 — 시야에 들어온 어떤 사람이든 체계의 도구일 수 있다는 것 — 이 말로 언급되기 전에 자리를 잡는다. 뒷부분에서 한 노인이 엉뚱한 순간에 고개를 돌리는 장면은 전적으로 여기서 닦아 둔 바닥 위에서 작동한다.\n\n이 오프닝이 감춰 두는 것 또한 의도적이다. 관객은 인물들이 무엇을 할 수 있는지는 알게 되지만 왜 그런지는 전혀 알지 못하며, 그렇게 생긴 간극이 느린 중반부를 끌고 가는 동력이 된다.",
   gloss:[{w:"premise",ko:"전제, 설정"},{w:"inert",ko:"불활성의, 아무 작용 없는"},
          {w:"at stake",ko:"걸려 있는"},{w:"front-load",ko:"앞쪽에 배치하다"},
          {w:"articulate",ko:"말로 표현하다"},{w:"withhold",ko:"감추다, 내주지 않다"}],
   qs:[
     {q:"According to the passage, why is explanation described as \"inert\"?",
      opts:["It uses vocabulary the audience does not know.",
            "Nothing is at stake while a rule is merely being described.",
            "It is usually delivered by minor characters.",
            "It contradicts what the audience has already seen."],
      ans:1, exp:"2문단: '걸린 것이 없으므로 긴장이 생기지 않는다.' 설명 자체는 사건이 아니기 때문이다."},
     {q:"What does the audience receive when the rules are finally stated?",
      opts:["Instruction about an unfamiliar system",
            "Confirmation of something already witnessed",
            "A correction of an earlier misunderstanding",
            "A summary delivered by a narrator"],
      ans:1, exp:"2문단 마지막: 이미 작동하는 모습을 보았으므로 '지시가 아니라 확인'을 받는다."},
     {q:"Why does the passage mention the old woman who turns her head?",
      opts:["To show that the film reuses its opening location",
            "To give an example of a later scene that depends on the opening's groundwork",
            "To criticize the film for repeating an effect",
            "To identify the moment the rules are finally explained"],
      ans:1, exp:"수사적 의도 문제. 3문단 마지막: 그 장면은 '전적으로 여기서 닦아 둔 바닥 위에서' 작동한다."}
   ]},

  /* ─────────── 2. 흰 토끼와 책 ─────────── */
  {id:"mx-book", exam:"TOEFL", type:"영화·해석", level:4,
   series:"🕶 매트릭스", title:"The Hollowed Book and the Instruction to the Viewer",
   topic:"속을 파낸 책 — 관객에게 주는 읽기 지침",
   passage:"Early in the film the protagonist retrieves illicit software from inside a hollowed-out book. The camera holds on the cover long enough for the title to register: a work of theory concerned with copies that have replaced the originals they were made from. The shot is a message to the audience rather than to any character.\n\nFilms with unusual premises often plant such objects. The function is to supply a frame of reference before the premise arrives, so that when the explanation comes the viewer already has somewhere to put it. A viewer who noticed the book has been told, in advance and without a line of dialogue, what kind of story this will be.\n\nThe treatment of the book is nonetheless pointed. It has been cut open and emptied; its pages exist to conceal a hiding place. The protagonist keeps it for the cavity, not the argument. Read one way this is a small joke at the expense of the borrowing — the film uses the theory as a container too. Read another way it describes the character's position exactly: he possesses the relevant idea without having read it, which is his situation with respect to his own life.\n\nThe scene is also the first appearance of the film's method of directing attention. Instructions arrive in the same form throughout — a message on a screen, a tattoo, a phrase repeated by strangers — and the protagonist follows them before understanding them.",
   ko:"영화 초반, 주인공은 속을 파낸 책 안에서 불법 소프트웨어를 꺼낸다. 카메라는 제목이 눈에 들어올 만큼 표지에 머무른다. 원본을 대체해 버린 복제물을 다루는 이론서다. 이 숏은 어느 인물에게가 아니라 관객에게 보내는 전언이다.\n\n낯선 전제를 가진 영화는 흔히 그런 물건을 심어 둔다. 전제가 도착하기 전에 참조 틀을 미리 공급해서, 설명이 왔을 때 관객이 그것을 놓아둘 자리를 이미 갖고 있게 하는 기능이다. 그 책을 알아본 관객은 대사 한 줄 없이, 그리고 미리, 이것이 어떤 종류의 이야기가 될지를 전해 들은 셈이다.\n\n그럼에도 이 책이 다루어지는 방식은 뾰족하다. 그 책은 잘려 나가고 비워졌다. 그 책장들은 은닉처를 감추기 위해 존재한다. 주인공이 그 책을 간직하는 것은 논지 때문이 아니라 그 구멍 때문이다. 한편으로 이것은 그 차용을 스스로 겨눈 작은 농담으로 읽힌다. 영화 역시 그 이론을 용기(容器)로 쓰고 있으니까. 다른 한편으로 이것은 이 인물의 처지를 정확히 기술한다. 그는 읽지 않은 채로 그 개념을 소유하고 있으며, 이는 그가 자기 삶에 대해 놓인 자리 그대로다.\n\n이 장면은 또한 이 영화가 주의를 이끄는 방식이 처음 나타나는 자리이기도 하다. 지시는 내내 같은 형태로 도착한다. 화면에 뜨는 메시지, 문신, 낯선 이들이 되풀이하는 한 구절. 그리고 주인공은 그것들을 이해하기 전에 먼저 따른다.",
   gloss:[{w:"illicit",ko:"불법의"},{w:"hollowed-out",ko:"속을 파낸"},
          {w:"frame of reference",ko:"참조 틀"},{w:"pointed",ko:"뾰족한, 의도가 뚜렷한"},
          {w:"cavity",ko:"빈 공간, 구멍"},{w:"at the expense of",ko:"~를 겨누어, ~를 희생시켜"}],
   qs:[
     {q:"What function does the author assign to objects like the book?",
      opts:["They identify which character can be trusted.",
            "They give the viewer a frame of reference before the premise is explained.",
            "They allow the film to avoid explaining its premise at all.",
            "They mark the point at which the story changes location."],
      ans:1, exp:"2문단: 전제가 도착하기 전에 참조 틀을 공급해 설명을 놓아둘 자리를 미리 만들어 준다."},
     {q:"What does the author find significant about the book being hollowed out?",
      opts:["It shows the protagonist cannot afford new books.",
            "The character keeps it for the hiding place rather than the argument.",
            "It proves the theory is irrelevant to the film.",
            "It indicates the book was damaged by the authorities."],
      ans:1, exp:"3문단: 'He keeps it for the cavity, not the argument.' 이것이 농담이자 인물의 처지에 대한 정확한 기술이라고 본다."},
     {q:"What pattern does the scene introduce?",
      opts:["Instructions that the protagonist follows before understanding them",
            "Conversations that are repeated later with different meanings",
            "Objects that turn out to be simulations",
            "Characters who conceal their real names"],
      ans:0, exp:"마지막 문단: 메시지·문신·되풀이되는 구절로 지시가 오고, 그는 이해하기 전에 따른다."}
   ]},

  /* ─────────── 3. 심문 ─────────── */
  {id:"mx-interrogation", exam:"TOEFL", type:"영화·구성", level:4,
   series:"🕶 매트릭스", title:"The Interrogation and the Uncertain Waking",
   topic:"심문 장면 — 깨어남을 믿을 수 없게 만들기",
   passage:"The interrogation sequence performs a task the film needs done before its premise can land. The protagonist is detained, his mouth seals shut, and a device is placed inside his body. He then wakes in his own bed, and the scene is constructed so that the obvious conclusion — that he dreamt it — is available and comfortable.\n\nThe film then removes that conclusion. The device is retrieved from his body a short time later, in front of witnesses. What this establishes is not merely that the interrogation happened. It establishes that an experience indistinguishable from a dream can be an event, which is the proposition the entire premise depends on.\n\nThe ordering matters. Had the film asserted its premise first and offered this scene as illustration, the scene would be evidence for a claim already made, and the viewer would assess it accordingly. Presented before any claim, it functions instead as an experience the viewer has and cannot categorize. The doubt is produced rather than argued for.\n\nThe sequence also does quieter work on the antagonist. He is shown to be capable of acts that violate physical constraint while remaining entirely composed, and he addresses the protagonist by two different names — the legal one and the chosen one — treating the distinction as a matter he has authority over. Everything the film later says about who controls identity is contained in that exchange.",
   ko:"심문 시퀀스는 이 영화의 전제가 착지하기 전에 반드시 해 두어야 할 일을 수행한다. 주인공은 구금되고, 입이 봉해지며, 몸 안에 장치가 심긴다. 그런 뒤 그는 자기 침대에서 깨어나고, 이 장면은 뻔한 결론 — 꿈이었다는 것 — 이 손닿는 곳에 편안하게 놓이도록 지어져 있다.\n\n그러고 나서 영화는 그 결론을 걷어 간다. 얼마 지나지 않아 그 장치가 목격자들 앞에서 그의 몸에서 꺼내진다. 이것이 확립하는 바는 단지 그 심문이 실제로 있었다는 사실이 아니다. 꿈과 구별되지 않는 경험도 하나의 사건일 수 있다는 것, 즉 이 영화의 전제 전체가 기대고 있는 명제를 확립한다.\n\n순서가 중요하다. 영화가 전제를 먼저 주장하고 이 장면을 예시로 내놓았다면, 그 장면은 이미 제기된 주장을 뒷받침하는 증거가 되고 관객은 그에 맞춰 그것을 평가했을 것이다. 어떤 주장보다 앞서 제시되면, 그것은 대신 관객이 겪되 분류할 수 없는 경험으로 기능한다. 의심은 논증되는 것이 아니라 만들어진다.\n\n이 시퀀스는 적대자에 대해서도 조용한 일을 한다. 그는 물리적 제약을 어기는 행위를 완전히 침착한 상태로 해내는 존재로 그려지고, 주인공을 두 개의 이름으로 — 법적인 이름과 스스로 택한 이름으로 — 부르며 그 구분을 자기에게 권한이 있는 사안처럼 다룬다. 누가 정체성을 통제하는가에 대해 이 영화가 나중에 말하는 모든 것이 그 짧은 대화에 담겨 있다.",
   gloss:[{w:"detain",ko:"구금하다"},{w:"land",ko:"착지하다, 먹혀들다"},
          {w:"indistinguishable",ko:"구별할 수 없는"},{w:"proposition",ko:"명제"},
          {w:"categorize",ko:"분류하다"},{w:"composed",ko:"침착한"},
          {w:"constraint",ko:"제약"}],
   qs:[
     {q:"What proposition does the retrieval of the device establish?",
      opts:["That the protagonist had been drugged during the interrogation",
            "That an experience indistinguishable from a dream can be an event",
            "That the antagonist can be defeated by ordinary means",
            "That the protagonist's memory is unreliable"],
      ans:1, exp:"2문단: 단순히 심문이 있었다는 사실이 아니라 '꿈과 구별되지 않는 경험도 사건일 수 있다'는 명제를 세운다."},
     {q:"Why does the author emphasize the ordering of the scene?",
      opts:["Because it appears before the film's premise is asserted",
            "Because it was filmed before the rest of the sequence",
            "Because it repeats material from the opening",
            "Because it is the last scene before a change of setting"],
      ans:0, exp:"3문단: 주장보다 앞서 놓였기에 증거가 아니라 '분류할 수 없는 경험'으로 기능하고, 의심이 만들어진다."},
     {q:"What is significant about the antagonist using two names?",
      opts:["It reveals that he has met the protagonist before.",
            "It treats control over identity as something within his authority.",
            "It shows that he is uncertain which name is correct.",
            "It signals that the interrogation is unofficial."],
      ans:1, exp:"마지막 문단: 그 구분을 '자기에게 권한이 있는 사안처럼' 다루며, 정체성 통제라는 주제가 여기에 압축되어 있다."}
   ]},

  /* ─────────── 4. 빨간 알약 ─────────── */
  {id:"mx-pill", exam:"TOEFL", type:"영화·주제", level:4,
   series:"🕶 매트릭스", title:"What Makes the Choice a Choice",
   topic:"빨간 알약 — 선택을 선택으로 만드는 조건",
   passage:"The scene in which the protagonist is offered two pills has become a cultural shorthand, usually for a decision between comfortable illusion and difficult truth. Read closely, the scene is careful about something the shorthand omits: whether a decision made under these conditions counts as one at all.\n\nThe offer is explicitly asymmetrical. The character making it states that he can only show the door, and that all he is offering is the truth — nothing more. He declines to describe what the truth is, on the stated ground that it cannot be told. The person choosing therefore has no information about one of the two outcomes, which is precisely the situation in which a choice is normally considered uninformed.\n\nThe film addresses this by attending to consent rather than to information. Nothing is done to the protagonist that he has not agreed to; he is warned that the decision is irreversible; he is given the alternative in a form that is genuinely available, and the film shows another character who later regrets not taking it. The scene's insistence on procedure is doing the work that disclosure cannot.\n\nWhether that is sufficient is left open, and the sequel material treats it as unsettled. What the scene establishes for the immediate story is narrower: the protagonist cannot afterwards claim that this was done to him. Everything that follows rests on that, including his authority to make claims about what others should do.",
   ko:"주인공이 알약 두 개를 제안받는 장면은 문화적 약칭이 되었다. 대개 편안한 환상과 힘든 진실 사이의 결정을 가리키는 말로 쓰인다. 꼼꼼히 읽으면 이 장면은 그 약칭이 빠뜨린 무언가에 대해 조심스럽다. 이런 조건에서 내린 결정을 과연 결정이라 할 수 있는가 하는 문제다.\n\n제안은 명시적으로 비대칭적이다. 제안하는 인물은 자신이 보여 줄 수 있는 것은 문뿐이며, 자신이 내주는 것은 진실이지 그 이상은 아니라고 말한다. 그는 그 진실이 무엇인지 서술하기를 거부하는데, 말로 전할 수 없다는 것이 그 이유로 제시된다. 그러므로 선택하는 사람은 두 결과 중 하나에 대해 아무 정보도 갖지 못하며, 이는 통상 정보 없는 선택으로 여겨지는 상황 그대로다.\n\n영화는 이 문제를 정보가 아니라 동의 쪽에서 다룬다. 주인공이 동의하지 않은 일은 그에게 행해지지 않고, 그 결정이 되돌릴 수 없다는 경고를 받으며, 대안은 실제로 택할 수 있는 형태로 주어진다. 그리고 영화는 나중에 그 대안을 택하지 않은 것을 후회하는 다른 인물을 보여 준다. 이 장면이 절차에 집착하는 것은 정보 공개가 할 수 없는 일을 대신 시키기 위해서다.\n\n그것으로 충분한지는 열린 채 남고, 후속작의 재료들은 이를 미결로 다룬다. 이 장면이 당장의 이야기를 위해 확립하는 것은 더 좁다. 주인공은 이후로 이것이 자신에게 '가해진' 일이라고 주장할 수 없다는 것. 뒤따르는 모든 것이 그 위에 서 있으며, 남들이 무엇을 해야 하는지에 대해 그가 주장할 자격도 거기에 포함된다.",
   gloss:[{w:"shorthand",ko:"약칭, 줄여 쓰는 표현"},{w:"asymmetrical",ko:"비대칭적인"},
          {w:"uninformed",ko:"정보 없는"},{w:"consent",ko:"동의"},
          {w:"irreversible",ko:"되돌릴 수 없는"},{w:"disclosure",ko:"정보 공개"},
          {w:"unsettled",ko:"미결의"}],
   qs:[
     {q:"Why does the author call the offer asymmetrical?",
      opts:["One pill is described in detail and the other is not.",
            "The chooser is given no information about one of the outcomes.",
            "Only one of the two options can be reversed.",
            "The offer is made in front of witnesses."],
      ans:1, exp:"2문단: 진실이 무엇인지는 서술되지 않으므로 두 결과 중 하나에 대해 아무 정보가 없다."},
     {q:"How does the film compensate for the missing information?",
      opts:["By having another character explain it later",
            "By attending carefully to consent and procedure",
            "By showing the outcome before the choice is made",
            "By allowing the decision to be reconsidered"],
      ans:1, exp:"3문단: 정보 대신 동의를 다루며, 경고·실질적 대안 등 절차가 '정보 공개가 할 수 없는 일'을 한다."},
     {q:"What does the scene establish for the rest of the story?",
      opts:["That the protagonist cannot later say this was done to him",
            "That the offer was made to several people at once",
            "That the alternative was never genuinely available",
            "That the protagonist had already guessed the truth"],
      ans:0, exp:"마지막 문단: 그 위에 뒤따르는 모든 것이, 그리고 그의 발언 자격이 서 있다."}
   ]},

  /* ─────────── 5. 컨스트럭트 ─────────── */
  {id:"mx-construct", exam:"TOEFL", type:"영화·구성", level:3,
   series:"🕶 매트릭스", title:"Turning a Lecture Into a Place",
   topic:"컨스트럭트 — 설명을 장소로 바꾸기",
   passage:"Roughly halfway through the film the premise must finally be explained, and the explanation is long: a history of the war, the function of the simulation, the condition of the world outside it. Delivered as dialogue in a room, this material would stop the film. The solution adopted is to give the explanation a location.\n\nThe two characters enter a featureless white space in which objects appear when named. The setting is justified within the story — it is a loading program — but its real function is compositional. It allows the explanation to be staged: a chair arrives when a chair is needed, a television when an image is required, and the ruined landscape can be shown rather than described. The scene converts a lecture into a series of demonstrations.\n\nThe space does further work. Because it is empty, it makes visible the distinction the film has been circling, between an environment and the information that generates one. The characters are standing in something that is transparently constructed, which prepares the audience to accept that the familiar city was constructed too. The point is made by the setting rather than by any line spoken in it.\n\nThe sequence is also where the film's tone shifts. Up to this stage the protagonist has been pursued and instructed; from here he is a student, and the remainder of the middle section is organized around training rather than escape.",
   ko:"영화의 대략 절반쯤에서 전제는 마침내 설명되어야 하고, 그 설명은 길다. 전쟁의 내력, 시뮬레이션의 기능, 그 바깥 세계의 상태까지. 이 재료를 방 안의 대화로 전달했다면 영화는 멈춰 섰을 것이다. 채택된 해법은 그 설명에 장소를 주는 것이다.\n\n두 인물은 이름을 부르면 물건이 나타나는, 아무 특징 없는 흰 공간으로 들어간다. 이 설정은 이야기 안에서 정당화되어 있다. 불러오기 프로그램이라는 것이다. 그러나 그 실제 기능은 구성상의 것이다. 그 덕에 설명을 연출할 수 있게 된다. 의자가 필요하면 의자가 도착하고, 영상이 필요하면 텔레비전이 도착하며, 폐허가 된 풍경은 서술되는 대신 보여질 수 있다. 이 장면은 강의를 일련의 시연으로 바꿔 놓는다.\n\n이 공간은 그 이상의 일도 한다. 비어 있기 때문에, 영화가 계속 맴돌던 구분 — 환경과 그 환경을 생성하는 정보 사이의 구분 — 을 눈에 보이게 만든다. 인물들은 지어졌다는 것이 훤히 드러나는 무언가 안에 서 있고, 이는 관객이 저 익숙한 도시 또한 지어진 것임을 받아들일 준비를 시킨다. 논점은 그 안에서 발화된 어떤 대사가 아니라 배경 자체가 만들어 낸다.\n\n이 시퀀스는 영화의 어조가 바뀌는 자리이기도 하다. 이 단계까지 주인공은 쫓기고 지시받는 인물이었다. 여기서부터 그는 학생이며, 중반부의 나머지는 도피가 아니라 훈련을 중심으로 조직된다.",
   gloss:[{w:"featureless",ko:"아무 특징 없는"},{w:"compositional",ko:"구성상의"},
          {w:"stage",ko:"연출하다, 무대에 올리다"},{w:"circle",ko:"맴돌다"},
          {w:"transparently",ko:"훤히 들여다보이게"},{w:"organize around",ko:"~를 중심으로 짜다"}],
   qs:[
     {q:"What problem does the white space solve?",
      opts:["It hides the characters from their pursuers.",
            "It prevents a long explanation from halting the film.",
            "It reduces the number of locations the production needed.",
            "It allows the protagonist to rest between fights."],
      ans:1, exp:"1문단: 방 안 대화로 전달했다면 영화가 멈췄을 설명에 장소를 주어 시연으로 바꾼다."},
     {q:"According to the passage, what does the emptiness of the space make visible?",
      opts:["The distinction between an environment and the information generating it",
            "The limits of the characters' abilities",
            "The passage of time inside the simulation",
            "The difference between the two main characters"],
      ans:0, exp:"3문단이 그대로 밝힌다 — 영화가 맴돌던 그 구분을 배경 자체가 눈에 보이게 만든다."},
     {q:"What change follows this sequence?",
      opts:["The protagonist becomes a student and training replaces escape.",
            "The antagonist disappears from the story.",
            "The film returns to the location of its opening.",
            "The explanation is revealed to have been false."],
      ans:0, exp:"마지막 문단: 쫓기고 지시받던 인물에서 학생으로 바뀌고, 중반부가 훈련 중심으로 재편된다."}
   ]},

  /* ─────────── 6. 훈련 프로그램 ─────────── */
  {id:"mx-training", exam:"TOEFL", type:"영화·주제", level:4,
   series:"🕶 매트릭스", title:"Learning as Upload, and What Survives It",
   topic:"훈련 시퀀스 — 학습을 내려받기로 다룰 때 남는 것",
   passage:"The training sequences propose that skill can be installed. Programs are loaded directly, and the protagonist announces that he now knows a martial art. The premise removes practice from the acquisition of ability, which ought to eliminate the standard structure of this kind of story, where a character earns competence over time.\n\nThe film keeps that structure anyway, and the contradiction is instructive. In the sparring scene that follows the upload, the protagonist is defeated repeatedly, and his instructor tells him that knowing the movements is not the same as performing them. The stated obstacle is not information but disposition: he is described as trying to hit rather than hitting, which locates the deficiency in something the upload did not transfer.\n\nThe jump program makes the same point more bluntly. The task is simple and requires no technique, and he fails it in front of an audience that expected him to. The failure is not a knowledge problem, and no program addresses it.\n\nWhat the sequences establish, then, is a division the rest of the film relies on. Anything that can be specified can be supplied instantly; whatever remains after that is the actual subject of the story. This is why the training section can be brief and largely comic while carrying real weight. It defines, by elimination, what the protagonist will have to do without assistance.",
   ko:"훈련 시퀀스는 기술을 설치할 수 있다는 전제를 내놓는다. 프로그램이 곧바로 내려받아지고, 주인공은 자신이 이제 어떤 무술을 안다고 선언한다. 이 전제는 능력의 습득에서 연습을 걷어 내며, 그렇다면 인물이 시간을 들여 역량을 얻어 가는 이런 종류의 이야기가 갖는 표준 구조도 사라져야 마땅하다.\n\n그런데 영화는 그 구조를 그대로 유지하고, 이 모순이 시사하는 바가 있다. 내려받기 직후의 대련 장면에서 주인공은 거듭 패하고, 그의 스승은 동작을 아는 것과 그것을 해내는 것은 다르다고 말한다. 명시된 장애물은 정보가 아니라 태도다. 그는 때리는 것이 아니라 때리려 하고 있다고 서술되는데, 이는 결함의 자리를 내려받기가 옮겨 주지 못한 무언가에 놓는다.\n\n점프 프로그램은 같은 논점을 더 노골적으로 만든다. 과제는 단순하고 기술을 요구하지 않는데, 그는 그가 실패하리라 예상한 관객 앞에서 실패한다. 이 실패는 지식의 문제가 아니고, 어떤 프로그램도 그것을 다루지 않는다.\n\n그러므로 이 시퀀스들이 확립하는 것은 영화의 나머지가 기대는 하나의 구분이다. 명세할 수 있는 것은 무엇이든 즉시 공급될 수 있고, 그러고도 남는 것이 이 이야기의 진짜 소재다. 훈련 대목이 짧고 대체로 희극적이면서도 실질적인 무게를 지니는 이유가 여기에 있다. 그것은 주인공이 아무 도움 없이 해내야 할 일이 무엇인지를 소거법으로 규정한다.",
   gloss:[{w:"install",ko:"설치하다"},{w:"acquisition",ko:"습득"},
          {w:"instructive",ko:"시사하는 바가 있는"},{w:"disposition",ko:"태도, 마음가짐"},
          {w:"deficiency",ko:"결함, 부족"},{w:"bluntly",ko:"노골적으로"},
          {w:"by elimination",ko:"소거법으로"}],
   qs:[
     {q:"Why does the author call the retained structure a contradiction?",
      opts:["The uploads are shown to fail more often than they succeed.",
            "Removing practice should have eliminated the earn-your-competence structure.",
            "The instructor gives advice that conflicts with the film's premise.",
            "The protagonist never uses the martial art again."],
      ans:1, exp:"1문단 마지막: 연습이 걷힌 전제라면 시간을 들여 역량을 얻는 표준 구조도 사라져야 하는데 영화는 그것을 유지한다."},
     {q:"Where does the sparring scene locate the protagonist's deficiency?",
      opts:["In the quality of the program that was loaded",
            "In something the upload did not transfer",
            "In his physical condition after leaving the pod",
            "In his unfamiliarity with the instructor"],
      ans:1, exp:"2문단: 장애물은 정보가 아니라 태도이며, 결함은 '내려받기가 옮겨 주지 못한 무언가'에 있다."},
     {q:"What division do the training sequences establish?",
      opts:["Between what can be specified and supplied, and what remains",
            "Between the characters who were born free and those who were not",
            "Between programs that are safe and programs that are dangerous",
            "Between training inside the simulation and training outside it"],
      ans:0, exp:"마지막 문단: 명세 가능한 것은 즉시 공급되고, 그러고도 남는 것이 이야기의 진짜 소재라는 구분이다."}
   ]}

]);
