// TOEFL 빈출 어휘 데이터셋
// 각 항목: { word, pos(품사), en(영영 뜻), ko(한글 뜻), ex(예문) }
window.TOEFL_WORDS = [
  { word: "abandon", pos: "v.", en: "to leave completely and finally; to give up", ko: "버리다, 포기하다", ex: "The crew had to abandon the sinking ship." },
  { word: "abstract", pos: "adj.", en: "existing in thought or as an idea but not concrete", ko: "추상적인", ex: "Abstract concepts like justice are hard to define." },
  { word: "accumulate", pos: "v.", en: "to gather or collect a large amount gradually", ko: "축적하다, 모으다", ex: "Dust began to accumulate on the old books." },
  { word: "acquire", pos: "v.", en: "to obtain or get something for oneself", ko: "습득하다, 획득하다", ex: "Children acquire language rapidly in early years." },
  { word: "adequate", pos: "adj.", en: "enough in quantity or good enough in quality", ko: "충분한, 적절한", ex: "The salary is adequate for basic living expenses." },
  { word: "advocate", pos: "v.", en: "to publicly support or recommend a cause", ko: "옹호하다, 지지하다", ex: "She advocates for stronger environmental laws." },
  { word: "aesthetic", pos: "adj.", en: "concerned with beauty or the appreciation of it", ko: "미적인, 심미적인", ex: "The building has great aesthetic appeal." },
  { word: "aggregate", pos: "n.", en: "a whole formed by combining several elements", ko: "총계, 집합체", ex: "The aggregate of all scores determines the ranking." },
  { word: "allocate", pos: "v.", en: "to distribute resources for a particular purpose", ko: "할당하다, 배분하다", ex: "The government allocated funds for education." },
  { word: "ambiguous", pos: "adj.", en: "open to more than one interpretation; unclear", ko: "모호한, 애매한", ex: "His ambiguous reply confused everyone." },
  { word: "analogy", pos: "n.", en: "a comparison between two things for explanation", ko: "유추, 비유", ex: "She drew an analogy between the brain and a computer." },
  { word: "anticipate", pos: "v.", en: "to expect or predict something in advance", ko: "예상하다, 기대하다", ex: "We anticipate a rise in demand next quarter." },
  { word: "arbitrary", pos: "adj.", en: "based on random choice rather than reason", ko: "임의적인, 제멋대로인", ex: "The decision seemed arbitrary and unfair." },
  { word: "articulate", pos: "v.", en: "to express an idea clearly and effectively", ko: "명확히 표현하다", ex: "She articulated her argument with precision." },
  { word: "assess", pos: "v.", en: "to evaluate or judge the value of something", ko: "평가하다, 사정하다", ex: "Teachers assess students at the end of each term." },
  { word: "attribute", pos: "v.", en: "to regard something as caused by a person or thing", ko: "~의 탓으로 돌리다", ex: "She attributes her success to hard work." },
  { word: "augment", pos: "v.", en: "to make something greater by adding to it", ko: "증대시키다, 늘리다", ex: "He took a second job to augment his income." },
  { word: "authentic", pos: "adj.", en: "genuine; of undisputed origin", ko: "진짜의, 진정한", ex: "The museum displays authentic ancient artifacts." },
  { word: "benevolent", pos: "adj.", en: "well-meaning and kindly", ko: "자비로운, 인정 많은", ex: "The benevolent donor funded the new library." },
  { word: "bias", pos: "n.", en: "prejudice in favor of or against something", ko: "편견, 편향", ex: "The report showed a clear bias toward one side." },
  { word: "coherent", pos: "adj.", en: "logical and consistent; clearly connected", ko: "일관된, 논리 정연한", ex: "She gave a coherent explanation of the theory." },
  { word: "coincide", pos: "v.", en: "to happen at the same time or agree exactly", ko: "동시에 일어나다, 일치하다", ex: "Our vacations happened to coincide this year." },
  { word: "compel", pos: "v.", en: "to force or oblige someone to do something", ko: "강요하다, ~하게 만들다", ex: "Illness compelled him to cancel the trip." },
  { word: "complement", pos: "v.", en: "to complete or enhance by adding something", ko: "보완하다, 보충하다", ex: "The wine complements the meal perfectly." },
  { word: "comprehensive", pos: "adj.", en: "complete and including everything necessary", ko: "포괄적인, 종합적인", ex: "The book offers a comprehensive review of the topic." },
  { word: "conceive", pos: "v.", en: "to form an idea or plan in the mind", ko: "생각해내다, 상상하다", ex: "It is hard to conceive of a world without the internet." },
  { word: "conform", pos: "v.", en: "to comply with rules, standards, or conventions", ko: "따르다, 순응하다", ex: "All products must conform to safety standards." },
  { word: "consecutive", pos: "adj.", en: "following one after another without interruption", ko: "연속적인", ex: "It rained for five consecutive days." },
  { word: "constitute", pos: "v.", en: "to be a part of or make up a whole", ko: "구성하다, ~이 되다", ex: "Women constitute half of the workforce." },
  { word: "contemporary", pos: "adj.", en: "belonging to the present time; modern", ko: "현대의, 동시대의", ex: "The gallery features contemporary art." },
  { word: "contradict", pos: "v.", en: "to assert the opposite; to be inconsistent with", ko: "모순되다, 반박하다", ex: "His actions contradict his words." },
  { word: "convey", pos: "v.", en: "to communicate or make an idea known", ko: "전달하다, 전하다", ex: "Words alone cannot convey how grateful I am." },
  { word: "credible", pos: "adj.", en: "able to be believed; convincing", ko: "믿을 수 있는, 신뢰할 만한", ex: "The witness gave credible testimony." },
  { word: "cumulative", pos: "adj.", en: "increasing by successive additions", ko: "누적되는", ex: "The cumulative effect of stress harmed his health." },
  { word: "deduce", pos: "v.", en: "to reach a conclusion by reasoning", ko: "추론하다, 연역하다", ex: "From the clues, she deduced the culprit." },
  { word: "deficient", pos: "adj.", en: "not having enough of a needed quality", ko: "부족한, 결핍된", ex: "His diet is deficient in vitamins." },
  { word: "deliberate", pos: "adj.", en: "done consciously and intentionally", ko: "고의적인, 신중한", ex: "It was a deliberate attempt to mislead us." },
  { word: "denote", pos: "v.", en: "to be a sign of; to indicate or refer to", ko: "나타내다, 의미하다", ex: "A red light denotes danger." },
  { word: "deteriorate", pos: "v.", en: "to become progressively worse", ko: "악화되다, 나빠지다", ex: "Her health deteriorated over the winter." },
  { word: "diminish", pos: "v.", en: "to make or become less in size or importance", ko: "줄어들다, 감소시키다", ex: "The medicine diminished the pain." },
  { word: "distinct", pos: "adj.", en: "recognizably different in nature; clear", ko: "뚜렷한, 별개의", ex: "There are two distinct species in this region." },
  { word: "diverse", pos: "adj.", en: "showing a great deal of variety; very different", ko: "다양한", ex: "The city has a diverse population." },
  { word: "dominant", pos: "adj.", en: "most important, powerful, or influential", ko: "지배적인, 우세한", ex: "English is the dominant language of business." },
  { word: "elaborate", pos: "adj.", en: "involving many carefully arranged details", ko: "정교한, 상세한", ex: "They planned an elaborate ceremony." },
  { word: "elicit", pos: "v.", en: "to draw out a response or reaction", ko: "이끌어내다, 유도하다", ex: "The question elicited an angry response." },
  { word: "eloquent", pos: "adj.", en: "fluent and persuasive in speaking or writing", ko: "웅변의, 유창한", ex: "She gave an eloquent speech." },
  { word: "emerge", pos: "v.", en: "to become apparent or come into existence", ko: "나타나다, 부상하다", ex: "New evidence emerged during the trial." },
  { word: "empirical", pos: "adj.", en: "based on observation or experiment, not theory", ko: "경험적인, 실증적인", ex: "The claim lacks empirical support." },
  { word: "endure", pos: "v.", en: "to suffer patiently; to last over time", ko: "견디다, 지속되다", ex: "The tradition has endured for centuries." },
  { word: "enhance", pos: "v.", en: "to intensify or improve the quality of", ko: "향상시키다, 높이다", ex: "Good lighting enhances the photograph." },
  { word: "explicit", pos: "adj.", en: "stated clearly and in detail; leaving no doubt", ko: "명백한, 명시적인", ex: "She gave explicit instructions." },
  { word: "facilitate", pos: "v.", en: "to make an action or process easier", ko: "촉진하다, 용이하게 하다", ex: "The new software facilitates collaboration." },
  { word: "feasible", pos: "adj.", en: "possible to do easily or conveniently", ko: "실현 가능한", ex: "Is it feasible to finish by Friday?" },
  { word: "fluctuate", pos: "v.", en: "to rise and fall irregularly in number or amount", ko: "변동하다, 오르내리다", ex: "Prices fluctuate with the seasons." },
  { word: "fundamental", pos: "adj.", en: "forming a necessary base or core; essential", ko: "근본적인, 기본적인", ex: "Trust is fundamental to any relationship." },
  { word: "hypothesis", pos: "n.", en: "a proposed explanation to be tested", ko: "가설", ex: "The experiment confirmed her hypothesis." },
  { word: "impose", pos: "v.", en: "to force something to be accepted or established", ko: "부과하다, 강요하다", ex: "The government imposed new taxes." },
  { word: "incentive", pos: "n.", en: "something that motivates or encourages action", ko: "동기, 유인책", ex: "Bonuses are an incentive to work harder." },
  { word: "inevitable", pos: "adj.", en: "certain to happen; unavoidable", ko: "불가피한, 필연적인", ex: "Change is inevitable in life." },
  { word: "infer", pos: "v.", en: "to conclude from evidence and reasoning", ko: "추론하다", ex: "We can infer his mood from his tone." },
  { word: "innovative", pos: "adj.", en: "featuring new methods or ideas", ko: "혁신적인", ex: "The company is known for innovative products." },
  { word: "integral", pos: "adj.", en: "necessary to make a whole complete; essential", ko: "필수적인, 없어서는 안 될", ex: "Practice is integral to mastery." },
  { word: "intricate", pos: "adj.", en: "very complicated or detailed", ko: "복잡한, 정교한", ex: "The watch has an intricate mechanism." },
  { word: "intrinsic", pos: "adj.", en: "belonging naturally; essential", ko: "본질적인, 고유한", ex: "Gold has intrinsic value." },
  { word: "justify", pos: "v.", en: "to show or prove to be right or reasonable", ko: "정당화하다", ex: "Nothing can justify such cruelty." },
  { word: "legitimate", pos: "adj.", en: "conforming to the law or to accepted rules", ko: "합법적인, 정당한", ex: "She has a legitimate claim to the property." },
  { word: "manipulate", pos: "v.", en: "to control or influence cleverly or unfairly", ko: "조종하다, 다루다", ex: "He manipulated the data to fit his theory." },
  { word: "meticulous", pos: "adj.", en: "showing great attention to detail; very careful", ko: "꼼꼼한, 세심한", ex: "She kept meticulous records." },
  { word: "mitigate", pos: "v.", en: "to make less severe, serious, or painful", ko: "완화하다, 경감하다", ex: "Planting trees can mitigate climate change." },
  { word: "notion", pos: "n.", en: "a belief or idea about something", ko: "개념, 관념", ex: "He has an odd notion of fairness." },
  { word: "obscure", pos: "adj.", en: "not clearly understood or well known", ko: "모호한, 잘 알려지지 않은", ex: "The poem's meaning remains obscure." },
  { word: "paradox", pos: "n.", en: "a statement that seems contradictory but may be true", ko: "역설", ex: "It is a paradox that standing still can move you forward." },
  { word: "persist", pos: "v.", en: "to continue firmly despite difficulty", ko: "지속하다, 고집하다", ex: "If symptoms persist, see a doctor." },
  { word: "phenomenon", pos: "n.", en: "a fact or event observed to exist or happen", ko: "현상", ex: "The aurora is a natural phenomenon." },
  { word: "plausible", pos: "adj.", en: "seeming reasonable or probable", ko: "그럴듯한, 타당한", ex: "That is a plausible explanation." },
  { word: "precede", pos: "v.", en: "to come or go before in time or order", ko: "앞서다, 선행하다", ex: "A short introduction precedes each chapter." },
  { word: "predominant", pos: "adj.", en: "present as the strongest or main element", ko: "지배적인, 주된", ex: "Blue is the predominant color here." },
  { word: "prevail", pos: "v.", en: "to prove more powerful; to be widespread", ko: "만연하다, 우세하다", ex: "Justice will prevail in the end." },
  { word: "profound", pos: "adj.", en: "very great, intense, or deeply felt", ko: "심오한, 깊은", ex: "The book had a profound influence on me." },
  { word: "prohibit", pos: "v.", en: "to formally forbid by law or rule", ko: "금지하다", ex: "Smoking is prohibited in this building." },
  { word: "prominent", pos: "adj.", en: "important, famous, or easily noticed", ko: "저명한, 두드러진", ex: "She is a prominent scientist." },
  { word: "rational", pos: "adj.", en: "based on reason or logic", ko: "이성적인, 합리적인", ex: "Try to make a rational decision." },
  { word: "reinforce", pos: "v.", en: "to strengthen or support something", ko: "강화하다, 보강하다", ex: "The results reinforce our earlier findings." },
  { word: "reluctant", pos: "adj.", en: "unwilling and hesitant to do something", ko: "꺼리는, 마지못한", ex: "He was reluctant to admit his mistake." },
  { word: "resemble", pos: "v.", en: "to be similar to or look like something", ko: "닮다, 비슷하다", ex: "The twins resemble each other closely." },
  { word: "resilient", pos: "adj.", en: "able to recover quickly from difficulties", ko: "회복력 있는, 탄력적인", ex: "Children are remarkably resilient." },
  { word: "scarce", pos: "adj.", en: "insufficient for demand; rarely found", ko: "부족한, 드문", ex: "Fresh water is scarce in the desert." },
  { word: "scrutinize", pos: "v.", en: "to examine closely and critically", ko: "면밀히 조사하다", ex: "The auditor scrutinized every receipt." },
  { word: "simultaneous", pos: "adj.", en: "occurring at the same time", ko: "동시의", ex: "The events were simultaneous." },
  { word: "sophisticated", pos: "adj.", en: "highly developed, complex, or refined", ko: "정교한, 세련된", ex: "It is a sophisticated piece of technology." },
  { word: "subsequent", pos: "adj.", en: "coming after something in time; following", ko: "그 다음의, 이후의", ex: "Subsequent events proved him right." },
  { word: "substantial", pos: "adj.", en: "of considerable importance, size, or worth", ko: "상당한, 실질적인", ex: "They made a substantial profit." },
  { word: "sufficient", pos: "adj.", en: "enough; adequate for the purpose", ko: "충분한", ex: "We have sufficient supplies for a week." },
  { word: "susceptible", pos: "adj.", en: "likely to be affected by something", ko: "영향받기 쉬운, 취약한", ex: "Young plants are susceptible to frost." },
  { word: "tentative", pos: "adj.", en: "not certain or fixed; provisional", ko: "잠정적인, 시험적인", ex: "We made tentative plans for July." },
  { word: "transform", pos: "v.", en: "to change completely in form or nature", ko: "변형시키다, 완전히 바꾸다", ex: "The internet transformed how we communicate." },
  { word: "underlying", pos: "adj.", en: "existing beneath the surface; fundamental", ko: "근본적인, 기저에 있는", ex: "We must address the underlying causes." },
  { word: "undermine", pos: "v.", en: "to weaken or damage gradually", ko: "약화시키다, 훼손하다", ex: "Constant criticism can undermine confidence." },
  { word: "utilize", pos: "v.", en: "to make practical and effective use of", ko: "활용하다, 이용하다", ex: "We utilize solar energy to heat the water." },
  { word: "viable", pos: "adj.", en: "capable of working successfully; feasible", ko: "실행 가능한, 실용적인", ex: "Is this a viable business plan?" },
  { word: "vigorous", pos: "adj.", en: "strong, energetic, and forceful", ko: "활발한, 격렬한", ex: "He is a vigorous supporter of reform." },
  { word: "vital", pos: "adj.", en: "absolutely necessary; essential to life", ko: "필수적인, 매우 중요한", ex: "Water is vital for survival." }
];
