// TOEFL 빈출 어휘 데이터셋 (난이도별: level 1=기초, 2=중급, 3=고급)
// 각 항목: { word, pos, en, ko, ex, level }
window.TOEFL_WORDS = [
  {"word":"abandon","pos":"v.","en":"to leave completely and finally","ko":"버리다, 포기하다","ex":"The crew had to abandon the sinking ship.","level":2},
  {"word":"abnormal","pos":"adj.","en":"different from what is normal","ko":"비정상적인","ex":"The test revealed abnormal levels of the chemical.","level":3},
  {"word":"abolish","pos":"v.","en":"to formally end a law or system","ko":"폐지하다","ex":"The government voted to abolish the old tax.","level":3},
  {"word":"absorb","pos":"v.","en":"to take in liquid or knowledge","ko":"흡수하다","ex":"Plants absorb water through their roots.","level":2},
  {"word":"abstract","pos":"adj.","en":"based on ideas, not concrete things","ko":"추상적인","ex":"Philosophy often deals with abstract concepts like justice.","level":2},
  {"word":"abundant","pos":"adj.","en":"existing in large quantities","ko":"풍부한","ex":"The region has abundant natural resources.","level":2},
  {"word":"accelerate","pos":"v.","en":"to make something happen faster","ko":"가속하다","ex":"New technology can accelerate economic growth.","level":2},
  {"word":"accessible","pos":"adj.","en":"able to be reached or obtained","ko":"접근 가능한","ex":"The museum is accessible by public transport.","level":2},
  {"word":"accommodate","pos":"v.","en":"to provide space or adjust for","ko":"수용하다","ex":"The hall can accommodate five hundred people.","level":3},
  {"word":"accumulate","pos":"v.","en":"to gather or increase over time","ko":"축적하다","ex":"Snow began to accumulate on the mountain peaks.","level":2},
  {"word":"accurate","pos":"adj.","en":"correct and without errors","ko":"정확한","ex":"Scientists need accurate measurements for the experiment.","level":1},
  {"word":"acknowledge","pos":"v.","en":"to accept or admit something","ko":"인정하다","ex":"The scientist acknowledged the limitations of the study.","level":2},
  {"word":"acquire","pos":"v.","en":"to gain or obtain something","ko":"획득하다","ex":"Children acquire language skills at an early age.","level":2},
  {"word":"adapt","pos":"v.","en":"to adjust to new conditions","ko":"적응하다","ex":"Animals must adapt to survive in harsh climates.","level":1},
  {"word":"adequate","pos":"adj.","en":"enough for a purpose","ko":"충분한, 적절한","ex":"The workers demanded adequate safety equipment.","level":2},
  {"word":"adjacent","pos":"adj.","en":"next to or near something","ko":"인접한","ex":"The library is adjacent to the science building.","level":3},
  {"word":"advance","pos":"n.","en":"progress or development","ko":"진보, 발전","ex":"Medical advances have extended human life.","level":1},
  {"word":"advocate","pos":"v.","en":"to publicly support an idea","ko":"옹호하다, 지지하다","ex":"Many scientists advocate reducing carbon emissions.","level":3},
  {"word":"aesthetic","pos":"adj.","en":"relating to beauty or art","ko":"미적인","ex":"The building has great aesthetic appeal.","level":3},
  {"word":"affect","pos":"v.","en":"to have an influence on","ko":"영향을 미치다","ex":"Pollution can seriously affect human health.","level":1},
  {"word":"aggregate","pos":"n.","en":"a total formed from parts","ko":"총계, 집합체","ex":"The aggregate of all donations exceeded expectations.","level":3},
  {"word":"allocate","pos":"v.","en":"to distribute for a purpose","ko":"할당하다","ex":"The government will allocate funds for education.","level":3},
  {"word":"alter","pos":"v.","en":"to change or modify","ko":"바꾸다, 변경하다","ex":"Climate change may alter migration patterns.","level":2},
  {"word":"ambiguous","pos":"adj.","en":"having more than one meaning","ko":"모호한","ex":"The instructions were ambiguous and confusing.","level":3},
  {"word":"amplify","pos":"v.","en":"to make larger or stronger","ko":"증폭시키다","ex":"Social media can amplify public opinion.","level":3},
  {"word":"analyze","pos":"v.","en":"to examine something in detail","ko":"분석하다","ex":"Researchers analyze data to find patterns.","level":1},
  {"word":"ancient","pos":"adj.","en":"belonging to the distant past","ko":"고대의","ex":"Archaeologists study ancient civilizations.","level":1},
  {"word":"annual","pos":"adj.","en":"happening once every year","ko":"연간의, 매년의","ex":"The company publishes an annual report.","level":1},
  {"word":"anticipate","pos":"v.","en":"to expect something to happen","ko":"예상하다","ex":"Economists anticipate a rise in prices.","level":2},
  {"word":"apparatus","pos":"n.","en":"equipment for a specific purpose","ko":"기구, 장치","ex":"The lab installed new scientific apparatus.","level":3},
  {"word":"apparent","pos":"adj.","en":"clearly seen or understood","ko":"명백한","ex":"It became apparent that the plan had failed.","level":2},
  {"word":"appreciate","pos":"v.","en":"to recognize the value of","ko":"인정하다, 감사하다","ex":"Students appreciate clear explanations from teachers.","level":1},
  {"word":"approach","pos":"n.","en":"a way of dealing with something","ko":"접근법","ex":"The scientist used a new approach to solve the problem.","level":1},
  {"word":"appropriate","pos":"adj.","en":"suitable for a situation","ko":"적절한","ex":"Formal clothing is appropriate for the interview.","level":2},
  {"word":"arbitrary","pos":"adj.","en":"based on random choice, not reason","ko":"임의적인","ex":"The rules seemed arbitrary and unfair.","level":3},
  {"word":"arise","pos":"v.","en":"to come into existence or happen","ko":"발생하다","ex":"Problems may arise during the experiment.","level":2},
  {"word":"articulate","pos":"v.","en":"to express ideas clearly","ko":"명확히 표현하다","ex":"She could articulate her arguments with confidence.","level":3},
  {"word":"aspect","pos":"n.","en":"one part or feature of something","ko":"측면","ex":"We must consider every aspect of the problem.","level":1},
  {"word":"assemble","pos":"v.","en":"to gather or put together","ko":"모으다, 조립하다","ex":"Workers assemble the parts on the production line.","level":2},
  {"word":"assert","pos":"v.","en":"to state firmly as true","ko":"주장하다","ex":"The author asserts that history repeats itself.","level":3},
  {"word":"assess","pos":"v.","en":"to evaluate or judge","ko":"평가하다","ex":"Teachers assess students through regular exams.","level":2},
  {"word":"assign","pos":"v.","en":"to give a task or duty","ko":"할당하다, 배정하다","ex":"The professor will assign essays next week.","level":1},
  {"word":"associate","pos":"v.","en":"to connect in the mind","ko":"연관시키다","ex":"We often associate spring with new beginnings.","level":2},
  {"word":"assume","pos":"v.","en":"to accept as true without proof","ko":"가정하다","ex":"We should not assume the results are correct.","level":1},
  {"word":"assure","pos":"v.","en":"to tell someone confidently","ko":"확신시키다, 보장하다","ex":"The doctor assured the patient of a full recovery.","level":2},
  {"word":"attain","pos":"v.","en":"to achieve or reach a goal","ko":"달성하다","ex":"Few students attain such high scores.","level":3},
  {"word":"attribute","pos":"v.","en":"to explain something as caused by","ko":"~의 탓으로 돌리다","ex":"Experts attribute the decline to overfishing.","level":3},
  {"word":"authentic","pos":"adj.","en":"genuine and real","ko":"진짜의, 진정한","ex":"The museum displays authentic Roman artifacts.","level":2},
  {"word":"authority","pos":"n.","en":"the power to make decisions","ko":"권위, 권한","ex":"The committee has the authority to approve budgets.","level":1},
  {"word":"available","pos":"adj.","en":"able to be used or obtained","ko":"이용 가능한","ex":"More information is available on the website.","level":1},
  {"word":"aware","pos":"adj.","en":"having knowledge of something","ko":"인식하고 있는","ex":"People are increasingly aware of environmental issues.","level":1},
  {"word":"balance","pos":"n.","en":"an even distribution of weight","ko":"균형","ex":"Ecosystems depend on a delicate balance.","level":1},
  {"word":"barrier","pos":"n.","en":"something that blocks progress","ko":"장벽, 장애물","ex":"Language can be a barrier to communication.","level":2},
  {"word":"benchmark","pos":"n.","en":"a standard for comparison","ko":"기준, 척도","ex":"The test serves as a benchmark for progress.","level":3},
  {"word":"beneficial","pos":"adj.","en":"producing good or helpful results","ko":"유익한","ex":"Regular exercise is beneficial to health.","level":2},
  {"word":"bias","pos":"n.","en":"an unfair preference or prejudice","ko":"편견","ex":"The study was criticized for its bias.","level":3},
  {"word":"biological","pos":"adj.","en":"relating to living organisms","ko":"생물학적인","ex":"The disease has a biological cause.","level":2},
  {"word":"boost","pos":"v.","en":"to increase or improve","ko":"증진시키다","ex":"Advertising helped boost the company's sales.","level":2},
  {"word":"boundary","pos":"n.","en":"a line marking a limit","ko":"경계","ex":"The river forms the boundary between the two nations.","level":2},
  {"word":"brief","pos":"adj.","en":"lasting a short time","ko":"간단한, 짧은","ex":"The professor gave a brief overview of the topic.","level":1},
  {"word":"brilliant","pos":"adj.","en":"extremely clever or impressive","ko":"뛰어난, 훌륭한","ex":"Einstein was a brilliant physicist.","level":1},
  {"word":"brittle","pos":"adj.","en":"hard but easily broken","ko":"부서지기 쉬운","ex":"Old bones can become brittle and fragile.","level":3},
  {"word":"broad","pos":"adj.","en":"wide in range or scope","ko":"넓은, 광범위한","ex":"The course covers a broad range of subjects.","level":1},
  {"word":"bulk","pos":"n.","en":"the main or largest part","ko":"대부분, 부피","ex":"The bulk of the population lives in cities.","level":2},
  {"word":"burden","pos":"n.","en":"a heavy load or difficult duty","ko":"부담, 짐","ex":"Debt can be a serious financial burden.","level":2},
  {"word":"candid","pos":"adj.","en":"honest and straightforward","ko":"솔직한","ex":"He gave a candid account of the failure.","level":3},
  {"word":"capable","pos":"adj.","en":"having ability or skill to do something","ko":"능력 있는, 유능한","ex":"She is capable of solving difficult problems.","level":1},
  {"word":"capitulate","pos":"v.","en":"to surrender or give in","ko":"항복하다, 굴복하다","ex":"The army refused to capitulate to the enemy.","level":3},
  {"word":"cause","pos":"n.","en":"a thing that makes something happen","ko":"원인, 이유","ex":"Poor diet is a common cause of illness.","level":1},
  {"word":"century","pos":"n.","en":"a period of one hundred years","ko":"세기, 100년","ex":"The building has stood for over a century.","level":1},
  {"word":"challenge","pos":"n.","en":"a difficult task that tests ability","ko":"도전, 난제","ex":"Learning a new language is a real challenge.","level":1},
  {"word":"characteristic","pos":"n.","en":"a typical feature or quality","ko":"특징, 특성","ex":"Patience is a key characteristic of good teachers.","level":1},
  {"word":"circumvent","pos":"v.","en":"to find a way around an obstacle","ko":"우회하다, 회피하다","ex":"They tried to circumvent the strict rules.","level":3},
  {"word":"climate","pos":"n.","en":"the usual weather of a region","ko":"기후","ex":"The climate here is warm and humid.","level":1},
  {"word":"coalesce","pos":"v.","en":"to come together to form one","ko":"합체하다, 융합하다","ex":"The small groups began to coalesce into one movement.","level":3},
  {"word":"cogent","pos":"adj.","en":"clear, logical, and convincing","ko":"설득력 있는","ex":"She made a cogent argument for reform.","level":3},
  {"word":"coherent","pos":"adj.","en":"logical and clearly connected","ko":"일관된, 논리 정연한","ex":"She gave a coherent explanation of the theory.","level":2},
  {"word":"collapse","pos":"v.","en":"to fall down suddenly","ko":"붕괴하다, 무너지다","ex":"The bridge began to collapse under the weight.","level":2},
  {"word":"combine","pos":"v.","en":"to join or mix things together","ko":"결합하다, 합치다","ex":"The chef combined several spices in the dish.","level":1},
  {"word":"commensurate","pos":"adj.","en":"proportionate in size or degree","ko":"상응하는, 비례하는","ex":"The salary is commensurate with experience.","level":3},
  {"word":"commodity","pos":"n.","en":"a raw material or product for trade","ko":"상품, 원자재","ex":"Oil is a valuable commodity on the market.","level":2},
  {"word":"common","pos":"adj.","en":"happening often; shared by many","ko":"흔한, 공통의","ex":"It is common to feel nervous before exams.","level":1},
  {"word":"community","pos":"n.","en":"a group of people living together","ko":"공동체, 지역사회","ex":"The community organized a cleanup event.","level":1},
  {"word":"compensate","pos":"v.","en":"to make up for a loss","ko":"보상하다","ex":"The company will compensate workers for extra hours.","level":2},
  {"word":"competent","pos":"adj.","en":"having sufficient skill or ability","ko":"유능한, 능숙한","ex":"He proved to be a competent manager.","level":2},
  {"word":"complacent","pos":"adj.","en":"self-satisfied and unaware of dangers","ko":"자기만족의, 안일한","ex":"We must not become complacent about safety.","level":3},
  {"word":"complex","pos":"adj.","en":"having many connected parts; complicated","ko":"복잡한","ex":"The brain is a highly complex organ.","level":1},
  {"word":"comprehensive","pos":"adj.","en":"including all or nearly all elements","ko":"포괄적인, 종합적인","ex":"The report gave a comprehensive overview of the issue.","level":2},
  {"word":"conceal","pos":"v.","en":"to hide from view or notice","ko":"숨기다, 감추다","ex":"He tried to conceal his disappointment.","level":2},
  {"word":"concept","pos":"n.","en":"an abstract idea or notion","ko":"개념","ex":"The concept of gravity was hard to grasp.","level":1},
  {"word":"conciliatory","pos":"adj.","en":"intended to make peace","ko":"회유적인, 달래는","ex":"He adopted a conciliatory tone in the meeting.","level":3},
  {"word":"conclude","pos":"v.","en":"to reach a decision or end","ko":"결론짓다, 마치다","ex":"The researchers conclude that exercise improves memory.","level":2},
  {"word":"condition","pos":"n.","en":"the state something is in","ko":"상태, 조건","ex":"The old car is in poor condition.","level":1},
  {"word":"conform","pos":"v.","en":"to comply with rules or standards","ko":"따르다, 순응하다","ex":"All products must conform to safety regulations.","level":2},
  {"word":"congenial","pos":"adj.","en":"pleasant and agreeable","ko":"마음이 맞는, 쾌적한","ex":"They worked in a congenial atmosphere.","level":3},
  {"word":"consequence","pos":"n.","en":"a result of an action","ko":"결과, 영향","ex":"Every decision has a consequence.","level":2},
  {"word":"consider","pos":"v.","en":"to think about carefully","ko":"고려하다","ex":"We must consider all the options before deciding.","level":1},
  {"word":"conspicuous","pos":"adj.","en":"clearly visible; attracting attention","ko":"눈에 띄는, 두드러진","ex":"His absence was conspicuous at the meeting.","level":3},
  {"word":"constitute","pos":"v.","en":"to form or make up a whole","ko":"구성하다, ~이 되다","ex":"Women constitute half of the workforce.","level":2},
  {"word":"constrain","pos":"v.","en":"to limit or restrict","ko":"제한하다, 억제하다","ex":"A tight budget can constrain research efforts.","level":2},
  {"word":"contain","pos":"v.","en":"to hold or include within","ko":"포함하다, 담고 있다","ex":"This bottle can contain two liters of water.","level":1},
  {"word":"contemporary","pos":"adj.","en":"belonging to the present time","ko":"현대의, 동시대의","ex":"The museum features contemporary art.","level":2},
  {"word":"contradict","pos":"v.","en":"to assert the opposite of","ko":"모순되다, 반박하다","ex":"The new data contradict earlier findings.","level":2},
  {"word":"contribute","pos":"v.","en":"to give a part to a whole","ko":"기여하다, 기부하다","ex":"Many factors contribute to climate change.","level":2},
  {"word":"controversy","pos":"n.","en":"public disagreement over an issue","ko":"논란, 논쟁","ex":"The policy sparked a major controversy.","level":2},
  {"word":"convert","pos":"v.","en":"to change from one form to another","ko":"전환하다, 변환하다","ex":"Plants convert sunlight into energy.","level":2},
  {"word":"correspond","pos":"v.","en":"to match or be similar to","ko":"일치하다, 상응하다","ex":"The results correspond to our predictions.","level":2},
  {"word":"corroborate","pos":"v.","en":"to confirm or support with evidence","ko":"확증하다, 입증하다","ex":"Witnesses corroborate the victim's story.","level":3},
  {"word":"create","pos":"v.","en":"to make something new","ko":"창조하다, 만들다","ex":"Artists create works that inspire people.","level":1},
  {"word":"crucial","pos":"adj.","en":"extremely important; decisive","ko":"결정적인, 중대한","ex":"Sleep is crucial for good health.","level":2},
  {"word":"cryptic","pos":"adj.","en":"having a hidden or obscure meaning","ko":"수수께끼 같은, 모호한","ex":"She left a cryptic note on the desk.","level":3},
  {"word":"culpable","pos":"adj.","en":"deserving blame or responsibility","ko":"비난받을 만한, 유죄의","ex":"The manager was found culpable for the error.","level":3},
  {"word":"cultivate","pos":"v.","en":"to grow crops or develop qualities","ko":"재배하다, 기르다","ex":"Farmers cultivate rice in these fields.","level":2},
  {"word":"culture","pos":"n.","en":"the customs and beliefs of a society","ko":"문화","ex":"Each country has its own unique culture.","level":1},
  {"word":"cumulative","pos":"adj.","en":"increasing by successive additions","ko":"누적되는","ex":"The cumulative effect of stress can harm health.","level":2},
  {"word":"damage","pos":"n.","en":"physical harm that reduces value","ko":"손상, 피해","ex":"The storm caused serious damage to the roof.","level":1},
  {"word":"danger","pos":"n.","en":"the possibility of harm","ko":"위험","ex":"Firefighters often face great danger at work.","level":1},
  {"word":"debilitate","pos":"v.","en":"to weaken greatly","ko":"쇠약하게 하다","ex":"The illness can debilitate patients for months.","level":3},
  {"word":"decade","pos":"n.","en":"a period of ten years","ko":"10년","ex":"The town has grown rapidly over the past decade.","level":1},
  {"word":"decide","pos":"v.","en":"to make a choice","ko":"결정하다","ex":"They will decide the winner tomorrow.","level":1},
  {"word":"declare","pos":"v.","en":"to state clearly and formally","ko":"선언하다, 공표하다","ex":"The nation was forced to declare independence.","level":2},
  {"word":"decline","pos":"v.","en":"to decrease or refuse politely","ko":"감소하다, 거절하다","ex":"Sales began to decline last winter.","level":2},
  {"word":"dedicate","pos":"v.","en":"to devote time or effort to","ko":"바치다, 헌신하다","ex":"She chose to dedicate her life to research.","level":2},
  {"word":"define","pos":"v.","en":"to state the meaning of","ko":"정의하다","ex":"It is hard to define happiness precisely.","level":2},
  {"word":"deleterious","pos":"adj.","en":"causing harm or damage","ko":"해로운","ex":"Pollution has a deleterious effect on health.","level":3},
  {"word":"demonstrate","pos":"v.","en":"to show clearly by example","ko":"증명하다, 보여주다","ex":"The experiment demonstrates the principle well.","level":2},
  {"word":"denigrate","pos":"v.","en":"to criticize unfairly; belittle","ko":"폄하하다, 헐뜯다","ex":"He would often denigrate his rivals in public.","level":3},
  {"word":"dense","pos":"adj.","en":"closely packed; thick","ko":"밀집한, 빽빽한","ex":"The forest was too dense to walk through.","level":2},
  {"word":"deprive","pos":"v.","en":"to take something away from","ko":"박탈하다, 빼앗다","ex":"Lack of sleep can deprive the brain of rest.","level":2},
  {"word":"deride","pos":"v.","en":"to mock or ridicule","ko":"조롱하다, 비웃다","ex":"Critics deride the plan as unrealistic.","level":3},
  {"word":"derive","pos":"v.","en":"to obtain from a source","ko":"끌어내다, 유래하다","ex":"Many drugs derive from natural plants.","level":2},
  {"word":"describe","pos":"v.","en":"to say what something is like","ko":"묘사하다, 설명하다","ex":"Please describe what you saw at the scene.","level":1},
  {"word":"desultory","pos":"adj.","en":"lacking purpose or plan","ko":"산만한, 두서없는","ex":"He made only a desultory effort to study.","level":3},
  {"word":"detect","pos":"v.","en":"to discover or notice","ko":"감지하다, 탐지하다","ex":"The sensor can detect small changes in temperature.","level":2},
  {"word":"determine","pos":"v.","en":"to find out or decide firmly","ko":"결정하다, 밝히다","ex":"Genes help determine a person's height.","level":2},
  {"word":"develop","pos":"v.","en":"to grow or make more advanced","ko":"발전시키다, 개발하다","ex":"The company plans to develop new software.","level":1},
  {"word":"difference","pos":"n.","en":"the way things are not the same","ko":"차이","ex":"There is a clear difference between the two plans.","level":1},
  {"word":"diligent","pos":"adj.","en":"showing careful and steady effort","ko":"부지런한, 근면한","ex":"A diligent student reviews notes every day.","level":3},
  {"word":"discern","pos":"v.","en":"to perceive or distinguish clearly","ko":"식별하다, 분간하다","ex":"It was hard to discern the truth from lies.","level":3},
  {"word":"discover","pos":"v.","en":"to find something for the first time","ko":"발견하다","ex":"Scientists discover new species every year.","level":1},
  {"word":"disparate","pos":"adj.","en":"fundamentally different in kind","ko":"이질적인, 상이한","ex":"The study combined disparate sources of data.","level":3},
  {"word":"distinct","pos":"adj.","en":"clearly different or separate","ko":"뚜렷한, 별개의","ex":"The two species are quite distinct.","level":2},
  {"word":"distribute","pos":"v.","en":"to give out or spread among","ko":"분배하다, 배포하다","ex":"Volunteers distribute food to the poor.","level":2},
  {"word":"diverse","pos":"adj.","en":"showing much variety","ko":"다양한","ex":"The city has a diverse population.","level":2},
  {"word":"dogmatic","pos":"adj.","en":"asserting opinions as certainly true","ko":"독단적인","ex":"His dogmatic views left no room for debate.","level":3},
  {"word":"dubious","pos":"adj.","en":"doubtful or questionable","ko":"의심스러운, 미심쩍은","ex":"The claim rests on dubious evidence.","level":3},
  {"word":"elaborate","pos":"v.","en":"to explain in more detail","ko":"자세히 설명하다","ex":"Could you elaborate on your main argument?","level":2},
  {"word":"elicit","pos":"v.","en":"to draw out a response or reaction","ko":"이끌어내다, 유도하다","ex":"The question elicited an angry response.","level":3},
  {"word":"eliminate","pos":"v.","en":"to remove or get rid of","ko":"제거하다, 없애다","ex":"The new policy aims to eliminate waste.","level":2},
  {"word":"emerge","pos":"v.","en":"to appear or become known","ko":"나타나다, 출현하다","ex":"New evidence began to emerge during the trial.","level":1},
  {"word":"emphasize","pos":"v.","en":"to give special importance to","ko":"강조하다","ex":"The teacher emphasized the need for practice.","level":1},
  {"word":"empirical","pos":"adj.","en":"based on observation or experiment","ko":"경험적인, 실증적인","ex":"The theory lacks empirical support.","level":3},
  {"word":"enable","pos":"v.","en":"to make something possible","ko":"가능하게 하다","ex":"The tool enables faster data analysis.","level":1},
  {"word":"encounter","pos":"v.","en":"to meet or experience unexpectedly","ko":"마주치다, 직면하다","ex":"Researchers encounter many obstacles in the field.","level":2},
  {"word":"endure","pos":"v.","en":"to bear or last over time","ko":"견디다, 지속되다","ex":"The monument has endured for centuries.","level":2},
  {"word":"enhance","pos":"v.","en":"to improve the quality of","ko":"향상시키다, 강화하다","ex":"Exercise can enhance cognitive performance.","level":2},
  {"word":"enormous","pos":"adj.","en":"very large in size or amount","ko":"거대한, 막대한","ex":"The project required an enormous amount of funding.","level":1},
  {"word":"ensure","pos":"v.","en":"to make certain of something","ko":"보장하다, 확실히 하다","ex":"Rules ensure fairness in the competition.","level":1},
  {"word":"entail","pos":"v.","en":"to involve as a necessary part","ko":"수반하다, 필요로 하다","ex":"The job entails frequent travel.","level":3},
  {"word":"enumerate","pos":"v.","en":"to list things one by one","ko":"열거하다","ex":"The report enumerates several possible causes.","level":3},
  {"word":"environment","pos":"n.","en":"surroundings or natural conditions","ko":"환경","ex":"Pollution damages the natural environment.","level":1},
  {"word":"equivalent","pos":"adj.","en":"equal in value or meaning","ko":"동등한, 상응하는","ex":"One mile is roughly equivalent to 1.6 kilometers.","level":2},
  {"word":"erode","pos":"v.","en":"to wear away gradually","ko":"침식하다, 약화시키다","ex":"Water can erode rock over thousands of years.","level":2},
  {"word":"erratic","pos":"adj.","en":"irregular or unpredictable","ko":"불규칙한, 변덕스러운","ex":"The patient's heartbeat was erratic.","level":3},
  {"word":"establish","pos":"v.","en":"to set up or create firmly","ko":"설립하다, 확립하다","ex":"The university was established in 1850.","level":1},
  {"word":"estimate","pos":"v.","en":"to roughly calculate a value","ko":"추정하다, 추산하다","ex":"Experts estimate the damage at millions.","level":1},
  {"word":"evaluate","pos":"v.","en":"to judge the value or quality","ko":"평가하다","ex":"Scientists evaluate the results carefully.","level":1},
  {"word":"evident","pos":"adj.","en":"clearly seen or understood","ko":"명백한, 분명한","ex":"Her talent was evident from an early age.","level":2},
  {"word":"evoke","pos":"v.","en":"to bring a feeling or memory to mind","ko":"불러일으키다","ex":"The song evokes memories of childhood.","level":3},
  {"word":"evolve","pos":"v.","en":"to develop gradually over time","ko":"진화하다, 발전하다","ex":"Languages evolve as societies change.","level":2},
  {"word":"exceed","pos":"v.","en":"to go beyond a limit","ko":"초과하다, 넘어서다","ex":"The costs exceeded the original budget.","level":2},
  {"word":"exhibit","pos":"v.","en":"to show or display publicly","ko":"전시하다, 보이다","ex":"The museum exhibits ancient artifacts.","level":2},
  {"word":"expand","pos":"v.","en":"to become larger in size","ko":"확장하다, 팽창하다","ex":"Metal tends to expand when heated.","level":1},
  {"word":"explicit","pos":"adj.","en":"stated clearly and in detail","ko":"명시적인, 분명한","ex":"The instructions were explicit and easy to follow.","level":3},
  {"word":"exploit","pos":"v.","en":"to use fully or unfairly","ko":"이용하다, 착취하다","ex":"The company exploited cheap labor abroad.","level":3},
  {"word":"expose","pos":"v.","en":"to reveal or make vulnerable","ko":"노출시키다, 드러내다","ex":"The report exposed serious safety flaws.","level":2},
  {"word":"external","pos":"adj.","en":"relating to the outside","ko":"외부의, 외적인","ex":"External factors influenced the outcome.","level":2},
  {"word":"extract","pos":"v.","en":"to remove or take out","ko":"추출하다, 뽑아내다","ex":"Machines extract oil from the ground.","level":2},
  {"word":"facilitate","pos":"v.","en":"to make a process easier","ko":"촉진하다, 용이하게 하다","ex":"Technology can facilitate communication.","level":3},
  {"word":"factor","pos":"n.","en":"an element contributing to a result","ko":"요인, 요소","ex":"Diet is an important factor in health.","level":1},
  {"word":"fascinate","pos":"v.","en":"to attract and hold interest","ko":"매혹시키다","ex":"Ancient history has always fascinated me.","level":2},
  {"word":"feasible","pos":"adj.","en":"possible to do easily","ko":"실현 가능한","ex":"The plan seems feasible within the budget.","level":3},
  {"word":"feature","pos":"n.","en":"a distinctive characteristic","ko":"특징, 특성","ex":"The design has several unique features.","level":1},
  {"word":"fertile","pos":"adj.","en":"able to produce abundant growth","ko":"비옥한, 기름진","ex":"The valley has very fertile soil.","level":2},
  {"word":"finite","pos":"adj.","en":"having limits or bounds","ko":"유한한, 한정된","ex":"The world has finite natural resources.","level":3},
  {"word":"flexible","pos":"adj.","en":"able to change or bend easily","ko":"유연한, 융통성 있는","ex":"The schedule is flexible enough to adjust.","level":1},
  {"word":"flourish","pos":"v.","en":"to grow or develop successfully","ko":"번성하다, 번영하다","ex":"The arts flourished during that era.","level":3},
  {"word":"fluctuate","pos":"v.","en":"to rise and fall irregularly","ko":"변동하다, 오르내리다","ex":"Prices fluctuate with market demand.","level":3},
  {"word":"focus","pos":"v.","en":"to concentrate attention on","ko":"집중하다, 초점을 맞추다","ex":"The study focuses on urban development.","level":1},
  {"word":"forbid","pos":"v.","en":"to order not to do something","ko":"금지하다","ex":"The rules forbid smoking indoors.","level":2},
  {"word":"formulate","pos":"v.","en":"to create or express carefully","ko":"만들다, 공식화하다","ex":"Scientists formulate hypotheses to test.","level":3},
  {"word":"foster","pos":"v.","en":"to encourage the development of","ko":"촉진하다, 육성하다","ex":"Good teachers foster curiosity in students.","level":3},
  {"word":"foundation","pos":"n.","en":"a basis on which something rests","ko":"기초, 토대","ex":"Trust is the foundation of friendship.","level":1},
  {"word":"fragile","pos":"adj.","en":"easily broken or damaged","ko":"부서지기 쉬운, 취약한","ex":"The ecosystem is extremely fragile.","level":2},
  {"word":"fragment","pos":"n.","en":"a small broken-off piece","ko":"조각, 파편","ex":"Archaeologists found a fragment of pottery.","level":2},
  {"word":"framework","pos":"n.","en":"a basic supporting structure","ko":"틀, 체계","ex":"The theory provides a useful framework.","level":2},
  {"word":"frequent","pos":"adj.","en":"happening often","ko":"빈번한, 잦은","ex":"The bus makes frequent stops downtown.","level":1},
  {"word":"function","pos":"n.","en":"the purpose or role of something","ko":"기능, 작용","ex":"The heart's function is to pump blood.","level":1},
  {"word":"fundamental","pos":"adj.","en":"forming a necessary base","ko":"근본적인, 기본적인","ex":"Freedom is a fundamental human right.","level":2},
  {"word":"furnish","pos":"v.","en":"to provide or supply","ko":"제공하다, 갖추다","ex":"The report furnishes detailed statistics.","level":3},
  {"word":"futile","pos":"adj.","en":"producing no useful result","ko":"헛된, 소용없는","ex":"Their efforts to save the ship proved futile.","level":3},
  {"word":"gauge","pos":"v.","en":"to measure or estimate","ko":"측정하다, 가늠하다","ex":"The survey aims to gauge public opinion.","level":3},
  {"word":"gene","pos":"n.","en":"a unit of heredity in cells","ko":"유전자","ex":"Scientists identified the gene for the disease.","level":2},
  {"word":"generate","pos":"v.","en":"to produce or create","ko":"생성하다, 발생시키다","ex":"Wind turbines generate electricity.","level":1},
  {"word":"generic","pos":"adj.","en":"general, not specific or branded","ko":"일반적인, 포괄적인","ex":"The store sells generic medicines cheaply.","level":3},
  {"word":"genuine","pos":"adj.","en":"real and authentic","ko":"진짜의, 진실한","ex":"She showed genuine interest in the topic.","level":2},
  {"word":"germinate","pos":"v.","en":"to begin to grow, as a seed","ko":"발아하다, 싹트다","ex":"Seeds germinate in warm, moist soil.","level":3},
  {"word":"glacier","pos":"n.","en":"a slow-moving mass of ice","ko":"빙하","ex":"The glacier has retreated significantly.","level":2},
  {"word":"gradual","pos":"adj.","en":"happening slowly over time","ko":"점진적인, 서서히","ex":"There was a gradual rise in temperature.","level":2},
  {"word":"grant","pos":"v.","en":"to give or allow formally","ko":"부여하다, 승인하다","ex":"The government granted them permission.","level":2},
  {"word":"grasp","pos":"v.","en":"to understand fully","ko":"이해하다, 파악하다","ex":"Students struggled to grasp the concept.","level":2},
  {"word":"gravity","pos":"n.","en":"the force pulling objects downward","ko":"중력","ex":"Gravity keeps the planets in orbit.","level":2},
  {"word":"gregarious","pos":"adj.","en":"sociable and fond of company","ko":"사교적인, 무리를 이루는","ex":"Elephants are highly gregarious animals.","level":3},
  {"word":"guarantee","pos":"v.","en":"to promise or ensure","ko":"보장하다, 보증하다","ex":"Hard work does not always guarantee success.","level":2},
  {"word":"guideline","pos":"n.","en":"a rule or principle to follow","ko":"지침, 가이드라인","ex":"The agency issued new safety guidelines.","level":2},
  {"word":"habitat","pos":"n.","en":"natural home of an animal or plant","ko":"서식지","ex":"Deforestation destroys the natural habitat of many species.","level":1},
  {"word":"hamper","pos":"v.","en":"to prevent free movement or progress","ko":"방해하다","ex":"Heavy snow hampered the delivery of supplies.","level":3},
  {"word":"haphazard","pos":"adj.","en":"lacking order or planning","ko":"무계획적인, 되는대로의","ex":"His research notes were kept in a haphazard manner.","level":3},
  {"word":"hardy","pos":"adj.","en":"able to endure difficult conditions","ko":"강건한, 튼튼한","ex":"These hardy plants survive even in cold winters.","level":2},
  {"word":"harsh","pos":"adj.","en":"unpleasant, severe, or cruel","ko":"가혹한, 혹독한","ex":"The desert has a harsh and dry climate.","level":1},
  {"word":"hazard","pos":"n.","en":"a danger or risk","ko":"위험, 위험 요소","ex":"Smoking is a serious hazard to your health.","level":1},
  {"word":"heritage","pos":"n.","en":"traditions passed down over generations","ko":"유산, 전통","ex":"The festival celebrates the nation's cultural heritage.","level":2},
  {"word":"hierarchy","pos":"n.","en":"a system ranking people or things by level","ko":"위계, 계층 구조","ex":"The company has a strict management hierarchy.","level":2},
  {"word":"hinder","pos":"v.","en":"to make progress or action difficult","ko":"방해하다, 저해하다","ex":"Poor weather can hinder the rescue operation.","level":2},
  {"word":"hollow","pos":"adj.","en":"having an empty space inside","ko":"속이 빈","ex":"The tree trunk was completely hollow inside.","level":1},
  {"word":"homogeneous","pos":"adj.","en":"of the same kind or uniform","ko":"동질의, 균질한","ex":"The population of the town is remarkably homogeneous.","level":3},
  {"word":"hostile","pos":"adj.","en":"unfriendly or aggressive","ko":"적대적인","ex":"The crowd grew hostile toward the speaker.","level":2},
  {"word":"humid","pos":"adj.","en":"having a lot of moisture in the air","ko":"습한","ex":"The tropical climate is hot and humid.","level":1},
  {"word":"hybrid","pos":"n.","en":"something made by combining two things","ko":"혼합물, 잡종","ex":"A mule is a hybrid of a horse and donkey.","level":2},
  {"word":"hypothesis","pos":"n.","en":"a proposed explanation to be tested","ko":"가설","ex":"The experiment was designed to test the hypothesis.","level":2},
  {"word":"identical","pos":"adj.","en":"exactly the same","ko":"동일한","ex":"The twins wore identical outfits to the party.","level":1},
  {"word":"identify","pos":"v.","en":"to recognize or name someone or something","ko":"확인하다, 식별하다","ex":"Researchers were able to identify the cause.","level":1},
  {"word":"illustrate","pos":"v.","en":"to explain or make clear with examples","ko":"설명하다, 예시하다","ex":"The graph illustrates the rise in temperatures.","level":1},
  {"word":"immense","pos":"adj.","en":"extremely large or great","ko":"엄청난, 광대한","ex":"The project required an immense amount of effort.","level":2},
  {"word":"imminent","pos":"adj.","en":"about to happen very soon","ko":"임박한","ex":"The dark clouds warned of an imminent storm.","level":3},
  {"word":"impact","pos":"n.","en":"a strong effect or influence","ko":"영향, 충격","ex":"The new law had a major impact on farmers.","level":1},
  {"word":"impartial","pos":"adj.","en":"fair and not favoring one side","ko":"공정한, 편견 없는","ex":"A judge must remain impartial at all times.","level":3},
  {"word":"impede","pos":"v.","en":"to slow or block progress","ko":"방해하다, 지연시키다","ex":"Bureaucracy can impede rapid decision-making.","level":3},
  {"word":"imply","pos":"v.","en":"to suggest without stating directly","ko":"암시하다, 함축하다","ex":"Her silence seemed to imply disagreement.","level":2},
  {"word":"impose","pos":"v.","en":"to force something on someone officially","ko":"부과하다, 강요하다","ex":"The government decided to impose new taxes.","level":2},
  {"word":"improve","pos":"v.","en":"to make or become better","ko":"향상시키다, 개선하다","ex":"Regular practice will improve your writing skills.","level":1},
  {"word":"incentive","pos":"n.","en":"something that motivates or encourages","ko":"동기, 유인책","ex":"Bonuses provide a strong incentive to work harder.","level":2},
  {"word":"incessant","pos":"adj.","en":"continuing without stopping","ko":"끊임없는","ex":"The incessant noise made it hard to concentrate.","level":3},
  {"word":"include","pos":"v.","en":"to contain as part of a whole","ko":"포함하다","ex":"The price does not include shipping costs.","level":1},
  {"word":"increase","pos":"v.","en":"to become or make greater in amount","ko":"증가하다, 늘리다","ex":"Sales began to increase during the holidays.","level":1},
  {"word":"indicate","pos":"v.","en":"to show or point out","ko":"나타내다, 가리키다","ex":"The results indicate a clear improvement.","level":1},
  {"word":"indigenous","pos":"adj.","en":"native to a particular place","ko":"토착의, 원산의","ex":"These plants are indigenous to the region.","level":3},
  {"word":"indispensable","pos":"adj.","en":"absolutely necessary","ko":"필수적인, 없어서는 안 될","ex":"Water is indispensable for all living things.","level":3},
  {"word":"inevitable","pos":"adj.","en":"certain to happen, unavoidable","ko":"불가피한, 필연적인","ex":"Change is an inevitable part of life.","level":2},
  {"word":"inevitably","pos":"adv.","en":"in a way that cannot be avoided","ko":"불가피하게","ex":"Rapid growth inevitably brings new challenges.","level":2},
  {"word":"infer","pos":"v.","en":"to conclude from evidence and reasoning","ko":"추론하다","ex":"We can infer the answer from the given data.","level":2},
  {"word":"influence","pos":"n.","en":"the power to affect people or things","ko":"영향, 영향력","ex":"Parents have a strong influence on their children.","level":1},
  {"word":"ingenious","pos":"adj.","en":"clever, original, and inventive","ko":"독창적인, 기발한","ex":"She found an ingenious solution to the problem.","level":3},
  {"word":"inhabit","pos":"v.","en":"to live in a particular place","ko":"거주하다, 서식하다","ex":"Many rare species inhabit the rainforest.","level":2},
  {"word":"inherent","pos":"adj.","en":"existing as a natural, permanent quality","ko":"내재된, 고유한","ex":"There is an inherent risk in any investment.","level":3},
  {"word":"initiate","pos":"v.","en":"to begin or start something","ko":"시작하다, 착수하다","ex":"The company will initiate a new training program.","level":2},
  {"word":"innovation","pos":"n.","en":"a new idea, method, or invention","ko":"혁신","ex":"Technological innovation drives economic growth.","level":2},
  {"word":"insight","pos":"n.","en":"a deep understanding of something","ko":"통찰, 통찰력","ex":"The study offers valuable insight into human behavior.","level":2},
  {"word":"integrate","pos":"v.","en":"to combine parts into a whole","ko":"통합하다","ex":"The school aims to integrate technology into lessons.","level":2},
  {"word":"intricate","pos":"adj.","en":"very complicated or detailed","ko":"복잡한, 정교한","ex":"The watch has an intricate mechanism.","level":3},
  {"word":"intrinsic","pos":"adj.","en":"belonging naturally, essential","ko":"본질적인, 고유의","ex":"Gold has an intrinsic value across cultures.","level":3},
  {"word":"isolate","pos":"v.","en":"to separate from others","ko":"고립시키다, 분리하다","ex":"Scientists managed to isolate the virus.","level":2},
  {"word":"jeopardize","pos":"v.","en":"to put at risk of harm or loss","ko":"위태롭게 하다","ex":"Poor decisions could jeopardize the whole project.","level":3},
  {"word":"judicious","pos":"adj.","en":"showing good judgment and sense","ko":"현명한, 신중한","ex":"She made judicious use of the limited budget.","level":3},
  {"word":"junction","pos":"n.","en":"a point where things join or meet","ko":"교차점, 연결점","ex":"The accident happened at a busy road junction.","level":2},
  {"word":"justify","pos":"v.","en":"to show that something is reasonable","ko":"정당화하다","ex":"He could not justify his sudden decision.","level":2},
  {"word":"juvenile","pos":"adj.","en":"relating to young people or animals","ko":"청소년의, 어린","ex":"The zoo studies the behavior of juvenile lions.","level":3},
  {"word":"keen","pos":"adj.","en":"eager, enthusiastic, or sharp","ko":"열망하는, 예리한","ex":"She has a keen interest in marine biology.","level":2},
  {"word":"kindle","pos":"v.","en":"to arouse a feeling or start a fire","ko":"불붙이다, 불러일으키다","ex":"The teacher tried to kindle a love of reading.","level":3},
  {"word":"knowledge","pos":"n.","en":"information and understanding of a subject","ko":"지식","ex":"Scientific knowledge continues to expand rapidly.","level":1},
  {"word":"labor","pos":"n.","en":"work, especially physical effort","ko":"노동, 노력","ex":"The factory relies on cheap manual labor.","level":1},
  {"word":"landscape","pos":"n.","en":"all the visible features of an area","ko":"풍경, 경관","ex":"The mountain landscape was breathtaking.","level":1},
  {"word":"latent","pos":"adj.","en":"existing but not yet visible or active","ko":"잠재된","ex":"The disease can remain latent for years.","level":3},
  {"word":"launch","pos":"v.","en":"to start or send off something","ko":"시작하다, 발사하다","ex":"The company plans to launch a new product.","level":1},
  {"word":"layer","pos":"n.","en":"a single thickness covering a surface","ko":"층","ex":"A thick layer of snow covered the ground.","level":1},
  {"word":"legislation","pos":"n.","en":"laws made by a government","ko":"법률, 입법","ex":"New legislation was passed to protect wildlife.","level":2},
  {"word":"legitimate","pos":"adj.","en":"allowed by law or reasonable","ko":"합법적인, 정당한","ex":"She had a legitimate reason for her absence.","level":2},
  {"word":"leisure","pos":"n.","en":"free time for relaxation and enjoyment","ko":"여가","ex":"People spend their leisure time in many ways.","level":2},
  {"word":"liberal","pos":"adj.","en":"open to new ideas and change","ko":"자유주의의, 개방적인","ex":"He holds fairly liberal political views.","level":2},
  {"word":"likelihood","pos":"n.","en":"the chance that something will happen","ko":"가능성","ex":"There is a strong likelihood of rain tomorrow.","level":2},
  {"word":"linger","pos":"v.","en":"to stay longer than expected","ko":"오래 머물다, 남다","ex":"The smell of smoke lingered in the room.","level":3},
  {"word":"locate","pos":"v.","en":"to find the position of something","ko":"위치를 찾다","ex":"Rescuers struggled to locate the missing hikers.","level":1},
  {"word":"lofty","pos":"adj.","en":"very high or noble in nature","ko":"높은, 고귀한","ex":"The organization has lofty goals for reform.","level":3},
  {"word":"logical","pos":"adj.","en":"based on clear and sound reasoning","ko":"논리적인","ex":"She gave a logical explanation for the results.","level":1},
  {"word":"lucrative","pos":"adj.","en":"producing a lot of money or profit","ko":"수익성이 좋은","ex":"Software development can be a lucrative career.","level":3},
  {"word":"luminous","pos":"adj.","en":"giving off or reflecting light","ko":"빛나는, 발광하는","ex":"The luminous dial glowed in the dark.","level":3},
  {"word":"magnify","pos":"v.","en":"to make something appear larger","ko":"확대하다, 과장하다","ex":"The microscope can magnify tiny cells hundreds of times.","level":2},
  {"word":"maintain","pos":"v.","en":"to keep in an existing state","ko":"유지하다, 주장하다","ex":"Regular exercise helps maintain good health.","level":1},
  {"word":"manipulate","pos":"v.","en":"to handle or control skillfully","ko":"조종하다, 다루다","ex":"Scientists manipulate variables to test a hypothesis.","level":3},
  {"word":"marginal","pos":"adj.","en":"small in importance or amount","ko":"미미한, 주변의","ex":"The new policy had only a marginal effect on sales.","level":3},
  {"word":"massive","pos":"adj.","en":"very large in size or amount","ko":"거대한, 대규모의","ex":"The earthquake caused massive destruction across the region.","level":1},
  {"word":"mature","pos":"adj.","en":"fully developed or grown","ko":"성숙한, 다 자란","ex":"A mature tree can absorb large amounts of carbon.","level":1},
  {"word":"maximize","pos":"v.","en":"to make as great as possible","ko":"극대화하다","ex":"Farmers rotate crops to maximize soil fertility.","level":2},
  {"word":"mediate","pos":"v.","en":"to resolve a dispute between parties","ko":"중재하다, 조정하다","ex":"The council tried to mediate between the two nations.","level":3},
  {"word":"mediocre","pos":"adj.","en":"of only average quality","ko":"평범한, 그저 그런","ex":"The critics called the film mediocre and forgettable.","level":3},
  {"word":"mercantile","pos":"adj.","en":"relating to trade or commerce","ko":"상업의, 무역의","ex":"The city grew wealthy through its mercantile activities.","level":3},
  {"word":"meticulous","pos":"adj.","en":"showing great attention to detail","ko":"꼼꼼한, 세심한","ex":"The scientist kept meticulous records of every experiment.","level":3},
  {"word":"migrate","pos":"v.","en":"to move from one region to another","ko":"이주하다, 이동하다","ex":"Many birds migrate south for the winter.","level":2},
  {"word":"mimic","pos":"v.","en":"to imitate closely","ko":"흉내 내다, 모방하다","ex":"Some insects mimic leaves to avoid predators.","level":2},
  {"word":"minimize","pos":"v.","en":"to reduce to the smallest amount","ko":"최소화하다","ex":"The company took steps to minimize its waste.","level":2},
  {"word":"mitigate","pos":"v.","en":"to make less severe or painful","ko":"완화하다, 경감하다","ex":"Planting trees can mitigate climate change.","level":2},
  {"word":"moderate","pos":"adj.","en":"average in amount or degree","ko":"적당한, 온건한","ex":"The region enjoys a moderate climate year-round.","level":2},
  {"word":"modify","pos":"v.","en":"to make partial changes to","ko":"수정하다, 변경하다","ex":"Engineers modified the design to improve safety.","level":2},
  {"word":"molecule","pos":"n.","en":"smallest unit of a chemical compound","ko":"분자","ex":"A water molecule contains two hydrogen atoms.","level":2},
  {"word":"momentum","pos":"n.","en":"force gained by motion or events","ko":"탄력, 운동량","ex":"The reform movement gained momentum after the election.","level":3},
  {"word":"monitor","pos":"v.","en":"to observe and check over time","ko":"감시하다, 관찰하다","ex":"Doctors monitor the patient's heart rate closely.","level":1},
  {"word":"monotonous","pos":"adj.","en":"dull and repetitive","ko":"단조로운, 지루한","ex":"The factory work was monotonous and exhausting.","level":3},
  {"word":"motive","pos":"n.","en":"a reason for doing something","ko":"동기, 이유","ex":"The detective searched for a motive behind the crime.","level":2},
  {"word":"mutual","pos":"adj.","en":"shared or felt by both sides","ko":"상호의, 서로의","ex":"The agreement was based on mutual respect.","level":2},
  {"word":"narrate","pos":"v.","en":"to tell or describe a story","ko":"이야기하다, 서술하다","ex":"The author narrates the events in vivid detail.","level":2},
  {"word":"navigate","pos":"v.","en":"to find a way through or across","ko":"항해하다, 길을 찾다","ex":"Sailors used the stars to navigate the ocean.","level":2},
  {"word":"negligible","pos":"adj.","en":"so small as to be unimportant","ko":"무시해도 될, 미미한","ex":"The temperature difference was negligible.","level":3},
  {"word":"negotiate","pos":"v.","en":"to reach agreement through discussion","ko":"협상하다","ex":"The two companies negotiated a new contract.","level":2},
  {"word":"neutral","pos":"adj.","en":"not supporting either side","ko":"중립의","ex":"The country remained neutral during the war.","level":1},
  {"word":"nocturnal","pos":"adj.","en":"active during the night","ko":"야행성의","ex":"Owls are nocturnal hunters with keen eyesight.","level":3},
  {"word":"nominal","pos":"adj.","en":"existing in name only; very small","ko":"명목상의, 아주 적은","ex":"Members pay only a nominal fee to join.","level":3},
  {"word":"norm","pos":"n.","en":"a standard or usual pattern","ko":"규범, 표준","ex":"Social norms vary widely between cultures.","level":2},
  {"word":"notable","pos":"adj.","en":"worthy of attention or remarkable","ko":"주목할 만한, 유명한","ex":"The city is notable for its ancient architecture.","level":2},
  {"word":"notion","pos":"n.","en":"an idea or belief","ko":"개념, 관념","ex":"The notion that Earth was flat persisted for centuries.","level":2},
  {"word":"nourish","pos":"v.","en":"to provide food for growth","ko":"영양분을 공급하다, 기르다","ex":"Rich soil nourishes the growing plants.","level":2},
  {"word":"novel","pos":"adj.","en":"new and original","ko":"새로운, 참신한","ex":"The researchers proposed a novel approach to treatment.","level":2},
  {"word":"numerous","pos":"adj.","en":"existing in large numbers","ko":"수많은, 다수의","ex":"The scientist published numerous papers on the subject.","level":1},
  {"word":"nurture","pos":"v.","en":"to care for and encourage growth","ko":"양육하다, 육성하다","ex":"Good teachers nurture curiosity in their students.","level":2},
  {"word":"obscure","pos":"adj.","en":"not clearly understood or known","ko":"모호한, 잘 알려지지 않은","ex":"The poem's meaning remains obscure to many readers.","level":3},
  {"word":"observe","pos":"v.","en":"to watch carefully","ko":"관찰하다, 준수하다","ex":"Astronomers observe distant galaxies through telescopes.","level":1},
  {"word":"obsolete","pos":"adj.","en":"no longer used or useful","ko":"쓸모없는, 구식의","ex":"New technology made the old machines obsolete.","level":3},
  {"word":"obstacle","pos":"n.","en":"something that blocks progress","ko":"장애물","ex":"Lack of funding was the main obstacle to the project.","level":1},
  {"word":"obtain","pos":"v.","en":"to get or acquire","ko":"얻다, 획득하다","ex":"Researchers obtained permission to study the site.","level":1},
  {"word":"obvious","pos":"adj.","en":"easily seen or understood","ko":"명백한, 분명한","ex":"The solution to the problem was obvious.","level":1},
  {"word":"occupy","pos":"v.","en":"to fill space or time","ko":"차지하다, 점령하다","ex":"The library occupies the entire top floor.","level":1},
  {"word":"occur","pos":"v.","en":"to happen or take place","ko":"발생하다, 일어나다","ex":"Earthquakes occur along fault lines.","level":1},
  {"word":"offset","pos":"v.","en":"to balance or counteract","ko":"상쇄하다, 벌충하다","ex":"Higher wages were offset by rising prices.","level":3},
  {"word":"omit","pos":"v.","en":"to leave out or exclude","ko":"생략하다, 빠뜨리다","ex":"The editor omitted several paragraphs from the article.","level":2},
  {"word":"ongoing","pos":"adj.","en":"continuing to happen","ko":"진행 중인","ex":"The ongoing research may take several more years.","level":2},
  {"word":"opaque","pos":"adj.","en":"not able to be seen through","ko":"불투명한","ex":"The glass was opaque, blocking all light.","level":3},
  {"word":"optimal","pos":"adj.","en":"best or most favorable","ko":"최적의","ex":"Plants grow best under optimal light conditions.","level":3},
  {"word":"optimistic","pos":"adj.","en":"hopeful about the future","ko":"낙관적인","ex":"Scientists are optimistic about the new vaccine.","level":2},
  {"word":"optional","pos":"adj.","en":"not required; left to choice","ko":"선택적인","ex":"The extra assignment is optional for students.","level":1},
  {"word":"orbit","pos":"n.","en":"path of an object around another","ko":"궤도","ex":"The satellite completed one orbit around Earth.","level":2},
  {"word":"ordeal","pos":"n.","en":"a painful or difficult experience","ko":"시련, 고난","ex":"Surviving the storm was a terrible ordeal.","level":3},
  {"word":"organism","pos":"n.","en":"an individual living thing","ko":"유기체, 생물","ex":"Bacteria are single-celled organisms.","level":2},
  {"word":"orient","pos":"v.","en":"to align or find direction","ko":"방향을 잡다, 적응시키다","ex":"New students orient themselves to campus life.","level":2},
  {"word":"origin","pos":"n.","en":"the point where something begins","ko":"기원, 근원","ex":"The origin of the disease is still unknown.","level":1},
  {"word":"ornate","pos":"adj.","en":"elaborately decorated","ko":"화려하게 장식된","ex":"The palace featured ornate golden ceilings.","level":3},
  {"word":"outcome","pos":"n.","en":"a result or consequence","ko":"결과","ex":"The outcome of the experiment surprised everyone.","level":1},
  {"word":"outdated","pos":"adj.","en":"old-fashioned or no longer valid","ko":"구식의, 시대에 뒤진","ex":"The textbook contained outdated information.","level":2},
  {"word":"outlook","pos":"n.","en":"a view or prospect for the future","ko":"전망, 관점","ex":"The economic outlook remains uncertain.","level":2},
  {"word":"output","pos":"n.","en":"amount produced by a system","ko":"산출량, 생산량","ex":"The factory increased its output last year.","level":1},
  {"word":"overlap","pos":"v.","en":"to extend over and cover partly","ko":"겹치다, 중복되다","ex":"The two studies overlap in several areas.","level":2},
  {"word":"overlook","pos":"v.","en":"to fail to notice","ko":"간과하다, 못 보고 넘어가다","ex":"Researchers overlooked an important variable.","level":2},
  {"word":"overwhelm","pos":"v.","en":"to overpower with force or emotion","ko":"압도하다","ex":"The volunteers were overwhelmed by the demand for aid.","level":2},
  {"word":"paradigm","pos":"n.","en":"a typical example or model","ko":"패러다임, 전형","ex":"The discovery created a new scientific paradigm.","level":3},
  {"word":"perceive","pos":"v.","en":"to become aware of through senses","ko":"인지하다, 감지하다","ex":"We perceive color through the eyes.","level":2},
  {"word":"peripheral","pos":"adj.","en":"of minor or secondary importance","ko":"주변적인, 지엽적인","ex":"That issue is peripheral to our main goal.","level":3},
  {"word":"persist","pos":"v.","en":"to continue firmly","ko":"지속하다, 고집하다","ex":"The symptoms persist despite treatment.","level":2},
  {"word":"pervasive","pos":"adj.","en":"spreading widely throughout","ko":"만연한, 널리 퍼진","ex":"Corruption was pervasive in the government.","level":3},
  {"word":"phase","pos":"n.","en":"a distinct stage of development","ko":"단계, 국면","ex":"The project entered its final phase.","level":1},
  {"word":"phenomenon","pos":"n.","en":"an observable fact or event","ko":"현상","ex":"Scientists studied the strange natural phenomenon.","level":2},
  {"word":"plausible","pos":"adj.","en":"seeming reasonable or probable","ko":"그럴듯한, 타당한","ex":"That is a plausible explanation for the results.","level":2},
  {"word":"portion","pos":"n.","en":"a part of a whole","ko":"부분, 일부","ex":"A large portion of the budget was cut.","level":1},
  {"word":"postulate","pos":"v.","en":"to suggest as a basis for reasoning","ko":"가정하다, 상정하다","ex":"Scientists postulate the existence of dark matter.","level":3},
  {"word":"potential","pos":"n.","en":"capacity to develop or succeed","ko":"잠재력, 가능성","ex":"The student showed great potential.","level":1},
  {"word":"practical","pos":"adj.","en":"useful in real situations","ko":"실용적인, 실질적인","ex":"We need a practical solution to the problem.","level":1},
  {"word":"pragmatic","pos":"adj.","en":"dealing with things practically","ko":"실용적인, 현실적인","ex":"He took a pragmatic approach to the crisis.","level":3},
  {"word":"precede","pos":"v.","en":"to come before in time","ko":"앞서다, 선행하다","ex":"A loud noise preceded the explosion.","level":2},
  {"word":"precipitation","pos":"n.","en":"rain, snow, or other moisture","ko":"강수, 강수량","ex":"Annual precipitation varies across the region.","level":3},
  {"word":"precise","pos":"adj.","en":"exact and accurate","ko":"정확한, 정밀한","ex":"The instrument gives precise measurements.","level":1},
  {"word":"predict","pos":"v.","en":"to say what will happen","ko":"예측하다","ex":"Experts predict a rise in temperatures.","level":1},
  {"word":"predominant","pos":"adj.","en":"most common or strongest","ko":"지배적인, 우세한","ex":"Rice is the predominant crop in the area.","level":3},
  {"word":"preliminary","pos":"adj.","en":"coming before the main part","ko":"예비의, 사전의","ex":"The preliminary results look promising.","level":3},
  {"word":"presume","pos":"v.","en":"to assume without proof","ko":"추정하다, 가정하다","ex":"We presume the theory is correct.","level":3},
  {"word":"presumption","pos":"n.","en":"an assumption taken as true","ko":"추정, 가정","ex":"The presumption of innocence protects the accused.","level":3},
  {"word":"prevalent","pos":"adj.","en":"widespread or common","ko":"널리 퍼진, 만연한","ex":"The disease was prevalent in coastal regions.","level":2},
  {"word":"primary","pos":"adj.","en":"main or most important","ko":"주요한, 일차적인","ex":"Reading is the primary goal of the class.","level":1},
  {"word":"principle","pos":"n.","en":"a fundamental truth or rule","ko":"원리, 원칙","ex":"The design follows basic engineering principles.","level":1},
  {"word":"procedure","pos":"n.","en":"an established way of doing something","ko":"절차, 방법","ex":"Follow the safety procedure carefully.","level":1},
  {"word":"profound","pos":"adj.","en":"very deep or intense","ko":"심오한, 깊은","ex":"Her work had a profound impact on society.","level":2},
  {"word":"prohibit","pos":"v.","en":"to forbid by law or rule","ko":"금지하다","ex":"The law prohibits hunting in the reserve.","level":2},
  {"word":"proliferate","pos":"v.","en":"to increase rapidly in number","ko":"급증하다, 확산하다","ex":"New species proliferated in the warm water.","level":3},
  {"word":"prominent","pos":"adj.","en":"important or well-known","ko":"저명한, 두드러진","ex":"He is a prominent figure in modern physics.","level":2},
  {"word":"prone","pos":"adj.","en":"likely to do or suffer something","ko":"~하기 쉬운, ~하는 경향이 있는","ex":"The area is prone to flooding.","level":2},
  {"word":"proponent","pos":"n.","en":"a supporter of an idea","ko":"지지자, 옹호자","ex":"She is a leading proponent of reform.","level":3},
  {"word":"prosper","pos":"v.","en":"to succeed or flourish","ko":"번영하다, 번창하다","ex":"Small businesses prosper in a stable economy.","level":2},
  {"word":"prosperity","pos":"n.","en":"the state of being successful","ko":"번영, 번성","ex":"The nation enjoyed decades of prosperity.","level":2},
  {"word":"provoke","pos":"v.","en":"to cause a reaction","ko":"유발하다, 자극하다","ex":"The speech provoked strong criticism.","level":2},
  {"word":"proximity","pos":"n.","en":"nearness in space or time","ko":"근접, 가까움","ex":"The house's proximity to school is ideal.","level":3},
  {"word":"quaint","pos":"adj.","en":"attractively old-fashioned","ko":"예스러운, 고풍스러운","ex":"They visited a quaint village by the sea.","level":3},
  {"word":"qualitative","pos":"adj.","en":"relating to quality not quantity","ko":"질적인, 정성적인","ex":"The study used qualitative interviews.","level":3},
  {"word":"quantify","pos":"v.","en":"to measure the amount of","ko":"수량화하다, 정량화하다","ex":"It is hard to quantify the benefits.","level":3},
  {"word":"quantitative","pos":"adj.","en":"relating to measurable amounts","ko":"양적인, 정량적인","ex":"Quantitative data supported the hypothesis.","level":3},
  {"word":"quell","pos":"v.","en":"to suppress or put an end to","ko":"진압하다, 억누르다","ex":"The government tried to quell the protests.","level":3},
  {"word":"quench","pos":"v.","en":"to satisfy thirst or put out","ko":"해소하다, 끄다","ex":"Cold water can quench your thirst.","level":2},
  {"word":"query","pos":"n.","en":"a question or inquiry","ko":"질문, 문의","ex":"The database answered the query quickly.","level":2},
  {"word":"quest","pos":"n.","en":"a long search for something","ko":"탐구, 추구","ex":"The quest for knowledge drives research.","level":2},
  {"word":"quintessential","pos":"adj.","en":"representing the perfect example","ko":"전형적인, 정수의","ex":"It is the quintessential example of the style.","level":3},
  {"word":"quiver","pos":"v.","en":"to shake slightly","ko":"떨다, 진동하다","ex":"The leaves quiver in the breeze.","level":2},
  {"word":"quota","pos":"n.","en":"a fixed share or limit","ko":"할당량, 한도","ex":"The factory met its production quota.","level":2},
  {"word":"quote","pos":"v.","en":"to repeat someone's words","ko":"인용하다","ex":"The article quotes several experts.","level":1},
  {"word":"radiant","pos":"adj.","en":"sending out light or heat","ko":"빛나는, 복사하는","ex":"The sun is a source of radiant energy.","level":2},
  {"word":"range","pos":"n.","en":"the extent or scope of something","ko":"범위, 폭","ex":"The store sells a wide range of goods.","level":1},
  {"word":"reciprocal","pos":"adj.","en":"given in return; mutual","ko":"상호간의, 호혜적인","ex":"The two nations signed a reciprocal deal.","level":3},
  {"word":"reciprocity","pos":"n.","en":"mutual exchange of benefits","ko":"상호주의, 호혜","ex":"Trade relies on reciprocity between nations.","level":3},
  {"word":"reduce","pos":"v.","en":"to make smaller or less","ko":"줄이다, 감소시키다","ex":"The plan aims to reduce pollution.","level":1},
  {"word":"redundant","pos":"adj.","en":"not needed; superfluous","ko":"불필요한, 중복된","ex":"The report contained redundant information.","level":3},
  {"word":"refute","pos":"v.","en":"to prove to be false","ko":"반박하다, 논박하다","ex":"New evidence refutes the old claim.","level":3},
  {"word":"region","pos":"n.","en":"a large area of land","ko":"지역, 지방","ex":"The region is known for its forests.","level":1},
  {"word":"reinforce","pos":"v.","en":"to strengthen or support","ko":"강화하다, 보강하다","ex":"The findings reinforce earlier theories.","level":2},
  {"word":"release","pos":"v.","en":"to set free or let out","ko":"방출하다, 풀어주다","ex":"The plant releases oxygen into the air.","level":1},
  {"word":"reluctance","pos":"n.","en":"unwillingness to do something","ko":"꺼림, 주저","ex":"He agreed with obvious reluctance.","level":3},
  {"word":"reluctant","pos":"adj.","en":"unwilling or hesitant","ko":"꺼리는, 주저하는","ex":"She was reluctant to share her opinion.","level":2},
  {"word":"rely","pos":"v.","en":"to depend on with trust","ko":"의존하다, 의지하다","ex":"Farmers rely on seasonal rain.","level":1},
  {"word":"renewable","pos":"adj.","en":"able to be replenished naturally","ko":"재생 가능한","ex":"Solar power is a renewable energy source.","level":2},
  {"word":"require","pos":"v.","en":"to need or demand","ko":"요구하다, 필요로 하다","ex":"The task requires great patience.","level":1},
  {"word":"resemble","pos":"v.","en":"to look or be similar to","ko":"닮다, 유사하다","ex":"The fossil resembles a modern bird.","level":2},
  {"word":"reservoir","pos":"n.","en":"a large store of water or supply","ko":"저수지, 저장고","ex":"The reservoir supplies water to the city.","level":2},
  {"word":"resilient","pos":"adj.","en":"able to recover quickly","ko":"회복력 있는, 탄력적인","ex":"Coral reefs are surprisingly resilient.","level":3},
  {"word":"resolve","pos":"v.","en":"to find a solution","ko":"해결하다","ex":"They worked hard to resolve the conflict.","level":2},
  {"word":"resource","pos":"n.","en":"a supply of something useful","ko":"자원, 재원","ex":"Water is a valuable natural resource.","level":1},
  {"word":"response","pos":"n.","en":"a reaction or reply","ko":"반응, 응답","ex":"The response to the survey was positive.","level":1},
  {"word":"restrict","pos":"v.","en":"to limit or control","ko":"제한하다","ex":"The rules restrict access to the lab.","level":2},
  {"word":"retain","pos":"v.","en":"to keep or hold onto","ko":"유지하다, 보유하다","ex":"The soil retains moisture after rain.","level":2},
  {"word":"reveal","pos":"v.","en":"to make known or show","ko":"드러내다, 밝히다","ex":"The study reveals surprising patterns.","level":1},
  {"word":"reverse","pos":"v.","en":"to change to the opposite","ko":"뒤바꾸다, 역전시키다","ex":"They hope to reverse the decline.","level":2},
  {"word":"rigid","pos":"adj.","en":"stiff and not flexible","ko":"경직된, 엄격한","ex":"The rules were too rigid to change.","level":2},
  {"word":"robust","pos":"adj.","en":"strong and healthy; sturdy","ko":"튼튼한, 강건한","ex":"The economy remained robust despite the crisis.","level":3},
  {"word":"rudimentary","pos":"adj.","en":"basic or undeveloped","ko":"기초적인, 초보의","ex":"They had only a rudimentary understanding.","level":3},
  {"word":"scarce","pos":"adj.","en":"not enough; in short supply","ko":"부족한, 드문","ex":"Fresh water is scarce in desert regions.","level":2},
  {"word":"scrutinize","pos":"v.","en":"to examine something very carefully","ko":"면밀히 조사하다","ex":"Scientists scrutinize data before drawing conclusions.","level":3},
  {"word":"sequence","pos":"n.","en":"an ordered series of things","ko":"순서, 연속","ex":"The DNA sequence was analyzed in detail.","level":1},
  {"word":"shift","pos":"n.","en":"a change in position or direction","ko":"변화, 이동","ex":"There was a major shift in public opinion.","level":1},
  {"word":"significant","pos":"adj.","en":"important or large enough to matter","ko":"중요한, 상당한","ex":"The study found a significant increase in temperature.","level":1},
  {"word":"simulate","pos":"v.","en":"to imitate a real process or system","ko":"모의실험하다, 흉내내다","ex":"The software can simulate weather patterns.","level":2},
  {"word":"solitary","pos":"adj.","en":"existing or living alone","ko":"혼자의, 고독한","ex":"The tiger is a largely solitary animal.","level":3},
  {"word":"sophisticated","pos":"adj.","en":"advanced and complex","ko":"정교한, 세련된","ex":"The lab uses sophisticated measuring equipment.","level":2},
  {"word":"sparse","pos":"adj.","en":"thinly spread; not dense","ko":"드문드문한, 희박한","ex":"Vegetation is sparse at high altitudes.","level":3},
  {"word":"specific","pos":"adj.","en":"clearly defined or particular","ko":"구체적인, 특정한","ex":"Each cell performs a specific function.","level":1},
  {"word":"speculate","pos":"v.","en":"to form ideas without firm evidence","ko":"추측하다, 사색하다","ex":"Researchers speculate about the cause of extinction.","level":3},
  {"word":"spontaneous","pos":"adj.","en":"happening without planning or cause","ko":"자발적인, 자연발생적인","ex":"The reaction occurred through a spontaneous process.","level":3},
  {"word":"stable","pos":"adj.","en":"firmly fixed; not likely to change","ko":"안정된, 견고한","ex":"The bridge provided a stable structure.","level":1},
  {"word":"static","pos":"adj.","en":"not moving or changing","ko":"정적인, 고정된","ex":"The population remained static for a decade.","level":2},
  {"word":"stimulate","pos":"v.","en":"to encourage activity or growth","ko":"자극하다, 촉진하다","ex":"Sunlight stimulates the production of vitamin D.","level":2},
  {"word":"strategy","pos":"n.","en":"a plan to achieve a goal","ko":"전략, 계획","ex":"The company adopted a new marketing strategy.","level":1},
  {"word":"structure","pos":"n.","en":"the way parts are arranged together","ko":"구조, 구성","ex":"The molecular structure determines its properties.","level":1},
  {"word":"subordinate","pos":"adj.","en":"lower in rank or importance","ko":"종속적인, 하위의","ex":"These clauses play a subordinate role in the sentence.","level":3},
  {"word":"subsequent","pos":"adj.","en":"coming after something in time","ko":"그 다음의, 이후의","ex":"Subsequent experiments confirmed the initial results.","level":2},
  {"word":"substantial","pos":"adj.","en":"large in size or importance","ko":"상당한, 실질적인","ex":"The project required a substantial amount of funding.","level":2},
  {"word":"subtle","pos":"adj.","en":"not obvious; hard to notice","ko":"미묘한, 감지하기 힘든","ex":"There is a subtle difference between the two theories.","level":2},
  {"word":"successive","pos":"adj.","en":"following one after another","ko":"연속적인, 잇따른","ex":"The team won three successive championships.","level":3},
  {"word":"summit","pos":"n.","en":"the highest point of something","ko":"정상, 정점","ex":"Few climbers reach the mountain's summit.","level":2},
  {"word":"superficial","pos":"adj.","en":"shallow; on the surface only","ko":"피상적인, 표면적인","ex":"His knowledge of the topic was superficial.","level":3},
  {"word":"supplement","pos":"v.","en":"to add to something to improve it","ko":"보충하다, 보완하다","ex":"Farmers supplement their income with tourism.","level":2},
  {"word":"suppress","pos":"v.","en":"to hold back or prevent","ko":"억제하다, 진압하다","ex":"The drug helps suppress the immune response.","level":3},
  {"word":"surge","pos":"n.","en":"a sudden strong increase","ko":"급증, 밀려듦","ex":"There was a surge in demand for the product.","level":2},
  {"word":"surpass","pos":"v.","en":"to be greater or better than","ko":"능가하다, 뛰어넘다","ex":"Sales this year surpass last year's totals.","level":2},
  {"word":"susceptible","pos":"adj.","en":"likely to be affected by something","ko":"영향받기 쉬운, 취약한","ex":"Young plants are susceptible to frost.","level":3},
  {"word":"sustain","pos":"v.","en":"to keep something going over time","ko":"지속하다, 유지하다","ex":"The economy could not sustain such rapid growth.","level":1},
  {"word":"symmetry","pos":"n.","en":"balanced arrangement of parts","ko":"대칭, 균형","ex":"The building is admired for its perfect symmetry.","level":3},
  {"word":"synthesize","pos":"v.","en":"to combine parts into a whole","ko":"종합하다, 합성하다","ex":"The essay synthesizes ideas from several sources.","level":3},
  {"word":"tackle","pos":"v.","en":"to deal with a problem","ko":"다루다, 씨름하다","ex":"The team worked to tackle the issue.","level":1},
  {"word":"tangible","pos":"adj.","en":"real and able to be touched","ko":"실체가 있는, 만질 수 있는","ex":"The research produced tangible benefits.","level":3},
  {"word":"technique","pos":"n.","en":"a way of doing something skillfully","ko":"기법, 기술","ex":"The artist developed a new painting technique.","level":1},
  {"word":"tedious","pos":"adj.","en":"boring and long","ko":"지루한, 싫증나는","ex":"The process of sorting data is tedious.","level":3},
  {"word":"temporary","pos":"adj.","en":"lasting only a short time","ko":"일시적인, 임시의","ex":"The workers found only temporary employment.","level":1},
  {"word":"tendency","pos":"n.","en":"an inclination to behave a certain way","ko":"경향, 성향","ex":"There is a tendency for prices to rise.","level":2},
  {"word":"tension","pos":"n.","en":"a state of strain or stress","ko":"긴장, 팽팽함","ex":"There was tension between the two groups.","level":1},
  {"word":"terminate","pos":"v.","en":"to bring something to an end","ko":"종료하다, 끝내다","ex":"The company decided to terminate the contract.","level":2},
  {"word":"terrestrial","pos":"adj.","en":"relating to the land or earth","ko":"육지의, 지구의","ex":"Insects are the most diverse terrestrial animals.","level":3},
  {"word":"theoretical","pos":"adj.","en":"based on theory, not practice","ko":"이론적인","ex":"The model has only theoretical applications.","level":2},
  {"word":"threshold","pos":"n.","en":"a point where something begins","ko":"문턱, 한계점","ex":"The pain threshold varies among individuals.","level":3},
  {"word":"thrive","pos":"v.","en":"to grow or develop well","ko":"번성하다, 잘 자라다","ex":"These fish thrive in warm waters.","level":2},
  {"word":"tolerate","pos":"v.","en":"to allow or endure something","ko":"견디다, 용인하다","ex":"These plants tolerate very dry conditions.","level":2},
  {"word":"trace","pos":"v.","en":"to find the origin of something","ko":"추적하다, 거슬러 올라가다","ex":"Scientists trace the virus to its source.","level":2},
  {"word":"trait","pos":"n.","en":"a distinguishing quality or feature","ko":"특성, 특징","ex":"Curiosity is a common trait in scientists.","level":2},
  {"word":"transfer","pos":"v.","en":"to move from one place to another","ko":"옮기다, 이동시키다","ex":"Heat can transfer between the two objects.","level":1},
  {"word":"transform","pos":"v.","en":"to change completely in form","ko":"변형시키다, 바꾸다","ex":"Technology can transform how we work.","level":1},
  {"word":"transient","pos":"adj.","en":"lasting only a short time","ko":"일시적인, 덧없는","ex":"The effect proved to be transient.","level":3},
  {"word":"transition","pos":"n.","en":"a change from one state to another","ko":"전환, 이행","ex":"The transition to renewable energy is underway.","level":2},
  {"word":"transmit","pos":"v.","en":"to pass something from one to another","ko":"전달하다, 전송하다","ex":"Mosquitoes can transmit the disease.","level":2},
  {"word":"transparent","pos":"adj.","en":"able to be seen through; clear","ko":"투명한, 명료한","ex":"Glass is a transparent material.","level":2},
  {"word":"tremendous","pos":"adj.","en":"extremely large or great","ko":"엄청난, 거대한","ex":"The discovery had a tremendous impact.","level":2},
  {"word":"trigger","pos":"v.","en":"to cause something to start","ko":"유발하다, 촉발하다","ex":"Stress can trigger a range of symptoms.","level":2},
  {"word":"trivial","pos":"adj.","en":"of little value or importance","ko":"사소한, 하찮은","ex":"He dismissed the error as trivial.","level":3},
  {"word":"turbulent","pos":"adj.","en":"full of disorder or violent movement","ko":"격동의, 난기류의","ex":"The plane passed through turbulent air.","level":3},
  {"word":"typical","pos":"adj.","en":"having the usual qualities of a type","ko":"전형적인, 일반적인","ex":"This is a typical example of the style.","level":1},
  {"word":"ubiquitous","pos":"adj.","en":"present everywhere at once","ko":"어디에나 있는, 편재하는","ex":"Smartphones have become ubiquitous in modern life.","level":3},
  {"word":"ultimate","pos":"adj.","en":"final or most important","ko":"궁극적인, 최종적인","ex":"The ultimate goal is to reduce waste.","level":1},
  {"word":"undergo","pos":"v.","en":"to experience something, often change","ko":"겪다, 받다","ex":"The metal will undergo a chemical change.","level":2},
  {"word":"underlying","pos":"adj.","en":"hidden but important as a basis","ko":"근본적인, 기저의","ex":"We must address the underlying causes.","level":2},
  {"word":"undermine","pos":"v.","en":"to weaken gradually","ko":"약화시키다, 훼손하다","ex":"Corruption can undermine public trust.","level":3},
  {"word":"uniform","pos":"adj.","en":"the same throughout; unvarying","ko":"균일한, 획일적인","ex":"The temperature was kept uniform.","level":2},
  {"word":"unique","pos":"adj.","en":"being the only one of its kind","ko":"독특한, 유일한","ex":"Each fingerprint is completely unique.","level":1},
  {"word":"unprecedented","pos":"adj.","en":"never having happened before","ko":"전례 없는","ex":"The country faced unprecedented challenges.","level":3},
  {"word":"uphold","pos":"v.","en":"to support or maintain","ko":"지지하다, 유지하다","ex":"The court chose to uphold the ruling.","level":3},
  {"word":"utilize","pos":"v.","en":"to make practical use of","ko":"활용하다, 이용하다","ex":"Plants utilize sunlight to make food.","level":2},
  {"word":"vary","pos":"v.","en":"to be different or change","ko":"다르다, 변화하다","ex":"Prices vary from region to region.","level":1},
  {"word":"vast","pos":"adj.","en":"extremely large in size or amount","ko":"방대한, 광대한","ex":"The desert covers a vast area.","level":1},
  {"word":"viable","pos":"adj.","en":"capable of working successfully","ko":"실행 가능한, 생존 가능한","ex":"Solar power is now a viable option.","level":3},
  {"word":"vigorous","pos":"adj.","en":"strong, energetic, and forceful","ko":"활발한, 격렬한","ex":"The debate was long and vigorous.","level":3},
  {"word":"volatile","pos":"adj.","en":"likely to change suddenly","ko":"변동이 심한, 휘발성의","ex":"The stock market can be very volatile.","level":3},
  {"word":"withstand","pos":"v.","en":"to resist or endure successfully","ko":"견디다, 버티다","ex":"The bridge can withstand strong winds.","level":3}
];
